### ISSUE TITLE
Project 281 - Missing Data: hits exist for 'NA' receiver with device ID

### ISSUE THREAD

**Issue by leberrigan** [MotusDev/Motus-TO-DO#1005]
There are 9 power tags (registered with tag type LifeTag2 and LIFETAG2) in project 281 that are missing detections on the website. In R, there are detections for receivers which have a device ID but no serial number. Specifically, these are devices **1925** and **2292**. Looking up these IDs in our database (sensors_hash_keys), they correspond to serial numbers **CTT-34C82914C473** and **CTT-8EF1CB0D3FAC**, respectively. Why don't these receivers exist in our in the sensors table? Apparently they were registered on *8/26/2020 10:56:24 AM* and *6/16/2021 4:34:02 PM*, respectively.

motusTagID | deviceID | recv | nHits | nRuns
-- | -- | -- | -- | --
55526 | 1925 | NA | 43 | 3
55527 | 1925 | NA | 41 | 3
55528 | 1925 | NA | 51 | 3
55529 | 1925 | NA | 63 | 3
55530 | 1925 | NA | 54 | 4
55531 | 1925 | NA | 94 | 3
55531 | 2292 | NA | 17 | 1
55532 | 1925 | NA | 67 | 3
55532 | 2292 | NA | 15 | 2

**Comment by cjardine-bsc** [comment]
That's as it should be. 

The receivers are in the sensor_hash_key table, but not in the sensors table. That means CTT has piped data to us from those receivers, but no user has registered the receivers to their project. We don't know who they belong to until someone claims them, and ideally creates deployments. 

Until that time they are not displayed on the website, since the data is not in a deployment or tied to a project.

**Comment by cjardine-bsc** [comment]
I've made a change to vwR_Metadata_for_receivers_recvDeps to pull he receiverID from sensor_hash_keys instead of sensors. That should help a bit in the R package

**Comment by cjardine-bsc** [comment]
Awaiting testing. @leberrigan
