### ISSUE TITLE
cannot complete new user registration

### ISSUE THREAD

**Issue by jsayers-bsc** [MotusDev/Motus-TO-DO#1007]
A new user is trying to sign up and complete their registration but is unable to do so.

I've tried changing the status to registered from this end and get an error: _Cannot insert the value NULL into column 'statprov_code', table 'motus.dbo.user_status'; column does not allow nulls. INSERT fails._ Thing is that the statprov_code is not null.

I've also tried deleting the record so that the user can try again and though I get a "user deleted" message the user remains. 

User id 26401

**Comment by cjardine-bsc** [comment]
Where are you changing the status?

**Comment by cjardine-bsc** [comment]
![image](https://user-images.githubusercontent.com/22172758/131571728-73d67391-853f-4ece-bd9f-245866213b12.png)

Does it lie to me?

**Comment by denislepage** [comment]
The province code in user_status is a remnant from other sources. For this table, everyone is normally assigned ON (Ontario), regardless of the address in their profile. The main utility of this table in Motus is to determine the user access level: 1 = regular user, 2 = PI, 3 = Motus admins (us).

I suspect that the “delete” function only removes the record from user_status, not user_id. Removing user_id would require potentially checking all the places where the user_id might be referenced, so we typically don’t do that. Of course, if someone asked to be removed entirely for privacy reason, we can do it, but it’d be hard to fully automate due to the dependencies.

Once you remove the user_status record, the person should no longer be able to log in. Because the login name is still in his user_id record, trying to register again with the same login would likely throw an error that says the login exists.

2 options: we clear the login, password hashes when we “delete” a user, or we manually reinsert a new user_status record to re-enable the account. I’d favor door #2.

We have many users without a user_status or login credentials in that user_id table (e.g. contact info for stations), but in this case, it’s caught in limbo because it still has the login name. Our tool to change the status potentially attempts to do the second option, but is leaving out the province field which is required. This value should always be ON for everyone in user_status.

select distinct proj_id, statprov_code from user_status

proj_id                 statprov_code
MOTUS                ON

**Comment by cjardine-bsc** [comment]
Door number 2 implemented.
