### ISSUE TITLE
Tag Metadata: Nom_freq

### ISSUE THREAD

**Issue by cjardine-bsc** [MotusDev/Motus-TO-DO#1011]
Heya folks, 

I've created a proc that is checking batches to see if they are detecting tags on a different frequency than what we expect for the project. 

The issue is that there are 547 tags in our database that have nom_freq that are not consistent with our expected 4 values. Any batch that detects these tags is going to flag as problematic. I suggest we fix the tag metadata. Something to touch on tomorrow, I'm not sure where these errors have crept in or how tagfinder is managing them. 

Select * from tags where round(nom_freq, 3) not in (select frequency from lk_frequency)

**Comment by leberrigan** [comment]
@cjardine-bsc - it's be a few months, is this still the next step?

**Comment by cjardine-bsc** [comment]
I believe so. I think some of these are legitimate, but I'd still like the list from @Hussell to check.

**Comment by Hussell** [comment]
Frequency|#Tags|Last Registration Date|Notes
-|-|-|-
NULL|7178|2022-04-18|?
149.4|3|2015-10-23|used during the initial stages of the first project in Europe
150.1|4930|2022-04-12|Lotek tags from Europe and Africa
150.34|243|2016-06-01|used during the initial stages of the first project in Europe
150.44|2|2015-10-23|used during the initial stages of the first project in Europe
151.5|488|2022-02-13|Lotek tags from Australia and Asia
160.38|1|2017-01-07|likely a typo, since all other tags in its project are 166.38
160.4|2|2016-08-30|from a bat project, they're probably correct but a one-time use
166.3|278|2017-05-05|Should be investigated in depth. From 6 different projects, but it seems likely they're all the same mistake: truncation of 166.38.
166.32|6|2018-06-27|used by project 62 "Western Chickadees" (as in UWO, so in Ontario) during a brief tag shortage
166.36|11|2018-06-27|used by project 62 "Western Chickadees" (as in UWO, so in Ontario) during a brief tag shortage
166.38|30956|2022-04-18|Lotek tags from the Americas
434|1958|2022-03-17|CTT tags
999.999|1|2016-04-20|placeholder in a placeholder project

Attention needed for 160.38, 166.3, and NULL.
