### ISSUE TITLE
Noisy antenna notification

### ISSUE THREAD

**Issue by leberrigan** [MotusDev/Motus-TO-DO#1016]
As discussed, we are to add a new notification for noisy antennas. We have decided on a threshold of 1 million pulses in a day.

The issue will read something along thee lines of:

> This antenna has received an unusually high number of pulses which is likely caused by **radio noise**. Noisy antennas can result in missed detections and/or false positives. For more information on identifying and resolving noisy stations: https://docs.motus.org/stationguide/noisy-stations

**Comment by cjardine-bsc** [comment]
Okay, I'm killing a few different birds with this one stone. 

One request that has been sitting on my desk for a while is to expand the batches activity table to include all hour bins within a batch, regardless of whether tags were detected in that hourbin. I've decided to start there first, and then I will use the batches_activity table to generate the validation centre warning you request above. 

I've made a bunch of changes in prSGBatchesActivityBatchID in sandbox to support this. **The batches_activity table will now have one entry for every hour bin between the tsBegin of the batch and the tsEnd of the batch**, along with all the GPS, pulse_count and run information for that hourbin. That should be useful to users. 

It's a bit problematic for the batches where tsBegin is inaccurate (you'll recall there are a bunch of times where this is ~1970) for now I'm truncating those to 2010. I'm not sure I have a better solution at this point. That problem probably should be tackled upstream and we should assign accurate tsBegins to batches. A battle for another day. 

I've added a new field to the det_batches_activity table called numGPSfix. I've added this to batches activity R view in sandbox (vwR_Batches_activity) this field needs to be added to the r package. @steffilazerte 

I'm re-running all the batches activity summaries in sandbox now. While this is a low risk change (if there are bugs in my code we can always just re-generate the summary) I'd like to have it tested before moving it over to live. @ajmacdonald3 I think I recall that you've worked with the activity table in R a bit. Would you be able to do pull your data from sandbox and look over the activity data to make sure its as you would expect it? 

One thing I noticed while I was doing this is that **the hourbin used in the det_pulse_counts table is calculated using Round, not floor**. That seems incorrect to me, but given that one is pre-calculated by tagfinder and we can't calculate it on the fly in the motus database I've changed the way we calculate hourbin for runs and gps to use round so that we can do consistent joins. That might explain some inconsistencies we've seen in the past between the number of hits in an hourbin and the number of pulse_counts. 

I don't think this requires an update to the motus filter chapters of the R book (5.4.1) and I think the description of the activity table is still accurate: 

![image](https://user-images.githubusercontent.com/22172758/136107079-a1c6a6c5-2a54-4929-8bad-a12ca11ac4c3.png)

But if anyone more familiar with the R book than me thinks it needs an update anywhere let me know. 

Now that the batches_activity table has all activity (all pulse_counts) I'm going to use it trigger the error above. Talking to Stu today, this error is of most interest within a rolling window of the last 30 days (open to discussion), so I've started with that. 

There is a new error in sandbox called "High Number of Radio Pulses" (can someone think of a better name?) the text there should be reviewed before translation. 

The activity will take a little while to finish running, so this is something we can test tomorrow. I'll give a poke here with a list of projects that trigger the new error.

**Comment by cjardine-bsc** [comment]
The query returns the following receivers and antennas:


<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/CATHER~1/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/CATHER~1/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<style>

</style>
</head>

<body link="#0563C1" vlink="#954F72">



project_id | motusDeviceID | (No column name) | receiverID | ant | NumDaysOver1milHits
-- | -- | -- | -- | -- | --
0 | 1554 | v_noise | SG-3847RPI3BD14 | 2 | 22
0 | 1569 | v_noise | SG-484CRPI35902 | 1 | 18
0 | 1588 | v_noise | SG-D8D5RPI3CF17 | 2 | 15
48 | 923 | v_noise | SG-CDC6RPI35494 | 1 | 21
48 | 1685 | v_noise | CTT-867459049276207 | 3 | 22
48 | 1685 | v_noise | CTT-867459049276207 | 4 | 29
78 | 1730 | v_noise | SG-61B0RPI36626 | 2 | 27
113 | 1012 | v_noise | SG-5016BBBK1123 | 2 | 29
113 | 1012 | v_noise | SG-5016BBBK1123 | 5 | 29
123 | 1015 | v_noise | SG-3615BBBK0C15 | 1 | 12
123 | 1015 | v_noise | SG-3615BBBK0C15 | 2 | 13
123 | 1015 | v_noise | SG-3615BBBK0C15 | 3 | 13
223 | 1332 | v_noise | SG-5305RPI3BB5A | 1 | 31
223 | 1332 | v_noise | SG-5305RPI3BB5A | 3 | 20
223 | 1569 | v_noise | SG-484CRPI35902 | 1 | 18
280 | 1588 | v_noise | SG-D8D5RPI3CF17 | 2 | 15
291 | 1554 | v_noise | SG-3847RPI3BD14 | 2 | 22



</body>

</html>

**Comment by jsayers-bsc** [comment]
Jeremy summarized some of the occurrences of batches in the future here: https://github.com/MotusDev/Motus-TO-DO/issues/969#issuecomment-884478860

**Comment by leberrigan** [comment]
I can confirm it works! I also see the new variables (stationID and stationName in recvDeps; numGPSfix in activity). I had to use forceMeta=T for station metadata to populate.

**Comment by leberrigan** [comment]
Has been implemented, tested, and is on live
