### ISSUE TITLE
Reprocessing W. European receivers

### ISSUE THREAD

**Issue by leberrigan** [MotusDev/Motus-TO-DO#1017]
We had to correct the burst intervals of a selection of tags from Project 113 which had an issue with their recordings during registration (resulting in missed detections). The project collaborator would now like us to reprocess receiver data from all of W. Europe uploaded after 28 August. As we've discussed previously before, I know this can't be done efficiently, so I'm interesting in knowing the options. 

1. On average, how long will it take for these data to be reprocessed? A month or two?
2. Is there a growing capacity to reprocess data? I.e., have processing speeds been increasing and methods for reprocessing improved?
3. What is a ballpark threshold for the maximum number of stations you will reprocess at a time?

**Comment by denislepage** [comment]
We should first do this on a trial basis and make sure it improves the results on a few receivers in a way that warrant re-running.

I’d like also to confirm that all necessary BI changes are made before we do a large reprocessing. Measure twice, cut once.

**Comment by jsayers-bsc** [comment]
Is there any benefit to registering new tags with the "proper" BI and then merging them?

**Comment by Hussell** [comment]
New data is currently being rerun after approximately 2 months, though I'm trying to improve that to 1 month. Subsequent intervals double.

Some improvements have been made to reprocessing speed and automation, but I'm not sure whether or not it has kept up with the growth in data. My impression is that they're roughly in balance because I put more time into improving the process when reruns seem to be taking a long time. But the improvements have come in sudden large jumps while the amount of uploaded data varies with the seasons, so without concrete measurements on a graph I'm not sure.

Requests to rerun geographic areas are annoying because I don't have an easy way set up to query which stations are in an arbitrary region. If there's a list of serial numbers it's relatively easy now, though I still have to look at each one. Maybe 10 or 20 stations as a ballpark limit? It also depends on what's in the queue already at the moment and how much data each station has. I would like to avoid rerunning Old Cut, for example, because it takes more time to rerun than 100 normal stations put together. There are a couple of stations in Europe which generate equally enormous amounts of data, so I prefer to rerun them on schedule so as not to cause delays. I'm not completely sure that's a valid rule-of-thumb, but that's my current thinking.

**Comment by jsayers-bsc** [comment]
#1039 has created additional demand for European re-runs, both directly and indirectly.

Using country code in sensor_deployments there are 133 receivers in Europe that have data within the last 2 months. Current issues aside, that's a lot.

But some of these may already have been re-run recently. Is there a way to query most recent rerun date against the list to identify potential priorities?

SG-5305RPI3BB5A
SG-C2D4RPI3E059
SG-66D6RPI3F32F
SG-1315BBBK0104
SG-964CRPI3CF17
SG-D346RPI380D6
SG-D22CRPI39DC5
SG-4414BBBK0737
SG-14D1RPI39753
SG-2980RPI3BA26
SG-C927RPI32264
SG-5016BBBK1B6A
SG-5016BBBK177E
SG-4815BBBK0173
SG-49F1RPI36953
Lotek-687
SG-2485RPI32B5D
SG-03CDRPI3BE4D
SG-5016BBBK200B
SG-5016BBBK19D5
SG-938FRPI30102
SG-5016BBBK0DC0
SG-32D5RPI3236B
SG-1215BBBK1742
SG-4FA7RPI3B265
SG-1E10RPI2E46A
SG-1EF8RPI3FC69
SG-B338RPI3178C
SG-5016BBBK1123
SG-5016BBBK17D2
SG-F042RPI3F23D
SG-E818RPI3A6F6
SG-D28CRPI3F266
SG-5016BBBK1B68
SG-1116BBBK098F
SG-1116BBBK0BE8
SG-5016BBBK0F85
SG-1D49RPI3A7D3
SG-F3DDRPI2AA6F
SG-1116BBBK0CEB
SG-1315BBBK0099
SG-B2AERPI34D9D
SG-0402RPI32799
SG-A655RPI363B3
SG-A2DCRPI3A284
SG-3B5DRPI38553
SG-E146RPI3170B
SG-0C7DRPI32949
SG-CB6CRPI3E9EF
SG-53B9RPI38E29
SG-3615BBBK0B9E
SG-F790RPI3E8DD
SG-5016BBBK18E8
SG-1315BBBK0088
SG-BD3BRPI3170E
SG-367CRPI3F183
SG-57F2RPI304FE
SG-1215BBBK1773
SG-A0C1RPI329DF
SG-0044RPI31985
SG-A98FRPI321DA
SG-484CRPI35902
SG-1116BBBK0CB9
SG-05F2RPI327EA
SG-CA83RPI36DAB
SG-6F20RPI3E5BB
SG-1116BBBK0C40
SG-428ARPI351C8
SG-5016BBBK1B7C
SG-456CRPI3DBBB
SG-3291RPI35718
SG-764FRPI20AF2
SG-1116BBBK0983
SG-550CRPI31890
SG-F4B4RPI34EC5
SG-4815BBBK0175
SG-9941RPI30396
SG-0554RPI3E2D7
SG-D061RPI35538
SG-2E42RPI3232D
SG-DEEARPI3F9D4
SG-3615BBBK254B
SG-32A1RPI36156
SG-3615BBBK0CD0
CTT-8EEB1C3FC849
SG-92CCRPI30443
SG-AC08RPI33D9B
SG-7822RPI34A0A
SG-B361RPI3E47B
SG-0EF7RPI32BB8
SG-5016BBBK1995
SG-C5B9RPI3760E
SG-3615BBBK03B3
SG-3035RPI3A1BE
SG-1315BBBK0141
SG-3615BBBK0F94
SG-3615BBBK0BBD
SG-EC46RPI3EA8A
SG-3C27RPI38BCE
SG-58C2RPI31EE7
SG-B32CRPI3E2FC
SG-AEB7RPI35E9F
SG-0733RPI37C19
SG-3615BBBK0BA8
SG-3615BBBK0C15
SG-50D6RPI38864
SG-5016BBBK17E4
SG-0816BBBK0909
SG-6DEFRPI3EA3A
SG-80BERPI323CE
SG-5016BBBK0F73
SG-4414BBBK1318
SG-9EB7RPI36C3D
SG-1116BBBK14B3
SG-9E7CRPI3D27D
SG-E244RPI3C099
SG-1116BBBK0D6A
SG-1315BBBK0102
SG-22A9RPI3666D
SG-3615BBBK071F
SG-3615BBBK0421
SG-88BERPI35833
SG-47CCRPI347B5
SG-4721RPI31989
SG-3615BBBK01F1
SG-E8F8RPI33ACB
SG-EEC0RPI38FE7
SG-FCFFRPI3CA7F
SG-4815BBBK0087
SG-5016BBBK15A4
SG-3615BBBK0B93
SG-5016BBBK17DA
SG-7614RPI3ED8C

**Comment by Hussell** [comment]
I've edited your list to show the order in which they'll be rerun, ones at the top first. The one at the bottom is currently 1452/1500 on my list, the one at the top is 6/1500.

**Comment by Hussell** [comment]
I should note that prioritization doesn't only look at recent data. Some of the receivers have data from a long time ago which hasn't been rerun for an even longer time, and they end up having higher priority because so many tags have been registered since the older data was last run.

**Comment by jsayers-bsc** [comment]
> I should note that prioritization doesn't only look at recent data. Some of the receivers have data from a long time ago which hasn't been rerun for an even longer time, and they end up having higher priority because so many tags have been registered since the older data was last run.

Right. In the case of the recent requests they are most interested in the tags that are, or were around recently, but good point.

Any rough estimate on when the first and last would be re-run?

**Comment by Hussell** [comment]
Normally the answer would be that the first is already being rerun and the last would be rerun a month or two from now. With the current backlog and delay, I think the first will probably get rerun tonight, and the last might not get rerun for as long as three months? It depends a lot on how fast the reruns can be done, which will depend on how much data gets uploaded this month. We're heading into a quiet time, winter for the northern hemisphere, so I'm hopeful that by the end of the month we'll actually be ahead of schedule instead of behind. On the other hand, that's probably way too optimistic given past experience.

Note that the receivers which are near the end of the list are very low priority for good reasons. E.g. the last three on the list were rerun on the 23rd of October, and receivers not on the list at all are ones from which we don't have any recent data.

**Comment by Hussell** [comment]
#1031 is delaying reruns even more. The NAS drive seems to have failed yesterday evening, before reruns could be started.
