### ISSUE TITLE
ConcurrentModificationException

### ISSUE THREAD

**Issue by denislepage** [MotusDev/Motus-TO-DO#102]
This is typically due to a List object being modified while trying to loop over it. (e.g. removing an object from a Vector during a while loop.

Solution usually is to identify the object(s) within the loop, and use a separate process to deal with them.

Error reference number: 1511200766759
________________________________________
Exception:
java.util.ConcurrentModificationException
Stack trace:

File Name | Line Number | Class Name | Method Name | Native Method?
-- | -- | -- | -- | --
␀ | -1 | java.util.ArrayList$Itr | checkForComodification | false
␀ | -1 | java.util.ArrayList$Itr | next | false
ForEachSupport.java | 119 | org.apache.taglibs.standard.tag.common.core.ForEachSupport$SimpleForEachIterator | next | false
ForEachSupport.java | 141 | org.apache.taglibs.standard.tag.common.core.ForEachSupport | next | false
LoopTagSupport.java | 295 | javax.servlet.jsp.jstl.core.LoopTagSupport | doAfterBody | false
edit_jsp.java | 1702 | org.apache.jsp.WEB_002dINF.data.receiver.deployment.edit_jsp | _jspx_meth_c_005fforEach_005f2 | false
edit_jsp.java | 311 | org.apache.jsp.WEB_002dINF.data.receiver.deployment.edit_jsp | _jspService | false
HttpJspBase.java | 70 | org.apache.jasper.runtime.HttpJspBase | service | false
HttpServlet.java | 729 | javax.servlet.http.HttpServlet | service | false
JspServletWrapper.java | 438 | org.apache.jasper.servlet.JspServletWrapper | service | false
JspServlet.java | 396 | org.apache.jasper.servlet.JspServlet | serviceJspFile | false
JspServlet.java | 340 | org.apache.jasper.servlet.JspServlet | service | false
HttpServlet.java | 729 | javax.servlet.http.HttpServlet | service | false
ApplicationFilterChain.java | 291 | org.apache.catalina.core.ApplicationFilterChain | internalDoFilter | false
ApplicationFilterChain.java | 206 | org.apache.catalina.core.ApplicationFilterChain | doFilter | false
WsFilter.java | 52 | org.apache.tomcat.websocket.server.WsFilter | doFilter | false
ApplicationFilterChain.java | 239 | org.apache.catalina.core.ApplicationFilterChain | internalDoFilter | false
ApplicationFilterChain.java | 206 | org.apache.catalina.core.ApplicationFilterChain | doFilter | false
ApplicationDispatcher.java | 721 | org.apache.catalina.core.ApplicationDispatcher | invoke | false
ApplicationDispatcher.java | 466 | org.apache.catalina.core.ApplicationDispatcher | processRequest | false
ApplicationDispatcher.java | 391 | org.apache.catalina.core.ApplicationDispatcher | doForward | false
ApplicationDispatcher.java | 318 | org.apache.catalina.core.ApplicationDispatcher | forward | false
ApiContext.java | 515 | org.bsc.motus.ApiContext | dispatch | false
EditRecvDeploymentServlet.java | 95 | org.bsc.motus.web.EditRecvDeploymentServlet | doGet | false
HttpServlet.java | 622 | javax.servlet.http.HttpServlet | service | false
HttpServlet.java | 729 | javax.servlet.http.HttpServlet | service | false
ApplicationFilterChain.java | 291 | org.apache.catalina.core.ApplicationFilterChain | internalDoFilter | false

**Comment by pmorrill** [comment]
The exception was thrown while a jsp file was iterating over a List. The jsp is not modifying the list, only displaying values. The modification is happening elsewhere.

This jsp loops over the following variables:

ProjectBean#projectSites - a member variable
fixtureTypeOptions - temporary Map created from the static lookups structures 
dongleOptions (same as fixtre type optons, bu new, so not the cause of the exception)

Since the projectSites is the only ArrayList here, it's the likely culprit. However, this is a member variable on an object that is owned only by the current session. Not sure how it can get modified while the user is displaying the recv deployment edit page.

If a user adds a new site while saving the deployment record, the site list is in fact modified: it is nulled and therefore rebuilt in the ProjectBean object, when the html template is displayed afterwards. There shouldn't be any concurrency issue with that. But if the site list is reset by some other code - the user having two windows open, for example - it could happen right while the jsp file is iterating through those sites. Very unusual.

You'd better keep sending me these exceptions when you see them, and I'll keep looking into this.

**Comment by denislepage** [comment]
Yeah, weird. If the error happens on a different thread (even within the same session), then the solution would be to run the updates to the object in a synchronized block. There is no real downside to do that anyway, though I usually tend to only do this for static objects If you are storing ProjectBean as a session object, I guess there is a chance that 2 separate threads can access it at the same time (as you say, different windows would be one way).

I’ll let you know if I see more of them. I think I have only seen it happen for this page so far. It’s happened only a few times.
