### ISSUE TITLE
New station type fields

### ISSUE THREAD

**Issue by zcrysler** [MotusDev/Motus-TO-DO#103]
Since it's required that you select type of station to save a receiver deployment, we need options to allow for manual tracking and tracking done with cars.  We could include individual options as is already the case (ship and plane already exist, and then add handheld and automobile), or we could remove ship and plane and just have one option of "mobile" that covers all of this.  It's probably worth knowing the type of mobile receiver though

**Comment by cjardine-bsc** [comment]
I've added handheld and automobile to lk_fixture_type

**Comment by denislepage** [comment]
Yes, we need to rethink this a little.

If we had GPS readings in all cases, this would be less of an issue. A problem is that the we don’t always have them, so we need to capture at least some details in the deployment.

For one thing, I think we should require a deployment location in all cases. For mobile/hand-held, this would be the starting point, something we’d have to explicitly say on the page and the instructions. This requirement would apply in order to activate a deployment with a start date, not with pending ones.

The biggest distinction I think we need re: mobile is whether the movement is localized or not. Someone on foot covering 1-2 km is different from a vehicle. In the first case, you can still use the coordinates at a continental scale. I was thinking at first we just needed hand-held and vehicle, but planes is still very different from ground-based, and probably different from ships.

So, I think I would rename the receiver types to be a little more generic, so we are not being asked to expand the list later:


·         hand-held

·         aircraft (e.g., plane, helicopter)

·         ground-based vehicle (e.g., car).

·         ship (e.g. ferry, boat)

**Comment by cjardine-bsc** [comment]
Catherine Jardine
Ph: (604)-350-1972
www.birdscanada.org

**Comment by cjardine-bsc** [comment]
I’ve made those changes to the lookup table.

Catherine Jardine
Ph: (604)-350-1972
www.birdscanada.org
