### ISSUE TITLE
Parallel uploads from the same receiver cause havock

### ISSUE THREAD

**Issue by Hussell** [MotusDev/Motus-TO-DO#1039]
This is more of a rant about something I don't see any easy way to fix than a bug report, so... sorry in advance.

Our systems are set up to divide raw signal data from receivers into batches, which can be of arbitrary length. Usually a batch ends and a new one is begun when the receiver reboots. Often this happens when a field technician goes out to retrieve the last few weeks or months of data. Solar powered receivers often reboot if the weather is particularly overcast for a few days and the batteries get drained. Bad solar setups sometimes result in a receiver loosing power every night and rebooting in the morning. Faulty power can cause a receiver to reboot every few seconds. These situations are common enough that our systems were designed to handle them gracefully, so receivers with thousands of batches each a few seconds long are handled fine. On the other end of the scale, since some receivers are now connected to the internet and upload data hourly, they can go quite a long time between reboots. One of the major features John Brzustowski completed before going on to other things was to change the tag finder so it could handle _resuming_ a batch when newer data is uploaded. So, hourly uploads from connected receivers don't cause the entire batch to be rerun, only the new hour's-worth of data.

However.

If data from the middle of a batch is uploaded, the system reruns _the whole batch_. This isn't a problem if the batch is short, but if the batch is very long, a lot of computing resources are consumed to very little effect. This is a problem John was thinking about before he left, but the best solution would probably involve rewriting the whole system to divide data into fixed-length units (e.g. days or weeks) instead of arbitrary-length batches, and we don't really want to do that. It mostly doesn't happen, so we've been able to ignore the issue.

Last weekend one of our collaborators (doesn't matter who, this isn't their fault) uploaded several archives each containing one day of data from a particular receiver.  That worked, sort-of. Our system doesn't handle parallel processing of data from the same receiver well, so there were a few database deadlocks. In fact, we already warn people to upload everything from a receiver in a single archive exactly to prevent this. No matter, I just reran the uploads one-at-a-time and everything was back to normal.

Then the collaborator uploaded 30 more archives containing one day's worth of data each. Out of order. From a batch which began on 2020-12-17 and ended 2021-09-29. So the tag finder has been busy rerunning the same 10-month-long batch over and over again. This is also part of the reason there's four times more data in the transfer table than there was last month: multiple copies of all the hits from the same 10-month-long batch. (The other part is that it's just that time of year: it seems as though everyone in the northern hemisphere is uploading a full year's worth of data from their receivers at the same time. A bit of an exaggeration, but more than half the data in the transfer tables is still from other projects.)

So, that's why there are currently 50 upload jobs waiting in the queue to be processed. Reruns have been completely halted until the backlog is clear. Hourly and daily uploads from connected receivers and CTT receivers are still being processed, though I'm seriously considering pausing them too. I've been trying to estimate how long it's going to take, and unless something changes it looks as though the repeated reruns of that one batch won't be finished for another week.

**Comment by tve** [comment]
Out of curiosity, is the bottleneck in the tag finder, the database or elsewhere?

**Comment by denislepage** [comment]
All of it. I mentioned today that there are too many steps involved in the processing. This is the main piece I had in mind. Much of this complexity has to do with the requirement that John created by deciding that runs should be independent from batches. IE, if you upload 2 different data files, runs initiated in previous batches should be allowed to continue across.  For animals staying permanently around a receiver, these runs could in theory extends for weeks, uninterrupted (a run do allow individual gaps in detection, but up to a certain limit, such as 20x the period, after which point a new run is initiated.

There is no fixing this in the current system without a complete re-write that fundamentally changes the rules used. 

There are about 12 different possible different paths involved, with permutations for connected receivers, manual uploads, CTT receivers, Lotek receivers, etc. Here's the longest path possible for a data point (high level, perhaps with a few inaccuracies). 

- sensorgnome (sg) unit captures the pulses and convert the radio pulse to a data record
- sg pushes the pulses to sensorgnome.org in a gzip file (about 250kb each)
- sensorgnome pushes the files to sgdata.motus.org, packaged in a zip file
- motusServer unpacks the zip archive and places the files in a repository folder
- tagfinder runs on the new batch, including chaining runs with earlier batches  (involves at least 2 steps: converting pulses to candidate tag bursts, and chaining bursts into runs of consecutive hits on a single antenna).
- batches, runs and hits data is saved to a local sqlite file
- a separate process aggregate the data from the local sqlite files into a Maria DB database
- Over to Motus.org, we have a script that connects to the sgdata API and pulls new data in the maria DB (based on the last batchID), and puts them into the motus database
- a number of processes are then run to tie individual detections to metadata, and generate summaries that can be used for various outputs
- older batches that are duplicate of newer one are marked as deprecated and deleted. Older Maria DB records are also removed.
- Users use the R package and pull data and metadata from motus.org

One bottleneck, but not the only one, is that the main hits table has now reached about 5 Billion records. Inserting new records is slow (in part due to indexing).

Since we're at it, this is my dream system:

- SG pushes individual gzip to motus.org
- tag finder v. 2 grabs the files submitted so far and ignores the runs from earlier batches, making the runs self-contained within batches
- tag finder pushes data to the motus.org database
- data summaries are run, potentially including trying to tie runs across batches (as a separate step), but they might be done on the runs records, rather than the hits (about an order of magnitude less data)

Under this model, we'd potentially saved the hits into archive files (presumably one file per run?) rather than the database, and only save the batch and run records in the database, with an link to the file matching the batch, but I haven't given this too much thought, and there are several complications/changes we'd need to make. Data from Lotek and CTT receivers would both come as pre-identified tags, which would presumably allow skipping a step in the tag finder process, but they still need to be linked as runs. Actually, the process above is more or less how things are currently working for CTT data (CTT doesn't use period as parameter, so the process is even simpler, and as long as hits from the same tag are on the same antenna within an arbitrary period of 5 minutes, they are treated as a run within a batch).

One minor downside to not trying to link runs across batches is that individual tag hits at the edge of the period would be discarded, as we need at least 2 hits to register a run. This seems like a minor issue in the grand scheme of things, but John was adamant that it needed to be accommodated, especially under a model where batches are relatively short (e.g. an hour). We could potentially set a schedule that minimizes this by allowing data to accumulate for 12 or 24 hours before they are processed, which creates a bit of a lag.

The main hurdle in implementing this I think is the tag finder algorithm, which we would likely need to rewrite. At that point, I'm even wondering if the same algorithm would be used, or if something different might be better (seems like a good candidate for Machine Learning - I started looking a bit into it, but I'm starting with a VERY basic understanding of how it would work).

Fun?

**Comment by tve** [comment]
Thanks for the reply! 5B records, that's unwieldy ;-) Is that table partitioned, e.g. by time? That should cut down the effective data size the DB needs to deal with to a manageable size... (What's the DB you're using?)
It also seems that a bit of reorg to make runs the "central" detection unit and keep the hits just for "more detail..." might be a good move overall.
WRT batch boundaries and runs, maybe one of the outputs of a tag finder process could be the last hit for each tag. Then the  processing of the next batch could prepend this fairly small chunk of data and thereby runs straddling batches can be detected?

**Comment by denislepage** [comment]
Can we do this? (please)

![image](https://user-images.githubusercontent.com/21110542/139516551-1ab855ec-8e52-4b71-b0c9-9554436c2078.png)

**A batch**: The unit to store the original data. Matches a file containing raw data for a certain period for a receiver (e.g. a gz file, or a DET file, or a CSV for CTT detections)

**A job**: the processing unit. An event that grabs a series of files (batches) for the same receiver. For instance, 40 files received for receiver XXX in the past 24 hours, or 4000 files over the past 3 months

**jobs_batches**: the list of batches included in a job

**runs**: series of consecutive detections of the same tag on the same antenna/node, within a job.

Re-runs of a new job would lead to deprecating earlier ones. If we wanted to be a bit more granular, we'd need to make the jobs arbitrarily shorter (e.g. never more than 1 week worth of data), so we could decide to only rerun the recent batches. Deprecation I guess would be based on using overlapping batchID (no need to worry about flaky timestamps).

Hits would NOT be saved in the database, but hits data from each runs would be saved in a file (or a NOSQL database, or something like that). Those data would only be available during the R downloads, but we could have the tagfinder v2.0 generate some additional metrics about average signal strength, etc.. Those details would still be available to the R users at the individual hit level.

Deploy ID's would be resolved at the runs level, not the hits (e.g. the start of a run). We could potentially integrate some validation during the run generation that prevents a run from overlapping 2 distinct deployments, but changes to metadata may create issues.

**Comment by denislepage** [comment]
Our motus db is SQL server. We likely have unused unexploited for partitioning and gaining efficiency. The above approach would likely be simpler.

Each run would have their start and end timestamps, so chaining them after the processing is what I had in mind. Or, basically just grouping runs by period (e.g a day), but for short runs, it'd be important to confirm that they still are at the expected intervals from each other. It'd seem better to separate that process from the one that happens within a job, so you could in theory add a new file, and only do the last step to chain runs, rather than having to re-start the whole processing from the beginning, which is what we have to do now.

This seems so much simpler on so many levels, but I'm sure complications will creep back in soon. The main bottleneck is rebuilding motusServer, tag-finder to do all of this...

**Comment by Hussell** [comment]
I've found a <s>hack</s> way to make the tag finder clear the queue before going back to deal with the problematic uploads, so for everyone else things should be back to normal by Monday. I'll be cleaning up the mess for longer than that, but uploads should be back to being processed rapidly soon enough. Reruns... we'll see. Connected receivers and CTT receivers weren't impacted much.

**Comment by Hussell** [comment]
From my point of view, the current bottleneck for the tag finder is in copying and reading files. I think the processes on sgdata are spending >50% of their time finding, reading, and writing files? Maybe 90%? I don't have an easy way to measure, so this is just based on probing what processes are doing at particular moments. The amount of time required to transfer the runs and hits to the main Motus database has been relatively manageable since the bottleneck in the transfer tables was cleared out.

The tag finder itself does require a lot of time when it's processing large batches (months or years of data), but I think that's about as optimized as it can be? The tag finder is written in C++. It's using a greedy algorithm to assign pulses to bursts and bursts to runs, so it's doing a single pass through the data without trying anything fancy. I don't think there's much else that can be accomplished there in terms of reducing the amount of work being done when there are tens of thousands of candidate pulses per day per receiver, besides reading data off the hard-drive faster _and not reprocessing the same data 30 times in a row_. Connecting runs across files/batches doesn't even register on measures of processing time. Complexity and maintainability, yes, processing bottlenecks, no.

**Comment by Hussell** [comment]
Finally finished cleaning this up.

Receiver timeline now with gaps only where files are actually missing:
https://motus.org/data/receiver/timeline?year=2021&id=2174
