### ISSUE TITLE
Detection and GPS data duplicated in two receiver repos upon upload

### ISSUE THREAD

**Issue by jsayers-bsc** [MotusDev/Motus-TO-DO#1052]
A while back we noticed something odd about the [Breakwater station (SG-D2D4RPI32C60)](https://motus.org/data/receiver/edit?id=3777&projectID=1). The receiver was showing data more recent than the most recent visit (and we were certain that it had not been visited).

Upon looking at the GPS locations for that receiver's uploaded data we saw that it was actually in two places. From November 2020 through April 24 it was at [Point Farms Provincial Park (SG-F930RPI3D4A0)](https://motus.org/data/receiver/edit?id=3551&projectID=1). But on April 18, it was also at Breakwater, where the physical receiver was installed on that date. 

This receiver has never been to Point Farms from what we could tell. Meanwhile the receiver actually at Point Farms has been there since 2019.

Eventually we realized that the data from Point Farms from November 2020 to April 24 was uploaded in an archive along with the data from Breakwater from April 18. This then duplicated all of the Point Farms receiver data from that period into the file repo for SG-D2D4RPI32C0. (I'm not sure if this went the other way as well; there is no GPS record at Breakwater for the Point Farms receiver at any rate, but Jeremy may already have fixed this part.)

Screenshot below shows the receiver timeline from Point Farms (left) and its data duplicated for Breakwater (right)

![image](https://user-images.githubusercontent.com/55001144/143273119-dfccbe94-4be8-47bf-a0a4-fdd2ffc00090.png)

**Comment by tve** [comment]
How is this possible? Doesn't each file include the sensorgnome_id in its name? (And I believe the newer files also contain the ID in the file itself, no? Have to check...)  How were these attributed to the wrong receiver?

**Comment by Hussell** [comment]
Dang, I was sure I'd fixed this.

It might be only be a matter of having to manually deprecate some old batches from SG-D2D4RPI32C60 in the main database, it looks like everything is in order over on sgdata.

**Comment by Hussell** [comment]
@tve, the files were given the wrong name, with the wrong serial number. How that happened, we aren't quite sure.

**Comment by Hussell** [comment]
I've deprecated the misattributed batches, and that has automatically removed the corresponding misattributed detections, but I think I'll need help to get rid of the GPS and activity counts.

**Comment by Hussell** [comment]
Batch IDs:
2249835 to 2249850
2833830 to 2833831
2842126 to 2842145

**Comment by cjardine-bsc** [comment]
Activity counts should also be deleted with deprecation. 

For GPS, did the GPS records for the correct batches come through? I.E. Do I need to delete the bad batches or update their batchIDs?

**Comment by Hussell** [comment]
The bad batches need to be deleted. They're assigned to the wrong receiver (SG-D2D4RPI32C60) and there are already duplicates with GPS for the correct receiver (SG-F930RPI3D4A0).

**Comment by cjardine-bsc** [comment]
Peachy. Done.

**Comment by Hussell** [comment]
Josh pointed out some inconsistencies in what I reported above, so I re-investigated.

SensorGnomes compress each hour's data into a gzip file with a filename which includes the receiver's serial number. When a bunch of these are compressed into a zip file (or other supported archive format) and uploaded, everything works as expected. And when several of these single-receiver archives are in turn bundled into a single zip file and uploaded, everything works as expected. But when hourly gzip files from multiple receivers are bundled into an archive, all the data ends up assigned to one receiver. This is what happened above, in <a href='https://sgdata.motus.org/status?jobID=6554714'>this job</a>. The archive mostly contained files from SG-F930RPI3D4A0, but had a few files from SG-D2D4RPI32C6. It looks like the tag finder sorted the files by boot number first, and since the files from SG-D2D4RPI32C6 had the lowest boot number, everything got assigned to that receiver. This is definitely a bug, since there is no good reason not to check the serial number on each file.

**Comment by Hussell** [comment]
I've investigated a random sample of data issue alerts about GPS locations being widely separated, and didn't find any further examples of files being assigned to the wrong receiver.

**Comment by Hussell** [comment]
@cjardine-bsc GPS was deleted, but the batches were not deleted. Activity counts for the batches listed above are still present in det_pulse_counts and det_taghits still has rows with the batchIDs above.

**Comment by cjardine-bsc** [comment]
Hmmm I see you've changed those to batch filter 6, you'll need to use 2 if you want the delete proc to run through them.

**Comment by Hussell** [comment]
I just want those batches to be deleted, I don't care how. Though now that you mention it, the delete proc should probably be let loose on batch filters 6, 7, and 8.

**Comment by cjardine-bsc** [comment]
No thanks. Leave 6, 7 and 8. 

If you want them deleted, change their batch filter to 2 and it shall be so.
