### ISSUE TITLE
Edit tag link leads to 404

### ISSUE THREAD

**Issue by j-sayers** [MotusDev/Motus-TO-DO#1095]
The Edit Tag link accessed from here https://motus.org/data/tag?id=60394 is now a dead link.

**Comment by j-sayers** [comment]
This also affects "edit" links in the Data Issues page

**Comment by j-sayers** [comment]
Added priority label since Erica has been emailing many projects about fixing metadata. There will be a lot of people going in here and trying to use this page to dig down into their issues.

**Comment by denislepage** [comment]
I changed the link in sandbox to the general page where tags are now managed: https://motus.org/data/project/tags

There is no distinct page in the case of tag properties that we can send people to.

In one of these pages, perhaps the stations page, Paul had set up a way to open a specific ID in the right panel, but I am not finding this for tags.

Anyway, that’s already a step better than 404, and will need deploying to beta/live.

**Comment by Hussell** [comment]
This is the closest I can manage:
https://motus.org/data/project/tags?setTagId=60394&projectID=377#tagSummary

You still have to learn to ignore the stuff on the left, and find and click the "Modify tag" button. Why is this in a modal dialog only accessible from this page instead of having a dedicated page for the task?

**Comment by j-sayers** [comment]
That's good, as long as the links go somewhere

**Comment by denislepage** [comment]
We also still need to deploy to live. Jeremy could you merge and confirm?

**Comment by Hussell** [comment]
I've been going through all the links in the data issues center. There are 13 distinct links, of which 6 are good, 5 bad, and 2 ugly. There are multiple copies of most links though, so 33 out of 42 types of issue needed updates to their links.

Most changes are simple, but there are some complications.
 - v_dist_deploy_gps_2 and v_dist_deploy_gps_3, the warning and error respectively about GPS hits far from the recorded location of a receiver deployment, used to link to the page to edit the deployment. Now the lat/lng aren't associated with deployments, so @cjardine-bsc should rework these two issues to return the station ID which needs to be edited.
 - Links to stations which are inactive send the user to a page where only active stations are shown on the map. The URL can be used to change the map to show all stations, or to set the station ID, but not both. There's a similarly inflexible URL for editing tags, but the default on that page is to show all tags instead of only active ones.
 - Links to edit stations, tags, and receivers now go to crowded pages with lots of irrelevant information among which the user has to spot and press a button in order to bring up a modal dialog to edit the thing. This is a very poor user experience.

I've updated the links on sandbox. If other people don't immediately see anything broken there (besides the issues above), the updated links should probably be copied to beta/live ASAP, since most of the links are broken at the moment.

**Comment by leberrigan** [comment]
1. Makes sense. That means the links should also change once Catherine makes so that the station ID is returned? 
2. Interesting. Might be because of lines 117:122 of `ManageStationsServlet.java`:
```
ProjectBean.ProjectResourceFilter stationFilter = handleStationFilter(request);
if ( stationFilter == null ) {
	/* signals that the filter as been updated: perform a redirect */
	ctx.redirectRaw("/data/project/stations?projectID=" + projectId);
	return;
}
```
3.  Agreed. We should discuss a better workflow for this and how it could be implemented (another url parameter?).

**Comment by cjardine-bsc** [comment]
RE: 1. v_dist_deploy_gps_2 and v_dist_deploy_gps_3, the warning and error respectively about GPS hits far from the recorded location of a receiver deployment, used to link to the page to edit the deployment. Now the lat/lng aren't associated with deployments, so @cjardine-bsc should rework these two issues to return the station ID which needs to be edited.

The lat/lons used are from vwBase_gps, which are from the station, not the deployment so that is good. But the error description should probably be updated a bit for these ones. With the new station framework the most likely cause of these errors is that he deployment was assigned to the wrong station . Its a bit less likely that the user will need to update the lat/lon of the existing station. 

I'm updating the proc to return the station_id now, but we should think a little on where we want the user to be directed for this one.

**Comment by Hussell** [comment]
I forgot some things on the call. There are two links needed for the receiver location warning and error:
 - The "View" link, which requires the receiver deployment ID.
 - The "Edit" link, which requires the station ID.

The links can include the columns 'project_id', 'id', and 'id_conflict' in the table adm_validation_errors. I can update the data issues servlet so they can also include the columns 'string', 'string2', and 'string3', but they don't at the moment.

I think the most sensible thing is to put the receiver ID in the 'id' column, and the station ID in the 'id_conflict' column? For now I've updated the links on sandbox to match that, so let me know if you end up doing something different, @cjardine-bsc. Example links to verify they're working: https://sandbox.motus.org/data/issues?id=1#v_dist_deploy_gps_3

**Comment by Hussell** [comment]
Fixed 2. by adding some code to make sure all other parameters are copied into the redirect's query string.

**Comment by leberrigan** [comment]
New text language (translated using Google):

### v_dist_deploy_gps_2

#### English

> 
> **GPS Fixes Far from Station Location**
> 
> At least 3 GPS fixes from each of these stations fell over 100m away from their registered latitude and longitude within a 24 hour period.
> 
> This error can arise due to one of the following reasons: the station was registered with an incorrect latitude/longitude; the station deployment has the wrong receiver selected; the station deployment was registered with incorrect start and/or end dates; or there is a fault with the on-board GPS of the receiver. 
> 
> Please review each of the following stations to resolve this issue:
> 

#### French

> 
> ** Corrections GPS loin de l'emplacement de la station **
> 
> Au moins 3 repères GPS de chacune de ces stations sont tombés à plus de 100 m de leur latitude et longitude enregistrées sur une période de 24 heures.
> 
> Cette erreur peut survenir pour l'une des raisons suivantes : la station a été enregistrée avec une latitude/longitude incorrecte ; le déploiement de la station a sélectionné le mauvais récepteur ; le déploiement de la station a été enregistré avec des dates de début et/ou de fin incorrectes ; ou il y a un problème avec le GPS embarqué du récepteur.
> 
> Veuillez examiner chacune des stations suivantes pour résoudre ce problème :
> 

#### Spanish

> 
> **Reparaciones de GPS lejos de la ubicación de la estación**
> 
> Al menos 3 posiciones de GPS de cada una de estas estaciones cayeron a más de 100 m de su latitud y longitud registradas en un período de 24 horas.
> 
> Este error puede surgir debido a una de las siguientes razones: la estación se registró con una latitud/longitud incorrecta; el despliegue de la estación tiene seleccionado el receptor incorrecto; el despliegue de la estación se registró con fechas de inicio y/o finalización incorrectas; o hay una falla con el GPS integrado del receptor.
> 
> Revise cada una de las siguientes estaciones para resolver este problema:	

---

### v_dist_deploy_gps_3

#### English

> 
> **Station Location or Selected Receiver Incorrect**
> 
> Over 50% of the GPS fixes from each of these stations fell over 1000m away from the station latitude and longitude within a 24 hour period.
> 
> This error can arise due to one of the following reasons: the station was registered with an incorrect location; the station deployment has the wrong receiver selected; the station deployment was registered with incorrect start and/or end dates; or there is a fault with the on-board GPS of the receiver. 
> 
> Please review each of the following stations to resolve this issue:
> 

#### French

> 
> **Emplacement de la station ou récepteur sélectionné incorrect**
> 
> Plus de 50% des repères GPS de chacune de ces stations sont tombés à plus de 1000 m de la latitude et de la longitude de la station sur une période de 24 heures.
> 
> Cette erreur peut survenir pour l'une des raisons suivantes : la station a été enregistrée avec un emplacement incorrect ; le déploiement de la station a sélectionné le mauvais récepteur ; le déploiement de la station a été enregistré avec des dates de début et/ou de fin incorrectes ; ou il y a un problème avec le GPS embarqué du récepteur.
> 
> Veuillez examiner chacune des stations suivantes pour résoudre ce problème :
> 

#### Spanish

> 
> **Ubicación de la estación o receptor seleccionado incorrecto**
> 
> Más del 50 % de las posiciones de GPS de cada una de estas estaciones cayeron a más de 1000 m de la latitud y longitud de la estación en un período de 24 horas.
> 
> Este error puede surgir debido a una de las siguientes razones: la estación se registró con una ubicación incorrecta; el despliegue de la estación tiene seleccionado el receptor incorrecto; el despliegue de la estación se registró con fechas de inicio y/o finalización incorrectas; o hay una falla con el GPS integrado del receptor.
> 
> Revise cada una de las siguientes estaciones para resolver este problema:

**Comment by cjardine-bsc** [comment]
@denislepage can you look over the french and give it your blessing? Then I'll update the DB. 

Way to be bilingual :-)

**Comment by leberrigan** [comment]
@denislepage have you had the chance to read over the French above?

**Comment by denislepage** [comment]
Few adjustments.

```
Emplacement de la station ou récepteur sélectionné incorrect

Plus de 50% des positions GPS de chacune de ces stations sont tombés à plus de 1000 m de l'emplacement de la station enregistrée sur une période de 24 heures.

Cette erreur peut survenir pour l'une des raisons suivantes : la station a été enregistrée avec un emplacement incorrect; le déploiement de la station est lié à un récepteur de façon incorrecte; le déploiement de la station a été enregistré avec des dates de début et/ou de fin incorrectes ; ou il y a un problème avec le GPS intégré au récepteur.

Veuillez examiner chacune des stations suivantes pour résoudre ce problème :

```
I also looked at the Spanish, and it seems ok. I can't fully vouch that despliegue is the correct usage of the word deployment in our context, but otherwise, I am not seeing anything obviously wrong.

**Comment by cjardine-bsc** [comment]
I've updated those in sandbox. @Hussell did you make all your changes in Sandbox? I'm going to push everything to live and don't want to overwrite any of your changes so just confirming first. 

prAdmTransferErrorCodes

**Comment by cjardine-bsc** [comment]
okay, I ran the sync between sandbox and live. 

Josh, I tested 4 different receiver errors and they all worked, so I gave up :-)

Do you want to look at adm_error_types in the database and let me know if everything makes sense to you in terms of the urls to or view the metadata?
