### ISSUE TITLE
Do we store daily summary reports from Iridium-networked SS?

### ISSUE THREAD

**Issue by leberrigan** [MotusDev/Motus-TO-DO#1103]
If not, does CTT make them available to us? 

These are valuable data for system health reporting. If we can get at least daily resolution on station up time using summary reports, that would suffice. Bonus if we're able to tell which antennas are functioning each day.

I'm asking in regard to the offshore wind projects where many of them will be satellite networked and health reporting will be important for planning maintenance trips. However, this will be useful for any remote station.

**Comment by denislepage** [comment]
We'll need to follow up with CTT. I suggested that the data should come through the same process as the rest of the CTT data. Trying to remember the last discussion, but wasn't one of us (Lucas?) going to look into what fields we wanted to integrate into our dashboards, and which ones needed to be archived for R users? We may be talking about 2 different things (e.g. CTT Station log data?), but the question is similar. At the moment, I am not aware that CTT is exposing this data to us, so we'd need to agree on a process and format by which this happens.

**Comment by StuMackenzie** [comment]
bob send us a sample of the data they collect and then we were going pick up the conversation again. I think Catherine has it? I can look.

____________________

**Comment by StuMackenzie** [comment]
CTT Checkins are here - https://drive.google.com/file/d/1jAlrnaLdxHaD00lYIIWVO5ItyxAGBbpE/view?usp=sharing

Ideally we'll want some consistency with respect to whether they are SS, SG's or LOtek depending on which receiver it is. Not all receivers need to display all teh same info.

**Comment by StuMackenzie** [comment]
From Bob

"**Hi Denis, Catherine - it was good to sync up with satellite integration protocols.

I'm attaching about 200 of the most recent checkin reports from V2 Sensor Stations. The format of the file is a new line for each record in the following format
•	YYYY-MM-DD HH:MM:SS: {JSON}
where JSON is the JSON representation of the health / statistics of tag beeps since the station was powered on.  Within the JSON object is a "stats"  key which has each radio channel broken down by the details we had spoken about, including Node health reports and Node breakdowns (if the channel is listening to nodes).

Apparently I've already encoded the file count / cumulative size for each of the CTT set of files and Sensorgnome set of files within each checkin object.  This would have to be embedded into the Satellite transfer protocol so we can start sending this in the future.  You'll see an "uploads" key which has an object with a "ctt" and a "sg" key where that information is broken out.

You can have a look at these checkin reports for a preview of what we are currently sending.  None of this data is filtered by valid tags at this point.  We can clean these checkin reports before sending them to you once we're ready to start a pipeline.

V1 station checkins are in a different format - I'll have to review those and make some decisions about integrating them as well.

Let me know if you have any questions.
**

**Comment by leberrigan** [comment]
@denislepage: I think this is a different issue. We also want to provide a way to sort out whether the station is networked or offline which may have be something like the number of uploads to Motus over the past 24 hours, or something similar.

@StuMackenzie: Catherine had sent me that file, but it looks like all the check-ins come from stations with modems connected to the cell network. Do we have another example somewhere for iridium data?


Apparently, CTT has said they are already sending us these data, but perhaps we ignore it since it doesn't match any of the expected JSON objects. 
 
All we really need is daily ping indicating whether the Iridium station checked in. I could reference a table specifically for the iridium pings, or we could insert a GPS hit into the receiver GPS table once a day. The latter version would allow me to recycle the methods I would be using to calculate station up time for cell-networked stations. At least on my end, I would like to keep GPS hits and antenna pulses per hour for all connection types in the `activity` table in an indexedDB. Satellite-networked, cell-networked, and offline stations will all be fairly distinct in the pattern of data they produce so I should be able to separate them out with javascript. I could do something like:

```
// Get metadata for a single station from the IndexedDB based on 'stationID '
var selectedStation= async motusData.db.stations.get( stationID );

// Get activity for a single station from the IndexedDB
var stationActivity = async motusData.db.activity.get( selectedStation.id );
// Returns JSON object with one row per hour in which data were recorded with the following child objects:
// ts = timestamp of hour bin; gps = number of gps hits recorded; ant1 = pulses on antenna 1, antN = pulses on antenna N, ...

function getConnectivityType( activity, isNetworked ) {

   // Look at activity from the last seven hour bins that were recorded
   let recentActivity = activity.filter( ( _, i ) => i >= activity.length - 7 ).reduce( (prevVal, currVal) => {
         prevVal.gpsHits += currVal.gps;
         prevVal.days.push( ( new Date( ts ) ).toISOString().substring(0, 10) ) // Converts datetime to date string like "2021-12-31"
      }, ({gpsHits: 0, days: []}) );

   // Iridium stations will only transmit a single GPS hit per day and no antenna pulses
   // If there are no more than 1 GPS hits per day
   if ( recentActivity.days.filter( onlyUnique ).length == prevVal.gpsHits ) 
      return "satellite";

   // Networked stations will record one or more GPS hits each hour, but we can only distinguish them from offline
   //  stations with recently-uploaded data based on the number of uploads there have been in the past 24 hours
   return isNetworked ? "cellular/Wi-Fi/Ethernet" : "offline";
   
   
}

var stationConnectivity = getConnectivityType( stationActivity, selectedStation.networked );
// Returns: "satellite", "cellular/Wi-Fi/Ethernet", "offline";
```

**Comment by leberrigan** [comment]
The answer is no, but we will soon!
