### ISSUE TITLE
Mobile receivers

### ISSUE THREAD

**Issue by zcrysler** [MotusDev/Motus-TO-DO#112]
The checkbox on the receivers deployment page should be a dropdown menu to select either mobile or stationary.  It should be a required field.  For existing deployments the field can be set like this:

Stationary: anything with receiver types building, tower, pop-tower, dam
Mobile: anything with receiver types ground-based vehicle, ship, aircraft, hand-held

we can't fill it in automatically for receiver type "existing"

**Comment by pmorrill** [comment]
I believe what we have decided, going forward (next release):

1. We will not require lat / long or site for **mobile** deployments, but we **will** allow those fields;

2. However, if someone tries to set up a new site as part of the deployment creation / edit step, then they MUST provide lat / long as well, for that deployment. (And, I will look at also asking for a landowner)

In the short term, we want to locate all existing sites that are missing lat / long. This should not be allowed! For those sites on the list:

a) if linked only to mobile deployment(s), the site can be de-linked from those deployments and DELETED;

b) if linked to non-mobile deployments (this should not happen!) - we need to deal with them on a case by case basis?

**Comment by cjardine-bsc** [comment]
There were 26 sites with blank lat/lon assigned to mobile fixture_types

SELECT *
  FROM [motus].[dbo].[sensor_sites] a left join sensor_deployments b 
  on a.id = b.site_id 
  where (a.latitude is null or a.longitude is null) and fixture_type in ('Ship','Automobile', 'Aircraft', 'Handheld')

Id's: 1347,1347,1458,1470,1471,1493,1515,1556,1596,1597,1598,1605,1625,1685,1685,1686,1701,1717,
1726,1726,1807,1808,1857,1862,1867,1874

I've removed the link from deployments and deleted those sites. 

There were 4 sites with no location info that were not linked to any deployment. I've also deleted those. 

One site did not have location info but it's deployment did. I've updated the site's location info from the deployment.

Two sites from project 16 (1734, 1735) have a note stating "Can't release location due to confidentiality agreements". Zoe, we might want to contact them and ask about these deployments. This might be a good use of the is_private fields, though the other 5 deployments for this project have locations.

Project 41 has 5 empty deployments created for one empty site (id= 1890) those will be flagged through the notification center and hopefully fixed. I suspect they might be errors. 

That leaves just two sites for which there are legitimate deployments but no location information. Project 78 (Site ID 2150 Deux Rivieres) and project 130 (site 2298 San Javier (Chile)) Hopefully users will fix these through the notification center. 

Tidy tidy.

**Comment by denislepage** [comment]
Hm. Interesting. If we force users to enter a set of coordinates, I’m wondering what people with concerns about revealing their sites will do. They may not trust (let alone be aware) that the site precision approach will be sufficient (frankly, I am not sure I am 100% confident we have or will always implement this properly).

These are rare cases, and people will undoubtedly find creative ways to work around that, including using 0 or rounding coordinates. Maybe that’s ok.

Denis

**Comment by zcrysler** [comment]
Project 16 confidential deployment locations: Liam McGuire and Justin Boyles were contacted about this twice in the past and both times said the sites had to remain private due to confidentiality agreements.  I can contact them again if we really want this info, but what is our justification?  They said no other tags were detected there, I can't confirm right now because I'm having trouble downloading by receiver.

Possibly related, if not I'll make a new entry: why can't I see the number of receivers in project 16 here: https://motus.org/data/projects even when logged in, is it privacy settings?

**Comment by Hussell** [comment]
Zoe, the projects table shows the number of currently active receiver deployments. There's actually a tooltip, but it ended up on the wrong column when a new column was added. I'll fix that now.

**Comment by denislepage** [comment]
As per earlier email, I think we need to allow blank or rounded coordinates in these exceptional cases, without making it too easy.

If we went that way, It’d definitely be an error on the notification center, but one that they can dismiss.

Dang.

**Comment by pmorrill** [comment]
The mobile status of a recv deployment is now encapsulated in the fixture type selection. The checkbox for 'is_mobile' has been removed. You may now input lat / long for all fixture types including mobile ones (as of next code deployment, that is: beta5 and master branches)

**Comment by pmorrill** [comment]
As of now, beta5 and master branches will require that the user input a lat / long when creating a new deployment site; This is regardless of whether the fixture type is mobile or not.

We require site for all deployments, but there might be an argument for removing that requirement if the fixture type is mobile.

**Comment by zcrysler** [comment]
Creating a new deployment as a mobile receiver with no coordinates and no site still allows me to save - based on what you've said I think it should be giving me a warning about a missing site?

Doing the same but with a non mobile receiver gives the warning that I need to select a site.

**Comment by pmorrill** [comment]
I was wrong in my description above. In fact, if a fixture type is 'mobile', the site is optional. This is easy to change, if we decide to enforce a site selection even on mobile fixtures.

**Comment by zcrysler** [comment]
So sounds like this is working as it should be
