### ISSUE TITLE
need a new field for defunct tags

### ISSUE THREAD

**Issue by denislepage** [MotusDev/Motus-TO-DO#113]
A problem now is that we don't know the status of undeployed tags. After a while, the codeset of these tags will likely be reused, creating potential problems if the originals are deployed. Lotek says that unused tags can be good for up to 3 years, so we should be able to discriminate between tags still pending and those that are guaranteed to never be deployed.

We also can't assume that a tag that has been deployed in the past is out of the picture. It may have been recovered and stored for later use.

To consider a codeset available for the purpose of Lotek, etc. we need to clarify some rules, and possibly create a new field that would allow people to mark their tags as "defunct", which I think is the best term to describe this. This would be a good alternative to allowing people deleting tags. This would be done on the tag edit page, not something attached to a deployment. We have a similar field called "deprecated" in sensors_hash_keys. May be good to bring those 2 concepts under the same name. Is deprecated used for anything with sensors?

That means we should think about adding a new field to our exported table, which is the available_dt. When to consider a codeset available:

1) for tags that can potentially be still be used (no deployments, deployments with unconfirmed start dates, or only terminated deployments): 3 years from registration date (or dateBin?).

2) for all tags that have an open-ended deployment: start date + lifespan_calc (including the buffer)

3) any tag marked as defunct, regardless of their deployment status. I am presuming that we would require people to terminate any open-ended deployments before applying this, but it could also be used for undeployed tags. The available date for those would be the most recent of the last deployment end or the registration date, or better left as null?

Does that make sense?

**Comment by cjardine-bsc** [comment]
I prefer to think of this conceptually in the inverse of how you've framed it here. I.E. We're giving lotek a list of codesets they cannot use, not a list of ones they can. 6 of one, half dozen of the other, but for building the queries and for interpretation by lotek it makes more sense to me to think of it this way. This way we can provide both the excluded codeset and the date that it is anticipated to become available based on lifespan_calc. Any codesets not on the list can be used. 

I've altered my query for active tags so that it includes tags that only have terminated deployments. I think we can do something a little more sophisticated in the long term. I'm picturing a popup when a user enters an end date for a tag deployment that asks users to confirm whether the tag is still usable or should be considered defunct,  but this works for now. Previously this query was releasing codesets after they had been registered and undeployed for > 2 years, I've changed that to three years now. The DateEnd field in this query provides the date this codeset becomes available. It is currently null for tags that have not been deployed. We could expand this and have a MinDateEnd (today's day + lifespan_calc) and a MaxDateEnd (today's date + 3 years +lifespan_calc) but that depends on whether that is of any use to lotek. I suspect not?

ALTER VIEW [dbo].[vwTagsActive]
AS

SELECT * FROM (
SELECT a.id as tag_id, a.model, mfg_id, a.period, a.date_bin, a.nom_freq, b.id as deploy_id, lifespan_calc,
CAST(DATEADD(day, -2, dt_start) as Date) as DateStart
, CAST(DATEADD(day, ISNULL(lifespan_calc, 400), dt_start) as DATE) as DateEnd
FROM tags a 
LEFT JOIN (SELECT * FROM tags_deployments WHERE dt_end is NULL) b on a.id=b.tag_id)a 
WHERE (DateEnd > GETDATE()) 
or
(deploy_id is null AND
((((DATEPART(year, GETDATE()) - 2010) * 4) + DATEPART(QUARTER, GETDATE())) - 
(((LEFT(date_bin,4) - 2010) * 4) + RIGHT(date_bin, 1))) < 12 )
GO

 I agree we need a new field for deprecated/defunct/destroyed tags. There are currently 3 levels of error flagging in the validation center for marking undeployed tags. 

1. Tags that were registered within the last quarter (note)
2. Tags registered between 3months and 2 years ago (warning)
3. Tags registered > 2 years ago. (error)

Users need to be able to address these issues by indicating whether or not their tag is defunct. Tags marked as defunct would not be included on this list of unavailable codesets that we send to Lotek. We'd also need a process that automatically marks tags as defunct if they pass the three year threshold, and a means to warn/handle situations where someone tries to create a deployment for a tag marked as defunct. 

I don't have any insight on the deprecated field in sensors_hash_keys but I suspect you're right. I'd be happy with the field in tags to be named "deprecated" as well. Defunct sounds a little colloquial to me...but maybe I'm a snob :)
