### ISSUE TITLE
Tag detections occurring from 1970's to early 2000s

### ISSUE THREAD

**Issue by eageldart** [MotusDev/Motus-TO-DO#1130]
As I go through data issues on the Notification Center, I am coming across quite a bit of instances where tags are being detected outside of deployments , in particular, the detections are **starting** in the years 1972, 1980, 2000, 2004, to name a few. For example, see these data issues that I ignored: https://motus.org/data/issues?id=458#v_tag_hits_out_deploy_ignored  These detections are however ending at a more realistic time. 

If I am not mistaken, detections are impossible this early on?

**Comment by cjardine-bsc** [comment]
Ugh. Bad GPS time stamps. I'll have to add a date cut off to that check. Thanks.

**Comment by cjardine-bsc** [comment]
I've made a change in SB. Can you give it a test?

**Comment by leberrigan** [comment]
Hmm.. We need another example. Project 458 isn't on Sandbox!

**Comment by tve** [comment]
I'm not sure focusing on the date is a good idea. Yes, detections prior to the start of the Motus project are certainly indicative of the time&date not being set, but that doesn't include all such cases. I.e., while an ancient date indicates a problem, a recent date doesn't indicate the absence of a problem ;-). There's a letter in each file that indicates the accuracy of time synchronization or its absence and any detection made in the absence of time sync should be flagged/discarded/treated specially.

In the new version of the SG software, files produced in the absence of time sync will no longer have ancient dates due to linux forcing the date to be at least the date of the system image build, and also to avoid GPS rollover issues that could prevent GPS from proving a reasonable time&date...

**Comment by cjardine-bsc** [comment]
he raw data should be the same, so if the 1970s hits are missing from sandbox its a good indication all is well.

**Comment by leberrigan** [comment]
Looks good on Sandbox! Deploy to beta!

**Comment by cjardine-bsc** [comment]
Running on live now. Can be tested and hopefully closed.

**Comment by cjardine-bsc** [comment]
oh whoops, I responded to the wrong issue. Now this is deployed :-)

**Comment by eageldart** [comment]
I checked a few notification centers for projects I know this was an issue for, and it seems to be fixed. Thanks Catherine! I am going to close this issue now.

**Comment by eageldart** [comment]
I have reopened this issue because I have noticed a few projects that still have data issues concerning tag detections too early (1970-early 2000). 

Here is an example: https://motus.org/data/issues?id=247#v_tag_hits_no_deploy 
![image](https://user-images.githubusercontent.com/94930170/186906394-5f8b89bb-c7db-4010-ad91-6f54e51d6bfd.png)

**Comment by cjardine-bsc** [comment]
Ah, this is slightly different (v_tag_hits_out_deploy vs v_tag_hits_no_deploy)

I'm actually going to change  v_tag_hits_no_deploy a bit. It will pretty much always be triggered by a false detection or two now that we register the tags via lotek. That will be confusing for users. 

I'm now only going to trigger that warning if he hit passes the motus filter. Which should help. 

I also think the motus filter should clean out those bad time stamps.  I've added some processing that will filter any hits before 2010 or after the day they are processed. 

So I just made a few key changes, test and let me know if anything seems amiss.
