### ISSUE TITLE
Bad link on Edit Station Deployment page

### ISSUE THREAD

**Issue by leberrigan** [MotusDev/Motus-TO-DO#1134]
Link in the station name hasn't been updated with the new URL parameter; it still contains `setStationID` when it should be `stationID`.

Example: https://motus.org/data/station/deployment/edit?projectID=1&id=2429

![image](https://user-images.githubusercontent.com/35931796/158611099-f1534eb6-a585-44b7-ac50-a3fb0355cc9b.png)

**Comment by denislepage** [comment]
I have posted a few fixes changing setStationId to stationId. Ready to test in live.

**Comment by denislepage** [comment]
Hm. I see now. The problem was actually only the redirect. The setStationId= parameter was correct, but the redirect was being set to the wrong URL, and this was compounded by the double redirection.

I think I have it right, now, if tests can be made. I have posted the changes in all branches and servers.

**Comment by leberrigan** [comment]
It's been tested and confirmed fixed. Thanks!
