### ISSUE TITLE
Return all receiver metadata with tagme()

### ISSUE THREAD

**Issue by zcrysler** [MotusDev/Motus-TO-DO#116]
Likely every project will at some point want to make a map or view all receivers that were active at some point during their tagging.  They can access/download all receiver metadata online already (that have correct permissions), can we allow it back into the tagme() function to make is easier to access in one step?  

It was in there at some point weeks/months ago, I'm not sure when it got removed or what the reason was

**Comment by denislepage** [comment]
That is unfortunately not a very simple change, and needs changes from both the API and the motusClient, but I expect we’ll want to do this (but maybe in a next release).

Right now, the call to metadata_for_tags or _for_receivers builds a list of tags/receivers already in the database and only asks for those metadata. This is a reasonable approach for the receiver-based data files, but not the project-based data.

There are a few possible approaches to modify the existing R code. All of them would require matching support on the API side:


-          we make 2 new API entries that return the list of tagID’s or deviceID’s that people should be pulling metadata for, and modify the code to pass back that list to the server with the existing queries.



-          we modify the R code to request the data from the API on the basis of projectID’s rather than a list of tags.


-          we create a new R function which sole purpose is to deal with this, and request all metadata on a project basis for tags (e.g. metadata(176, forceMeta=TRUE))


I think I would support the latter option. This would be by far the cleanest, as opposed to trying to modify the existing R script. Tagme would continue to give people the tag and receiver meta that matches the detection data, and metadata would give them more options.

In order to get tag metadata, they would have to provide a projectID, but they should be able to get metadata for receivers across all projects (for which they have permission based on their status). Maybe we could allow a optional couple filters, such as a time range (tsBegin and tsEnd). That would likely be enough for now.

I think this function should only work for tag project motus files, not receiver ones.

We would therefore new 2 new API entry points (or modify the existing ones to support a project ID instead of a list of device or tag ID’s, that would also work):

metadata_for_tags_by_project
metadata_for_receivers_by_project

The would be working the same as their pending metadata_for_xxx, but return records on the basis of a project ID. For receivers, a NULL project ID would be acceptable, and the API would then need to get a list of all receiver project metadata that the user can see. That may mean mixing permission types here: full details for receivers where they are project users, and securable version for other projects. I expect that will be the primary complication on this.

Anyway, I’ve already made a bit of progress on a new metadata function in R. We can discuss this again soon.

Denis

**Comment by jbrzusto** [comment]
`tagme` is a function with an easily-stated purpose: 

>  update a user's copy of a tag project database or
> receiver database with all detections and associated metadata.

Contrary to the comment above, this works for both project and receiver databases.

If users want metadata **not** associated with their detections (i.e. not belonging to the tag or the
receiver involved in the detection, at the time of the detection), then it seems to me a different function should be created for that. If it is specifically receiver activity that is desired, then I propose a new function such as:

```
   getActiveReceivers(tsRange, latRange, lonRange)
```
with:
 -  **tsRange**: double vector of length 2; time period of interest, as min, max timestamps
 -  **latRange**: (optional) double vector of length 2; range of latitudes of interest, as min, max  decimal degrees (with positive being North, negative being South)
 -  **lonRange**: (optional) double vector of length 2; range of longitudes of interest as min, max
    decimal degrees (with positive being East, negative being West)

The return value would be a `data.frame` with:
 - one row for each antenna active during at least one hourBin of `tsRange`  (Note: `hourBin(ts) := floor(ts / 3600.0)`
- columns for receiver serial number, deviceID, and antenna metadata
- a nested column (i.e. list column) column giving the integer hourBins for which the antenna was known to be active, based on pulse counts. 

Note: R data.frame columns are normally vectors of strings, numbers, or logical values, with each item in the vector corresponding to one row.  But a column can also be a `list`, where the item in each row is itself a vector.  That seems to me the natural approach here.

### Abbreviated sample return value with only a few metadata columns ###
(just to show the nesting of hourBins)

```R
data.frame(serno=c("Lotek-153","SG-1013BB000626", "SG-1013BB000626"),
             deviceID = c(915,563, 563),
             ant = c(1, 1, 2),
             antType = c("Yagi-5", "Yagi-9", "Yagi-9"),
             hourBins = I(list(c(397222, 397223, 397224), c(397221, 397222), c(397221, 397224)))
            )
            serno deviceID ant antType     hourBins
1       Lotek-153      915   1  Yagi-5 397222, ....
2 SG-1013BB000626      563   1  Yagi-9 397221, ....
3 SG-1013BB000626      563   2  Yagi-9 397221, ....

```
and `jsonlite::toJSON(..., dataframe="columns")` serializes the above to:
```json
{
"serno":["Lotek-153","SG-1013BB000626","SG-1013BB000626"],
"deviceID":[915,563,563],
"ant":[1,1,2],
"antType":["Yagi-5","Yagi-9","Yagi-9"],
"hourBins":[
   [397222,397223,397224],
   [397221,397222],
   [397221,397224]
   ]
}
```
So the wire-format for an API call is reasonable.

Also, some thought should be given to:
 - where are such non-associated metadata stored on the user's side? e.g. nowhere, leaving 
   it up to the user to store them somewhere?
 - what functions are used to retrieve these metadata from the user's storage?
 - can they be fetched incrementally from the server, or does the function have to grab all of them at 
   once?
 - what permissions are required?

**Comment by pmorrill** [comment]
I haven't time to dig into details on this today, but I **do** agree with John: this merits a new function, rather than adjusting the way tagme works.
