### ISSUE TITLE
Do we need tag lifespan to be editable?

### ISSUE THREAD

**Issue by zcrysler** [MotusDev/Motus-TO-DO#117]
User asked if they should be inputting anything here, since tag lifespan is calculated by us, and they can enter an end date if the tag is retrieved - what's the purpose of allowing users to enter a tag life?

**Comment by denislepage** [comment]
It should be (or was, anyway). There is a field for it in both tags and deployments, in any case, which are meant to override the calculations based on the model.

**Comment by cjardine-bsc** [comment]
Right now I'm not using this to override my calculations of tag lifespan. 

I'm in favour of dropping this column. Right now it's only used by one project for 38 deployments and is always set as 60, which is the estimated lifespan for the tag as provided by lotek. So at the moment this field provides no useful information. 

I also think that I'd rather calculate the lifespan of previously deployed tags programmatically instead of asking users to do math :D 

Denis, I sent you the database changes I've implemented to handle this. I'm hoping the function I've built can take the place of this field.

**Comment by jbrzusto** [comment]
Are users able to see the details of how lifespans are calculated?   The model we've been using
is available as a [pdf](https://github.com/jbrzusto/motusServer/blob/new_server/inst/doc/modelLotekTagLifeSpan.pdf) and [R markdown source](https://github.com/jbrzusto/motusServer/blob/new_server/inst/doc/modelLotekTagLifeSpan.pdf)

**Comment by denislepage** [comment]
Lotek has, in the past at least, provided the lifespan for tags to the users. Few people seem to have entered this, let alone seen it.

If we have all the pieces to consistently calculate it, then there may not be a need to allow an override.

The calculation is based on the document provided in the motusServer package.
