### ISSUE TITLE
Missing fields in lt_receiver_types

### ISSUE THREAD

**Issue by leberrigan** [MotusDev/Motus-TO-DO#1187]
There are two entries in `lt_receiver_types` that are each missing the values for `regex` and `key_name`. 

@denislepage Do you know what the regex should be for the Lotek SRX-1200? I have entered the following based on the serno's I have seen, but it should be confirmed. I think we shouldn't allow unknown receivers to be registered (hence the blank regex).

receiver_type | regex | key_name
-- | -- | --
LOTEKSRX1200 | `(MD\|M\|D){0,1}[0-9]{6}` | LOTEKSRX1200_regex
UNKNOWN |  | UNKNOWN_recv_regex

**Comment by denislepage** [comment]
The regex string for the database table would be expected to start with ^Lotek-. The DTA file will only provide the suffix, so adding Lotek- is something that motusServer does.

If I'm reading your notes correctly, the regex would be: ^Lotek-(?:MD|M|D)\d{6}$

For instance: Lotek-MD000123, Lotek-M000234 , Lotek-D000345

However, the last one overlaps with the regex for "LOTEKSRX800D", ^Lotek-D\d{6}$. I expect that this shouldn't happen.

Can you confirm?

motusServer seems pretty flexible, but may still need at least a few adjustments.  Here are a few that I found so far. I only looked for occurrences of Lotek-, so I may have missed places that happen in the code before the Lotek- prefix is added:


inst/scripts/maintenance/populate_products_table.R:

allProds = cbind(allProds, splitToDF("(?i)(?sx).*/(?<projectID>[0-9]+)/(?<serno>(Lotek-[0-9D]+)|(SG-[0-9A-Z]{12}))?.*", allProds$URL))

R/motusConstants.R:

MOTUS_LOTEK_SERNO_REGEX = "Lotek-D?[0-9]+(?:_[0-9])?"

inst/scripts/www/status2.js:

var serno_re=/(?:(?:SG-[0-9A-Z]{4}(?:RPi[1234z]|BBBK|BB[0-9][0-9A-Z])[0-9A-Z]{4}(?:_[0-9])?)|(?:Lotek-D?[0-9]+(?:_[0-9])?)|(?:CTT-(?:[0-9]{15}|[0-9A-F]{12}))|(?:SEI_[A-Z]_[0-9A-Z]{9}))|(?:-[0-9A-Z]{4}(?:RPi[1234z]|BBBK|(?:BB[0-9][0-9A-Z]))[0-9A-Z]{4}-)/ig;


Do you already have some DTA files for these receivers? Have we confirmed that no other adjustments are necessary yet? I know we talked about it. We may need the file specs from Lotek, rather than trying to decipher the format from the example files.

**Comment by leberrigan** [comment]
Yes, we should confirm with Lotek - the examples we have are `Lotek-MD020100` and `Lotek-D0020107` so perhaps there are _slight_ differences (note additional zero on the `D` model). 

There are a few formats available and that issue was resolved in #1004. 
[format 1 (date, time and uSeconds in 3 separate columns TXT).TXT](https://github.com/MotusDev/Motus-TO-DO/files/8472375/format.1.date.time.and.uSeconds.in.3.separate.columns.TXT.TXT)

**Comment by leberrigan** [comment]
@denislepage We're getting the following error:

> Error: Error in getRecvSrc(serno, dbdir = dbdir): invalid receiver serial number Lotek-MD020110

Has the regex been changed to accept the 'MD' prefix?

**Comment by leberrigan** [comment]
I think the correct change would be: 
`MOTUS_LOTEK_SERNO_REGEX = "Lotek-M?D?[0-9]+(?:_[0-9])?"`
https://github.com/MotusWTS/motusServer/blob/1a591bf4cc6b61b0a239f912bc4283f9f78b659a/R/motusConstants.R#L181

**Comment by cjardine-bsc** [comment]
it was still null in sandbox and Live. For the moment, I've changed it on sandbox to the below. I believe that covers what you need, but I admit I only skimmed :-) , ping me again if this isn't right. 

^Lotek-(?:MD|M|D)\d{6}$

I also need a text key associated with the instructions for that regex.

**Comment by leberrigan** [comment]
@Hussell Can you rerun Job 16409293? The file can't be uploaded again, but it failed last time so it needs to be reprocessed.

**Comment by Hussell** [comment]
The motusServe Lotek regexes have been updated, and the job successfully rerun. 0 detections though.
