### ISSUE TITLE
Unusually large volume of detections in January 2017

### ISSUE THREAD

**Issue by leberrigan** [MotusDev/Motus-TO-DO#1188]
I made a plot of `det_taghits_daily` for a presentation and noticed an unusually  large spike in the number of detections starting January 1st, 2017 and continuing for a number of weeks, but gradually decreasing. It seems like the vast majority of these detections are occurring outside of a registered deployment (sensor_deploy_id = 0).

![cumsum_tagHits_2022](https://user-images.githubusercontent.com/35931796/162944637-4a428d95-9cf0-429c-bb11-f6a8e1cdb216.png)

date | n_hits | n_sensors | n_tags
-- | -- | -- | --
2016-12-26 | 17576 | 11 | 65
2016-12-27 | 19927 | 15 | 64
2016-12-28 | 22349 | 15 | 75
2016-12-29 | 11742 | 13 | 58
2016-12-30 | 8531 | 11 | 65
2016-12-31 | 7648 | 10 | 62
2017-01-01 | 6939151 | 11 | 83
2017-01-02 | 3618305 | 15 | 77
2017-01-03 | 2932184 | 14 | 74
2017-01-04 | 2352495 | 10 | 52

**Comment by cjardine-bsc** [comment]
well...thats weird. 

First thing I did was try to reproduce. I get the same jump, but a corresponding large jump in tag_ids. What did you use as the raw data set to run your query? 

num_sensors	num_tags	date	(No column name)
11	65	2016-12-26	17576
15	64	2016-12-27	19927
15	75	2016-12-28	22349
13	58	2016-12-29	11742
11	65	2016-12-30	8531
10	62	2016-12-31	7648
11	2780	2017-01-01	7666082
15	1224	2017-01-02	3845020
14	1071	2017-01-03	3120210
10	895	2017-01-04	2586279
12	682	2017-01-05	2241961
15	592	2017-01-06	2189305

If you look at Jan 1st, almost all the hits fall outside a sensor or tag deployment: 

SELECT  *    
  FROM [motus].[dbo].[det_taghits_daily]
  where [date] = '2017-01-01' 

Hits outside of deployments are either false detections, bad deployment metadata or incorrect timestamps on the hits. 

If I re-run the summary and only include cases where there is a station and tag deploy id, the numbers make a lot more sense. Not surprising, but a good sanity check. 

num_sensors	num_tags	date	(No column name)
9	64	2016-12-26	17431
13	63	2016-12-27	19859
14	74	2016-12-28	22299
10	57	2016-12-29	11674
8	64	2016-12-30	8466
7	61	2016-12-31	7576
8	59	2017-01-01	12567
11	59	2017-01-02	21860
11	55	2017-01-03	8631
6	40	2017-01-04	4559
9	56	2017-01-05	10436
11	50	2017-01-06	20749

I'm guessing bad timestamps have a tendency to cluster around 2017-01-01. That day apparently covers 22k batches. Which is quite a ludicrous number. 

I guessed wrong. Not bad time stamps. Its all data from CTT

SELECT  distinct b.*
  FROM [motus].[dbo].[det_taghits_daily] a inner join det_batches b on a.batch_id = b.batchID 
  where [date] = '2017-01-01' 

Oodles of hits, across 94 CTT receivers, none of which resolve to tag deployments in our DB. 

We'll have to ask them about it. I don't know what those are. They aren't likely causing harm, because they never resolve to any metadata they don't show in any summaries, but why CTT pushed those data to us is a mystery to me.

**Comment by Hussell** [comment]
Possibly related: https://github.com/MotusDev/Motus-TO-DO/issues/969#issuecomment-884478860
(CTT sent us a bunch of data with bad timestamps one week in Aug. 2020.)

**Comment by cjardine-bsc** [comment]
We should circle back to this once we delete the extra CTT data we currently have. I'm adding this to the agenda for our next CTT call. We should understand a bit more about their timestamps. 

the take home is that we should really only report on data that have deployment IDs.

**Comment by cjardine-bsc** [comment]
add any ctt hits that come from a sensor station before 2018 to motus filter. 

RPI has bad timestamps, often returning 2017, but that is before we deployed the first sensor station.

**Comment by cjardine-bsc** [comment]
CTT believes these data are from bad timestamps. 

One useful, though not comprehensive, way to identify these is to filter out any hits that have timestamps before Jan 1 2019, when the first sensor station became available. I've added that to the filtering proc, which will now set the motus filter to true for all CTT runs before that date. 

This will not impact any of our public outputs because none of these records had deployments, but it will help out with data in the r package. And it makes me happy to have all the little runs correctly categorized into their neat little bins. :-) 

Implemented in Sandbox for now.

**Comment by denislepage** [comment]
There may be a handful of Cornell tags/receivers that pre-date 2019, but I don't think we need to overly worry about those. We should make sure we don't entirely delete them from taghits, but I'm ok if they are left out of summaries and activity data.

**Comment by denislepage** [comment]
There are 3 projects that have CTT tags in 2017 or 2018, for Sanderlings, Tree and Barn Swallows. 207, 224 and 222

We can likely use 2019 as the cutoff for summaries and imports, etc. moving forward. I will keep the hits for 2017 and 2018 in the database, but I won't be separating those for the valid tags or not in those 2 years, at least initially.
