### ISSUE TITLE
Send a confirmation email when users sign up for a new account.

### ISSUE THREAD

**Issue by Hussell** [MotusDev/Motus-TO-DO#119]
Split from #108

**Comment by zcrysler** [comment]
There's been a noticeable increase in the number of fake email registrations in the past few days - I think now users are getting en email when they register - but is motus@birdscanada.org getting an email before the user confirms?

**Comment by Hussell** [comment]
This isn't done. Currently the user just registers, and motus at birdscanada gets an email saying that a new user has registered.

How many fake email registrations have there been in the past few days? (Rough approximation acceptable.)

**Comment by zcrysler** [comment]
There were about 10 over the weekend, and about the same Monday/Tuesday.  It's usually maybe one a week or so

**Comment by denislepage** [comment]
That’s still not many, relative to what I have seen elsewhere, but that could potentially increase quite a bit.

There are a few changes we need with the registration, so we should think about how we will deal with them at the same time.


·         One is that PI will be required to provide their address.


·         The other is that users (all?) will be asked to confirm the acceptance of the policy.


·         I think people should be required to accept a confirmation email in order to be fully registered. That means that they can’t use the user pages (except the profile page) until they’ve confirmed, AND that they can’t be added to a project until they do either.


I think that we can deal with them all through the same process: automatically send the users to the profile page when try to access a page behind login until all the requirements are met, depending on their level. We would also need to modify the profile page in the following ways:


·         After the initial registration page, there should be a message indicating that they can fill in the optional information below, and that for PI, the contact information is required. Also should say that a confirmation email has been sent and that they must click on the link included to complete their registration.


·         I can’t remember the details of how we approve PI (an email sent to Zoe, I know, but how we store this in the database, etc.). We could add a line in the profile indicating that their request for PI is pending approval.



·         There should be a way for users to accept the revised policy. Something like this, for instance: “The Motus User Policy has changed. You must review the new policy and confirm that you accept. If you are a primary investigator, you must also indicate that you accept the Tag Fee policy.” (I would probably have the policy and the tag fee separated and only show the tag fee one for people who have asked to be, or confirmed, PI.



·         We can use the real_user field (maybe) to flag when people have accepted the confirmation email, and have a message saying: You have not yet confirmed your registration via email. If your registration token has expired, you can click the “Resend email” button to have a new one sent to you. Everyone already in the system would be approved automatically until the system is in place.

Exact details are still a bit fuzzy, but I’d like to see the above steps in place. We can discuss this Thu, maybe?

**Comment by zcrysler** [comment]
It might be getting worse, I've gotten ~20 fake emails just this morning.  This might be part of the plan, but can we make it so that I don't get an email until users have confirmed through the email they get (once that's setup)?

**Comment by Hussell** [comment]
Testing shows this system isn't working correctly in sandbox now. (I swear it was working earlier!) It's suffering from problems similar to #144 and #208.

**Comment by Hussell** [comment]
Seems to be working again, now that issues #144 and #208 have (apparently) been solved.

During testing, several emails were sent to motus@birdscanada.org with links that wouldn't have worked on the live system. Sorry about that, I'll try harder to remember to modify the destination address during testing.
