### ISSUE TITLE
Tag deployment upload bugs

### ISSUE THREAD

**Issue by ajmacdonald3** [MotusDev/Motus-TO-DO#1202]
A bulk tag deployment metadata upload resulted in three tags (tagIDs 65425, 65426, 65427) with warnings that they had been entered with a future deployment date. This wasn't the case, but maybe there is a discrepancy with UTC time? I am 7 hours behind UTC and entered the data about 5 hours after tagging the birds.

![image](https://user-images.githubusercontent.com/44593593/170556251-5f3d7f87-7771-4a0e-b135-500f389e8be7.png)

Opening the deployment on the website and re-entering the same time and saving changes fixed the issue, but ideally it shouldn't happen in the first place.

When you click on "Modify this deployment" and then click "Cancel" it goes to the [404 error page](https://motus.org/404.php) instead of back to the Manage Tags page.

**Comment by cjardine-bsc** [comment]
5 hours? You're a marvel.  5 hours after banding and I'm generally asleep....

Yes, The proc was using the local date from our servers in Ontario, not the UTC date. I've made that change. 

This might need to be a separate issue. Probably one for @Hussell eventually. : When you click on "Modify this deployment" and then click "Cancel" it goes to the [404 error page](https://motus.org/404.php) instead of back to the Manage Tags page.
