### ISSUE TITLE
Deprecating R package functions

### ISSUE THREAD

**Issue by steffilazerte** [MotusDev/Motus-TO-DO#1220]
I've been going through the package looking for historical artifacts that can be removed, streamlined, or moved to more appropriate places.

I would like to deprecate and eventually remove the following functions. @denislepage, @j-sayers, @ajmacdonald3, do any of you use these functions or know of active use cases for them?

[`safeSQL()`](https://github.com/MotusWTS/motus/blob/master/R/safeSQL.R)
By it's documentation this serves to protect from injection attacks and can work with both SQLite and MySQL connections. I suspect this is left over from dealing with server side Motus data processing. 
I propose to remove this function and use the standard `DBI::dbGetQuery()` and `DBI::dbExecute()` functions directly for transparency and simplicity. I can't see how injection attacks are relevant here since the databases are local, but there are easier ways around if that's a worry.

[`sqliteToRDS`](https://github.com/MotusWTS/motus/blob/master/R/sqliteToRDS.R)
Meant for saving parts of a SQLite data base to rds (flat R data file) quickly. I'm not sure how relevant this is to users. It's seems to be a bit finicky and only works on linux. Perhaps not the best thing to keep around and support?

**Comment by ajmacdonald3** [comment]
Personally, I don't use either of these functions and I'm not aware of active use cases for them. I think deprecating and removing these functions would be fine.

**Comment by j-sayers** [comment]
I've also never used either of those. As you mentioned, since the SQL involved is a local SQLite db, so protecting against an injection attack seems not relevant (maybe that wasn't the case previously?).

Looks like part of the purpose of `sqliteToRDS()` was dealing with large datasets in a more efficient manner — something that remains a challenge. But I doubt anyone is using this approach instead of `saveRDS()`. Providing better documentation/ diagram of the database (#550, #645) would go a long way to helping people construct their own minimal queries of just the required tables/ records in cases where alltags or even allruns is too unwieldy.

**Comment by steffilazerte** [comment]
Thanks for the feedback! Okay, so these functions aren't necessary, but would be good to add a diagram to perhaps the article on [Understanding Motus Data](https://motuswts.github.io/motus/articles/database-variables.html)? I'll take a look at the [discussion](https://github.com/MotusDev/Motus-TO-DO/discussions/1143) and see what I can come up with
