### ISSUE TITLE
Rerun receiver SG-9C9CRPI3381B 

### ISSUE THREAD

**Issue by leberrigan** [MotusDev/Motus-TO-DO#1256]
There are detections of real tags in the pre-processed data (running tag finder unifile), but nothing is showing up after it's uploaded to Motus.
Project 113, Deployment 8869.

**Comment by j-sayers** [comment]
Out of curiosity, has the unifile output been filtered for run length? Last time they had a similar issue it turned out most was due to short run lengths (including single hits) that were showing up by default in the standalone data but not on the web output; there were very few if any runs over 3 despite the proximity.

**Comment by Hussell** [comment]
It's in the queue, hopefully it'll be done by Monday.

**Comment by Hussell** [comment]
Still in the queue. I estimate it'll be done on Wednesday, based on the speed things were going over the weekend (which may not be representative of weekdays).

**Comment by Hussell** [comment]
It's done, finally. Many new detections: https://motus.org/data/receiver/deployment/plot?id=8869
