### ISSUE TITLE
Tag Never Deployed errors for tags under 3 years old

### ISSUE THREAD

**Issue by eageldart** [MotusDev/Motus-TO-DO#1275]
Tags that have not been registered to a project for over 3 years are being flagged under 'Tag Never Deployed' Critical Error 

For example, project 223: https://motus.org/data/issues?id=223#v_tag_not_deployed_released

These motusTagIDs (48319, 48335, 48321, 48322, 48258, 48251, 48249, 48566) say they were registered Fall 2020, so only 2 years ago.

**Comment by cjardine-bsc** [comment]
huh. Thats always been that way it seems. The proc puts everything between 9 months and 2 years in the v_tag_not_deployed_2 error and everything over 2 in v_tag_not_deployed_released. But you're right that doesn't match the descriptions. I've changed the proc. 

I do think we need to update the instructions for v_tag_not_deployed_2 (current version below) this needs a warning that the tag will be released after 3 years if they don't deploy them. It also needs to give instructions for the user to deprecate tags they do not intend to use instead of contacting motus. Are you okay to update that text? 

![image](https://user-images.githubusercontent.com/22172758/195212758-42451b21-0b26-42b7-8e5f-843c3b4a9afd.png)

**Comment by eageldart** [comment]
Catherine, I emailed you an updated Data Issues Instructions sheet with these instructions!

**Comment by cjardine-bsc** [comment]
Databases updated.
