### ISSUE TITLE
Error when adding user

### ISSUE THREAD

**Issue by zcrysler** [MotusDev/Motus-TO-DO#128]
I just got an error when adding a user to a new project (179), the error said an automatic message was sent so I'm assuming someone got an alert about this.  When I went back to the user page, the user had been added and saved correctly so I'm not sure why the error was generated.  I was having issues saving the short label which may be related but it's all in there now.

**Comment by denislepage** [comment]
I have not seen any errors come in for this.

**Comment by Hussell** [comment]
Denis sent an error message in a later email. It appears to come down to a null pointer error due to the project having a null primary contact (projects.lead_user_id). Looking in the database, there are 12 projects with a null in that column. Looking at the code for creating and editing projects, I'm not sure how this could have happened: when creating a new project, the user who creates it is automatically set as the primary contact; when editing a project the primary contact field is mandatory; and it isn't permitted to delete the primary contact when managing the users.

**Comment by zcrysler** [comment]
Would this happen if I create a project through the database?  I always add a user but maybe somehow they aren't set as the primary?

**Comment by Hussell** [comment]
Yes, that would do it.

**Comment by zcrysler** [comment]
Ok, so from here on when I create a project for someone, the best way to do it would be:
- create project through the website
- add other user
- change primary contact from me to them
- delete myself from user list

Or I guess just login with their info and create a project as them

**Comment by Hussell** [comment]
Um. I just tried this and it seems you can't delete yourself from a project, even if you're an administrator and not the primary contact. I'll check in a fix for that. Even after fixing that, the workflow is ugly. (Too many clicks to get everything set up.) I think I assumed that it would be PIs creating projects, and they'd therefore naturally want to be registered with the project. Maybe something to discuss on the call.

The projects with no primary contact are:
30	Range Tests
131	York University Killdeer
145	Kirtland's Warbler Tracking, Bahamas - Michigan
148	Indiana
149	Belize
156	Black Tern movements - breeding/migration
158	Eastern Ontario Grasshopper Sparrow
162	Western MA Tree Swallows
165	Southern Michigan Motus Array
174	Bahia Lomas Shorebirds
176	Sample Data
178	Toronto Zoo

Zoe, you should save a primary contact for these projects on the "Manage Project" page.

Four of the projects don't have any registered users at all! I'm not sure who should be assigned to these projects, but someone should be, and someone should be the primary contact.
30	Range Tests
148	Indiana
158	Eastern Ontario Grasshopper Sparrow
176	Sample Data

**Comment by zcrysler** [comment]
The projects listed above with no primary user do have a primary users listed in the projects page online eg project 131: https://motus.org/data/project/edit?id=131, this automatically gets set as the first user I add to the project.  They don't have a user in the database but I don't have permissions to update that field, so I'm kicking this issue back to you Jeremy

I added users for projects that previously had none registered, I made Stu the contact for the sample data project since we're all admins but can add others if we feel it's necessary.  Adding users to these projects resulted in the error message that started this thread, but they've all been saved correctly and have primary users online but not in the database.

For now, if I login to the website with as the user that needs a new project and create it that way, then that eliminates the need for me to remove myself from that project, or having to create it through the database.  Maybe not the best long term solution if there's actually a need for users to delete themselves, but for now it would stop this from continuing to happen.

**Comment by Hussell** [comment]
Go to https://motus.org/data/project/edit?id=131 , pick a user to be primary contact, and hit the save button at the bottom of the page. That updates the database.

**Comment by denislepage** [comment]
If that helps to enforce a rule, we could make the primary contact a required field in the table. Any attempt to save to the table without one would fail, including thought Access.

I think that all projects should have at least a primary contact, and probably at least 1 user with project edit permissions also. A project manager could be able to remove themselves from the list, but only if another user has already been added and if he/she is no longer the primary contact.

Maybe the best way to do this is to :


-          Ensure that all projects have a primary contact identified and that this person has PI permission (I think)

-          Ensure that the primary contact is listed as a project user and has full project management permissions

IE:


-          You can’t save a project without a primary user (who has PI level?). Is there any downside to allow non PI’s to have full permission on a single project?

-          When you create a new project, the current user is used as the default primary contact and is added to the project users with full edit permissions

-          You cannot remove a user that is the primary contact, or downgrade the project permissions for such users

-          I think should be able to remove/downgrade yourself if you have project edit permissions (or admin). Of course, this probably needs to come with proper warnings, or we could restrict this option to admin users only.

We should check whether our existing data match those conditions before they are implemented.

Denis

**Comment by zcrysler** [comment]
A few of them worked that way, the ones below aren't being assigned a primary user in the database despite going to the project page and saving repeatedly

30	Range Tests
156	Black Tern movements - breeding/migration
158	Eastern Ontario Grasshopper Sparrow
162	Western MA Tree Swallows
165	Southern Michigan Motus Array
174	Bahia Lomas Shorebirds
176	Sample Data
178	Toronto Zoo

For project 156 I tried changing the lead user and saving, it refreshed the page but had switched back to the original lead user that was already listed - so for some reason it's not actually saving, but there's no indication of that online when you click save.

**Comment by Hussell** [comment]
... it worked for me. I've saved the projects with the first user as primary contact. The only exception is 176, which currently has no users (which should also be impossible...)

**Comment by zcrysler** [comment]
176 is the sample data, I had added Stu as the user by default and it saved...or it looked like it did since it clearly didn't.  

I added him again and got the same error, it looks like it's saved in the database

**Comment by Hussell** [comment]
I think I fixed the bug that was causing the manage-project page to sometimes fail to save, without giving an error message. It depended on a certain sequence of events, which is why things sometimes worked sometimes didn't.

By my count that makes three bugs found and fixed while dealing with this issue:
1. Null pointer error when adding a user to a project with null primary contact.
2. Administrators couldn't remove themselves from a project's list of users.
3. Saving a project's basic info failed under certain conditions, and gave no error message (but no success message either)

2 & 3 are done (on sandbox & beta), but 1 has only been "fixed" by assigning a primary contact to every project and trusting that Zoe will add a primary contact in future when she manually creates a project. We could make this more bulletproof by putting a non-null constraint on the column in the database, as per Denis' suggestion.

Denis' other suggestions are implemented in code - as they always have been. In fact, the null pointer error was happening during a check to make certain the primary contact can't have their project management permissions downgraded (which assumes a primary contact exists.) I don't know of any way to add constraints to the database which would guarantee the primary contact always be registered with the project, since there would be a chicken-egg problem in creating the project and registering the primary contact.
