### ISSUE TITLE
Deployment of SGs with a CTT integrated antenna

### ISSUE THREAD

**Issue by eageldart** [MotusDev/Motus-TO-DO#1284]
When station receivers are switched from a CTT Sensorstation, to another receiver type, the deployment for the new (non-CTT receiver) has an Integrated (CTT Sensorstation) under Dongle type that the user cannot delete. 

How does this happen? Lucas and I did some testing to find this out. 

- We made a new test station on project 0: https://motus.org/data/receiverDeployment?id=9155
- We first added a deployment with a CTT sensorstation and include a 'CTT integrated' antenna
- We terminated the deployment and then redeploy it, checking the box which says 'Keep the antenna configuration from the previous deployment' or whatever and uncheck the box which says 'Keep the same receiver'
- Selected a SensorGnome receiver when prompted and then keep the antenna config when asked again
- This resulted in a deployment of an SG with a CTT integrated antenna

Lucas deleted all CTT integrated antennas for non CTT Sensorstations. But we still have the example we created: Project 0, Station ID 12903

Denis, is there something you can do to prevent this from happening?

**Comment by denislepage** [comment]
I'd have to look again at the process. We are presumably allowing copying deployments at a station not on a receiver basis (like we used to), and there are legitimate reasons to potentially allow changing the receiver type, yes?

One way to deal with this is to only support the copying feature when the receiver type remains compatible. There are potentially times when switching between receiver types may happen (e.g. replacing a SensorGnome by a SensorStation), but it may not be common enough that we can't just ask people to enter a brand new deployment instead in those cases. 

If we allow it, the alternative, which is perhaps about not much more complicated to implement could be to do some cleanup to remove specific antennae that don't make sense by comparing the receiver types between the old and the new deployment. This is presumably the approach you were asking for, and I think that's fine. Are there any other features of deployments that would also not be compatible among receiver types?

**Comment by denislepage** [comment]
There's also 2 ways I can think of dealing with the 2nd option: we just delete (or prevent copying) antennae that are not compatible (perhaps with a warning to users, but that may not be highly necessary), OR, I can also copy them across at first, and modify the way the page is saved, so incompatible antennae get removed at that point. One small advantage if the latter approach is that it would potentially deal with any circumstances where the antennae is no longer compatible (e.g. changing the receiver type directly in the database), but those cases would be presumably quite rare, and I might be more inclined to do option 1 (not copy incompatible antennae).

**Comment by denislepage** [comment]
I just implemented something in sandbox for testing. 

1. Invalid dongle types for a receiver will no longer show in the list within the deployment, which should prevent any such related issues where the dongles saved for an antenna is not available in the dropdown list (one remaining issue is when the dongle_type value is the correct, but using a wrong case, such as FunCube Pro instead of Funcube Pro, and we could change the database case sensitivity for this field to prevent that).

2. Whenever the deployment is saved (including when saving edits, or copying antenna config), invalid antennae will be deleted from the database.

I made an exception so antennae that do not have a dongle_type identified are considered valid. It might be useful to disallow that, and create a type called Unknown that can be used in any receiver type, but we can deal with this a bit later.

There are many such examples in sandbox, but only one left in the main db, for deployment ID 9155 identified above (we'll need to copy these changes to beta11 for testing on the main db).

Ready for testing in sandbox.

**Comment by denislepage** [comment]
Somewhat separate issue that we discussed today: I have now changed all the antenna records to set the dongle_type. The majority (1300 out of 1500) were Lotek receivers, which was unambiguous (Lotek Integrated). A few were CTT integrated with 434 freq, and all the 150 and 161 I set to Funcube unconfirmed. 

Finally, I changed to dongle_type field to be required in the table, so that might throw an error if we allow trying to save without a dongle type.

**Comment by denislepage** [comment]
OK, I think I have figured it out.

Copying antennae will now initially preserve the invalid dongle types, but the web interface will show a drop down list instead of a fixed value, and the frequency and port # will be shown as null (a dongle type is required to allow an entry). The same will happen if there are any invalid combinations already in the database from a previous source.

It should no longer be possible to save invalid dongle types in the database, so I removed my script from yesterday that deletes upon saving, but invalid types could remain if the user closes the page after copying and before saving. Perhaps we can put this as a data validation, but it should be rare.

Now, if one tries to click Save immediately after copying and there were some invalid types (missing dongle type), the user will be prompted to select the values. 

However, I have also made some changes that disables the required attribute on the drop down lists if the user ask to remove the antenna record (the checkbox), so it will not force the user to enter values if the record is going to be deleted.

https://beta.motus.org/data/station/deployment/edit?projectID=0&id=9155&edit=1

![image](https://user-images.githubusercontent.com/21110542/198422760-2d5b88b0-e383-449f-a430-e882c3e4bb89.png)

Finally, as a quick fix, I changed the order of the frequencies so they are displayed in decreasing order. For now, this is only relevant for SDR dongles that support the 3 frequencies for N. Amer., Europe and Asia. That forces 166.38 at the top. We may eventually need a different approach, including trying to figure out the default value based on the deployment location or a project default that we could ask users to select based on major regions.

Ready for testing in beta and/or sandbox! @eageldart @leberrigan You may want to recreate the full steps above to confirm what happens when copying from SS to SG. I haven't tested that yet.

**Comment by eageldart** [comment]
I tested in Sandbox and when I copy antennas configuration from a SS to SG, I get "No antenna records defined" 

I tried copying three Funcube Pro's and an Integrated CTT Sensorstation

[Test CTT Integrated Dongle2](https://sandbox.motus.org/data/project/stations?projectID=0&setStationId=2618)

**Comment by denislepage** [comment]
Sandbox may just need a restart. Was all working in beta for me
