### ISSUE TITLE
MERGE Deprecated Projects

### ISSUE THREAD

**Issue by leberrigan** [MotusDev/Motus-TO-DO#1285]
There are projects which can be merged below (@eageldart, @j-sayers, @ajmacdonald3: please add to this list if there are any others):

Project ID | Project Name | Reason to merge | Project ID to merge with
 -- | -- | -- | --
442 | Motus Test 2 | No tags or stations registered. David La Puma says it's okay to go. | 251

**Comment by cjardine-bsc** [comment]
Where possible, we can merge projects into another existing project. All the registered tag/sensor details would move to the new project and the old project would be removed. This is the preferred approach (since we can't delete tags, deleting projects can be complex unless we have another project to move them to. Thanks!

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
From: Lucas Berrigan ***@***.***>
Sent: Wednesday, October 26, 2022 11:51:02 AM
To: MotusDev/Motus-TO-DO ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [MotusDev/Motus-TO-DO] Delete Deprecated Projects (Issue #1285)


There are projects which can be deleted below ***@***.***<https://github.com/eageldart>, @j-sayers<https://github.com/j-sayers>, @ajmacdonald3<https://github.com/ajmacdonald3>: please add to this list if there are any others):

Project ID      Project Name    Reason to delete
442     Motus Test 2    David La Puma says it's okay to go

**Comment by leberrigan** [comment]
Okay, thanks for the clarity, Catherine!

**Comment by cjardine-bsc** [comment]
Run!
