### ISSUE TITLE
Motus /api/receivers/deployments is missing receivers with active deployments

### ISSUE THREAD

**Issue by tve** [MotusDev/Motus-TO-DO#1303]
SG-68B4RPI33F06 is part of project #1: https://motus.org/data/receiver?id=4729 and has an active deployment: https://motus.org/data/receiverDeployment?id=8346 however, it is missing in the response for /api/receivers/deployments:

```
$ curl -i "https://motus.org/api/receivers/deployments?json=\{\"date\":\"$(date -u +%Y%m%d%H%M%S)\",\"serialNo\":\"SG-68B4RPI33F06\"\}"
HTTP/1.1 200 200
Content-Type: application/json;charset=UTF-8
Server: Microsoft-IIS/8.5
X-Powered-By: ASP.NET
Date: Fri, 18 Nov 2022 18:56:19 GMT
Content-Length: 17

{"version":"2.0"}
```

Here's a call without the `SerialNo` filter and using jq to attempt to get the record for this SG:
```
~> curl "https://motus.org/api/receivers/deployments?json=\{\"date\":\"$(date -u +%Y%m%d%H%M%S)\"\}" | jq '.data[ | select(.receiverID == "SG-68B4RPI33F06")'
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 2373k  100 2373k    0     0  1203k      0  0:00:01  0:00:01 --:--:-- 1203k
```

For comparison, here are the same calls for an SG that is included:

```
~> curl -i "https://motus.org/api/receivers/deployments?json=\{\"date\":\"$(date -u +%Y%m%d%H%M%S)\",\"serialNo\":\"SG-D011RPI31F2B\"\}"
HTTP/1.1 200 200
Content-Type: application/json;charset=UTF-8
Server: Microsoft-IIS/8.5
X-Powered-By: ASP.NET
Date: Fri, 18 Nov 2022 19:05:50 GMT
Content-Length: 914

{"version":"2.0","data":[{"motusRecvID":5350,"recvProjectID":1,"receiverID":"SG-D011RPI31F2B","receiverType":"SENSORGNOME","recvDeployID":9148,"deploymentStatus":"active","deploymentName":"TvE test station","siteName":"TvE test station","dtStart":"2022-10-24 00:00:00 +00:00","dtEnd":null,"tsStart":1.6665696E9,"tsEnd":null,"latitude":34.49920000,"longitude":-119.81670000,"elevation":630.0,"isMobile":false,"macAddress":"0","locationPrecision":"Exact"},{"motusRecvID":4718,"recvProjectID":460,"receiverID":"SG-D011RPI31F2B","receiverType":"SENSORGNOME","recvDeployID":8308,"deploymentStatus":"terminated","deploymentName":"tve-home","siteName":"tve-home","dtStart":"2021-11-06 00:00:00 +00:00","dtEnd":"2022-10-23 23:59:00 +00:00","tsStart":1.6361568E9,"tsEnd":1.6665695400000002E9,"latitude":34.49940000,"longitude":-119.81820000,"elevation":630.0,"isMobile":false,"macAddress":"0","locationPrecision":"Exact"}]}⏎                                                                                       ~> 

~> curl "https://motus.org/api/receivers/deployments?json=\{\"date\":\"$(date -u +%Y%m%d%H%M%S)\"\}" | jq '.data[] | select(.receiverID == "SG-D011RPI31F2B")'
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 2373k  100 2373k    0     0  1156k      0  0:00:02  0:00:02 --:--:-- 1156k
{
  "motusRecvID": 5350,
  "recvProjectID": 1,
  "receiverID": "SG-D011RPI31F2B",
  "receiverType": "SENSORGNOME",
  "recvDeployID": 9148,
  "deploymentStatus": "active",
  "deploymentName": "TvE test station",
  "siteName": "TvE test station",
  "dtStart": "2022-10-24 00:00:00 +00:00",
  "dtEnd": null,
  "tsStart": 1666569600,
  "tsEnd": null,
  "latitude": 34.4992,
  "longitude": -119.8167,
  "elevation": 630,
  "isMobile": false,
  "macAddress": "0",
  "locationPrecision": "Exact"
}
{
  "motusRecvID": 4718,
  "recvProjectID": 460,
  "receiverID": "SG-D011RPI31F2B",
  "receiverType": "SENSORGNOME",
  "recvDeployID": 8308,
  "deploymentStatus": "terminated",
  "deploymentName": "tve-home",
  "siteName": "tve-home",
  "dtStart": "2021-11-06 00:00:00 +00:00",
  "dtEnd": "2022-10-23 23:59:00 +00:00",
  "tsStart": 1636156800,
  "tsEnd": 1666569540.0000002,
  "latitude": 34.4994,
  "longitude": -119.8182,
  "elevation": 630,
  "isMobile": false,
  "macAddress": "0",
  "locationPrecision": "Exact"
}
```

**Comment by cjardine-bsc** [comment]
The deployment is a test, which are excluded from Lucas's Dashboard API calls.

**Comment by tve** [comment]
This isn't "Lucas's Dashboard API". This is the official published API: https://github.com/MotusDev/MotusAPI/blob/master/Motus%20SG%20API%202.0.md#23-list-receiver-deployments-flat-version
I'm using this call to determine which deployment a sensorgnome belongs to so it can upload data files.

**Comment by cjardine-bsc** [comment]
Which user are you utilizing to pull the data? The issue is that it's a test deployment, so it will be excluded from certain views.

**Comment by tve** [comment]
I'm using unauthenticated calls. Which view includes the test receivers?

**Comment by j-sayers** [comment]
The station is defined as a Test station. Other receiver deployments associated with this test station  are evidently exposed, at least based on continued successful uploads.

eg https://motus.org/data/receiverDeployment?id=8495 running the same software image

**Comment by cjardine-bsc** [comment]
First mystery:

The deployment_id (8346) that Thorsten mentions is listed as a test in the deployment table, and the station table. 
The deployment_id (8495) that Josh mentions is **not** listed as a test in the deployment table, but is listed as a test in the station table. 

So it appears that the difference is that the API is filtering out tests based on the field in the deployment table. That was an error that I've fixed (yay!), the views are now using the test field from the station table, not the deployment table (For context, we are in the process of removing the test field from the deployment table and using the new station table to track that information instead. That transition is just waiting on updates to the website to remove references to the test field in the deployment field.) That doesn't solve this issue, (actually it makes it worse) but it does explain the previous discrepancy. 

As for the API excluding test data, I can't speak to the original purpose of this API, but we have two types of views in the database. Base-views that contain all the data but require authentication to access, and Public-views that contain only public facing data (excluding sensitive data and test data). I'd have to dig into the code to confirm, but I suspect this API uses the data views when unauthenticated, and base views when authenticated. It does mention in the documentation that "Some receiver information is only visible to authenticated users."  which supports my hunch. We will never provide unauthenticated access to the Base-views because we have some sensitive data contained in those that we have agreed to not release publicly. 

Solutions:
1. Authenticate your call with an admin account. There are some receiver deployments that are not tests but are excluded from the public-views because they are in sensitive location (not many, only a couple of the 1000s of deployments) but authentication will give you access to those, which it sounds like you need. 

2. Set up a separate API for you that uses a new view that only filters our sensitive data and not test data. I don't think this meets your needs due to the sensitive stations mentioned above. 

Happy to discuss or if the above seems off I can sleuth further.

**Comment by tve** [comment]
Thanks for looking into this!! Maybe the easiest is not to support uploads from SGs in test stations for now. I can figure out later how to manually patch in a deployment.
