### ISSUE TITLE
Station map not loading on Station Management Page

### ISSUE THREAD

**Issue by eageldart** [MotusDev/Motus-TO-DO#1333]
Station map is not loading on Station Management Page

https://motus.org/data/project/stations?projectID=2
![image](https://user-images.githubusercontent.com/94930170/223828644-49af91df-52e2-4123-b3b1-c75ef6811578.png)

**Comment by Hussell** [comment]
Bug introduced with the fix for #1305 - station names were being communicated to the page in quoted strings '<station name>', but station names may contain arbitrary characters, including apostrophes. So everything after that part of the page was broken, including loading the map.

Names are being encoded now on sandbox and beta, and live as soon as the next deployment is done.

**Comment by denislepage** [comment]
The stationNames variable is not being properly escaped, so there's a single quote breaking the script for one of the stations (Matthew's Lake). I'll have a fix almost read to test in beta.

**Comment by denislepage** [comment]
Hm. Interesting. Beta was actually working fine already, and the names appear encoded (Matthew\x27s\x20Lake). Did someone already make a fix today? Ah, yes, I can see that Jeremy put a fix in beta, which I overrode. I used the JSONValue class to convert to a proper JSON object in my case.

**Comment by denislepage** [comment]
Posted to live.
