### ISSUE TITLE
Additional (problematic) fields are being downloaded when using tag deployment csv

### ISSUE THREAD

**Issue by j-sayers** [MotusDev/Motus-TO-DO#1334]
The csv download process for bulk tag deployments is introducing new fields (the two "last edit" fields)

![image](https://user-images.githubusercontent.com/55001144/224052513-c074965c-6d5b-40bc-b207-5a0eb6524345.png)

I don't believe the first of these was ever included in the template before, and certainly the second one is causing issues during data validation.

![image](https://user-images.githubusercontent.com/55001144/224052926-96ab9be5-d648-444a-8039-36b2266521a8.png)

**Comment by j-sayers** [comment]
The first `lastEdit` field is apparently not unexpected (though I guess it probably isn't present if a project has no deployments yet).

So it's just the second field that is causing the problem.

**Comment by cjardine-bsc** [comment]
Hi @j-sayers Where are you downloading a template that has two lastEdit dates in it?

URLs are always helpful to include in issues if possible. I'm using the "tags deployments" button on this page: https://sandbox.motus.org/data/project/tags/template?projectID=0

![image](https://user-images.githubusercontent.com/22172758/228389253-1b550615-3e65-4800-ae89-13756a0fdc88.png)

Using that I'm only getting one lastEdit field on live:

![image](https://user-images.githubusercontent.com/22172758/228389096-2221325a-c496-414e-964e-27579e674d4e.png)

And sandbox: 

![image](https://user-images.githubusercontent.com/22172758/228389162-2fc66272-ea9b-4171-bde8-b8a91d4680d5.png)

Let me know if you can point me in the right direction and I'll replace the doublemint gum with trident.

**Comment by j-sayers** [comment]
Same link, but different project (on live). https://motus.org/data/project/tags/template?projectID=357. Same project with issues #1335

**Comment by cjardine-bsc** [comment]
Ah-ha! Thanks Josh, that helped me figure it out. 

Slightly different issue. This project had uploaded and processed a template earlier. Since I haven't yet changed the data processing proc in live the lastEdit field is being saved as a custom deployment property (in tags_properties) and then added back to the template. Hence two fields. 

The trick here is to make sure that the lastEdit field is not written to api_tag_properties by the bulk tag import API. In the mean time I've deleted any "lastEdit" values from the tags_properties table and removed it from the template in live until we get things updated. 

Related to #1127 I'll close this one and fix it there.
