### ISSUE TITLE
Notification centre not updating

### ISSUE THREAD

**Issue by zcrysler** [MotusDev/Motus-TO-DO#140]
I created a new deployment to cover most of the detection data that fell outside of deployments, but even after rerunning the validation it's still reporting an error: https://motus.org/data/issues?id=38#v_sensor_hits_out_deploy

It's also saying there are no antenna bearings for the deployment I just created (4476), but clicking on the link shows that the bearings do exist in the deployment.

I realize there will still be some detections in March that fall outside of the 2 existing deployments, but most of these reported detections should be covered by the deployment I created.

**Comment by cjardine-bsc** [comment]
I found the reason why the data validation center is still showing these taghits as orphaned even though a deployment now exists. 

tr_sensor_deployments_update is updating TaghitsSummaries when a deployment is updated/inserted. It calls prTaghitsSummariesSensorDeployID which deletes records from sg_taghits_daily where sensor_deploy_id = “the updated deploy_id”. If the deployment ID is new, the delete statement does not remove the records from sg_taghits_daily because their sensor_deploy_id is set to zero. 

Because these records didn't already have a deployment, they are not being deleted from sg_taghits_daily. (sensor_id =0  and sensor_deploy_id =0).

SELECT [device_id]      ,[sensor_id]      ,[tag_id]      ,[sensor_deploy_id]      ,[tag_deploy_id]
      ,[date]      ,[batch_id]      ,dbo.ts2datetime([min_ts])      ,dbo.ts2datetime([max_ts])      ,[n_hits]
  FROM [motus].[dbo].[sg_taghits_daily]
  where device_id = 74 and sensor_deploy_id = 0 

New records are being inserted correctly, but the old records haven't been deleted. 

SELECT  [device_id]      ,[sensor_id]      ,[tag_id]      ,[sensor_deploy_id]      ,[tag_deploy_id]      ,[date]
      ,[batch_id]      ,dbo.ts2datetime([min_ts])      ,dbo.ts2datetime([max_ts])      ,[n_hits]  
FROM [motus].[dbo].[sg_taghits_daily]
  where device_id = 74 and sensor_deploy_id = 4476 

So, we need a method to delete records from a certain device_id from sg_taghits_daily when they now match a sensor_id and sensor_deploy_id. This will apply to both the inserts and updates of the sensor_deployments table. Anywhere taghits didn't previously overlap a sensor deployment and they now do. 

I see three approaches

1.       Do not include records in sg_taghits_daily that do not have sensor_ids or sensor_deploy_ids. This is easy(huzzah!) but has two downsides. It will cause these hits to be removed from the public summaries and I’ll have to alter prDataValidation_pr to rely on the raw tables instead of the summary (slower to validate data).
2.       Create a separate proc that goes through and cleans up sg_taghits_daily and removes records that now match.
3.       Create a new proc like prTaghitsSummariesSensorDeployID but one that does this by deviceID 

I think I like the proc by deviceID approach (door number 3). It would look like the below, but right now it's running quite a bit more slowly than the prTaghitsSummariesSensorDeployID. I can try to optimize for this approach, but before doing so I wanted to see if you want to keep barking up this tree or if you’d prefer to pursue one of the other options. 


USE [motus_sandbox]
GO

CREATE PROC [dbo].[prTaghitsSummariesDeviceID]
      @deploy_id  int
AS

DECLARE @ts_min float = dbo.datetime2ts('2010-01-01')
DECLARE @ts_max float = dbo.datetime2ts(getdate())
DECLARE @device_id int

SET @device_id = (SELECT c.id from sensor_deployments a 
                                                                                                INNER JOIN sensors b on a.sensor_id=b.id 
                                                                                                INNER JOIN sensors_hash_keys c on b.receiverID=c.receiverID 
                                                                        WHERE a.id = @deploy_id)

DELETE FROM sg_taghits_daily where device_id = @device_id

RAISERROR ('    Creating taghits_daily summary for sensor device ID %i', 0, 1, @device_id) WITH NOWAIT

INSERT INTO sg_taghits_daily (device_id, sensor_id, tag_id, sensor_deploy_id, tag_deploy_id, date, batch_id, min_ts, max_ts, n_hits)

select c.motusDeviceID, ISNULL(f.sensor_id,0) as sensor_id, d.motusTagID, ISNULL(b.recvDeployID,0) as sensor_deploy_id, 
ISNULL(b.tagDeployID,0) as tag_deploy_id, cast(dbo.ts2datetime(a.ts) as date) as [date], c.batchID, 
MIN(a.ts) as minTS, MAX(a.ts) as maxTS, count(*) as nHits
from sg_taghits a 
inner join sg_taghits_deploy_id b on a.hitID = b.hitID
inner join sg_batches c on a.batchID = c.batchID
inner join sg_runs d on a.runID = d.runID
left join sensor_deployments f on b.recvDeployID = f.id
where c.motusDeviceID = @device_id
and freqSD < 0.1 and d.[len] > 2
--and a.ts >= @ts_min and a.ts <= @ts_max
group by c.motusDeviceID, ISNULL(f.sensor_id,0), d.motusTagID, 
ISNULL(b.recvDeployID,0), ISNULL(b.tagDeployID,0), cast(dbo.ts2datetime(a.ts) as date), c.batchID

DELETE FROM sg_taghits_runs where (device_id = @device_id)

RAISERROR ('    Creating taghits_runs summary for sensor deployment %i', 0, 1, @deploy_id) WITH NOWAIT

INSERT INTO sg_taghits_runs (device_id, sensor_id, tag_id, sensor_deploy_id, tag_deploy_id, batch_id, run_id, ant, min_ts, max_ts, n_hits)
select c.motusDeviceID, ISNULL(f.sensor_id,0) as sensor_id, d.motusTagID, ISNULL(b.recvDeployID,0) as sensor_deploy_id, ISNULL(b.tagDeployID,0) as tag_deploy_id, c.batchID, d.runID, d.ant, 
MIN(a.ts) as minTS, MAX(a.ts) as maxTS, count(*) as nHits
from sg_taghits a 
 inner join sg_taghits_deploy_id b on a.hitID = b.hitID
inner join sg_batches c on a.batchID = c.batchID
inner join sg_runs d on a.runID = d.runID
left join sensor_deployments f on b.recvDeployID = f.id
where  c.motusDeviceID = @device_id
and freqSD < 0.1 and d.[len] > 2
and a.ts >= @ts_min and a.ts <= @ts_max
group by c.motusDeviceID, ISNULL(f.sensor_id,0), d.motusTagID, ISNULL(b.recvDeployID,0), ISNULL(b.tagDeployID,0), c.batchID, d.runID, d.ant

**Comment by cjardine-bsc** [comment]
FROM DENIS: 

In theory, I’m not opposed to door number 3, but we’d have to make that much faster. For that reason, door #2 may be more appealing, at least until/if we can figure that out.

This is very fast when limited to the specific device/deployment, and could be added to the existing prTaghitsSummaries proc. The same approach would likely be needed in other summary procs. 

DECLARE @deployID int = 4476 -– not needed. comes from the proc parameter
DECLARE @deviceID int
select @deviceID = c.id from sensor_deployments a inner join sensors b on a.sensor_id = b.id inner join sensors_hash_keys c on b.receiverID = c.receiverID where a.id = @deployID 

--delete from a
select * from sg_taghits_daily a where a.device_id = @deviceID and sensor_id = 0 
and exists (select * from sg_taghits_daily b where a.device_id = b.device_id and a.date = b.date and sensor_deploy_id = @deployID )
      
--delete from a
select * from sg_taghits_runs a where a.device_id = @deviceID and sensor_id = 0 
and exists (select * from sg_taghits_runs b where a.device_id = b.device_id and a.run_id = b.run_id and sensor_deploy_id = @deployID )

You’d also need to do a one-time delete for all receivers:

select * from sg_taghits_runs a where sensor_id = 0 
and exists (select * from sg_taghits_runs b where a.device_id = b.device_id and a.run_id = b.run_id and sensor_deploy_id > 0)

You can check that I haven’t left out some logic.

Denis

**Comment by cjardine-bsc** [comment]
Implemented.

**Comment by Hussell** [comment]
Dosen't seem to have worked: all issues still present after re-running the validation.

The antenna bearing thing may be because there's no bearing for the whip antenna?

**Comment by cjardine-bsc** [comment]
Ah, yeah we missed something. 

The taghits daily summary depends on the hit ts. 

There can be two records in one of the taghits summary tables for the same day if some of the hit ts’s fall outside the deployment for that day. 

So we should be checking to make sure the new deployment covers the whole ts for a given day:

--cleanup old entries where deploy_id = 0 
delete from a
from sg_taghits_daily a where a.device_id = @device_id and sensor_id = 0 
and exists (select * from sg_taghits_daily b where a.device_id = b.device_id and a.date = b.date and sensor_deploy_id = @deploy_id
AND a.min_ts between b.min_ts and b.max_ts and a.max_ts between a.min_ts and b.max_ts)

The cases where there are hits outside of the deployment there will still be records left in the summary table where deploy_id =0. The number of hits might be wrong for these rare cases, but it will be enough for users to see they need to change the times of their deployment on that given day. 

The changes had only been implemented in sandbox for testing. I've now deployed them to live. 

I also ran a one-time clean-up on the DB.

**Comment by cjardine-bsc** [comment]
Bah, nope. That's not going to work either. I was being dumb. 

What I actually need is below: 


delete from a
from sg_taghits_daily a 
CROSS JOIN sensor_deployments c 
where a.device_id = @device_id and a.sensor_id = 0 and c.id = @deploy_id
AND exists (select * from sg_taghits_daily b where a.device_id = b.device_id and a.date = b.date and sensor_deploy_id = @deploy_id
AND a.min_ts between dbo.datetime2ts(c.dt_start) and dbo.datetime2ts(c.dt_end) 
AND a.max_ts between dbo.datetime2ts(c.dt_start) and dbo.datetime2ts(c.dt_end))

delete from a
from sg_taghits_runs a 
CROSS JOIN sensor_deployments c 
where a.device_id = @device_id and a.sensor_id = 0 and c.id = @deploy_id
AND exists (select * from sg_taghits_runs b where a.device_id = b.device_id and a.run_id = b.run_id and sensor_deploy_id = @deploy_id
AND a.min_ts between dbo.datetime2ts(c.dt_start) and dbo.datetime2ts(c.dt_end) 
AND a.max_ts between dbo.datetime2ts(c.dt_start) and dbo.datetime2ts(c.dt_end))

delete from a
from sg_taghits_daily a 
CROSS JOIN tags_deployments c 
where a.tag_id = @tag_id and tag_deploy_id = 0 and c.id = @deploy_id
and exists (select * from sg_taghits_daily b where a.device_id = b.device_id and a.date = b.date and a.sensor_deploy_id = b.sensor_deploy_id 
and a.tag_id =b.tag_id and tag_deploy_id = @deploy_id
AND a.min_ts between dbo.datetime2ts(c.dt_start) and dbo.datetime2ts(c.dt_end) 
AND a.max_ts between dbo.datetime2ts(c.dt_start) and dbo.datetime2ts(c.dt_end))

delete from a
from sg_taghits_runs a 
CROSS JOIN tags_deployments c 
where a.tag_id = @tag_id and tag_deploy_id = 0 and c.id = @deploy_id
and exists (select * from sg_taghits_runs b where a.device_id = b.device_id and a.sensor_deploy_id = b.sensor_deploy_id and a.run_id = b.run_id 
and a.tag_id =b.tag_id and tag_deploy_id = @deploy_id 
AND a.min_ts between dbo.datetime2ts(c.dt_start) and dbo.datetime2ts(c.dt_end) 
AND a.max_ts between dbo.datetime2ts(c.dt_start) and dbo.datetime2ts(c.dt_end))

Zoe you can test this in the morning. We'll still need to do a full refresh of the summary tables so that the old data is correct, but this should keep the new data in line.

**Comment by denislepage** [comment]
Have you tested the response time? I find the CROSS JOIN queries rather scary here, and it may end up being faster to regenerate the whole summary by receiver. Either way, this may end up being to much CPU heavy?

Is the issue here not that the delete statements I suggested are working based on the new dates, rather than the previous ones before the update? If so, that might require calling the delete statements from a trigger, based on the values of the deleted table? 

Would that solve the problem?

**Comment by zcrysler** [comment]
Did a test and seems to work! I'm not sure about response time, I reran the validation and then did something else for maybe 10 mins and it was done when I got back to it

**Comment by cjardine-bsc** [comment]
Yes, I tested the response time (I too was nervous about the cross join), but it was < one second.  

Regenerating the whole summary by receiver and tag_id works (see code above: door number 1) but still seems to be slower on the tests I'm doing using the cross join. I think the inserts needed for those processes are more CPU heavy than the cross join on the deployment tables.

Calling the delete from the trigger wont work (the proc inserting the new summaries needs to run first, and that's done through the queue) BUT there is a way to do this without the cross join. I'll just pull the start and end date of the deployment into a proc variable and remove the join. :)

**Comment by cjardine-bsc** [comment]
I've made a that change. Zoe will you test one more time?

Thanks!

**Comment by zcrysler** [comment]
working great!
