### ISSUE TITLE
PI approval key invalid

### ISSUE THREAD

**Issue by zcrysler** [MotusDev/Motus-TO-DO#144]
Trying to approve a new user this morning through the following link http://motus.org/data/admin/approvePI?user=2886&key=C3ECCB08B98BB504DB191D6834D077DF, but I get warning "The PI approval key is invalid."  I'm able to select "confirm", but am then brought to the admin tools page with the same warning at the top.

Can this be ignored?  I'm not sure if she was approved or not, she doesn't have a project yet - could this be why?

**Comment by Hussell** [comment]
She has not been approved, and there's no entry for her in the PI approval key table. I'll look into this further after the call.

**Comment by Hussell** [comment]
Everything seems to be working as expected on sandbox. I'm not sure why the registration key isn't in the table. Catherine may have to manually change her status to PI, I'm not sure.

**Comment by Hussell** [comment]
Have you had other user registrations where everything went as expected? (Key was valid, and clicking "Confirm" caused a success message to display?) Or are all registrations happening as you describe above?

**Comment by zcrysler** [comment]
I haven't had a user register as a PI for a while now, I think the last time they did was when I posted this issue

**Comment by Hussell** [comment]
Ok, I think I've got it. A change was requested for the procedure prMoveUser, and Catherine made the change in the live database. I requested that it be made in the sandbox, since that was where the error the change was supposed to fix had occurred, and I failed to remind Catherine to revert the change in the live database. (We're supposed to test all changes to the database in the sandbox, so things like this won't happen.) As a result, in the live database user registration keys are being deleted whenever a user profile is updated. So if a user saves any change whatsoever to their profile, all registration keys associated with the user get deleted. Since editing her profile is the first thing a user is likely to do after registering, unless Zoe instantly receives and responds to a PI approval request, Zoe finds that the registration key in the PI approval request link is nonexistent and therefore invalid.

Catherine: please change prMoveUser back to its previous form in the live database. I'll keep working in the sandbox to figure out what needs to be updated to make everything work as expected.

This might be related to #208.

**Comment by cjardine-bsc** [comment]
I've commented out this line from prMoveUser in live. 

 --DELETE FROM user_registration_keys WHERE [user_id] = @Id;

Right now there is no FK between user_registration_keys and user_id, so this shouldn't interfere with the rest of the procedure. There was also no backup table or trigger for user_registration_keys (i've made those now). To fix the issue, we should either leave this line out of prMoveUser (the risk being that you might have orphaned records in this table) or change the update profile process to re-insert into this table. 

While we do endeavor to test everything in sandbox first, sometimes a change is needed to fix something in live immediately, or it comes time to sync the two DBs before a beta launch. We all understand the work flow and endeavor to be careful.

**Comment by Hussell** [comment]
I've traced through the code, and calling MotusUser.update() does the following:
prDisableCnUser -- disables constraints on everything related to users, for everyone
prMoveMotusUser -- despite the name, deletes a Motus User
prInsertUser -- re-inserts into user_id, using the original ID but possibly changing name, email, etc.
prInsertUserStatus -- re-inserts into user_status
prEnableCnUser -- re-enables constraints on everything related to users, for everyone
prInsertUserProperties -- re-inserts into user_properties
prEnableCnUser -- re-enables constraints again (unnecessarily)

Therefore, prMoveMotusUser should only delete rows from user_id, user_status, and user_properties. It should not delete rows from user_registration_keys, user_roles, user_pword_reset, or projects_users. This is true for both the live database and the sandbox database.

I strongly suspect this is the cause of #208.

Deleting a Motus User should NOT be done by calling prMoveMotusUser. There should be a different procedure for that, prDeleteMotusUser.

**Comment by cjardine-bsc** [comment]
Yes I agree. As Denis mentioned in #208:

"One thing to check for is that calling the update method on MotusUser should run the prMoveUser proc, which deletes a number of records associated with a user in related tables, including project_users. 

The expectation is that those will be reinserted from the MotusUser bean. If they are not, then every user that updates its profile will have lost their project info. Those can be recovered from backup tables if necessary."

So the solution should be to make sure the MotusUser bean is re-inserting those properly. 

In the mean time I've commented out project_users from that proc in live, until that can be corrected in Sandbox.

**Comment by Hussell** [comment]
"So the solution should be to make sure the MotusUser bean is re-inserting those properly."

No, the MotusUser bean doesn't store any of those other things. It should only delete the things it is able to re-insert, namely user_id, user_status, and user_properties. **Everything else** should be left alone. In sandbox too. Technically, the user bean should use an SQL update statement, not disable constraints, delete, insert, re-enable-constraints. But the code for that is buried in bsc-base where it can't be easily changed, partly because it's being used in many other BSC projects.

**Comment by cjardine-bsc** [comment]
Ahh I was unaware that you were disabling constraints. In your March 28th email you said the proc was silently failing due to the constraint to project_users and Denis asked me to modify the proc to include projects_users. 

I suspect you're trying to call this for both Updates and Deletes, which is what prMoveUser should be used for. If I remove project_users from the proc the error from March will come back, where you wont be able to re-enable constraints after deleting a user because of orphaned records in projects_users. I see why you're requesting a new proc specifically for deleting users, however Denis' instructions differ from what you're asking for. I believe his expectation was that the re-insert for projecs_users be handled by the bean. I'm not sure how complicated/possible it is for the user bean to be altered to cover projects_users, but we should check with the boss man before we alter the plan.

**Comment by cjardine-bsc** [comment]
As noted, I have already commented out the offending issue in live (see my first post from this morning). 

As discussed, we already know the cause and issue. The next step was to confirm with Denis that he is okay with us deviating from his expectation, before implementing a separate delete statement. No one is assigning blame anywhere, it's just a matter of me covering my bases and making sure everyone is on the same page before implementing another change. 

Now that he's given that the go ahead we can implement your request for a separate delete proc for use wherever it is that you're deleting users (where is that exactly? It's fine to delete fake users, but how are we identifying them and who is implementing the delete? Just curious. )   

You mention above that you've gone back to a simple delete statement. That's fine, but I'll need to add a few more triggers in the DB to make sure we're keeping backups of all the associated user tables, there are some that currently don't have backup tables. Probably better to do this with a PROC so that we can alter it if we end up with any additional user_id dependencies in the database.  I'll create that for you.  (at the moment I'm experiencing some connection issues with the server, so it might take a moment before it's available).

**Comment by Hussell** [comment]
As noted, the offending delete statements have NOT all been commented out. The only lines which should be in that procedure are the ones which delete from user_properties, user_status, and user_id.

**Comment by Hussell** [comment]
Also, the procedure in sandbox should be identical to the procedure in the live database.

**Comment by cjardine-bsc** [comment]
Jeremy, I've already told you that I know all this but I currently can't connect to the server. It will be done when I have access again. Please leave this be for a moment. Italics and all caps aren't necessary here. 

I executed the change to comment out the offending statements already, the first call succeeded and the proc is not deleting from project_users any longer. The second call failed due to a connection issue. I'll re-run it when I again can get back in, in both database.
