### ISSUE TITLE
Lotek Burst Interval Query

### ISSUE THREAD

**Issue by StuMackenzie** [MotusDev/Motus-TO-DO#154]
From Phil (https://github.com/MotusWTS/MotusRBook/issues/17):

Lotek has proposed a new set of burst intervals for tags, with the purpose of minimizing the numbers of ambiguous tags deployed. They want our 'tech people' to test these.

One test is to generate test files with various (random) sets of tags, and run those through the entire data handling process. This would best be done on a separate implementation of the whole Motus server, to avoid conflicts with real tags. Such a test could also help us find issues with the current data processing.

###

From Lotek: (related file here: https://drive.google.com/file/d/10EgX5LR4ldGM4aKWyMyGKLa0LwoXVFsr/view?usp=sharing)

Please find attached a list of proposed BIs utilizing a 0.010s timing increment.
We would like to introduces a list of  214 BIs. Adopting this list would not limit us from the full set of prime BIs n= 504 in the future. We feel taking a phased approach is more suitable. 
The attached also outlines the conflicts with the existing primes on tabs 2 (n = 214 proposed) and 3 (n = 504 BIs).

Can you have your tech people analyze and assess the proposed list.

Please keep in mind some time is still required in terms of selling and manufacturing tags with the proposed BIs.

**Comment by jbrzusto** [comment]
Questions:
- are these proposed burst intervals real or nominal?  We need to know the rate of the underlying
clock so that we can make this assessment correctly.

- once the possible BI have been selected, what is the **BI assignment rule** goint to be?
  A. all tags in an order get exactly the same BI
  **or**
  B. all tags in an order get BI chosen from a set within say 1s of a user's nominal choice of BI?
  **or**
  C. something else

There are three things we want to accomplish with this BI selection:

   1. extend the size of the codeset from 521 to potentially many more distinguishable tags

   2. avoid **ambiguous detections**, where two or more correct detections of a single-burst ID cannot be unambiguously assigned to a known physical tag because the observed interval between
them can be interpreted in more than one way (e.g. as `n * BI_1` or `m * BI_2`, within receiver tolerance parameters).  This problem is compounded because we want to allow for some missing
bursts in a run from a tag, due to e.g. antenna switching or atmospheric effects at low signal strength.

   3. avoid **aliasing**, where two tags bursting in temporary synchrony appear to instead be a third tag; 
     this has been a regular occurence at sites with many tags (colonies, e.g.)  Regardless of choice
     of BIs, accomplishing this goal will be difficult if BI assignment rule A is used.
