### ISSUE TITLE
tagme Error "not found"

### ISSUE THREAD

**Issue by zcrysler** [MotusDev/Motus-TO-DO#168]
Downloading data for project 47 (huge project), I got an error that what I assume was a batchID was not found.  I resumed download but I'm not sure that the batch that wasn't found was included when download resumed.  Or maybe the download was just interrupted while work was being done on the server?

batchID    76806 (#    71 of    911): got     44 GPS fixes                     
Error: Not Found (#    72 of    911): got      1 runs starting at               0
> tagme(47, update = TRUE, dir = "/Users/zoecrysler/Downloads")
Checking for new data in project 47
Project    47:  got   840 batch records

batchID    76812 (#     1 of    840): got      1 runs starting at               0

**Comment by zcrysler** [comment]
It ran for a while and then I got "Error: Bad Gateway", was able to resume though

batchID    99285 (#   305 of    840): got      4 runs starting at               0
Error: Bad Gateway#   305 of    840): got      8 hits starting at               0
> tagme(47, update = TRUE, dir = "/Users/zoecrysler/Downloads")
Checking for new data in project 47
Project    47:  got   536 batch records

batchID    99285 (#     1 of    536): got      4 runs starting at               0
batchID    99285 (#     1 of    536): got    321 GPS fixes                     
b

**Comment by denislepage** [comment]
Could be when I restarted the server earlier tonight to apply some patches.

Failed batches should normally resume correctly. All data are being stored in temp tables, then appended to the main ones. If anything stops, that shouldn’t cause any problems when resuming.

Occasional connection failures will happen otherwise. If they become too frequent, we may need to look into this more.

If the batch is missing, you can let me know

**Comment by zcrysler** [comment]
The batch was there so closing issue
