### ISSUE TITLE
download receiver data by project

### ISSUE THREAD

**Issue by zcrysler** [MotusDev/Motus-TO-DO#173]
A future wish list item for the motus package would be the ability to download receiver data on a project basis rather than running tagme on each receiver individually

**Comment by denislepage** [comment]
A lower priority for now, but I can see 2 ways to deal with this without making significant changes to the existing API. I’m not sure if the issue that the data goes in separate database and would be better in a single large (huge) database, or whether it is only the process of pulling in the data that needs to be improved.


1)      in the latter case, we could write a function that simply loops through each receiver and calls tagme on it. That could require a new API entry point that provides a list of receivers for a given project. The loop is then easy to write, each step calling the existing tagme function.

2)      If the issue is mainly that the data gets separated, we could add an option parameter to the tagme function that determines where the data gets stored, I think, other than the default based on project-xxx.motus or receiverno.motus. I’m not sure there are benefits to that, though, and could have some ramifications elsewhere in the R package. There may be better ways of combining data from various receivers.

I would rather not have to modify the existing calls to allow a single tagme call. The first one especially would be very simple to do and amount to the same thing. The second one could be more complicated.

**Comment by zcrysler** [comment]
I was thinking along the lines of option 1 to allow for easier download. Once users have the files they can write their own loops to read the data in, or pick and choose receivers.

**Comment by denislepage** [comment]
OK, the only piece missing at the moment is an API entry point that gives the list of receivers for a given project, and a few changes to the R packages.

I’ll ask Paul to look at whether that’s an easy thing to add, but I would expect so. I’ll have to create a new view for that under the R framework.

**Comment by denislepage** [comment]
Actually, never mind. The existing metadata functions would already give us everything we need, I think. I'll look a bit into this.

**Comment by denislepage** [comment]
This would do what you suggest. We can add as an example in the book.

```
library(motus)
proj.num = 9
# get a copy of the metadata only
sql.motus <- tagme(proj.num, new = TRUE, update = FALSE)  
metadata(sql.motus, proj.num)
tbl.recvDeps <- tbl(sql.motus, "recvDeps")
df.serno = tbl.recvDeps %>% 
	filter(projectID == proj.num) %>% 
	select(serno) %>% 
	distinct() %>% 
	collect() %>% as.data.frame()

# loop through each receiver (may take a while!)
for (row in 1:nrow(df.serno)) {
	tagme(df.serno[row, "serno"], dir="data", new=TRUE, update=TRUE)
}
```

**Comment by denislepage** [comment]
We can also make into a function, but I am not sure it is necessary. Maybe.

**Comment by jbrzusto** [comment]
If the databases have already been created (empty or not) in `dir`, they all get updated
by just calling `tagme() ` with no arguments:
```R
    if (missing(projRecv) && ! new) {
        ## special case: update all existing databases in \code{dir}
        return(lapply(dir(dir, pattern="\\.motus$"),
                      function(f) {
                          tagme(projRecv=sub("\\.motus$", "", f), update=TRUE, dir=dir, countOnly=countOnly, forceMeta=forceMeta)
                      }))
    }
```
