### ISSUE TITLE
Track Search Notice

### ISSUE THREAD

**Issue by StuMackenzie** [MotusDev/Motus-TO-DO#174]
Until we have a mechanism to flag and remove all 'suspect' public detections, can we please put this statement front and centre, and bold, on all track search pages and not just the maps - https://motus.org/data/tracksSearch

"Attention: These public animations have been created using broad filters based on theoretical flight speeds, logical geographic/time sequences, and at least 3 consecutive tag bursts at a single station. Individual tracks have not been inspected for accuracy. Please report any questionable tracks to motus@birdscanada.org to help us refine the filters."

**Comment by zcrysler** [comment]
And if it's not overkill, places like this:
https://motus.org/data/receiverDeploymentDetections?id=2729
https://motus.org/data/tagDeploymentDetections?id=675
https://motus.org/data/timeline?tagDeploymentId=675
https://motus.org/data/track?tagDeploymentId=675

I just got an email from a project user questioning impossible detections of their tags showing up on Koffler which is a known noisy site

**Comment by denislepage** [comment]
The sooner we can start identifying bad data, the better, even if we only deal with the worst offenders for now, such as the half dozen noisiest stations, and even if that means flagging entire batches out for now, until we can figure out a more refine way to deal with that.

**Comment by Hussell** [comment]
Added to these pages:
https://beta.motus.org/data/tracksSearch
https://beta.motus.org/data/tracksSelect?e=2013-01-01&l=2018-12-31&s=12200
https://beta.motus.org/data/track?tagDeploymentId=675

The text as given doesn't make sense for the tables and plots of detections. Perhaps:
"Attention: some receiver stations are known to be "noisy", and generate lots of spurious false-positive detections. We've made some effort to filter these out, but we know there are some remaining. If you can identify some detection or detections as likely to be false positive (e.g. because you know the species to which you attached the tag wouldn't be there at that time), please report them to motus@birdscanada.org to help us refine our filters.
