### ISSUE TITLE
data validation failing

### ISSUE THREAD

**Issue by zcrysler** [MotusDev/Motus-TO-DO#184]
Clicking "rerun data validation" here: https://motus.org/data/issues?id=1

gives me this: The last attempt to validate your data failed with the error message: org.bsc.exceptions.DBException com.microsoft.sqlserver.jdbc.SQLServerException: Conversion failed when converting the varchar value 'date' to data type int. SQL: "prDataValidation_pr @proj = 1" at org.bsc.SQLPreparedStmt.executeUpdate(SQLPreparedStmt.java:243) at org.bsc.motus.process.Job.run(Job.java:314)

**Comment by denislepage** [comment]
Tag ID 27847 has a dateBin = “dateBin=2018”. I don’t know how that happened.

I try changed it to “2018-1”, but there is a conflict with another registered tag with the same project and mfg, but different period (tag #27790).

I renamed the mfg to 2.1 for the tag with incorrect dateBin. These may be related to our attempts to register new tag models. These 2 tags would be ambiguous now, but neither is deployed, so one or both may need to be deleted?

We should nonetheless do some sanity check on the tag registration.

DateBin string should match this (works until 2099).

dateBin.matches("^20[0-9]{2}\\-[1-4]$")

We could also do it based on some modification on the current date instead, but in such cases we might as well calculate the dateBin ourselves and/or validate that it matches the one provided. We’d need to check first if there are situations where the dateBin doesn’t match the current date, so that could be too strict. I’d start with a more general regex check for now.

**Comment by denislepage** [comment]
Please add validation of dateBin during registration as 

`dateBin.matches("^20[0-9]{2}\\-[1-4]$")`

**Comment by jbrzusto** [comment]
That was my fault - I was trying to manually test the httr package and sent a bad query.

**Comment by denislepage** [comment]
is that a tag that we can delete? There are currently 2 tags with different periods with these properties. Just tests?

**Comment by jbrzusto** [comment]
The periods are coming from recordings that Zoe uploaded, so if there are two different ones,
I assume she was trying to register two different tags.

**Comment by zcrysler** [comment]
I'm not sure if there's anything planned for these tags - Stu can you confirm?

Two tags with mfgID 2, BIs are 19.9 and 4.7 - they're listed as NTQB-6-2, not sure this is correct for both

**Comment by StuMackenzie** [comment]
Pretty sure these were the same registration of the same test tag - just tests.

**Comment by denislepage** [comment]
I will delete then. Are there any valid tags under project 1, in any case?

**Comment by zcrysler** [comment]
I don't think so, it's nice to have at least one in there for testing so I don't need to use someone else's project

**Comment by denislepage** [comment]
deleted
