### ISSUE TITLE
Track tool errors

### ISSUE THREAD

**Issue by zcrysler** [MotusDev/Motus-TO-DO#185]
The track page says:

Attention: These public animations have been created using broad filters based on theoretical flight speeds, logical geographic/time sequences, and at least 3 consecutive tag bursts at a single station. Individual tracks have not been inspected for accuracy. Please report any questionable tracks to motus@birdscanada.org to help us refine the filters.

How would you like me to deal with users reporting these questionable tracks?  I've received an email from project "Indiana Bats 2015" saying the detections in Canada (and I'm guessing Alaska too) are incorrect.  The Ontario stations are Formosa and Old Cut are known noisy sites.

**Comment by StuMackenzie** [comment]
Thanks Zoe, for now I would just respond and say thank you for your attention.... and something like this” The errors you note are likely due to radio interference at two known ‘noisy’ sites. We’re working on ways to identify and remove detections such as this from the public database. For now these detections will remain in the primary database so that users can make the decisions about what spurious detections are possible or not.”

As for logging them - we can put them in the error log for now and we may discover some things that we don’t know about, or at least we’ll have a list to refer back to once we’ve implemented some changes to make sure the big problems have been solved. Snowy Plovers are another very problematic dataset.
