### ISSUE TITLE
Tag deployment lat/longs need some validation

### ISSUE THREAD

**Issue by pmorrill** [MotusDev/Motus-TO-DO#192]
Tag deployments entered via the website (possibly using the bulk upload tool) are not being sanity checked. We need to verify that ineligible values (2 degrees north of the north pole, for example) are not accepted. We should also present geo-located information in the deployment tools, as feedback (we do this for recv deployments already).

**Comment by Hussell** [comment]
Common mistakes I've spotted:
- swapping the latitude and longitude
- forgetting a negative sign on either value
- transposing two digits somewhere

There are probably other types of mistakes I haven't spotted.

A map is available to help users spot mistakes:
https://beta.motus.org/data/tag/deployment/map?projectId=47

**Comment by cjardine-bsc** [comment]
The bulk tool does check lat/long for various things, but it wont catch the errors listed by Jeremy above, there isn't a way to say for sure that those errors are not valid locations without input from the user. 

What we did previously, was to create a new field called region in the bulk upload table. I update this in the validation proc so that it lists the state/province and country of the deployment. So the user can validate that the location, at least at that scale, matches their expectations. I think we still need to alter the web page so these values are displayed back to the user for them to look over before completing the upload.

**Comment by pmorrill** [comment]
Welcome back Catherine! I hope to be on Motus later today and tomorrow. I will look at the interface and see how this works (remind myself, more like)

**Comment by cjardine-bsc** [comment]
Same as #96
