### ISSUE TITLE
Can't add user to project

### ISSUE THREAD

**Issue by zcrysler** [MotusDev/Motus-TO-DO#196]
Trying to add user 546 to project 1, but his name doesn't come up when I search by first/last name or email.  In the user_id table in the database there's no password for this user - is that why?  There are a number of users with no passwords, how is that possible? 

https://motus.org/data/project/users?projectID=1#addNewUser

**Comment by Hussell** [comment]
Due to an early design decision (before I was hired), information about landowners is stored in the user_id table alongside information about user accounts. Landowners don't have a login name or password.

So, technically, there is no user 546 and there never will be, because landowner 546 used up that ID. You'll have to create a user account for him/her/them, and then add that to the project.

**Comment by zcrysler** [comment]
Ok thanks!
