### ISSUE TITLE
receiver deployment table and timeline don't match in detections

### ISSUE THREAD

**Issue by zcrysler** [MotusDev/Motus-TO-DO#198]
https://motus.org/data/receiverDeploymentDetections?id=2905 and https://motus.org/data/timeline?receiverDeploymentId=2905 have different detections, for example the timeline doesn't include many of the detections in 2015 (eg. tag deploymentID 39, 636, 671 etc.) but the table does, although all the 2015 detections were on 2015-12-07 and likely false - but these two displays should be using the same filters and have the same results

**Comment by denislepage** [comment]
I looked into this a bit. There seems to be a condition on the query used for the timeline that say n_hits > 3.

I think it should say n_hits >= 3?

As far as I can tell, the filtering based on number of runs and freqSD is already being applied when creating the records in taghits_daily and taghits_run, so the filtering on n_hits may not be necessary in the web outputs.

This condition is found in prTaghitsSummaries... procs: freqSD < 0.1 and d.[len] > 2

That probably explains the main difference between the timelines and the tables.

**Comment by Hussell** [comment]
vwData_taghits_daily and vwBase_taghits_daily currently have no filters. So the tables are reporting detections for n_hits >= 1 at the moment. I'm not sure where to add the filters. The easiest would be in the views.

**Comment by Hussell** [comment]
Well, they do. Run length = 1 too.

**Comment by denislepage** [comment]
We went through this before. N_hits is not the same as run length.

In the summaries, n hits is the number of hits that have passed the filters. Nhits = 1 can happen if you have run length of 3, with 2 hits where freqSD > 0.1, for instance.

FreqSD on individual hits is probably not a good way to filter individual records. I think filtering should happen on entire runs.

In any case, those decisions should already be applied by the time the data gets to the summary tables.

**Comment by Hussell** [comment]
Ok, so John's documentation doesn't apply to filtering by n_hits, because that's number of runs, not number of bursts within one run. But the tables are not being filtered by n_hits, and the timelines and tracks are. So there's still the question of how we make those consistent. Removing the filter on n_hits from the tracks isn't an option, because too much bad data gets displayed (this is the issue Stu had when we were about to release the tracks maps, which was "solved" by filtering out n_hits <= 3).

Some options:
 - add filters to all the SQL queries used to generate the tables (~16 queries, I think)
 - add filters to the views of the summary tables (2 views, vwBase_taghits_runs and vwBase_taghits_daily, or maybe the vwData versions only)
 - filter on n_hits in the procedure that generates the summary tables (prTaghitsSummariesBatchID)
 - don't change anything (let the tables list more detections than the timelines and track maps)
 - remove the n_hits filters from the timelines (let the tables and timelines show more detections than the track maps)

**Comment by cjardine-bsc** [comment]
test comment

**Comment by zcrysler** [comment]
Not sure where this stands in determining the best way to filter, but it should at least match between the table and timeline view since users can easily toggle between the two and get confused: https://motus.org/data/receiverDeploymentDetections?id=2905 and https://motus.org/data/timeline?receiverDeploymentId=2905

**Comment by Hussell** [comment]
I've added filters to the queries so that everything matches.

**Comment by Hussell** [comment]
Discovered another layer to this: detections in the table are from the daily summary, which records the total number of hits during the day, the sum from all runs that day. When all runs have length 1, 2, or otherwise short enough to be filtered out from the timelines, the tables will show a day with detections not on the timelines.

Catherine has added a column max_length to the daily summary, so days which are composed entirely of short runs can now be filtered out. All queries have been modified to do this on sandbox.

**Comment by Hussell** [comment]
Seems this wasn't thorough enough. The new column max_length was added to vwBase_taghits_daily and vwData_taghits_daily, but not to the underlying table. So, for example, tag deployment ID 5224 on receiver deployment ID 645 has no runs of length > 3 in sg_taghits_runs, so it doesn't show on the timeline, but in sg_taghits_daily that tag deployment is listed as having n_hits = 4 on 2015-01-09.

**Comment by Hussell** [comment]
Ok, the example above is now good (no runs of length <= 3 are showing in the daily summary), but now there are runs with length > 3 which aren't in the daily summary. E.g. tag deployment ID 15213 on receiver deployment ID 2905.

**Comment by Hussell** [comment]
On both sandbox and beta/live, comparing sg_taghits_runs and sg_taghits_daily for non-test deployments of tag IDs 25926 through 25932, I see 15+ runs with plenty of hits, but nothing in sg_taghits_daily. This might be the problem causing complaints of missing detections in #449.

**Comment by cjardine-bsc** [comment]
ah, all those tags are part of Ambiguities. 

Ambigs are removed from the taghits daily table, but expanded and included in the sg_taghits_runs

**Comment by leberrigan** [comment]
Not sure if you are all aware of this already, but this is still an issue on Motus Live, but apparently not Sandbox. We were just notified by people from Columbus Zoo:
Device 1019, deployment 4462
Timeline: https://motus.org/data/receiver/deployment/detections/timeline?year=2019&id=4462
Table: https://motus.org/data/receiverDeploymentDetections?id=4462

**Comment by Hussell** [comment]
The extra detections appearing on the timeline are due to ambiguous tag IDs, so those are the one which should be ignored.

**Comment by Hussell** [comment]
From project 230 via Stu:
In the beta/live database, run ID 60440524 is in sg_taghits_runs but not sg_taghits_daily. I've examined prTaghitsSummariesBatchID and can find no reason why this should be. Am I looking at the wrong code, making a mistake, or did something fail to execute?

**Comment by denislepage** [comment]
I think it’s the latter option (failed to execute)

The view used in the proc for daily isn’t the issue, as it is returning a record for daily.

Re-running the proc for batch 415626 correctly adds the missing record in daily.

Given how much errors were happening in the past few weeks, this is hardly surprising. At the moment, we don’t have a way to replay failed jobs, and there is no easy way to implement this without risking creating a mess.

Funny though that the runs records were present, given that this happens after the daily summary in the proc. I can’t think of a way in which this can happen, unless they underlying data conditions have changed since it was previously run. I would have expected those conditions however to filter out daily and runs the same way.
