### ISSUE TITLE
GPS Fixes Far from Deployment Location

### ISSUE THREAD

**Issue by zcrysler** [MotusDev/Motus-TO-DO#199]
I'm wondering if we should expand the distance that flags this issue, there are 1897 of these issues in project 1, I looked at a few and in one case the difference in coordinates is 122m

Is it also possible to to make the .csv file that's downloaded have ts as a date rather than number?  It would make it much faster to find the date and receiver in question to make corrections

**Comment by Hussell** [comment]
Would it make sense to simply report the % of days during each receiver deployment which had at least 3 GPS fixes more than 100m away from the deployment location? That way there would be one issue per receiver deployment instead of one per day.

As for the .csv, that's intended to be imported into a database (or R, I guess) so a user can query to find the receiver and calculate the dates and distances themselves. The link to the .csv is a placeholder until we can generate a map of the GPS fixes for any receiver deployment (it's on the list #172).

**Comment by zcrysler** [comment]
Yes I think reporting the % of days would be a good solution because at least for the example I gave, there are a bunch of warnings for the same deployment, and updating the recvDepLat/Lon would solve all of them in one go.  It would certainly make it less overwhelming to dig into and start fixing.

**Comment by tcrewe** [comment]
On this note,

I'm trying to analyze data from Old Cut, and the GPS positions naturally
bounce around some mean lat/lon because of the error in the GPS location
estimates. This can cause problems in the analysis, because it assumes the
tower is in different locations. Rounding the lat/lon doesn't help, and
ends up placing the Old Cut tower closer to the main road.

So, my question is, for a given deployment where GPS positions tend to be
within 100m of a deployment, can the underlying database/api (whatever
happens behind the scenes) provide the user a mean lat and lon, and perhaps
an error in lat/lon (stdDev?), instead of the user having to replace all
lat and lons with some mean value. It's just a little misleading, because
the tower isn't moving.

Thanks,

Tara

**Comment by cjardine-bsc** [comment]
I presumed that users would use the deployment lat/lon in these cases, but Jeremy mentioned that this wasn't adequate/accurate? 

My first thought is that a mean might be better done on the user end in R. The reason being that when the user pulls new gps data from the receiver we would need to updated the mean lat and lon and stdDev (presumably stored in the deployment table) but the deployment table data only gets updated if you force a refresh of the  metadata. It might be a bit confusing for users in the long term?

This isn't something we'd want to dynamically on download, but I could write a query that would calculate the mean GPS fix for each deployment and store it in the database. We could run that periodically. 

Perhaps the best would be to try and write a query in SQLite that calculates this. The user can then decide if they want to use these values and they can be generated dynamically when new data is pulled. Without having to remember to run a metadata update call. SQLite has some restrictions in what it can do, but I'll look and see whether that's an option.  I suspect this will be a weighty calculation, and might be better handled in R. I'll have to dig in a little bit.

**Comment by tcrewe** [comment]
It's of course doable in R, it just adds another layer of complexity to an already complex task of downloading data (for people who aren't R savvy). It's also a little confusing because it makes it seem like the tower is moving when it isn't. Seems like this is something that could ideally be taken care of behind the scenes, if possible.

We do typically use the GPS coordinates. In the book, we suggest using those, because the median should be the most accurate, more so than the deployment coordinate (in theory), and then infill with deployment coordinates when the GPS ones aren't available.  If it's going to be super complicated on the back-end, we can add it to the R code in the book and explain why we are doing it. Maybe it's more transparent what is happening and why that way. I can obviously argue both sides....
