### ISSUE TITLE
Dealing with "AHO" antennas in raw data

### ISSUE THREAD

**Issue by zcrysler** [MotusDev/Motus-TO-DO#20]
Need to figure out how these are dealt with in the raw data to know if users need to account for that when creating deployment files online.

**Comment by jbrzusto** [comment]
Perhaps someone can verify what 'AH0' means?  I took it to mean the antenna was directly attached
to a receiver that only has one antenna port, rather than attached to a 6-way antenna switcher which
is in turn attached to the receiver (in which case, the antennas are labelled 1, 2, ... 6).  

I'm fine with treating 'AH0' as antenna 1 if that's appropriate, but someone more familiar with Lotek
receivers and their deployments needs to confirm that's okay.

**Comment by zcrysler** [comment]
This is Pam's response, who originally brought it up:

You are correct that AH0 is when the receiver only has one antenna port rather than the 6-way switchbox. The NOMS site had it labeled as port 1 in the Motus database and none of the NOMS data were in the output dataset (assuming I merged all of the parts together correctly, still lots of confusion around that). I relabeled the port to 0, redownloaded and reran the R  scripts to merge and the NOMS data were in the output. So I think the ports need to be in Motus as 0 but wanted to clarify?
