### ISSUE TITLE
receivers timeline very slow load

### ISSUE THREAD

**Issue by zcrysler** [MotusDev/Motus-TO-DO#200]
When trying to fix receiver issues on the error page, clicking "view" for the error "Detections Outside of Receiver Deployment" takes a very long time, or sometimes just doesn't load at all, to the point where it makes fixing these issues unmanageable.  Is there a way to get this page to load faster?  It could be the slow internet here, but other pages aren't having the same lag - maybe someone else could see how long it takes to load

**Comment by Hussell** [comment]
Tested it at BSC HQ, and it loads quickly (< 1s). If you're on Firefox, you can hit Ctrl-Shift-K while you're looking at the list of issues (an empty panel or window will open), then click on the link to the timeline, and a list of everything URL that's downloaded will be displayed, with the time it took displayed on the right. Would you do that, and ask Catherine to do the same, and report those times? (If you're using a different browser, let me know what it is, instead.) I have some guesses about how much difference the distance from here to there should make, but little evidence, so that would be useful to me even if it turns out not to help with this problem.

**Comment by zcrysler** [comment]
Catherine can you test this out?  I'm not back in the BC office for a few weeks now

**Comment by cjardine-bsc** [comment]
returning quickly for me here at the office too. 

*shrug*

**Comment by zcrysler** [comment]
Maybe I just have an especially slow EC computer, although other pages were ok, I'll stick to error fixing at home
