### ISSUE TITLE
missing antenna type bug

### ISSUE THREAD

**Issue by zcrysler** [MotusDev/Motus-TO-DO#201]
I think data issues are being generated for missing antenna types that are already listed as "custom".  Eg. https://motus.org/data/issues?id=1#v_sensor_antenna_type, there's a deployment listed as missing the antenna type, clicking the edit button brings you to a deployment that has all antennas listed as "custom" : https://motus.org/data/receiver/deployment/edit?projectID=1&id=684

**Comment by Hussell** [comment]
Checking the database, the antenna types are null, so the issues are correct. The problem appears to be on the edit page, where a null value results in no option being selected by default, so the browser just settles on showing the first option in the list, which happens to be 'custom'. (The options are shown in the order they appear in the database instead of alphabetical order.)

I've added a bit of code to this page to cause 'none' to show up by default when the value in the database is null.
