### ISSUE TITLE
Lots of empty files in archive

### ISSUE THREAD

**Issue by zcrysler** [MotusDev/Motus-TO-DO#204]
https://sgdata.motus.org/status?jobID=171072 when called directly with that link you can see the log, but when you select that job from the status page you're unable to get to this specific jobID, tried it as multiple users on different computers with no luck.  I'm not sure if that's related to the problem.  It appears all the files are empty - so is this likely a receiver issue?

Despite this being uploaded over a week ago it still says there's a pending job:

Log for 171072

Job 171072 with 1 pending subjobs entered processing queue #3

User wants to know if this is a problem receiver, an upload problem, or a processing issue

**Comment by Hussell** [comment]
I see Job ID 171072 on the list on the status page. Trying to click the status, on the other hand, results in a delay of 20+ seconds while the thing loads, because there's a list of 134,918 empty files in the log. The delay may be worse if you're looking at this through a slow network connection.

The bit about a pending subjob is part of the normal log message for every top-level job, which is printed out just before its first subjob is run. The first subjob usually creates another, or several others which in turn create more. It looks like all the subjobs for 171072 ran without errors and the queue was empty afterwards.

The upload appears to have completed normally (though I'm not yet 100% certain of this), so I'd guess the problem is in the file which was uploaded.

**Comment by Hussell** [comment]
I found the archived uploaded file on the server. It's 35,220,396 bytes (35MB), but when I unzip it all I get is a directory structure with those 134,918 empty files.

The user should:
 - check that the file sizes match (if not, then it's an upload problem and they should re-try)
 - unzip the file on their end and look at the file sizes (if they are zero, then it's probably a receiver issue; if they are not zero, then there may be a compatibility issue with the zip and unzip programs... ask them to report what versions they're using if this happens)

Note: sorry for the slow investigation; I'm just starting to learn how to investigate issues on sgdata.motus.org. I should get faster as I gain more experience at this.
