### ISSUE TITLE
gps error fixes not updating

### ISSUE THREAD

**Issue by zcrysler** [MotusDev/Motus-TO-DO#210]
There's an error for deployment 1503 in project 1 for gps fixes far away from the deployment.  This happened because testing data from CompuData is in the system and we had a deployment that mistakenly covered that testing period.  I changed the incorrect deployment to start after the compuData testing, and I created a test deployment for when the receiver was at CompuData.  Despite rerunning the validation, this is still showing up as an error.  

When I click the "view" button for that error I get brought here: https://motus.org/data/receiverMap?receiverDeploymentId=1503, it shows all the gps detections around CompuData occurred between 2014-03-11 and 2014-03-13 which aligns with the new deployment 4611.  When I click on the "edit" button it brings me to deployment ID 1503 https://motus.org/data/receiver/deployment/edit?projectID=1&id=1503, which now starts AFTER these detections on 2014-03-14.  The way I understand it, this issue should have been resolved by these changes.

The map you see when you click "view" is very very helpful!

**Comment by denislepage** [comment]
The proc that updates the deployment link was stalled today, precisely on that deployment. There were a few more pending updates on hold as well because of this.

I have now modified the proc and it seems to run faster. I also re-ran the queue. The modifications should now be applied, if you can confirm.
