### ISSUE TITLE
receiver with no detections - issue

### ISSUE THREAD

**Issue by zcrysler** [MotusDev/Motus-TO-DO#213]
Project 1 - receiver Lotek-D000438 is flagged as a warning that it has no data, but it does.  There are no detections, but there is an hourly plot for that receiver, which was placed on project 0 and might be the reason: https://sgdata.motus.org/download/0/Lotek-D000438-2017_no_project_(unregistered%20deployment)_hourly_tags.png

I also tried verifying the file for this receiver that I uploaded and got the warning "This file has already been uploaded by Zoe Crysler (2017-11-23 17:47:05; jobID: 130642)", so there's definitely data for this receiver, just no detections.

**Comment by Hussell** [comment]
Do you mean this? https://motus.org/data/issues?id=1#v_sensor_no_detections

This warning is specifically about the lack of detections. I think the description and instructions are clear.

**Comment by zcrysler** [comment]
It says "These receivers do not have any associated detection data.", I read that as not lack of detections, but lack of data.  It also says "If you have not uploaded any data for this receiver there is no need for further action..." and "If you are sure that the receiver serial number is correct and you have submitted raw detection data, please contact us" which is what made me think something was wrong, because I had uploaded data for that receiver.

If it's only referring to detections, and not data in general, the wording should be changed to something like 

These receivers do not have any associated detections.

If you have not uploaded any data for this receiver there is no need for further action. If you have uploaded data from the receiver, it is possible the serial number registered to your project does not match the serial number in raw detection files, please ensure the serial number listed here is correct. It is also possible there have been no detections in your raw data.  If you are sure that the receiver serial number is correct and you are expecting there to be detections, please contact us at motus@birdscanada.org

**Comment by denislepage** [comment]
As you say, there is a difference between no detections and no data.

If there are at least some batches for these receivers with zero hits, should there still be a warning at all?

I’m not sure what the error is looking for, but comparing against the batches table for any occurrence of a receiver should be enough, regardless of hits? In any case, even if we want a warning for zero detections, that should still be done on the basis of batches (where nhits > 0) as it should be more efficient.

The alternative option could be to check against pulse_counts. Empty batches with no pulse at all are probably problematic.

**Comment by Hussell** [comment]
I just looked up what prDataValidation_pr is checking to generate these warnings, and it's completely different from what I expected. I'll try drafting a better description and instructions.

Lotek-D000438 isn't registered (that is, we have metadata about it, but no entry in sensors_hash_keys). The uploads failed, with an error, but still produced an hourly plot.

**Comment by denislepage** [comment]
Which upload is failing? My impression was that tag finder would register new receivers if they weren't already in Motus. Is this not happening?

**Comment by Hussell** [comment]
I've traced through everything that's happening on sgdata. The registration is failing with an error message of "invalid-receiver-type". The receiver type being sent is "LOTEKSRX800D". The API is calling prInsertSensorsHashKeys, which rejects any receiver type which isn't present in the table lk_receiver_type.

lk_receiver_type currently contains:
LOTEKSRX600
LOTEKSRX800
LOTEKSRXDL
SENSORGNOME
UNKNOWN

Tracing through sgdata again, the receiver types it will attempt to register are:
LOTEKSRX-DL
LOTEKSRX400A
LOTEKSRX600
LOTEKSRX800
LOTEKSRX800D
LOTEKSRX800M/MD
SENSORGNOME

Looking in the sensors_hash_keys table, we haven't had any successful registrations of Lotek receivers since Jan. 2017.

**Comment by Hussell** [comment]
Looking in the logs on sgdata, there have only been two Lotek receivers which have failed due to this bug since Jan. 2017, so this isn't as scary as I had thought.
Lotek-D000427 (3 attempts, 1st on Dec 28th 2017, last on Feb 23rd 2018)
Lotek-D000438 (2 attemps, 1st on Dec 29th 2017, last on Feb 23rd 2018)

**Comment by denislepage** [comment]
Those models should already be supported by the Regex, but as long as they were submitted as LOTEKSRXDL. Can  you see what model type was submitted?

That raises a few questions, though:


1.       How do we know when new models need to be added?

2.       Can we loosen up the validation when registration come through the SG server? What are the consequences of that?

3.       We should probably set some email notifications on a few failed calls (all failed calls?) on our API.

4.       Once we have resolved the reason why this particular model failed to register, how do we complete the failed batches


.

**Comment by denislepage** [comment]
I am just catching on to your note.

So, we need to change LOTEKSRXDL to LOTEKSRX-DL, and add a few more types?

**Comment by Hussell** [comment]
Changing the types in our table to match what sgdata will try to register is the quickest fix, I think. However, I'm wondering why we're keeping track of individual Lotek models and not SensorGnome models. Perhaps we should change both sides so that the only options are LOTEK, SENSORGNOME, and UNKNOWN, and just record the serial number. The tag finder still needs to know about particular models, but those are worked out from the serial number. I'm fairly certain the tag finder doesn't refer to our metadata about the model at all. Doing things this way would future-proof us against more errors like this the next time Lotek introduces a new model and/or serial number format. It would also mean we wouldn't have to introduce a new regular expression for serial number validation every time Lotek creates a new variation.

**Comment by denislepage** [comment]
I don’t disagree, but that would require change in tag finder that I’m not sure we’re yet prepared to make.

Let’s add those models and, if we can’t sort out the proper regex for now, let’s make it loose enough to ensure that they can be registered.

Paul, could we easily set up email notifications when API registration calls fail? Have them sent to support@bsc-eoc.org<mailto:support@bsc-eoc.org> for now, or better yet, to motusProjInfo.getErrorEmail()

**Comment by denislepage** [comment]
I have added the receiver types above to our lookup. I am assuming that LOTEKSRX-DL and LOTEKSRXDL are the same, so I used the same regex, but I left both receiver types in there for now, but that will be confusing for users, so we should resolve this. 

For the other 3 (LOTEKSRX400A, LOTEKSRX800D and LOTEKSRX800M/MD), I have used ^Lotek-.+$ as the regex for now, until we can figure out the proper code.

**Comment by pmorrill** [comment]
Some email tracing should be easy enough.  I'll look at this next week.

**Comment by Hussell** [comment]
The regexes should probably be:
receiver_type | regex
------------- | -----
LOTEKSRX400A | ^Lotek-9\\d{3}A$
LOTEKSRX600 | ^Lotek-6\\d{3}$
LOTEKSRX800 | ^Lotek-([0-2]\\d{2}|3[0-8]\\d|390)$
LOTEKSRX800D | ^Lotek-D\\d{6}$
LOTEKSRX800M/MD | ^Lotek-(39[1-9]|[4-9]\\d{2})$
LOTEKSRX-DL | ^Lotek-8\\d{3}$
LOTEK | ^Lotek-\\w{3,}$

See https://github.com/jbrzusto/motusServer/blob/master/R/getRecvModel.R

Note also that receiver_descr and receiver_descr_fr for LOTEKSRX800D should be "Lotek SRX 800D".

**Comment by denislepage** [comment]
OK, I have changed the regexes. Hopefully, this won’t create new registration issues, so we may need to keep an eye on this. Adding the email notification will be important to do soon, just in case attempts are made that don’t match our rules.

**Comment by cjardine-bsc** [comment]
I've re-inserted the double backslashes.

**Comment by cjardine-bsc** [comment]
I've updated the cases in the DB where receiver type is LOTEKSRXDL to LOTEKSRX-DL and removed the duplicate from the lk_receiver_type table.

That should tidy that up a little.
