### ISSUE TITLE
Detections prior to deployment

### ISSUE THREAD

**Issue by zcrysler** [MotusDev/Motus-TO-DO#224]
Project 158 has all their tag metadata entered correctly, all tags were deployed in June 2017: https://motus.org/data/project/tags?projectID=158.  When you download project data, there are a lot of detections starting in April 2017.  I thought detections prior to deployment were removed?

Those detections prior to deployment aren't ambigs (no detections for that project are ambigs), and the detection data shows the motusTagID, but the rest of the tag metadata is NA (tagDeployID, etc.) which would be expected since there's no deployment for that time range.  What's the justification for allowing detections up to 2 months prior to deployment being let through?  It's straightforward to eliminate these from the user side, just wondering why there are so many hits outside deployment ranges.

**Comment by Hussell** [comment]
From what I can see, the tags were registered on May 31st 2017, but the tag deployments weren't entered until Jan 10th, 2018. Meanwhile, a lot of receivers' data were processed, so we found a bunch of detections for their tags with no known tag deployment, including (what I assume are) the times in April and May when they activated the tags to record their parameters and register them. When they entered deployment information, most of the detections were assigned to deployments.

I think we always provide all the detections we know of, whether they were during a known deployment or not, partly because people don't always enter information about tag deployments in a timely manner (or correctly, or at all), and partly because withholding any data seems like something we shouldn't do.

**Comment by zcrysler** [comment]
So what's the cutoff for detections that happen prior to deployment?  There must be one otherwise I imagine every project would have years of earlier data from repeated tags between projects/years.  Since detections for this project start April 1st - is it logical to assume you get all detections for hits matching your tag starting the day they were registered despite any metadata?

Would be good information to include in the RBook so I want to understand the process correctly

**Comment by Hussell** [comment]
But the active lifetimes at https://sgdata.motus.org/public/motus_tag_timeline.html are different than the active lifetimes that would have been there when the detections were processed, because the tag deployment metadata wasn't available until after the detections were processed, correct?

Right now the active lifetimes for the tags of project 158 are shown as June 2017 through February 2018, but I assume they would have been April 2017 through December 2017 at the time (or May through January for a tag registered in May)?

(Sorry to hear you're unavailable for now, John. Thank-you for the update.)

**Comment by jbrzusto** [comment]
You should be able to see what metadata were current when any given batch
of data were processed by looking at the commit history of this repo:

  https://github.com/jbrzusto/motus-metadata-history

(assuming it has been updating correctly, which is not always true!)

That's one of the main reasons I set it up.

The current metadata commit hash is saved in the batchParams table of a
receiver database whenever a new batch is generated.  I can't recall off hand
whether that is making it to the master database on sgdata.motus.org
But the date a batch was created will usualy be enough to find the appropriate
version of metadata.

J.

On Tue, May 1, 2018, at 14:53, Jeremy Hussell wrote:
> But the active lifetimes at 
> https://sgdata.motus.org/public/motus_tag_timeline.html are different 
> than the active lifetimes that would have been there when the detections 
> were processed, because the tag deployment metadata wasn't available 
> until after the detections were processed, correct?
> 
> Right now the active lifetimes for the tags of project 158 are shown as 
> June 2017 through February 2018, but I assume they would have been April 
> 2017 through December 2017 at the time (or May through January for a tag 
> registered in May)?
> 
> (Sorry to hear you're unavailable for now, John. Thank-you for the update.)
> 
> -- 
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub:
> https://github.com/MotusDev/Motus-TO-DO/issues/224#issuecomment-385739467


-- 
#-----------------------------------
#  John Brzustowski
#  Wolfville, NS  Canada

**Comment by zcrysler** [comment]
Thanks John, so when the metadata cache on sgdata.motus.org is updated would that mean that these early detections would no longer be assigned to the project because it would be working off of metadata which wasn't initially available?  Or if there are detections prior to metadata being entered, will it always use registration date?

**Comment by jbrzusto** [comment]
When the tag finder runs, it uses the metadata available that day.
Those detections are added to the master database, and basically immutable - 
any subsequent changes to metadata don't affect them.  So when metadata
change, we need a "smart" re-run of various batches, and replacement
of them in the database.  This is a long-standing TODO, but I'm not sure
how Denis is planning to deal with it.
