### ISSUE TITLE
Receivers map not updating

### ISSUE THREAD

**Issue by zcrysler** [MotusDev/Motus-TO-DO#243]
A new receiver was just registered in North Bay ON, but it's not appearing in the online map.  Everything looks good on the deployment and I thought the map updated automatically - is it set to only update once a day?

Deployment in question: https://motus.org/data/receiver/deployment/edit?projectID=1&id=4662

**Comment by Hussell** [comment]
I see it here: https://motus.org/data/receiversMap

The only thing that only updates once per day is the tracks map. Everything else should update immediately if you reload the page. (Thanks to improvements in the speed of retrieving detections from the database, I'm considering making the tracks map compute tracks each time the page is loaded, since precomputing the tracks has been annoying.)

**Comment by zcrysler** [comment]
Ok, there was some sort of delay though, it wasn't showing up on my computer or Ross's (who made the deployment) and I waited a couple hours before posting, but it's there now

**Comment by denislepage** [comment]
We can increase the frequency of the scheduled update. Moving to live would depend on the delay required to generate the info.
