### ISSUE TITLE
Data uploaded to wrong project

### ISSUE THREAD

**Issue by zcrysler** [MotusDev/Motus-TO-DO#249]
jobID 183444 was uploaded to project 136, it should have been uploaded to project 1. It also says there were no products (ie hourly plots), but also that there were 5 unfiltered detections which makes me think there should be a plot to see. I'm not sure if that's because of incorrect project assignment. Can this be assigned to project 1, and checked to see if data was processed correctly?

**Comment by pmorrill** [comment]
Zoe: I am unclear. Was the data uploaded to the wrong project by user error? Or did the software make an incorrect assignment during upload?

**Comment by tcrewe** [comment]
User error.

**Comment by Hussell** [comment]
In the event of a conflict between the user-entered project ID and project IDs from Motus metadata, the user-entered ID is ignored. So because this receiver was deployed by project 1 during the time covered by this upload, everything was assigned to project 1. I see the 5 hits in the motus.org database. The hourly plot doesn't seem to have been regenerated, because the detections were on May 9th, and the plot only goes to April 17th.

https://sgdata.motus.org/download/1/SG-3214BBBK8447-2017_Motus_Clear%20Creek_hourly_tags.png
