### ISSUE TITLE
Excel having trouble with UTF-8 in species list (to BOM or not to BOM, that is the question)

### ISSUE THREAD

**Issue by cjardine-bsc** [MotusDev/Motus-TO-DO#253]
The species list .csv on this page: https://motus.org/data/project/tags/template?projectID=137

Downloads corrupted French characters. Paul, I know you managed to add a wee bit of code to fix this in the other APIs. Could you apply that here?

Thanks!

**Comment by pmorrill** [comment]
I have put the new species-list generation in place (sandbox). The FR names appear good to me opening the file in LibreOffice. Let's check it out again tomorrow after deployment. But, even on the page you link above, my LibreOffice has no problem displaying the FR names.

**Comment by Hussell** [comment]
I'm able to view the CSV without any corruption as in Notepad++. It's in UTF-8 encoding.

**Comment by cjardine-bsc** [comment]
Interesting. They are corrupted in Excel, looks like Excel by default doesn't read in Unicode. 

I'm assuming that excel will be the default program most people will use to open this file and search for the species they are interested in. We should support it if we can. 

A potential partial fix would be to add a Byte Order Mark to the extract, which it seems works for Excel 2007 and higher. That will clue excel into the fact that the file is UTF encoded. 

https://stackoverflow.com/questions/155097/microsoft-excel-mangles-diacritics-in-csv-files

**Comment by denislepage** [comment]
Yes, BOM should be the correct way to handle UTF-8 files.

To confirm, open the file in NotePad++ and do Encoding, Convert to UTF-8-BOM.

If you open the CSV in Excel, it will recognize it right away as UTF-8.

I don’t know if there are any downsides to using BOM, but I think it should be done as a standard for all CSV downloads in UTF-8 formats.

**Comment by Hussell** [comment]
Using a BOM at the start of a UTF-8 file will make the file unopenable for some older software (including older versions of Excel), but the older versions are getting rare enough they can probably be ignored.

**Comment by denislepage** [comment]
We also need to check what happens when someone opens the file with BOM and saves it back as CSV (e.g. the tag template). I think the file then gets converted to ANSI, but the encoding is properly handled (suggesting that the transfer of encoding is done when you open the file).

Few people will bother trying to save it as Unicode (which is one of formats offered by Excel), so I think we have to expect that people will be mostly uploading ANSI?  From Excel, when you save as Unicode text, it is reported as UCS-2 LE BOM in Notepad.

How is our upload tool handling files saved with BOM, or saved with other encodings?

So many questions for such a seemingly simple thing.


1.       We need to make sure that switching to BOM to allow correct recognition in Excel doesn’t negatively impact other programs to open them, primarily R or Mac Excel. Which version of Excel started supported BOM?

2.       We need to understand what happens to those files in a few different software when they are saved back with user additions for upload.

a.       Excel CSV ANSI

b.      Excel Unicode (UCS-2 LE BOM) – also uses tabs by default, not commas.

c.       UTF-8 with BOM

d.      UTF-8 without BOM

e.      Mac Excel

f.        R CSV write

**Comment by pmorrill** [comment]
The BOM is now pre-pended to any csv download from the sandbox. We need to check the 'tag deployment template' file, and make sure that it can be uploaded back into the system even if the BOM is present.

**Comment by cjardine-bsc** [comment]
Thanks Paul. 

The species list is now downloading without corruption in excel in sandbox. 

I tested downloading the tag_deployment in sandbox and re-uploading it and the process seems to be working correctly in so far as it is processing the records into the api_tag_deployments table. However the process is returning an error to the user " Your template file appears to be empty." Even though the records have been processed into the table. 

I get this error on live and sandbox, using both a download from live and sandbox (so 4 different case scenarios, all with the same error). 

Zoe, have you seen this before? Any idea what might be causing this?

**Comment by cjardine-bsc** [comment]
Sorry Paul, this isn't an issue for you, it was all for me. (Mine! Mine! Mine! #findingNemo) 

The validation query was failing due to some aggregate code I put in to deal with multiples speciesIDs being returned for the same species name. Apparently you can't use an aggregate in an update statement (who knew?). Because the query was failing it wasn't returning the @count output parameter and your process was returning the "your file seems to be empty" error. 

Is there a way on your end to differentiate between the proc failing to return a @count parameter and returning a @count parameter of zero? I'm wondering if those two errors shouldn't be different. The proc failing to return the output parameter should ideally trigger and error telling the user to contact motus for support. 

On the plus side, the BOM file is downloading and uploading correctly on a PC.

**Comment by pmorrill** [comment]
I'd have to verify, but a getInt("count") that returns null would probably correspond with failure to return a @count param at all.

I won't get a chance to look until next week though.

**Comment by denislepage** [comment]
There's supposedly a way to save UTF8 files in Excel, but that isn't working for me. Most files won't have UTF8 characters, so it shouldn't really matter, in theory, unless they are using French or Spanish characters.

One thing that does work with UTF8 is to use Google Spreadsheets instead of Excel. 

Have you tried to open the file in R, write it back to a new file and reload the new file again? That should likely work.

**Comment by Hussell** [comment]
Seems to be broken on live and beta, but working in sandbox. Did something not get passed over to the beta branch?

**Comment by Hussell** [comment]
It looks like there's a view in the sandbox database which is missing from the beta/live database: vwSpeciesLookup.

**Comment by denislepage** [comment]
created just now

**Comment by Hussell** [comment]
Ok, now beta and live are returning a UTF-8 file with BOM. According to #348, should this go back to being a UTF-8 file without BOM?

**Comment by denislepage** [comment]
Yes, I think I had only tested the change in sandbox. We should make it in beta7 and live too.

**Comment by Hussell** [comment]
Ok, we're back to a UTF-8 file **without** BOM in beta7.
