### ISSUE TITLE
Change species download link to reference query instead of table

### ISSUE THREAD

**Issue by cjardine-bsc** [MotusDev/Motus-TO-DO#255]
The current species list button on the bulk tag deployment upload page pulls (I think) from the lk_species table. 

We'd like to change this to pull from a query so that we can include species_codes and remove non-motus eligible species like plants, lichens etc. 

I've built a new query in sandbox that can be used for this purpose called vwSpeciesLookup. 

Stu would like to explore making this list accessible in the tag registration instructions on sensorgnome and/or on the tag registration upload page.

**Comment by zcrysler** [comment]
I can put a list on the sensorgnome.org registration instruction page if you've got one ready. I don't think there's really a place for it here https://motus.org/data/project/sgJobs?projectID=137 since we don't go into any specifics of creating the package.

Should also use this info to replace the "species list" link here https://motus.org/data/downloads and on the bulk upload page: https://motus.org/data/project/tags/template?projectID=137

**Comment by pmorrill** [comment]
The API entrypoint used to generate this species list is used as well by the SG code. We don't want to force changes on that side, so I will create a new api function to handle this.

The original function allows filtering on the basis of name matches, and language. But I think what you want with the updated version is a verbatim return of the entire data set.

**Comment by cjardine-bsc** [comment]
You got it, no filtering needed on this one. 

Thanks Paul!
