### ISSUE TITLE
Tag lifespan estimates

### ISSUE THREAD

**Issue by zcrysler** [MotusDev/Motus-TO-DO#256]
There are detections of a tag past the estimated life expectancy that are available through the tagme() function. However, after a certain point despite still getting detections, there's no associated metadata. The metadata for this tag was updated March 28th, so after the last metadata push. So 3 things come up
1. are the lifespan estimates for new models too low (checking with Lotek)
2. once these batches are re-run, are all detections linking correctly with deployment metadata
3. if not, then John's lifespan calculations aren't matching with ours

project 123, motusTagID 28287, batchID 164223. The last hitID with metadata is 453738303, the first hitID with NO metadata is 453738304

**Comment by zcrysler** [comment]
There's an automatically generated tagDeployEnd, which is the date that the deployment metadata stops linking, but if we're saying the tag should be dead, then why are we searching for it, and why are we still showing detectiosn for it

**Comment by StuMackenzie** [comment]
Checked with Lotek and they were expecting these tags to last longer, but have no empirical evidence to assign new tag life’s. Unfortunately we have the best data to determine these new parameters, but that data is stuck within the data processing issue. For now, I would suggest we double any estimates so that no data is being excluded then refine when we have better tag-life estimates to assign.

**Comment by jbrzusto** [comment]
Here's what my code is generating as a lifespan estimate:
```R
> predictTagLifespan(model="NTQB2-1", bi=7.099)
[1] 26.7...  ## in days
```
But by default, we've been adding a 50% buffer to allow for occasionally longer lived tags
(and if I recall correctly, these are 80% lifetime estimates, so ~ 20% tags will live longer).
So for that tag (motus 28287), the active life is calculated 
as 2018-03-26 06:00:00 to 2018-05-05 07:01:17, which is 40 days (i.e. ~ 1.5 * 26.7 days)

**Comment by cjardine-bsc** [comment]
That's the same as I am getting for this tag (40 days), as I'm using your same formula. The tagDeployEnd in the alltags view in R is the deploy date plus this 40 days. 

Interestingly tagfinder is still assigning detections to this tag after May 5th, beyond the 40 days (I didn't think that would happen?). So there are detections that the user is seeing beyond the active life span that are assigned to this tag, but they are not being linked to the deployment in the alltags view because they are beyond the anticipated end date. 

It sounds like we need to change the D value for this tag, and probably all the new tags to be higher until we can test the tags with different frequencies and get actual D values for them. 

For the moment, I've bumped the D values for the new NTQG2 tags by 50%. That bring the expected lifespan of this tag to 60 days. That will translate to the metadata download in R and the alltags view will now link those hits to their deployment. 

I'm still not sure I fully understand how tagfinder is assigning tag_ids to these runs beyond the expected lifespan of the tag, but we may need to change the D values for these tags on that end too, in case there are detections beyond the expected lifespans of these new tags that we're missing.

**Comment by jbrzusto** [comment]
The detections of tag 28287 in the sgdata.motus.org master DB have this range of dates:

```sql
MariaDB [motus]> select min(t2.hitID), from_unixtime(min(t2.ts)),max(t2.hitID), from_unixtime(max(t2.ts)) from runs as t1 join hits as t2 on t2.runID=t1.runID where t1.motusTagID=28287;
+---------------+----------------------------+---------------+----------------------------+
| min(t2.hitID) | from_unixtime(min(t2.ts))  | max(t2.hitID) | from_unixtime(max(t2.ts))  |
+---------------+----------------------------+---------------+----------------------------+
|     441171010 | 2018-04-07 04:33:09.653500 |     453738447 | 2018-05-05 06:23:47.730900 |
+---------------+----------------------------+---------------+----------------------------+
```
so I'm not seeing any hits outside the active life as calculated above (when including the 50% buffer).

**Comment by cjardine-bsc** [comment]
Ahh it's a rounding issue. Our deployment goes from 2018-03-26 06:00:00.000 to  2018-05-05 06:00:00.000 as I've rounded tag lifespan to the nearest day. So the hits from the 23minutes after 6 on May 5th are orphaned. 

Either way, the fact that there are still hits down to the hour before the tag lifespan expires suggests that it is lasting longer than we expect and we might want to increase the D value for these tags, at least until we have more information.

**Comment by denislepage** [comment]
Note that for the time being at least, this is something that needs to be done in both Motus and SG servers, so John should be alerted.

**Comment by zcrysler** [comment]
In addition to the lifespan issue, a number of these tags are also showing up in the alltags table with detections after the tags have been de-activated (ie. the metadata has an end date, and the tag is sitting on the users desk not turned on). Examples of tags that have been deactivated online and the physical tag has been off when there are detections that look true are: 27965; 27971; 27953; 27954; 28001; 28006. Detections after the tag has been deactivated don't have any deployment metadata associated with them, these detections happen about a month after de-activation, so why are their detections still available to the user? maybe this is related to the metadata not being up to date right now.

The user also said "About 42% of our tags that have been detected by one or more receiver stations this season and that have not been deployed on Helgoland show up with detections on Helgoland (47 of 112, the obvious false positives sorted out). This is quite a lot I think. I really hope that there is no (or negligible) mess between tags that have been used by Thomas and Heiko on Helgoland and ours and that we can trust the data. For sure, we have a lot of birds alternating between antenna stations across the German Bight, and this is exactly what we're trying to elucidate in our project ;) "

These tags aren't listed as ambigs, I haven't gone through all tags in detail, but the few I've looked at from the list above look like potentially real hits

**Comment by zcrysler** [comment]
There's still something going on with these detections, tags are showing up in tagme() beyond when their deployment was ended (eg. motusTagIDs 27965; 27971; 27953; 27954; 28001; 28006). Although it seems like the original issue with the missing metadata due to rounding issues was resolved, the battery life for these tags still needs to be revisited since it seems like they may be detected well beyond lifespan estimates.

**Comment by cjardine-bsc** [comment]
The original issue here has been resolved, but two more wack-a-moles appeared in the comments. I've opened two new issues for those and am closing this one.
