### ISSUE TITLE
Failed Lotek tag registrations

### ISSUE THREAD

**Issue by zcrysler** [MotusDev/Motus-TO-DO#261]
It seems to me like tags are being registered with the wrong BI more frequently now than in the past, I don't know if something has changed or if I'm just noticing it more. jobID 186104 includes roughly 100 tag registrations, only 10 went through. Of those 10, only 6 have the correct BI.  What's more, the auto email that the user gets only lists issues with 11 tags - it says 1 failed to register and 10 have no estimate of BI.  Although it does say that only 10 tags were registered in the end, it doesn't mention the huge number of tags that failed due to "No tags detected in file tag005.wav in either codest Lotek4 or Lotek3".

I'm trying to get the uploaded file from the user, but can someone look into this job to see why no tags are being detected in so many .wav files?

**Comment by StuMackenzie** [comment]
Assuming that we’re comparing ‘our’ BI to labels or the document provided by Lotek, and given that these tags are largely untested, it may be worth trying to confirm who is actually wrong. Are BI’s being calculated wrong by our system, or is the label and sheet from Lotek wrong?

**Comment by zcrysler** [comment]
This was also happening with project 74, I looked at a few of their uploads and the recordings looked fine with the correct BIs but they were registering incorrectly. They had to re-record and re-upload and then they registered with the right BI

**Comment by zcrysler** [comment]
I just got the files the user uploaded, I checked a few tag recordings, ones that were registered with the wrong BI definitely have detections every 29 seconds as expected even though they're registereding as 58 or 87 seconds. Tags that had the warning "no tags detected in either codeset Lotek4 or Lotek3" also have 3 sets of detections 29 seconds apart. From visual inspection I don't see an obvious difference in recordings that went through and recordings that failed

**Comment by jbrzusto** [comment]
These files look as if they were recorded from the audio jack of a Lotek receiver: the pulses have a bell
shape (in an amplitude vs. time plot), and the first pulse of each burst seems wider than the rest.

Recordings from Lotek audio jacks for registration purposes should be disallowed; it already has
a warning on the [wiki page](https://sensorgnome.org/VHF_Tag_Registration#section_11), but I'm
not sure that is enough, or that users are following those instructions.  It seems that often the signal is too
modulated (to enhance perception by humans?) to allow for precise timing of the pulses.  It is hit or miss whether a burst will be detected.  

Also, some or all of these tags *might* have been misprogrammed:  they might
possibly be operating in the 7.5, 5, 5, 5, millisecond burst mode, instead of the usual 2.5, 2.5, 2.5, 2.5 millisecond burst mode.  The former are not reliably detected by sensorgnomes, and also
have considerably shorter lifetimes than advertised, because the transmitter is spending more than
twice as much time in "on" mode.

The same issue leads to incorrect burst interval, because a single misdetected pulse, or one detected with
bad timing resolution, can cause a burst to be missed.  The registration code then does its best to
estimate a burst interval, but it not's not that clever.  So the "wrong" BIs are always a small integer
multiple of the true BIs.

If users don't have a funcubedongle (or rtlsdr) with which to register tags, and want to use a Lotek receiver,
we should be asking them to record a .DTA file while activating each tag in turn for several bursts, and submit that, along with a list of the tag IDs they activated, in order. It will take a bit of code to use that, but it would be a more reliable way for Lotek-only users to register tags.  (It would not, unfortunately, catch the case of misprogrammed tags; i.e. the ones in the long-pulse mode that burns batteries faster.)

**Comment by zcrysler** [comment]
So what's the best course of action for this user? They only have Lotek receivers so it makes sense that that's how they would record tags.

**Comment by denislepage** [comment]
I would be tempted to insist that they get a FUN Cube if that will resolve the problem. Even, covering the cost may end up being less expensive than trying to manually process unsuitable recordings.

Do we have some spares that we can lend for short-term uses, if people are unwilling/unable to buy their own?

**Comment by jbrzusto** [comment]
Testing tag registration jobs against a different pulse detection algorithm.

`findpulsetdbatch` with tagfinder options `--unsigned-dfreq=1` and maxFreqSD=0.2
instead of 0.1

- Job 186104; 99 tags
10 tags registered, but 4 with incorrect BI:
Success: tag 6:29.3 was registered as motus tag 29297 under project 145
Success: tag 9:29.3 was registered as motus tag 29298 under project 145
Success: tag 10:58.6 was registered as motus tag 29299 under project 145
Success: tag 11:87.89 was registered as motus tag 29300 under project 145
Success: tag 14:29.3 was registered as motus tag 29301 under project 145
Success: tag 21:58.59 was registered as motus tag 29302 under project 145
Success: tag 45:29.3 was registered as motus tag 29303 under project 145
Success: tag 61:29.3 was registered as motus tag 29304 under project 145
Success: tag 93:58.59 was registered as motus tag 29305 under project 145
Success: tag 95:29.3 was registered as motus tag 29306 under project 145

New algorithm: 96 detected correctly with correct BI
1 correct ID but wrong BI, (tag102.wav)
2 no detections (tag44.wav, tag103.wav)

- Job 178395; 40 tags
4 tags registered, all with incorrect BI:
Success: tag 335:19.4 was registered as motus tag 31896 under project 74
Success: tag 351:19.4 was registered as motus tag 31897 under project 74
Success: tag 364:29.1 was registered as motus tag 31898 under project 74
Success: tag 371:38.8 was registered as motus tag 31899 under project 74

New algorithm: 40 detected correctly with correct BI (9.699s)

**Comment by jbrzusto** [comment]
note to: @zcrysler @cjardine-bsc 
After a number of changes to the pulse detector and tag finder used for registration, the tags
from project 145 have all been registered, but there are some duplicates which need to be removed.
The following table shows the duplicated tags.  In each case, we should end up with only one tag for each integer mfgID; i.e. the version with the **.1** suffix should be dropped, with any metadata transferred to the version without **.1** Also, in each case, the `period` field from the tag **with the .1 suffix** should be used in the final record.  i.e. the `period` field from the non-**.1** versions is not accurate.

motusTagID|mfgID|period|dateBin
---|---|---|---
29297|6|29.297|2018-1
31448|6.1|29.295|2018-1
29654|13|29.293|2018-1
31449|13.1|29.299|2018-1
29656|16|29.293|2018-1
31450|16.1|29.296|2018-1
29657|17|29.293|2018-1
31451|17.1|29.296|2018-1
29663|26|29.293|2018-1
31452|26.1|29.296|2018-1
29664|27|29.292|2018-1
31453|27.1|29.294|2018-1
29666|29|29.293|2018-1
31454|29.1|29.296|2018-1
29669|33|29.292|2018-1
31455|33.1|29.295|2018-1
29670|35|29.293|2018-1
31456|35.1|29.296|2018-1
29677|43|29.293|2018-1
31457|43.1|29.296|2018-1
29678|44|29.293|2018-1
31458|44.1|29.295|2018-1
29303|45|29.297|2018-1
31459|45.1|29.295|2018-1
29679|46|29.294|2018-1
31460|46.1|29.296|2018-1
29680|47|29.293|2018-1
31461|47.1|29.296|2018-1
29685|54|29.293|2018-1
31462|54.1|29.296|2018-1
29304|61|29.297|2018-1
31463|61.1|29.296|2018-1
29696|99|29.293|2018-1
31464|99.1|29.295|2018-1
29650|100|29.293|2018-1
31465|100.1|29.295|2018-1
29653|104|29.293|2018-1
31466|104.1|29.295|2018-1

**Comment by cjardine-bsc** [comment]
My process deals with merging all the metadata and detection data. So I've just merged the old tags with the incorrect periods into the new tags with the correct specifications. That's how we've been dealing with these type of issues thus far and it's working well. We keep a list of merged tags that we can reference if needed. 

Note that if you'd like to flag a post for someone the easiest thing is to assign them to the issue. 

Thanks John! Cheers!

**Comment by zcrysler** [comment]
Three tags are still registered to this project with an incorrect BI of 58.59, they also weren't on the list of duplicates above although they do appear twice

Tags 10, 93, 31, I think the original upload was jobID 186104

We can default to using the manual registration that Catherine did if they can't be registered based on the recordings from the user

**Comment by cjardine-bsc** [comment]
They aren't flagged as duplicates because they have different BIs. 

You can send me the merge tags statements to remove the incorrectly registered tags.

**Comment by zcrysler** [comment]
Before using the manually registered tags, Jeremy can you try re-running those recordings to see if we can get a real registration?

**Comment by Hussell** [comment]
As things are, rerunning this upload wouldn't change the registration of these tags: the existing registrations would have to be deleted first. If that's done, I can rerun the upload and these three will be re-registered, and all the others in the uploaded file will fail because of existing registrations.

**Comment by cjardine-bsc** [comment]
Even if they come through with different BIs? I would have thought that would re-register them (with .1 as the mfg_id) since the period would be different (indicating a distinct tag from the current incorrect registrations)

**Comment by Hussell** [comment]
A distinct tag, in this case, is one which has a unique combination of project ID, date bin, and manufacturer's ID.

**Comment by cjardine-bsc** [comment]
yes, but we have the ability to add the .1 to the mfg ID to manage cases where there are duplicates in those three parameters. 

That functionality suggests that we can register duplicates?

**Comment by zcrysler** [comment]
That's how we allow users to do it, we just tell them to save the wav files as tag 100.1.wav for example

**Comment by cjardine-bsc** [comment]
ah, let's do that then!

**Comment by jbrzusto** [comment]
The ".1" scheme is meant to be a consistent framework for handling tags with the same mfgID but
*different* BI being deployed in the same season. Details [here](https://sensorgnome.org/VHF_Tag_Registration/Use_of_tags_with_duplicate_IDs_within_a_project).

**Comment by cjardine-bsc** [comment]
Thanks John, that's understood. 

But deleting a tag is problematic, so we're just using this as a work around to get both tags registered and then we'll merge them.

**Comment by zcrysler** [comment]
As these tags didn't go through with the new algorithms, we'll use the manual registrations that Catherine did originally
