### ISSUE TITLE
User unable to complete data upload

### ISSUE THREAD

**Issue by zcrysler** [MotusDev/Motus-TO-DO#263]
When logged in as user 234 to project 195 I'm not able to upload detection data through https://motus.org/data/project/sgJobs?projectID=195&lang=en.  After successfully verifying the file, I'm not able to click on the "upload file for sensorgnome processing" button.  When logged in as myself I'm able to upload fine for that project.

**Comment by zcrysler** [comment]
They've got full permissions, he's listed as a PI on the project user page https://motus.org/data/project/users

And yes, the button stays disabled, nothing happens when you click it. It's a fairly new project, I was wondering if it's related to the metadata updates?

I didn't complete upload of the file when I tested logged in as me, I'll send it to you now through we transfer

**Comment by pmorrill** [comment]
OK - I have the file. Probably onw't gt to try it before the call though.

**Comment by pmorrill** [comment]
Zoe: do you recall whether you saw the message 'This file is new: you may upload it to the processing server' when you verified the file as Junior T. ?

If you are not sure, can you sign in as him again and retest? I just tried it as him and that message shows, and the 'Upload file' button is enabled and ready to use. (I did not click it to try the upload).

**Comment by zcrysler** [comment]
Yes I got the message that I could begin upload, the "upload file" button was there, but clicking it did nothing

**Comment by zcrysler** [comment]
I uploaded the data - jobID 186911 - it processed with no errors but the hourly plots don't include teh data I just uplaoded. There are data files up to 2018-06-09, but the hourly plot only goes to 2018-05-29

**Comment by zcrysler** [comment]
I have some new tag registrations from Junior, Paul can you let me know if you want me to try uploading logged in as him? Or send you the files directly?

**Comment by pmorrill** [comment]
Zoe: you should try at least one of them signed in as him. The thing we need to determine is whether this is a browser-specific problem. I use Firefox on Windows, and have seen no issues of the sort you describe.

If you see the msg to upload, watch the 'Upload File' button carefully. Is it enabled (clickable)? It should be. But if it is, then watch to see if any activity happens in the browser when you click it. In FF there is set of debugging tools that you can open, which let you see the details of any transaction. That is what we need to inspect as the button is clicked. But since I can't reproduce the issue, I can;t see that level of detail. 

On the other hand, if the button is still disabled, you won't see it click at all (it will remain static when you click). That would be an important finding.

**Comment by pmorrill** [comment]
BTW: there are also debugging tools in Chrome, and even in IE now.

**Comment by zcrysler** [comment]
When logged in as Junior on Firefox in Windows I'm able to verify file, then the "upload file" button seems clickable and looks like it's being clicked, but clicking it does nothing. I have debugging opened on Firefox but nothing is happening there, I'm not sure what I should be seeing/sending to you

**Comment by pmorrill** [comment]
ok - transfer that file to me.

**Comment by pmorrill** [comment]
Can you send me his password by email? Or, are you just using the 'assume a user id' tool?

**Comment by zcrysler** [comment]
I'll email it - I've never noticed the assume user id tool

**Comment by pmorrill** [comment]
I have checked a fix into master and beta6. At the same time I updated the jobs servlet to better handle missing projectID redirects. The user landing page links in beta6 are also updated to point to this new file upload tool, rather than the old SG version that John does not want supported. We'll test it in Beta tomorrow, then go to live if all is well.

Zoe: sign in as junior again after tomorrow's deployment, and use the beta server to test that same file you sent me earlier. Hopefully, all will be well.

**Comment by denislepage** [comment]
that was something specific to this user?

**Comment by zcrysler** [comment]
Can you let me know when it's ok to go ahead and test? Junior would ideally like to send these tags out tomorrow early afternoon (EST) but I need to confirm they register properly first

**Comment by pmorrill** [comment]
Maybe you can talk Jeremy into a beta6 deployment this afternoon?

**Comment by Hussell** [comment]
Done.

**Comment by zcrysler** [comment]
Thanks!

It works on beta - can I go ahead and upload the rest of his tags?

**Comment by zcrysler** [comment]
All uploaded as expected, so Junior should be able to do uploads to live now or is that still waiting for a beta push?

**Comment by Hussell** [comment]
The live server has been updated, so this should work now.
