### ISSUE TITLE
tagme - internal server error

### ISSUE THREAD

**Issue by Hussell** [MotusDev/Motus-TO-DO#266]
I called tagme(4, update=TRUE), provided my password and login, and got the message:

Error: Internal Server Error

I was successfully logged in: calling tagme again didn't cause a second request for my password and login. Possibly related to project permissions: I'm not registered with any projects. Nor am I an administrator.

**Comment by zcrysler** [comment]
I'm running into the same issue when I run

projnum = "Lotek-D000427"
tagme(projnum, new = TRUE, update = TRUE)

I'm not sure if it's related but this receiver has no deployment although it does have data submitted - which may or may not be processed correctly (see https://github.com/MotusDev/Motus-TO-DO/issues/269), and is the receiver that brought up this issue https://github.com/MotusDev/Motus-TO-DO/issues/264

**Comment by jbrzusto** [comment]
Is this version of tagme() talking to the server at motus.org, or the one at sgdata.motus.org?

**Comment by pmorrill** [comment]
It's talking to the motus.org servlet. The problem is on my side somewhere.

**Comment by pmorrill** [comment]
These are two different issues, though the R-client is making them look similar due to a limitation in our protocol, The server-side api returns a Http error 500 in both cases, along with a payload that details the actual error. the R-client code sees the 500 error and reports it, then dies (as far as I can tell). The explanation for the error is not reported. This seems to be a character of the RCurl library to behave this way (not of our own code).

John has reported this problem before: since we send back 500 http errors, it is difficult (impossible?) to parse payloads carried along with them.  I'm not going to try to hack the RCurl library.

However, tracing this issue reveals two elements that can be improved. First, out error package return was not properly bzip2 compressed (though the standard data payloads are compressed). I will put a fix in place today.

Secondly, the (email) api notifications we have in place are not being generated for these specific types of errors, which are basically 'handled' by sending back a 500 error, plus an explanation (the latter lost on the R-client side, as mentioned). I will beef up the notification handler to send us these messages as well, for the time being.

The error Jeremy's situation generates is actually 'Detection data access denied' (his account does not have direct access to project 4 - see issue #272.

The error for Zoe's case is certainly something different, and I will look into it further. However, her predictions are likely correct. If the R-client were able to 'see' the error explanation - and report it - rather than just a 500 Server Error message, we'd know if the error is appropriate or not.

**Comment by pmorrill** [comment]
All of this brings us to the question: are we determined to return 500 errors when we encounter problems in the request being made? I believe the argument for this relates to REST standards - I am not versed in this area, but we need to decide. A http OK (200) can be returned and the R-client picks out the error detail and reports it to the client user. Problem solved.

**Comment by jbrzusto** [comment]
I'd suggest switching from the `RCurl` package to the `httr` package.  I've done this for jbrzusto/motusServer (used when calling the motus.org API) but haven't had a chance to do so for jbrzusto/motusClient.  `httr` is better maintained, of cleaner design, and http queries through it return full header info and content separately, regardless of error status.
