### ISSUE TITLE
Entering text on filters reloads page

### ISSUE THREAD

**Issue by zcrysler** [MotusDev/Motus-TO-DO#284]
I'm not sure if this is an issue, but a user pointed out that when you enter any text or digits in the filter fields it reloads the page on each keystroke, eg: https://motus.org/data/projects

**Comment by Hussell** [comment]
There's a time delay before it starts to load the results, and if the user starts typing while the results are loading it will stop and wait some more.

Some sites load all results at once, then display them as the user types. This may be what the user is expecting. Since several of our tables (e.g. detections at swallow colonies) would take a very long time to load, we just load one page, then send a new request to the server when the user enters a search term, which again only returns one page of results.
