### ISSUE TITLE
Data Mgmt tools access rules audit

### ISSUE THREAD

**Issue by pmorrill** [MotusDev/Motus-TO-DO#285]
I've been reviewing the data mgmt tools in motus to ensure that access permission rules are applied consistently.  For the most part, it is good after a couple of adjustments. In a nutshell: the user landing page for a project XX can now be viewed by anyone who has XX on their 'readable' projects list.

The readable projects list includes all projects for which the user is a PI, or has AT LEAST read permission on one or more of the four access categories: project, receivers, tags, data.

The set of tool links presented on the user landing page is controlled by referencing the user's permissions for the various categories. If a user has 'UPDATE' permission on 'project, s/he will see all tool links, as this trumps the specific categories of revcs, tags, data.

But otherwise, the user sees the links in these groups:

a) If project UPDATE is allowed:
- manage project
- manage users
- MoveBank tools (in sandbox only)

b) if project READ is allowed:
- Data issues

c) if recv READ is allowed:
- manage receivers, but tool only allows view and sort of receiver records, and incomplete field presentation; NO landowner data available (just site name)

d) if recv UPDATE is allowed:
- manage receivers
- manage landowners and sites (see comment below)

e) if tags READ is allowed:
- manage tags, but tool only allows view and sort of tag records, and incomplete field presentation

f) if tags UPDATE is allowed:
- manage tags
- register new tags (see comment below)

g) if data READ, recv Read or tag READ is allowed:
- download project data

h) if data READ
- download the R client to access raw detection data

i) if data UPDATE is allowed:
- submit detection data

The specific tools accessed via these links are consistent in checking for the same access privilege as listed above. Exceptions are detailed in the following comments.

**Comment by pmorrill** [comment]
One question arising from this is the permission required to access the 'Manage Sites and Landowners' tool. As listed above, the current setup requires ReceiverEditor permission: anyone that can manage recvs, can also manage landowners/sites. Since we allow a recv editor to add a site via the recv-deployment mgmt tools, this makes sense to me. If someone objects (or this is being handled differently elsewhere), we better hash it out.

**Comment by pmorrill** [comment]
A second concern is that the SG data upload servlet handles BOTH tag registrations and detection data uploads. This opens a backdoor: someone with only tag editor permission can get to that tool, and could upload detection data. Also, vice-versa.

We could prevent this, by inspecting the file type begin uploaded before we proceed with the file verification and upload. It would also make sense to offer two (or three) versions of the Text Frag that carries the instructions: one for someone with only tag mgmt access, one for someone with only data mgmt access, and one for someone with both. Cumbersome, but possible,

**Comment by pmorrill** [comment]
Another loose end is the implementation of 'Tag Read' and 'Recv Read' permissions. As shown above, these permission levels confer no tools access by themselves. However, the following arguments exist:

1) Tag read access should allow viewing / searching the list of tags, without being able to manage (edit) them, or their deployments.

2) Same for recv read access, w.r.t receiver list / search

3) The data download page offers meta-data download links that are in fact operational for people with tag/recv view access (via securables). We should probably adjust so the tool link from landing page to data download servlet appears for people with READ on Tags / Recvs?

**Comment by denislepage** [comment]
As discussed today, let's ignore the upload tool question for now. Anyone with either tag OR data edit permission can upload files for processing.

For landowner, the proposal today was as follow: edit permissions on project is needed to edit landowner details, read permission on project gives access as read-only to landowners. That is not entirely satisfying.

I just discussed with Jeremy, and my counter proposal is (keep things about the same as they are now, essentially, but making it clear how we treat landowner info in the future?):

- receiver EDIT permission grants one access to view AND edit landowner information.

- receiver VIEW permission does NOT grant access to landowner info, even as read-only, at least until I am convinced otherwise. We could expose only the name if we wanted, for instance.

- Landowner info is not available through the R package.

- Landowner info "could" be made available as a downloadable file from the web site, but only if you have receiver edit permission.

An alternative implementation is that the DATA read option grants access to tag and receiver metadata as well through the R package. IE, for the purpose of permission handling in the R api, we only rely on the data permission? The main benefit would be to allow third-party users to access the data and metadata they need, but without some of the more sensitive info that we could make available only through the web site. Another benefit is that it would avoid inconsistencies whereby someone can download the data for a project, but can't access the metadata.

**Comment by denislepage** [comment]
>Another loose end is the implementation of 'Tag Read' and 'Recv Read' permissions. As shown above, these permission levels confer no tools access by themselves. However, the following arguments exist:

Yes, the 3 proposals for this sounds good.

**Comment by pmorrill** [comment]
I experimented yesterday with the original proposal from the call (recv edit permission gives access to site mgmt, not landowner mgmt; project edit required to access landowner mgmt; project read to view landowner list only). This is doable with an adjustment in the servlets.

Re:

> An alternative implementation is that the DATA read option grants access to tag and receiver metadata as well through the R package...

I am unclear on that: the R client does not see landowner data. Up to know we have used the term 'metadata' to refer to non-landowner details, I think?

**Comment by pmorrill** [comment]
Because of some uncertainty in this topic, the tools access permissions have been changed as reflected in the  original post (above), which I have edited. 

This means that Landowner mgmt tools are still available to those who have Recv Update permission. (You do not need Project Update), and there is no 'Read Landowners' page for those with Project read permission.
