### ISSUE TITLE
metadata not linking to detection data SG-3615BBBK0CD0

### ISSUE THREAD

**Issue by zcrysler** [MotusDev/Motus-TO-DO#298]
From project 123, which is a project on frequency 150.1 if that is related in some way.

When downloading that receiver through tagme(), all receiver metadata is NA except serial number for detections between 2018-03-07 and 2018-04-22, despite there being existing deployments covering this time period (deployment 4504 between 2018-03-05 to 2018-03-17, and deployment 4633 between 2018-04-06 to 2018-04-23).

Example batchIDs 155270, 155271, 158560

**Comment by denislepage** [comment]
I have seen cases like this where specific value respond very differently then others in term of query plan. I'll look into this. I could try using query hints to force the use of existing indexes.

**Comment by jbrzusto** [comment]
Batch 119705 has 10.7 million hits.  But it was generated Feb. 13, so why is it being fetched from sgdata.motus.org now?  I thought all user data requests were being served from motus.org.

The query which apparently "timed out" is

```
# Time: 180822 15:17:59 (GMT)
# User@Host: motus[motus] @ localhost []
# Thread_id: 356519  Schema: motus  QC_hit: No
# Query_time: 265.175117  Lock_time: 0.000109  Rows_sent: 10667102  Rows_examined: 10667102
# Rows_affected: 0
use motus;
SET timestamp=1534951079;
select * from hits t1 join batches t2 on t2.batchID=t1.batchID where t1.batchID=119705
```
(the mysql server log claims to have delivered 10.7 million rows, so it's likely the client that timed out while trying to format the returned result)

I don't know what generated that query.  It wasn't `motusServer::dataServer()` replying to an HTTP data request because:
- all `motusServer::dataServer` queries are paginated to a maximum number of rows
- there are no `select * from` queries there; they all specify columns to return
- sql queries in `motusServer` use an ` as ` in front of table aliases
- there's no record of a `hits_for_receiver` query in the apache logs around that time

So I'm not sure what's going on here.

**Comment by Hussell** [comment]
I incorrectly traced this to dataServer instead of the java class org.bsc.motus.servlets.SGDataAPI. The query in your server log was manually run by me while I was trying to figure out what was going on. I'm sorry for wasting your time on this one, John. Thank you for your quick response. I think I can figure out what's going on from here.

**Comment by jbrzusto** [comment]
Okay, no problem - just had me scratching my head.

**Comment by denislepage** [comment]
As far as I can tell, the indexes on sg_taghits are appropriate, but the size of the batch is the source of the problem here. There may be other ways to optimize this query. The join to sg_taghits_deploy_id is what seems to be slowing down the query. Without the join, the query returns in 4 seconds instead of 3.25 minutes.

**Comment by denislepage** [comment]
Holy guacamole.  I may have resolved the long query problem with receivers. At the very least for the receiver queries. It went from 3-4 minutes to < 1 second.

I'll also look at the hits_for_tag_project queries.

**Comment by denislepage** [comment]
I tried pulling in data for receiver SG-3615BBBK0CD0 with tagme, and that now seems faster.

I made a few tweaks on the project calls also, though I expect the difference won't be as noticeable.

Zoe, if you have a chance to try, you can let me know, but I'll close this issue for now. We can start a different one if there are still issues.

**Comment by Hussell** [comment]
Everything now looks fine in what I downloaded, except that the batches are all assigned to project 0. The batches all have the correct motusDeviceID, and so on. What metadata, exactly, is missing? (Also, try deleting the receiver database and downloading it again, if you hadn't already, since that's working now.)

**Comment by zcrysler** [comment]
I had deleted the database and was downloading from scratch, this is what I ran:
alltags <- tagme("SG-3615BBBK0CD0", new = TRUE, update = TRUE
alltags <- tbl(alltags, "alltags")
alltags <- filter(alltags, batchID %in% c155270, 155271, 158560()) %>% collect() %>% as.data.frame()

There was a deviceID, but deploymentID, dates, lat/lon, name etc. were all NA

**Comment by Hussell** [comment]
Ok, I've traced this back to a view (vwR_Metadata_for_receivers_recvDeps) which is expecting the column sensor_deployments.siteID to be non-null. The deployments that should have covered these hits have null site IDs. A quick search turns up 28 deployments with null site IDs, all of which are mobile. So the view needs to be modified to left join to sensor_sites instead of inner joining.

**Comment by cjardine-bsc** [comment]
I've modified the view.

**Comment by Hussell** [comment]
Ok, I re-downloaded this and the metadata is now present. Thanks to everyone who contributed to squashing these bugs!
