### ISSUE TITLE
exportData Error job 195742

### ISSUE THREAD

**Issue by zcrysler** [MotusDev/Motus-TO-DO#303]
upload for jobID 195742 ,SG-2516BBBK1DB1, project201 has an error:

195777 | exportData | 2018-07-26 20:10:42.109Z | Error | serno = SG-2516BBBK1DB1
-- | -- | -- | -- | --

The hourly plot looks ok, but I can't tell if I can get data from tagme() since there were no detections

Is this an error that needs to be fixed?

**Comment by zcrysler** [comment]
Same thing happened for another upload for project 201, jobID 195887:

195899 | exportData | 2018-07-27 18:45:25.276Z | Error | serno = SG-5DDFRPI3131A
-- | -- | -- | -- | --

**Comment by denislepage** [comment]
That receiver number has not yet been registered by SG in our database, but it has been placed in 2 different Motus projects, and one of them has a deployment (with no known deviceID). The SG error log has this:

2018-07-27T18-45-31.740660: Error with call stack saved to /sgm/errors//00195899.rds
More than one registered receiver has this serial number; motusIDs are:
  deviceID1        02        0
getMotusDeviceID(src)
stop("More than one registered receiver has this serial number; motusIDs ar
getMotusDeviceID(src)
pushToMotus(src, batchStatus)
h(j)


in getMotusDeviceID, this SQL check appears problematic, because it will return a row with a Null (or an incorrect) deviceID:

   ## see whether motus knows this receiver
    mm = MetaDB("select deviceID from recvDeps where serno=:serno", serno=m$recvSerno)*
    if (nrow(mm) > 0) {
        if (nrow(mm) == 1 || (nrow(mm) > 0 && useFirst)) {
            m$deviceID = mm$deviceID[1]
            rv = as.integer(m$deviceID)
            if (isTRUE(rv > 0))
                return(rv)
        } else {
            stop("More than one registered receiver has this serial number; motusIDs are:\n", capture.output(mm))
        }
    }

Maybe this will fix the problem (deviceID is not null)?

mm = MetaDB("select deviceID from recvDeps where deviceID IS NOT NULL and serno=:serno", serno=m$recvSerno)

Until then, deleting the deployment 4798 could be a work around.

**Comment by zcrysler** [comment]
I've asked Catherine to delete the receivers from project 202 which the user entered by mistake. Once that's done would it be better to get the user to re-upload those files, or wait for them to be re-run?

**Comment by denislepage** [comment]
If my understanding of the SG code is correct, the isn’t only that the receiver was listed under 2 projects, but the fact that it was deployed at all without a deviceID. Maybe not, because that is a common situation that I would expect is being dealt with properly.

We could try a re-run of the file after removing the extra project first, and if that fails again, try after removing the receiver deployment. If that works, we’ll need to make a change to the motusServer R code.

**Comment by zcrysler** [comment]
I think you're right that having a deployment without a deviceID shouldn't be a problem, I think the majority of the time users will create deployments before the very first upload.

Let me know once the re-run is done on these 2 receivers

**Comment by Hussell** [comment]
We've rerun these two failed sub-jobs, and they've successfully registered the receivers and transferred new batches to our database.

**Comment by denislepage** [comment]
I've created a fork of motusServer, and making a change to getMotusDeviceID to fix this problem. Essentially, if there are more than 1 deployment record on Motus before the receiver is registered by motusServer, it assumes that there are more than 1 deviceID.

This: 
select deviceID from recvDeps where serno=:serno

Becomes:
select distinct deviceID from recvDeps where deviceID IS NOT NULL and serno=:serno
