### ISSUE TITLE
Identical project short names

### ISSUE THREAD

**Issue by zcrysler** [MotusDev/Motus-TO-DO#305]
I'm not sure if this is a problem or not, but I just noticed that projects 25 and 29 both have short labels "R5_SALS".  From a user perspective the short labels only appear in the hourly plots, and in the tagme() database as part of the fullID of a tag so this might be alright since it also includes motusTagID.  These projects have been around for a while so I don't think it's been affecting processing in any way, but going forward would it make sense to make a rule that short names can't be repeated?

**Comment by cjardine-bsc** [comment]
That may cause problems. Though so far it doesn’t seem to be.

I remember that NULL project_codes caused issues. So I suspect duplicates may too.

To be cautious, I’ve renamed one project code to R5_SALS2 in sandbox and added a unique constraint to that column.

That will probably cause an error to be thrown whenever someone tries to create a new project code that already exists in the database. I suspect that error won’t be properly caught and Paul or Jeremy may need to add some error handling. You can test in sandbox now to see what happens if you create a project with R5_SALS as the code.

Catherine Jardine
Ph: (604)-350-1972
www.birdscanada.org

**Comment by Hussell** [comment]
Error handling for non-unique project_code when creating a new project or editing an existing project has been added to sandbox.

See #32 for previous discussion about this field.
