### ISSUE TITLE
Receiver re-runs for unregistered tag proj 64

### ISSUE THREAD

**Issue by zcrysler** [MotusDev/Motus-TO-DO#315]
A tag was registered with the wrong BI and then deployed motusTagID 28391, Catherine changed it to match the proper BI of the other tags that were registered. But this means receivers will need to be re-run to get detections of that tag. The local stations involved were Lotek-269, Lotek-D000426, Lotek-8372, Lotek-8373. Maybe they don't need re-runs if they're Lotek?

The bird has left the local area though so other stations need to be re-run but we don't know which. If the big re-run is still happening relatively soon then this issue can wait until then.

**Comment by denislepage** [comment]
Lotek receivers would still need to be re-run, because they are not dealing with BI’s.

We should have a bit of a strategy for dealing with cases like this that can only be fixed by wholesale re-runs of large swaths of the array. I’d rather not start doing that every time there’s a tag mis-registered.

We could, for instance, plan for a systematic re-run of any files that reach a certain age (e.g. 3 months), so that all files get run at least one other time leaving time to spot and fix metadata errors. We’d have to properly define how this is determined, but if anything less urgent happens within that 3-month period, we could simply tell people that they’ll be corrected with the planned re-runs. We could still do occasional more localized re-runs when this involves a limited number of receivers, or noisy receivers, etc.

From the documentation and code that I read in motusServer, I think there would be a few steps to put in place to allow this. We may need to make a few tweaks to the handleRerunReceiver function, or create a new one that can figure out which parameters to pass along.
