### ISSUE TITLE
Folder permissions messed up due to sharing between windows and linux

### ISSUE THREAD

**Issue by zcrysler** [MotusDev/Motus-TO-DO#325]
Uploads 203248 and 203215 are both tag registration uplaods that failed with the message:

Error: Error in rsqlite_send_query(conn@ptr, statement): attempt to write a readonly database 
and
203256 	registerTags 	2018-08-14 17:08:03.944Z 	Error

It seems like tags still registered alright, but possibly not the sql database?

**Comment by denislepage** [comment]
sqlite is on the motusServer side only.

This may have been a temporary glitch. Is there a way we know how to resume the job for tag registration?

**Comment by jbrzusto** [comment]
Something is **seriously** wrong on the NAS server: permissions to folders are getting scrambled, and new files created in some folders are ending up with default permissions that don't include "write" permission for the file's owner!  This has started happening since around Aug. 10, which rules out a problem on the sgdata.motus.org software side because the software servers there have been running since Aug. 3.  

Is some process on motus.org changing permissions of folders on the NAS?

I am stumped - this is not something any code on this side can reasonably deal with.

**Comment by jbrzusto** [comment]
The earliest file I can find that was created without owner write permissions was:
```bash
$ stat "/sgm/products/SG-4000BBBK9200/SG-4000BBBK9200-2018_MotusATL_Digby Neck_hourly_tags.rds"
  File: ‘/sgm/products/SG-4000BBBK9200/SG-4000BBBK9200-2018_MotusATL_Digby Neck_hourly_tags.rds’
  Size: 62697     	Blocks: 128        IO Block: 131072 regular file
Device: 1fh/31d	Inode: 22226672    Links: 1
Access: (0555/-r-xr-xr-x)  Uid: ( 1001/      sg)   Gid: ( 1001/      sg)
Access: 2018-08-11 00:15:52.516377898 +0000
Modify: 2018-08-11 00:15:52.542377438 +0000
Change: 2018-08-11 00:15:52.542377438 +0000
 Birth: -
```

**Comment by denislepage** [comment]
This is undoubtedly the result of something I did while trying to fix a similar issue on the windows side, so the users files (plots and tag db) can be accessed by Motus.org users. Many folders, presumably the new ones, did not have the necessary permissions for the windows user to read them.

I essentially changed the folders under those to have inheritable permissions from their parent, preserving any existing permission.

Changes I made impacted the /sgm/products and, I believe, /www/ folders, but they should only have added permissions to the existing ones. The permissions of the 2 parent folders also include Linux User and Linux Group, so any new folders should have received, in theory, the same permissions for reading and editing.

Did you revert back those permissions on www?  I think for this to work for both sides, permissions have to be inheritable, but they currently are not for www, so I expect new folders will not have the appropriate Windows permissions.

There are some details on why I made those changes on this issue, with a reference to permission on the 9th.:
https://github.com/MotusDev/Motus-TO-DO/issues/314

**Comment by denislepage** [comment]
Another folder that I need to access from Windows is file_repo.

Can we make the entire sgm folder permission inheritable to all subfolders? That would be the simplest option.

**Comment by jbrzusto** [comment]
On sgdata.motus.org, the NAS is mounted as an NFS v3 (rather than v4) filesystem as part of the work arounds described in jbrzusto/TO_DO#167.  That limits what I can see of the NAS's permission structure, and as far as I know there's no heritability concept from this side.

I don't know what the Windows view of the NAS is, but it's more flexible than what I have.  Unfortunately, use of some of that flexibility is breaking stuff that I have no way to fix from this side.

Here's my suggestion for how to proceed:
- you revert whatever changes you made to the permissions on your side
- we learn the detailed mapping on the NAS between linux and windows users and groups
- I make whatever changes you need, but using only concepts available to *this* side.  

The /sgm file hierarchy is not very deep, and up until now, the code has been having no trouble creating and maintaining appropriate permissions on it without requiring heritibability.

**Comment by denislepage** [comment]
Before I do more changes on the actual folders (which may create more problems?), can we try on a test folder?

I see for instance that you created a folder called sgm/testme, or is it not a new folder? Somehow, that folder has the proper Windows permissions I need to view its content (but not make changes). The Windows user is simply called "Everyone" which means anyone on the windows side with a login. There are also 2 Unix users called 1001 (Unix User\1001) and 1001 (Unix Group\1001). I confirmed also (below) that those 2 refer to the sg user and group, respectively.

Windows permissions that I can assign to those are 1) Full Control, 2) Modify, 3) Read & Execute, 4) List folder content, 5) Read, 6) Write.  None of them are currently assigned. 

There are also "Special permissions", which are shown here: https://www.sqa.org.uk/e-learning/ClientOS02CD/page_03.htm

All three users of testme only have "Special permissions", and no standard permissions. Unix user has full write access, and Everyone and Unix group only have read access.  I think special permissions are due to them being folders created on the Linux side.

I can confirm that I can read the content of testme from Windows Java, suggesting that this folder was created with the proper permissions that both sides need: https://sandbox.motus.org/data/testpath.jsp

From Windows, I created a subfolder called test. The only permissions that have been added are those of Everyone and Unix Group, plus my own Windows users, but not "Unix User", for an unknown reason. My own windows user has full access and Everyone and Unix Group have read access I can also confirm that I can read this folder from Java (with a different Windows account):

https://sandbox.motus.org/data/testpath.jsp?sub=test

From Linux, I then created a subfolder called test2 (using root user). The permissions that I can see are again read for Unix Group and Everyone, and there's a new Unix user called System Default User (DS1815_2\admin), with full access.

Again, I can read the content of that folder.
https://sandbox.motus.org/data/testpath.jsp?sub=test2

From Linux, I then created a subfolder called test3 (using root user, and then changed the ownership to sg). The permissions that I can see are again read for Unix Group and Everyone, and now the Unix User 1001 is also listed with full access. 

I can also read the content of that folder:
https://sandbox.motus.org/data/testpath.jsp?sub=test3

So, in all of my trials, the Everyone account seemed to have consistently been included in the permissions, which is really all I need. In which case, I don't need permissions to be inheritable. Somehow, however, several of the folders in the ones I have modified did not include that user, and were thus inaccessible.

If we can understand and fix why those subfolders under the products folder were not created with the 3 accounts permissions, that would likely resolve the issue.

**Comment by jbrzusto** [comment]
Are there any inaccessible folders that you haven't changed permissions for?  I'm trying to find something created on my side that causes problems for you.

**Comment by denislepage** [comment]
It may be possible to revert the inheritance and go back to the original permission, but I will have to try with a single folder. My options are not entirely clear with the tool I have.

**Comment by denislepage** [comment]
I have reverted 2 folders that previously did not have inheritance nor permission for Everyone (win user). They should be back to their original status before my changes.

sgm/products/SG-9AF3RPI33983
sgm/products/SG-9AFARPI2F695

I can confirm that removing the inheritance, at least on the latter one, removes my ability to list the content from the windows web user. Id have to dig longer to find out about the first one.

**Comment by denislepage** [comment]
Authentication errors are the same as this this issue. Unsure if this is related to file permissions.
https://github.com/jbrzusto/motusServer/issues/415

**Comment by jbrzusto** [comment]
I can't seem to do anything about this problem from my side.  Even if I mount the NAS using NFS v4, I don't have access to anything other than standard linux permissions:
```sh
sudo mount -t nfs4 174.140.177.35:/volume1/sgdata/sgm /mnt/sgdata_nfs4 -o acl,auto,noatime,nolock,bg,nfsvers=4,intr,tcp,actimeo=1800,timeo=3000,retrans=10,hard
sudo nfs4_getfacl /mnt/sgdata_nfs4/products
Operation to request attribute not supported.
```
It seems the NAS isn't exporting the NFS 4 ACL API, which means I have
no access to read or write permissions beyond the standard linux ones.

As for `sgm/products/SG-9AFARPI2F695` - are you now able to read those files?
I added 'x' permissions for user, group, and other to the files there.  That shouldn't
make any difference, though.  I am poking around in the dark here.  What I need is admin access to the NAS.  Without that, I can't see any way forward.

To summarize, here are the problems I'm seeing now:
- folders where I can create a file but then not write to it because I don't have permission:
```sh
$ echo yes > /sgm/products/SG-4000BBBK9200/test.txt
$ echo more >> /sgm/products/SG-4000BBBK9200/test.txt
-bash: /sgm/products/SG-4000BBBK9200/try.txt: Permission denied
$ ls -al /sgm/products/SG-4000BBBK9200/test.txt
-r-xr-xr-x 1 sg sg 4 Aug 21 11:07 /sgm/products/SG-4000BBBK9200/test.txt
$ umask
0022
```
So, despite having a sensible umask (underwhich group and other write permissions are not granted on newly-created files), files I create in that folder do not have ower write permission!
And the permissions on the folder itself look normal:
```sh
ls -ald /sgm/products/SG-4000BBBK9200/.
drwxrwxrwx 1 sg sg 1894 Aug 21 11:07 /sgm/products/SG-4000BBBK9200/.
```
This inability to append to files I create is now the norm in the /sgm/products
folder and its subfolders.

 - folder where every user has write permission (this is a security hole):
```sh
$ ls -al /sgm/products
$ ls -al /sgm/products
total 4
drwxrwxrwx 1 sg sg 25874 Aug 21 11:11 .
drwxr-xr-x 1 sg sg   826 Aug 21 11:11 ..
drwxrwxrwx 1 sg sg   402 Aug 23  2017 Lotek-153
drwxrwxrwx 1 sg sg   306 Aug 22  2017 Lotek-158
drwxrwxrwx 1 sg sg   636 Aug 23  2017 Lotek-159
drwxrwxrwx 1 sg sg   612 Aug 23  2017 Lotek-160
drwxrwxrwx 1 sg sg   582 Aug 23  2017 Lotek-161
drwxrwxrwx 1 sg sg   636 Aug 23  2017 Lotek-162
...
$ ls -al /sgm/www
total 84
drwxr-sr-x 1 sg   sg   1352 Aug 21 11:12 .
drwxr-xr-x 1 sg   sg    826 Aug 21 11:11 ..
drwxrwxrwx 1 sg   sg  32068 May 18 11:43 0
drwxrwsrwx 1 sg   sg 100744 Aug 21 11:15 1
drwxrwsrwx 1 sg   sg  26686 Aug 21 11:15 10
drwxrwsrwx 1 sg   sg    116 Aug 21 11:15 103
drwxrwsrwx 1 sg   sg   2104 Aug 21 11:15 105
drwxrwsrwx 1 sg   sg    412 Aug 21 11:15 106
drwxrwsrwx 1 sg   sg   1930 Aug 21 11:15 107
drwxrwsrwx 1 sg   sg   2830 Aug 21 11:15 11
```

**Comment by denislepage** [comment]
I haven’t yet had time to look into this with the IOC congress. I’ll try to get back to it soon. Until then, let me know if you see any of the current settings that impede with your code.

I’d generally be in favor of increasing (at least read) access for more (all, except the protected ones?) folders on the shared drive. Those are only being accessed by a limited number of BSC staff and yourself, and I don’t see plans to expand that list.

**Comment by jbrzusto** [comment]
I have no way to see any NAS settings.  Whatever they are, they force
me to explicitly add write permission for user `sg` even though user
`sg` just created the directory **with that permission**.  This
applies to new directories created in `/sgm/products`, but no other
directories that I've noticed so far.  This means the
view of the NAS being presented to the sgdata server isn't consistent
with normal linux permission semantics.  And this was not the case two
weeks ago.  Apparently, the "grant permission again" does work around
the problem, but I've only added it to the one location in the code
where I know the problem has been exposed.

**Comment by denislepage** [comment]
The 2 main folders I have attempted to modify to allow access from windows earlier on wre the receiver folders in:

/sgm/file_repo and /sgm/products

This folder for instance wasn’t visible to the Windows Java processes: /sgm/file_repo/SG-4002BBBK0580. This was the only remaining folder that seemed to be problematic, and it was last written to back in December 2017, so likely not as a result of any new processing. I have now added the read permissions to the Everyone windows user on that folder, and as seen from Linux, the permissions of this folder appear unaffected (exactly the same as all the other receiver folders).

Also, all folders and subfolders (e.g. date folders) of file_repo and products that have been created today all appear to have the correct permissions for the Windows user.

Things may be ok as they are now, for the most part (?). There seems to be occasionally some processes that create folders or files that don’t have the full suite of permissions that they typically do. I don’t know if there is a different process generating those or why it happens. It seems relatively rare, so I guess I’ll need to wait a bit, look at all the file permissions again later on, and see if there are any gaps reoccurring, then try to narrow down why these are different.

Since things are generally working now, I would wait until we tweak anything else. We should know relatively quickly if more problem occur that prevent processing. Our next release will also have ways of accessing the plots and sqlite files from the Motus web site. I am tracking file access issues in a log file, so we can at least try to spot when new problems arise.

**Comment by jbrzusto** [comment]
Still broken:

```sh
mkdir /sgm/file_repo/SG-4002BBBK0580/2018-01-01
3283$ ls -al /sgm/file_repo/SG-4002BBBK0580/2018-01-01
total 0
dr-xr-xr-x 1 sg sg     0 Sep  1 13:41 . ## no write permission for user to directory user just created
```

So if/when code on sgdata has to add new folders to
`/sgm/file_repo/SG-4002BBBK0580`, it will also have to **separately**
add write permissions to those folders before it can create files
there.

I tested, and this only happens in `/sgm/file_repo/SG-4002BBBK0580`:
```sh
$ cd /sgm/file_repo
$ for r in SG* Lotek*; do 
   d=$r/2020-01-01
   mkdir $d
   x=`stat --printf %A $d`
   if [[ ${x:0:3} != "drw" ]]; then 
      echo $r
   fi
   rmdir $d
done
SG-4002BBBK0580
$
```
But the same problem occurs for any new folders created in `/sgm/products`.

So I've recreated these folders from scratch:
```
/sgm/products
/sgm/file_repo/SG-4002BBBK0580
```
to fix this problem.

Do you still have read permission to these folders?
If so, we can close this issue.  If not, we need to find a different
way to provide read permission to appropriate users on the motus.org
side.

**Comment by denislepage** [comment]
One thing I noticed was that the Linux user was listed, but not the Linux group that is also normally listed.

The write permission problem may not be caused by my adding the windows user, but the missing group permission?

In any case, recreating the folder seems to have preserved the windows user permission. So far so good, so let's close this for now.

Thanks for your help with this
