### ISSUE TITLE
Proj 197 detections stopping abruptly

### ISSUE THREAD

**Issue by zcrysler** [MotusDev/Motus-TO-DO#328]
User uploaded data for several stations in this project and detections all seem to stop abruptly after August 7th, despite her seeing detections while she was downloading teh data on August 15th. Is this related to metadata issues or a tag end date somehow?

Receivers:
SG-3214BBBK8680: https://sgdata.motus.org/download/197/SG-3214BBBK8680-2018_TaylorSwallows_Degenhardts_hourly_tags.png

SG-1614BBBK1659: https://sgdata.motus.org/download/197/SG-1614BBBK1659-2018_TaylorSwallows_Cap%20Brule_hourly_tags.png

SG-1614BBBK1922: https://sgdata.motus.org/download/197/SG-1614BBBK1922-2018_TaylorSwallows_Wells2_hourly_tags.png

SG-3214BBBK8680: https://sgdata.motus.org/download/197/SG-3214BBBK8680-2018_TaylorSwallows_Degenhardts_hourly_tags.png

**Comment by Hussell** [comment]
Rerunning had no effect, and there are some detections after the 7th, so probably not a metadata caching issue. The tag lifespans don't start expiring until December, if I'm reading it right (tags_deployments.dt_start + tags.lifespancalc).

I agree that it's strange for all the swallows to disappear from distant receivers simultaneously, but archived weather reports show a thunderstorm in Moncton on the evening of the 7th, so maybe this is a real thing due to a widespread weather event?

**Comment by zcrysler** [comment]
A similar thing is happening with KIWA in project 145, based on geolocator data they were expecting detections in Ontario but haven't gotten any, in this case it's 2017 data. project 145 was using NTQBW-2 and project 197 was using NTQB-2

**Comment by Hussell** [comment]
Rerunning again worked. John fixed something?
