### ISSUE TITLE
rejected upload

### ISSUE THREAD

**Issue by zcrysler** [MotusDev/Motus-TO-DO#338]
Tara tried uploading data for project 214, but got the following message "This file has already been uploaded by Yuri Zharikov (2018-08-14 15:54:01; jobID: 203198)", is this based solely on the file name? There's no way the file is actually duplicated between the Tofino project (174) and the Australian project.

**Comment by pmorrill** [comment]
The file identification is based on a hash of the contents of the file, not the file name. It is possible, but very unlikely, that two different files will generate the same internal hash. If it has happened here, we should be generating bitcoin with Motus software! That's a joke.

I am away from the office. But, try changing some simple internal character of the file: add a line feed / carriage return somewhere that it won't make a difference. That will change the hash and the file will not conflict with the other one.

But, please save the original file for me to look at later. I have **never** seen a sha1 hash collision in years of working with crypto.

**Comment by jbrzusto** [comment]
Perhaps the files are basically empty, so the same.
This shouldn't happen if anyone is uploading a zipped archive, as in that case, the 
serial numbers and dates on the files within would differ.  But it's possible if someone
is uploading an individual .gz file from a sensorgnome, and it is more-or-less empty
(or has only a couple of lines in it, which could be identical between different receivers
if e.g. no radios are working and no GPS fix has been obtained).

Or perhaps the hash is being inadvertently computed on something other than
file contents; e.g. a pointer itself, rather than the data being pointed to.
In that case, a collision is much less improbable.

**Comment by zcrysler** [comment]
So you want Tara to try to re-upload? Can you clarify what you mean by "try changing some simple internal character of the file: add a line feed / carriage return somewhere that it won't make a difference", do you just mean change the file name?

**Comment by denislepage** [comment]
I expect her file is empty or nearly so. The file size should be a good clue.

To do what Paul suggests, she would have to say add an empty file that can be ignored by the tag finder to the gzip, or open one of the text files inside and had an extra empty line or something like this.

I don't think it's necessary or will make a difference anyway if there are no detections.



Denis Lepage
http://avibase.ca
http://ebird.ca
