### ISSUE TITLE
Manage data > Project ... > Receivers page lists an internal "ID" which is not the deviceID

### ISSUE THREAD

**Issue by jbrzusto** [MotusDev/Motus-TO-DO#34]
e.g. [here](https://motus.org/data/project/recvs?projectID=110)

The database ID for a receiver that would actually be useful to users, at least sometimes,
is the deviceID.  That's the table key to which results of the tag-finder are associated for a given
batch of data.

The "ID" shown on this page is not used by anything outside of the motus.org server, as far as I can tell.
Moreover, it's misleading; for example, if a receiver is deployed at different times under different projects, the deviceID is the same, but the "ID" shown on this page differs.

e.g. compare the "ID" for receiver SG-1013BB00626 ( deviceID = **563**)

[here](https://motus.org/data/project/recvs?projectID=110) = **1793**
vs. 
[here](https://motus.org/data/project/recvs?projectID=8) = **521**

Also, the ID shown on this page is not the deployID, which is shown when one edits a deployment record,
and which has an obvious purpose.

**Comment by pmorrill** [comment]
There have been several changes to the recv mgmt interface since this was posted; but I have recently added the Device ID field (from sensors_hash_keys) into various places. The website rarely uses this field: Receiver ID (from sensors) is the commonly used id for sensors.

John however makes a good point - users will benefit from having device id available for reference.
