### ISSUE TITLE
csv download issues in beta

### ISSUE THREAD

**Issue by zcrysler** [MotusDev/Motus-TO-DO#348]
When I download any of the csv files from the beta site, and open the file it looks fine. But if I make any changes or even just save it without making changes, once I close and re-open the file all the columns have merged into one. This is an issue for uploading bulk tag metadata.

I thought I might have somehow messed up some setting on my computer, but when I do the exact same thing with files from the live site I don't have this issue.

Wondering if it's related to any changes made here: https://github.com/MotusDev/Motus-TO-DO/issues/253. 

In the live site there are still special character issues, but these seem to have been resolved in beta at the expense of this new issue

**Comment by denislepage** [comment]
The problem here is Excel, not the file. Excel, for one thing is really doing a horrible job at saving in UTF-8.

The BOM character that I think we are inserting in the file to make it open correctly in Excel will almost certainly get lost when you try to re-export it again. That "could" explain the behavior that you see.

Can you send me the file that you have saved from Excel? What saving options are you using specifically?

**Comment by zcrysler** [comment]
Sending the file now. All I was doing was opening it and hitting save, then re-opening it resulted in the issue. Only for the beta files, not for the same files from live

**Comment by denislepage** [comment]
There's supposedly a way to save UTF8 files in Excel, but  that isn't working for me. Most files won't have UTF8 characters, so it  shouldn't really matter, in theory, unless they are using French or  Spanish characters. One thing that does work with UTF8 is to use Google Spreadsheets instead of Excel. 

Have you tried to open the file in R, write it back to a new file and reload the new file again? That should likely work.

**Comment by denislepage** [comment]
Your file is in UTF8 (how did you pull that off?), but as I suspected, your delimiters have been converted to tabs instead of commas, so your file technically is now a text file (.txt) rather than a CSV.

**Comment by zcrysler** [comment]
but why would it only do that with files downloaded from beta?

**Comment by zcrysler** [comment]
When I download the data, open it, save it with no changes, close it, and re-open it in live all the columns are merged into 1. If I do the same steps in beta it saves correctly.

I can get around this in live by doing "save as", but I think that leaves room for users to run into more problems that necessary
