### ISSUE TITLE
Wyndham Finches receiver issues - receiver plots not wide enough

### ISSUE THREAD

**Issue by zcrysler** [MotusDev/Motus-TO-DO#360]
SG-E561RPI3DE10 has no detections in the hourly plots, but I downloaded the data and got 60 hits for that station the majority of which have runLn > 2, it's in project 214, recvDeployID 4911. All detections are batchID 185586.

SG-21B9RPI33855 also in project 214 only has a few detections of their tags on it but they were doing tag testing at both locations and are expecting many more detections.

Is there a processing issue that would be hiding detections of these tags and/or receivers?

**Comment by Hussell** [comment]
The hourly plot for SG-E561RPI3DE10 is messed up so you can't see any detections:
https://sgdata.motus.org/download/214/SG-E561RPI3DE10-2018_Wyndham%20Finches%202018_Quarry.1_hourly_tags.png

So that's a bug. There's no problem with the processing, though.

SG-21B9RPI33855 has been rerun, with not much effect. I'll try again tomorrow, to rule out cache issues.

**Comment by Hussell** [comment]
I've rerun all of this project's receivers, and new detections have shown up for all of them, but the plots are now useless for all of them as well.

**Comment by Hussell** [comment]
Most of these seem to be resolved, but there's one remaining example:
https://sgdata.motus.org/download/214/SG-7F39RPI3E0D9-2018_Wyndham%20Finches%202018_WaterTower2.1_hourly_tags.png
