### ISSUE TITLE
Project 173 and 186 receiver re-run

### ISSUE THREAD

**Issue by zcrysler** [MotusDev/Motus-TO-DO#372]
Can these be re-run? The user is expecting detections and so far has none except for one receiver. Project 173 originally had an issue that we're waiting on the big re-run for: https://github.com/MotusDev/Motus-TO-DO/issues/230

**Comment by Hussell** [comment]
For project 173 nothing has been uploaded since May 14th, and all three receivers have been rerun multiple times since then. I reran them again just to be sure, but there was no change. All three look like they weren't working properly until the beginning of May.

For project 186's one receiver, there are detections from April through May 14th, when the last data was uploaded. Also no change when rerun.
