### ISSUE TITLE
/api/tag/undeploy fails with an obscure error message

### ISSUE THREAD

**Issue by Hussell** [MotusDev/Motus-TO-DO#383]
Tested with the following json:
```json
{
  "date":"20181009174024",
  "projectID":1,
  "login":"XXX",
  "pword":"XXX",
  "deployID":19062,
  "tagID":31910
}
```

(deployID and tagID are both test records which only exist on my machine, and I've double-checked to make certain they actually exist.)

Got this:
```json
{
  "version":"2.0",
  "errorCode":"database-error",
  "errorMsg":"A database error occurred - org.bsc.exceptions.DBException com.microsoft.sqlserver.jdbc.SQLServerException: Procedure expects parameter '@statement' of type 'ntext/nchar/nvarchar'. SQL: \"prAPIImportTagsDeploymentDelete (?, ?, ?)\""
}
```

But prAPIImportTagsDeploymentDelete doesn't contain the string 'statement'.

**Comment by cjardine-bsc** [comment]
Looking at prAPIImportTagsDeploymentDelete there is no parameter @statement 

There is an output parameter called @code that the proc expects, it might be missing from Jeremy's API call.

**Comment by pmorrill** [comment]
I will take a look at the flow of this tomorrow morning. The 'undeploy' call has not been used before to my knowledge.

**Comment by pmorrill** [comment]
I've reproduced Jeremy's error (above): the procedure expects parameter @statement. The proc itself does not use a parameter of that name - can this be related to a trigger that is fired when the record is deleted from api_import_tag_deployment, or during the [prDeleteTagsDeployment] procedure called ?

Catherine: can you make sense of this?

On a related note: because the proc queries only the api_import_tag_deployment table when checking validity of the input parameters, it can only be used to remove deployments that were initially created using an api call. Deployments added solely via the web interface do not populate this table (I don't think...). This behavior was by design when Denis originally created the entry-point, but depending on our goals, may be restrictive.

**Comment by pmorrill** [comment]
If you run the proc directly in SQL Mgmt Studio, you can see this slightly different version of the error:

> Msg 214, Level 16, State 2, Procedure sp_executesql, Line 1 [Batch Start Line 2]
> Procedure expects parameter '@statement' of type 'ntext/nchar/nvarchar'.
> 

This seems to be related to a block of script:

	BEGIN
		SET @sql = 'EXEC prDeleteTagsDeployment ' + CAST(@deploy_id as varchar(12))
		EXEC sp_executesql @sql
	END

The proc prDeleteTagsDeployment  requires a projectID parameter as well as deployID. It sure would be nice of MySQL could pass back a little more detail!

**Comment by cjardine-bsc** [comment]
Paul's got it. PrDeleteTagsDeployment needs a project ID. 

Are we using prAPIImportTagsDeploymentDelete? Is this so John can revoke deployments made through the API? Is that behaviour we should allow?

I'm trying to sort out it's purpose and how it's different than prDeleteTagsDeployment.

**Comment by Hussell** [comment]
I ran into this while documenting the API and matching up what we have to what CTT wants. CTT has asked for the ability to make tag deployments, and since the API doesn't (yet) expose any direct way to alter records, the only way to update or fix a mistake is to delete then re-create.

**Comment by cjardine-bsc** [comment]
ahh, we might actually want to look at the bulk tag deployment upload tool. That allows for changes to existing deployments.

**Comment by pmorrill** [comment]
I don't think this api entry-point was ever used by John's client. Denis created it (and a few others) in anticipation of their use, possibly by arbitrary clients. I moved them into the v 2.0 API code when we switched to a servlet-based context. But since they have not been well-tested (ie: John did not use them), they are a bit buggy.

We can discuss on tomorrow's call. Maybe there is a better way to deal with the ctt requirement to allow modifications. Is there a newer version of the ctt document than the one we used on the call with Russell?
