### ISSUE TITLE
Project 138 Missing Tag sqlite Databases

### ISSUE THREAD

**Issue by leberrigan** [MotusDev/Motus-TO-DO#394]
Project 138 does not have any .sqlite files appearing in the tag database even though there are two tags (23606, 24112) registered to this project:
https://motus.org/data/project/tagdb?projectID=138

This project is for testing tag sensitivity so both active deployments don’t have listed species and tags deployment status is ‘Test deployment’.

User wants to upload database to Sensorgnome, but is not able to at this time.

**Comment by denislepage** [comment]
In the past, we’ve seen issues where the files (SQLite databases and sg-generated plots) where missing due to permission issues on the NAS drive where those files are exported. In this case, however, there are actually no files available. Were these tags registered manually? That’s the only reason I could think the sqlite tag file is missing.

What database are they wanting to upload (detection files?), and why are they not able to do so?

**Comment by Hussell** [comment]
I've created a tag database for this project. It can be downloaded from https://sgdata.motus.org/download/138/project_138_2017-1_2017-2_tag_database.sqlite
