### ISSUE TITLE
User Interface enhancements

### ISSUE THREAD

**Issue by Hussell** [MotusDev/Motus-TO-DO#396]
Stu's outline is here (with comments): https://drive.google.com/file/d/1ZTkcZh9LDeWM-wpGWd--fqMDpvnzckDV/view

Summary:
 - create receiver maps which show station status and type
 - improve usability of popups on the receiver map
 - make receiver map searchable or filterable
 - make tables usable, sortable, searchable, single-pageable
 - new download options for tagme
 - redesign station timeline visualizations
 - check all the pages in French & English match
 - outline for future CTT Lifetag development

**Comment by StuMackenzie** [comment]
Notes from todays call: - Catherine, Jeremy, Paul and I solved all the world's problems.

We talked mostly about updating the map tool and Jeremy has enough to get started on that. 

Tag/Station Type: There was some discussion about how to separate and identify tag-types, but we decided using frequency was probably the best indicator overall that will allow for adaptability in the future. 

Data Upload Status: 

Discussed whether this could be integrated into the current map, or whether it should be a standalone map. Or, whether it should be scalable and work off the timeline, or more of just a current status indicator. Decided to go for current status indicator which may take the form of another separate map for simplicity sake. Jeremy also thought that using last pulse activity is probably the best metric we have for when a station was last active. Catherine will integrate this information into the metadata tables and we should probably also do so for the RPackage.

Station pop-up boxes: Jeremy like the detail. For now we're going to move the most useful information to the top, add last date information, and see what that looks like.

Searchable Map: decided to postpone, but the only really useful thing we can imagine is viewing a single project, or searching by deployment name or SG serial #.

Sort ability for tables: - not necessarily easy or necessary to implement across the board.  Stu and Luc (:), nudge) will make a list of the tables that would be useful to have sortable, and the specific fields which we should sort by.

View all fields for all tables: agreed that this should be implemented where it is not.

**Comment by adamdsmith** [comment]
These are excellent suggestions, and I'll add one more from a southeastern US perspective.

There are a growing number of Motus participants hosting stations simply to contribute to the greater good, with little to no intention of deploying tags, that simply want an easy interface to see what animals their stations have detected (and the when and where of their initial tagging). The pop-up for a station currently contains a redirect to a table ([e.g.](https://motus.org/data/receiverDeploymentDetections?id=2625)) or timeline ([e.g.](https://motus.org/data/timeline?receiverDeploymentId=2625)) of detections, but I've not found this list to correspond consistently with the figure(s) produced just after receiver data upload ([e.g.](https://sgdata.motus.org/download/4/SG-3115BBBK0782-2015_USFWS_R4_Cedar%20Island%20NWR,%20NC_hourly_tags.png)). This linked table is also missing some deployment metadata of interest - namely deployment lat/lon and date. 

While linking to a map illustrating the origins of detected animals would be better and more user-friendly, I think that can be left up to the user at this point if an easily downloaded csv file of detections is available without requiring R access. I can barely get people to register their stations with Motus, let alone use R to access their detections.

**Comment by StuMackenzie** [comment]
Thanks Adam, useful feedback. Along these lines, I think generally we often need to take a step and simplify things wherever possible. In a lot, but not all case, the well designed and executed display of less information will be more effective.

As a general timeline, it would be nice to have at least the 'station-type' map and more basic modifications listed above complete, or at least testing by Nov 12 when we have our next update with CANARIE.

**Comment by StuMackenzie** [comment]
Additional request: Can we please remove Mobile deployments from the main station map, make it another option, or separate them visually somehow. They cause some confusion on the main map and are not labelled as such on the pop-up box.

**Comment by StuMackenzie** [comment]
Dongle Type Info:

Funcubes - programmable to any frequency, but within Motus will currently only detect Lotek Nanotags operating on 166.380, 150.100 and 151.5 MHz

RTL-SDR  - same as Funcubes

Cornell XCVR  - only listen to 434 MHz (CTT LifeTags)

Note yet in System: CTT Dongles - same as XCVR dongles. -  - only listen to 434 MHz (CTT LifeTags)

**Comment by Hussell** [comment]
I've been experimenting with displaying tag codes similar to what's found on the <a href='https://sgdata.motus.org/download/4/SG-3115BBBK0782-2015_USFWS_R4_Cedar%20Island%20NWR,%20NC_hourly_tags.png'>figure produced during receiver upload on detection <a href='https://sandbox.motus.org/data/receiverDeploymentDetections?id=2625'>tables and <a href='https://motus.org/data/timeline?receiverDeploymentId=2625'>timelines</a>.

**Comment by adamdsmith** [comment]
Nice! I find the table much improved and interpretable...minus the odd NULL entries of course. 

The timeline is challenging from a viz standpoint once you get past a few months of deployment. In that case, it would be nice if the tag ID/link displayed in a pop-up when you hovered over the detection in the timeline. But that's likely not worth the effort when the table is what most users will want to view and download... 

As with individual tags, what about a map option for a receiver that displays the deployment locations of detected tags (with basic info in the popup---species, project, detection date(s)) as well as the receiver location? This potentially gives hosts a URL to easily navigate to for display...

**Comment by Hussell** [comment]
I've made some improvements to the timelines, including:
- splitting long timelines into separate years
- providing links to both tag and tag deployment where relevant
- providing links to both receiver and receiver deployment where relevant
- displaying the species the tags were deployed on
- highlighting detections from the same combination of receiver/tag when you hover over them
- popping up a box with the relevant parts of the legend when you click on a detection

These changes can be seen on sandbox, e.g. https://sandbox.motus.org/data/receiver/deployment/detections/timeline?id=2146&year=2018

More to come. Feedback welcome, and will be incorporated immediately.

**Comment by Hussell** [comment]
It still works for me, on Monday...

**Comment by denislepage** [comment]
The database may have been locked. We'll have to keep an eye on this. Can you email your queries to Catherine, so we can check if there are ways to improve them?

A few more suggestions, some of them relate to old issues that I still don't think we have properly addressed:

- it's not immediately obvious what we are looking at when opening the page. The header "Tag detections" is the same whether you are looking at detections at a receiver or for a tag. Change header to "Tag detections for a receiver", "Tag detections for a tag", "Tag detections for a tag at a single receiver", or something along those lines.

- the 3 links that you can click for a given tag are not obviously separated, so I initially missed that you had multiple options. I also think we need clearer instructions about what each link represent.

View tag [NJA-TU_SESA-SA#228:10.3 M.22333] - **View deployment** [Semipalmated Sandpiper (ID# 10175)] - **Show only detections for this tag at this receiver**

- I initially expected the last link to show me all detections of a tag (or deployment?) across all receivers, but it's only on the current receiver. I am not advocating we should offer both options, but people may be confused (the change of link name above may help).

One currently easily gets lost in the multiple navigation among all the various options, so uniformity in headers and options would be helpful.  It's not intuitively clear for instance why we are not offering the option to look at a timeline when on a tag page (that option is only available on a deployment page). Would it make sense for instance to add all deployments (usually only 1) directly in the tag page (e.g. https://sandbox.motus.org/data/tag?id=22333) rather than as a stand-alone? If so, does it make sense to also keep the option on only looking at a single deployment?

This solution may not work for receivers given how many deployments they can have.

**Comment by Hussell** [comment]
Old issues related to this one:
#317 #89 #58 #15

**Comment by cjardine-bsc** [comment]
This is looking good Jeremy! I like how you've split things by year and highlight all the detections of a tag when you hover. Slick!

My feedback: 
Similar to Denis I think this page needs a little intro paragraph explaining the tool and what it represents, I drafted a starting point below. We might want to include some additional details on things like what is happening when two tags are being detected at the same time. 

"The below plot is a graphical representation of which tags have been detected on this receiver. You can use this plot to explore when various taghits occur, for how long and how frequently. Each colour represents a different tag deployment, you may click on each colour within the plot to see details on the deployment and a link to a timeline specifically for that tag on this receiver.  A summary key is provided  beneath the plot. You can also use this key to navigate to timelines for specific tags. "

Instead of having a sentence on the top explaining "Chart uses UTC time on the X-axis, starting at midnight UTC on the left. " I would just label the x-axis 

When you hover over a colour it shows the links but you can't access them until you click, If we want a hover function I'd suggest it just show the deployment species and number with a line that says "click to access more information about this deployment" or something to that effect. Because right now its not intuitive how that you have to click. 

I think the three links at the bottom would be clearer and visually more neat and appealing if they were contained inside a table, perhaps with tool tips over the column headers. 

Suggested column headings: 
Tag, Tag Deployment, Filter Plot by this Tag (?) 

I think you're providing too much detail in the first column. Just the project name and tag id should be all you need (drop the additional details i.e. "12.7 M.16851")

Those are my thoughts on making this slightly clearer, though I recognize some of that might be hard to implement simply. 

Happy new year!

**Comment by pmorrill** [comment]
I have made the landowner and sites listings non-page-able, by option of the user. You can toggle back and forth.

This is in sandbox today, but can be put into beta7 for deploy to live easily enough.

**Comment by leberrigan** [comment]
I have a comment to add about tables:

There are a lot of IDs to keep track of when dealing with receivers and it's not all clear on the 'Manage Receivers' page. In particular, **device ID** and **receiver ID** are not the same thing, but why? Is one ID unique the receiver and the other unique to both the receiver _and_ project? Since all each of deployment, receiver, and device ID are 4-digit numbers they can be easily confused with one another.

None of the tables contain the receiver ID, just device ID (which is often blank) even though all URLs refer to the receiver ID. 

Can we add some information regarding these IDs to this page?

**Comment by Hussell** [comment]
Trying to answer this turned into a large off-topic diversion, so I moved it to a new issue: #431

**Comment by adamdsmith** [comment]
Is there any value to adding tags to projects to make them more search/filter friendly? I've had station hosts ask if there was a quick way to search projects by species. Perhaps species information can be harvested from tag deployments and added as tags so all projects tagging "Barn Swallow", for example, are returned by a filter query on the Projects page. I could envision similar searches by geography (e.g., "Florida" or "Ontario") being useful.

**Comment by Hussell** [comment]
There's a table at https://motus.org/data/species where you can get a list of all projects for a particular species. There's no link to this anywhere (yet), but there should be soon.

**Comment by adamdsmith** [comment]
Perfect, thanks!
