### ISSUE TITLE
Project 123, 76 Receiver Re-run for Missing Data

### ISSUE THREAD

**Issue by leberrigan** [MotusDev/Motus-TO-DO#415]
Tag test on Sept 5th, 2018 resulted in zero detections. Tag test involved two tags (ID 27950, 27965, project 123) deployed on an airplane and flown around receiver array. Researcher expects detections on _at least_ 9 receivers from Project 123 (deployment ID 2052 2054 2055 2084 2085 2086 2306 2308 2309)  and 2 receivers from Project 76 (deployment ID 3816 or 3855). Had both tags detected on a Lotek receiver plus a Window's version of tagfinder (compiled by John) resulted in these tags detected on those 11 receivers.  Same tag test was done back in July and was successful.

Could this be related to erroneous antenna frequencies associated with these projects? 

Researcher has requested a re-run of all receivers for project 123 and 76. Do any other steps need to be made first?

**Comment by Hussell** [comment]
A check of the [master timeline](https://sgdata.motus.org/public/motus_tag_timeline.html) shows the tag finder is only looking for the first deployment of these two tags. I'm not sure if that's a bug in the master timeline or in the tagfinder.

**Comment by Hussell** [comment]
Well, I reran SG-3615BBBK0428 and detections for both tags mentioned showed up, so it's just the code generating the timeline which doesn't plot multiple deployments.

I'm now putting receivers for project 123 and 76 into the queue to be rerun.

**Comment by Hussell** [comment]
All receivers in project 123 and 76 have been rerun.

**Comment by leberrigan** [comment]
It looks like tag 27950 still doesn't have any detections during its most recent deployment in September, but 27965 does. Perhaps there is still an issue with deployment timelines?

https://motus.org/data/tagDeployment?id=19939

**Comment by Hussell** [comment]
Most of the data on the website is pulled from summary tables, which are automatically regenerated when new data comes in. The process queue is full right now, so the summary tables haven't been regenerated since ~midnight here. So the new detections from most of the project 123 (and 217) receivers aren't visible yet. If immediate access is needed, the raw data can be downloaded through the R package. It looks like the summary tables will be regenerated by the end of the day (+- half a day).

**Comment by Hussell** [comment]
I double-checked this again this morning, and saw there were still no detections after the daily summaries were refreshed. Digging deeper, I realized there are multiple deployments for this tag, so earlier when I saw that there were a pile of detections in the raw data, they were mostly from earlier deployments. There's only 1 run for this deployment (19939) with only two hits, so it's filtered from the website as a false positive.

Since we have a detection (even though it's sketchy), we know the tagfinder is searching for this tag during the correct timespan. We got lots of detections of the other tag, too. There may be an actual issue with the tag itself this time. Maybe re-record it and compare to its original recording to see if the signal has changed?

**Comment by cjardine-bsc** [comment]
It's not likely a tag problem since it's showing up on the lotek receiver and their local tagfinder. 

My bet is that the problem is a lifespan issue. I think tagfinder is assuming these tags are beyond their expected lifespans and therefore no longer scanning for them. There's another git issue that talks about this and discusses solutions....I'm digging for it now.

**Comment by cjardine-bsc** [comment]
Hmm I dug further and it's not the lifespan (drat). 

Can you contact the user and confirm they had multiple detections  of 27950  when they were doing their testing?

**Comment by StuMackenzie** [comment]
resolved?
