### ISSUE TITLE
Project 173 and 186 Missing Detections

### ISSUE THREAD

**Issue by leberrigan** [MotusDev/Motus-TO-DO#430]
Receivers for both projects (Italy and Morocco) produced plenty of data and picked up tags on live web interface, but nothing is coming out from tag finder for 173 and only a small subset of tags for project 186. PI thinks there could be an issue with the way tags were registered because they had an issue where Zoe had to help them out in the past.

Receivers in both projects were rerun 3 times since May 2018, but did not result in any changes.  Last rerun was Sept 28. See #372.

I have little doubt the receivers were detecting tags - there must be something preventing tag finder from getting them. Could the burst rate of the registered tags be wrong?

Serial No. | Variant Code | Primary Freq | Code | Model
-- | -- | -- | -- | --
T447858 | 150.1 | 50.03333 | 391 | NTQB-1
T447859 | 150.1 | 50.03333 | 392 | NTQB-1
T447860 | 150.1 | 50.03333 | 393 | NTQB-1
NQ0003617 | 150.1 | 50.03333 | 331 | NTQB2-1
NQ0003618 | 150.1 | 50.03333 | 332 | NTQB2-1
NQ0003619 | 150.1 | 50.03333 | 333 | NTQB2-1

**Comment by leberrigan** [comment]
Project 173 contains 60 tags that were ordered at the same time (all on same shipping slip), but there are registered with three different (but similar) burst rates.

Tag IDs | Burst Rate
-- | --
331-350 | 12.7 s
351-370 | 13.1 s
371-390 | 13.7 s

**Comment by Hussell** [comment]
Is the user expecting detections from after May 14th 2018? We still have no data from after then. I just re-checked this on the sgdata server. None of the files uploaded for any of the receivers in these projects contain data from after that date.

**Comment by leberrigan** [comment]
No, their tags were all deployed at least a week before then. They are performing a tag test soon so hopefully we'll see their results shortly.

**Comment by jbrzusto** [comment]
This project uses 150.1 MHz.  Any project that isn't using tags and receivers at the 166.38 MHz
frequency needs to have a parameter override registered so that the tag finder knows what
tags it is looking for when the SG has failed to record its listening frequency, as it may have here.

**Comment by cjardine-bsc** [comment]
I looked at their data. Project 186 has lots of hits for their single receiver (deviceID 1061) but you're right that tag finder is not picking up any hits for deviceID 992, 993 or 994 registered to project 173. 

Just so I can understand....can you separate the problem for me in terms of the two projects? What's the issue with project 186? Is it that the tags from project 173 are not being detected on their receiver either?

We're now tracking the frequency a station is listening to in the antenna metadata for all projects. We need to incorporate that into the metadata used by tagfinder so that we don't need to keep a manually added parameter override. I believe (?) that's on Jon's to-do list. Though I'm not sure. Jon feel free to let me know what changes you might need on our end either to the database or metadata API to accommodate this. 

Jeremy, can you check to see if those three deviceIDs are included in the parameter override?

**Comment by Hussell** [comment]
The receivers and projects did not have parameter overrides. I set the default project frequency for both projects and reran the receivers, and the rerun logs say the parameter overrides were used, but no new detections appeared.

**Comment by Hussell** [comment]
Project 186:
https://sgdata.motus.org/download/186/SG-1914BBBK0863-2018_Maggini%20-%20Morocco_Yasmina_hourly_tags.png

Project 173:
https://sgdata.motus.org/download/173/SG-1914BBBK0833-2017_Italian%20Islands_Ventotene--Punta%20dell'Arco_hourly_tags.png
https://sgdata.motus.org/download/173/SG-1914BBBK0856-2017_Italian%20Islands_Ventotene-Museo_hourly_tags.png
https://sgdata.motus.org/download/173/SG-1914BBBK0873-2017_Italian%20Islands_Ventotene-Municipio_hourly_tags.png

**Comment by leberrigan** [comment]
Sorry, perhaps I should have made this two different issues. I was just asked about both projects at the same time as if it was the same problem.

**Project 173**
There are no detections for any of the 80 tags deployed in Oct 2017 and May 2018. Tags were deployed within 1 km of any one receiver on a small (2.5 km) island with three receivers on it. User saw live pulses which corresponded with burst interval of tags before and after deploying them.

**Project 186**
There are detections for only 17 of the 51 tags deployed in Apr-May 2018. Only one receiver, but live pulses were also monitored during each tag activation and afterwards to confirm individuals were around. Pulses also occurred at a regular interval corresponding to tag burst rates. Tags were all deployed within 50 m of the one receiver (device ID 1061, Serial SG-1914BBBK0863) in about 1 km^2 area of suitable habitat surrounded by desert.

**Comment by jbrzusto** [comment]
Brief comments:

Project 186; listening frequency of funcubes set to tag nominal frequency, rather than 4 kHz below,
which reduces ability to detect signal at all, and increases variance of estimates of offset frequency,
that will cause more detections to be filtered out because they have high `freq.sd`
This site will need to be re-run with an override of say `--frequency_slop=2` rather than the default `0.5`

Project 173: looks like a bad power situation on at least 2 maybe all 3 receivers; very frequent reboots.
Also, same problem with frequency setting as above.

**Comment by jbrzusto** [comment]
As well as the frequency-setting problem, **TLDR: project 186 tag deployment times appear to have been entered as local (GMT+1) times, rather than as GMT times.**

**Permanent Fix**
Verify the above, then change deployment times backward by 1 hour
for this project.  It might also be worth registering a parameter override for this receiver
to cover the period until they change the listening frequency in the SG's `deployment.txt`
to 150.096.  That parameter override

**Details**
Project 186:  another issue: tag deployment times appear to have been entered incorrectly; possibly this was an issue of timezones  (Italy is GMT + 0100).  So if a tag was deployed at 10AM local time (Italy) and that was entered directly as the deployment time, the tag finder would only start looking for the tag at 10 AM (GMT), which is 11 AM local time, by which point the bird has had an hour to put distance between itself and the stressful tagging event!

To test this, I temporarily pushed back all the deployment start timestamps for tags in project 186 by 3600 seconds like so:
```sql
meta
sqlite> update events set ts=ts-3600 where event = 1 and tagID in (select distinct tagID from tagDeps where projectID=186);
```
then re-ran SG-1914BBBK0863 like so:
```bash
rerunReceiver.R -t -U 232 -P 186 -o "--frequency_slop=2" SG-1914BBBK0863
```
and got this plot:
![sg-1914bbbk0863-2018_maggini - morocco_yasmina_hourly_tags](https://user-images.githubusercontent.com/1228504/51393869-26261480-1b0f-11e9-91f8-ce03073ca0e7.png)
which is at `/sgm/test_products/SG-1914BBBK0863/SG-1914BBBK0863-2018_Maggini\ -\ Morocco_Yasmina_hourly_tags.png`  (note that summary products produced when `rerunReceiver.R` is run with `-t` go in `/sgm/test_products/` rather than in the `/sgm/www/` hierarchy).

That picked up an additional ~20 tags from project 186.  The wonky (`?proj?`) tag labels on the plot are because the project is being looked up by tag deployment times, but I didn't change those (the events table is normally derived from the tag deployments table whenever the latter is updated from motus.org; it is what the tag finder actually uses to tell when to start and stop looking for every tag).

**Comment by leberrigan** [comment]
Could these receivers be re-run once more with the correct frequency setting to check whether there are any new detections?

**Comment by Hussell** [comment]
I've rerun these receivers with default_freq = 150.1 and frequency_slop = 2.

**Comment by leberrigan** [comment]
I was just notified that the receivers for project 173 have now been updated with the correct frequency (150.096 MHz). A new deployment has been created for the one tower that is currently operational and new deployments will be made for the other receivers once they fix the issues there.

Note that the latest data uploaded to this project had the receiver frequency set to 150.100 since this data comes from before the frequency was corrected. That means those receivers should be rerun yet again.

**Comment by Hussell** [comment]
There's been a parameter override set for these receivers since March, so data up until now has been rerun with the frequency fix.

Probably the larger problem here is the tag deployment times being off by an hour, and that doesn't seem to have been fixed. Until the tag deployment start times are corrected, rerunning won't change anything.

**Comment by leberrigan** [comment]
Is that so? I'll poke him again about that...
