### ISSUE TITLE
Species table

### ISSUE THREAD

**Issue by Hussell** [MotusDev/Motus-TO-DO#441]
Requested by Stu. Make a version of /data/admin/species for all users. Add a link to it from the main menu under Explore Data. Add a link from the Motus By the Numbers page (and make as many of the other numbers into links as is practical).

**Comment by Hussell** [comment]
Link added to "Explore Data" menu on sandbox and beta. Next time beta8 is deployed to live, the header and stripped header on live should be updated to match.

**Comment by cjardine-bsc** [comment]
I'm going to be contradictory here and suggest this doesn't warrant its own place in the drop down menus. 

I'd like to see the "Projects" link in the drop down changed to something a little more encompassing like "Explore Data" or "Data Discovery" or something. Since it's very unclear right now how much functionality that tool has. I suspect most users are not taking advantage of it's full potential.

https://motus.org/data/projects

If we rename that dropdown item, I'd say a link to the species list at the top of that page would make sense.

**Comment by Hussell** [comment]
Got another request for this: https://github.com/MotusDev/Motus-TO-DO/issues/396#issuecomment-476260140

Could we just update the live menu now, and discuss redesigning the navigation in a new issue?

**Comment by cjardine-bsc** [comment]
We already discussed and decided to implement, just havn't done it yet. 

On it.

**Comment by cjardine-bsc** [comment]
Ah, I actually had done it, but just left it commented out while I waited for the page to be deployed to live. 

Commenting removed. Last few times I've done this its taken a while to show up on live.

**Comment by Hussell** [comment]
For the Tomcat server, someone has to visit /data/admin and reload the banner, or the server has to be restarted. I've just done that, so the link is present everywhere under /data/ now. For the WordPress server, I wasn't aware that there was ever a delay after saving the header. But the link isn't there, so ???
