### ISSUE TITLE
Terminated receiver deployment start and end dates can't be edited

### ISSUE THREAD

**Issue by Hussell** [MotusDev/Motus-TO-DO#456]
Why? Could this be something left over from before we were computing deployment status?

I ask because a fair number of data issues are caused by slightly incorrect deployment start and end dates, many of which could easily be fixed. Right now, the data issues links to the deployment edit page, and asks the user to fix the deployment dates, only for them to find they can't.

It looks like the restriction can be removed easily.

**Comment by pmorrill** [comment]
I will take a look. There was a time when we discussed restrictions on when deployment datetimes could be edited. But it seems reasonable to allow them to be changed at pretty well anytime.

**Comment by leberrigan** [comment]
This is the same for tag deployments.

I believe this was put into place to prevent users from freely modifying their metadata long after it had been entered since this can disrupt other users' work. I think the idea is to force people to be extra careful when entering this information so they do it correctly the first time. 

That being said, I do think the idea behind this should be reassessed since I don't know how necessary or effective it is. I think people are generally either fairly diligent when it comes to entering their metadata or they don't bother fixing problems if it doesn't affect their own research, especially when they have to email me to get anything changed.

**Comment by denislepage** [comment]
Paul and/or Catherine should confirm that modifying the metadata dates (and only the dates, not other unrelated fields) triggers certain processes to re-link the data with their deployment ID's. This could become something disruptive if people made lots of changes, but as mentioned, this will be relatively rare.

**Comment by cjardine-bsc** [comment]
yes, there is a trigger on the tags_deployments table that insets prTaghitsDeployIDTagDeployID and prTaghitsSummariesTagDeployID into the procs queue when the start or end dates of a deployment are changed.
