### ISSUE TITLE
negative tsBegin in sg_batches

### ISSUE THREAD

**Issue by cjardine-bsc** [MotusDev/Motus-TO-DO#462]
I was working on #449 and noticed there are recent batches in sg_batches with a negative value for tsBegin. 

.......?

**Comment by Hussell** [comment]
Receivers sometimes fail to synchronize their clock with the GPS signal. The monotonic boot number (monoBN) can often be used to compensate for this, e.g.:
select * from sg_batches where motusDeviceID = 1167 order by monoBN

Most of these batches aren't long enough to have an activity pulse recorded, so, less than an hour long. I suspect that a lot of them are caused by low-power situations in solar-powered receivers.

**Comment by StuMackenzie** [comment]
Closed unless an action can be identified.
