### ISSUE TITLE
Re-validate projects one at a time

### ISSUE THREAD

**Issue by Hussell** [MotusDev/Motus-TO-DO#467]
When the process queue reruns all data validations, and fails, then every project gets an error message at the top of their data issues page for the rest of the day. This seems to happen about once a week (with lots of variability). Common reasons for failure lately are "Socket Closed", probably due to server restarts or power outages, and "Query timed out", which are both transient errors. More rarely, something unexpected happens in one query (i.e. a bug), and the whole process fails.

Given this, it would be good if each project's daily re-validation were run as a separate step on the queue. Then, whenever something failed, only one project would see an error message for a day.

**Comment by cjardine-bsc** [comment]
Okay. I've created a new proc that loops through all the projects called prDataValidationAll. I've set that up to run through the queue on Sandbox. I'd like that to run a few times so we can compare it to prDataValidation_pr, this new proc will take longer since its looping through projects one at a time instead of just doing them all at once. It may in fact cause more locks given it will now run the proc multiple times, depending on how the execution plan uses the where projID = XX statement

Let's leave this open for a few days while we test on Sandbox. 

I might prefer to just set something up that reverts the job IDs in adm_validation_process if the procs queue returns an error.

**Comment by cjardine-bsc** [comment]
Alternative approach would be to add this to the end of the prDataValidation_pr proc. 

UPDATE adm_validation_process
SET job_id = (SELECT MAX(job_id) FROM procs_queue_steps 
WHERE name = 'prDataValidationAll' and status = 'Complete')
WHERE project_ID = ISNULL(@proj,project_ID)

The downside being that if the proc  fails half way through only some of the validations will be run for all projects and errors will be missing from the download page. A way to address this would be to delete from adm_validation_errors at each step in the validation process. That will still be faster than running each project one at a time. I think I'm in favor of this approach....thoughts?

**Comment by cjardine-bsc** [comment]
Ya. That solution doesn't work: 

UPDATE adm_validation_process
SET job_id = (SELECT MAX(job_id) FROM procs_queue_steps
WHERE name = 'prDataValidation_pr' and status = 'Complete')
WHERE project_ID = ISNULL(@Proj,project_ID)

The last step, however, sets it to the job ID of the previous job, since the current job isn't marked complete until this procedure exits. This leads to the Data Issues page showing the wrong date and time for completed data validations.

**Comment by Hussell** [comment]
#500 is still an issue.
