### ISSUE TITLE
Timezone on lotek receivers 

### ISSUE THREAD

**Issue by cjardine-bsc** [MotusDev/Motus-TO-DO#478]
Moving this over from email. 

**Summary:**

Lotek receivers allow users to set their time zones twice, on set up and on data download. Users sometimes set the time zone to the local time instead of UTC. The result being that all the tag detections from that receiver are recorded with the incorrect time. 

**Solutions:**

1. The ultimate solution would be to work with lotek to force all receivers to use UTC. Always.
2. Another desirable solution would be if the timezone were listed in the file downloaded from the receiver. 
3. Failing those two, which are out of our control, we need to implement a DB solution where we track the timezone offset for each receiver deployment. 

**Steps needed:**

1. utc offset field added to sensor_deployments table. 3 options:
-  0 (utc time), 
- NULL (need details) 
-  a numerical offset from utc (i.e. -5 for EST)

2. Add this field to sensor deployment webpage for Lotek receivers only. We got a little sucked into this during our call.  Two options were: 

a) allow users to select their timezone from a drop down list. 
b) give users the option of UTC or local. Then use one of the many packages out there to get timezone from deployment date and location (https://stackoverflow.com/questions/16086962/how-to-get-a-time-zone-from-a-location-using-latitude-and-longitude-coordinates/16086964#16086964) 

Either way, what should be stored in the DB is the utc offset between the selected timezone and UTC. 

In all scenarios we need to make it clear that UTC is default and there should be strong language on the page telling users that anything other than UTC should only be used to fix an error.

3. Add error check that warns users of missing utc offset (in user decipherable terms)
4. Add utcOffset value to the R views and R package. 
5. Add details to the motus RBook on altering timestamps for gps, taghits, deployments and batches based on the utcOffset value. 

**Opinion:**

Timezones and daylight savings times are all stupid. We should all just bow to the superiority of the Queen and live our lives in UTC. Think of how easy it would be to schedule conference calls!

**Comment by cjardine-bsc** [comment]
Paul can you look into getting step 2 above rolling? Lucas dutifully poked at this after you left the meeting today. Thanks! 

Once that's done I'll get the error check deployed.

**Comment by pmorrill** [comment]
We already have use a lookup table of valid offsets (lk_timezones) in Motus. But it returns ~ 500 records, which is too many to present in a dropdown selection. Where are Lotek receivers being used? We could filter the list, if we have the country as part of landowner address. (But, because they can change 'site' in the same tool as we are collecting the offset, this would require an asynchronous update of the timezone selection, which is always more complicated than it should be).

We could add a new lk table that carries valid timezones for Motus deployments, just using the numerical value: this allows us to control the list and keep it manageable: basically 24 values plus the few oddballs we think important, like St Johns.

Alternative - quickest of all - is to just allow users to input the value themselves. It's their data so strong incentive to use the correct value. We can sanity check it on the server.

**Comment by pmorrill** [comment]
BTW: google's timezone api is half a cent per click, so that is not likely to amount to much, but setting up the code might be more effort than this merits?? Wish I'd been on the end of the call to better gauge the usage volume for this.

**Comment by leberrigan** [comment]
Would it make sense to have a dropdown with just three options? UTC, local, or other. I I can't think of why users would have anything besides the first two options, but just in case you can have the other option which would allow users enter a custom offset. Note a custom offset needs to allow for hours and minutes for weird cases like NL.

**Comment by denislepage** [comment]
we can possibly build our own without too much work. All I need is a shapefile.  This looks promising. https://github.com/evansiroky/timezone-boundary-builder

**Comment by pmorrill** [comment]
It just seems like overkill to write code that will look up / calculate offsets for them, based on location. As research scientists, they should be able to input their offsets themselves, as decimals! I would just put a text entry field on the tool and tell them how to use it!

**Comment by tabanid** [comment]
Offsets don't work because deployments can span changes in DST and then
people get confused. Use GMT. Period.

**Comment by Hussell** [comment]
> Offsets don't work because deployments can span changes in DST and then people get confused. Use GMT. Period.

Wish we could. But since Lotek receivers don't tell us what offset/timezone they're using, we have to solicit it from the users.

> Would it make sense to have a dropdown with just three options? UTC, local, or other. I can't think of why users would have anything besides the first two options,

"Local" will always be what's set on the computer they're doing metadata entry from. Sometimes this will be on the other side of the world from the receiver, or in Eastern Standard Time (-5) during the winter when the receiver was set to Eastern Daylight Time (-4) during the summer. Sometimes someone will be using a laptop from San Francisco to do data entry in Colombia.

> Lotek receivers allow users to set their time zones twice, on set up and on data download. Users sometimes set the time zone to the local time instead of UTC.

Just to clarify, are the Lotek receivers setting an _offset from UTC_, or a _timezone_? In other words, do Lotek receivers have an onboard timezone database? (I hope not.) If they're using a fixed offset, do they use offsets in minutes, whole hours, or something else like quarter-hours?


I think Paul has the right idea: Lotek receivers are in the minority, and most Lotek receivers are set to UTC, so the error-correction form should be simple: "Enter the offset from UTC which was set on your receiver:" followed by a number entry box. It should only show on Lotek receiver pages, and even there should be partially hidden so that it's only seen if a user specifically looks for it. E.g. instead of appearing on the deployment edit page directly, have a button "Timezone Correction" which opens a popup with a paragraph of explanation along with the form.

**Comment by pmorrill** [comment]
I have added a 'correction' capability to the recv deployments form (Lotek only). I am readonly displaying the current utc offset (hopefully it is zero), and provide a button that allows it to be corrected, We need to write instructions / warnings to go with this tool: I will take a crack at it in sandbox.

**Comment by denislepage** [comment]
This only took a few minutes to put together. I will reserve my comments for now on whether we should actually use it.

If there is value, then you can obtain the timezone ID with this function call:

SELECT dbo.[prFindTimezone](@lat, @long)

E.g.
SELECT dbo.[prFindTimezone](45, -77)

Returns America/Toronto.

This can be used to set the timezone ID in Java for the date object. I am not sure if all the values of the table are recognized by Java, but I think they are.

https://garygregory.wordpress.com/2013/06/18/what-are-the-java-timezone-ids/

**Comment by cjardine-bsc** [comment]
Moving some of Denis's comments over from email:

Until Lotek fixes this mess with their receiver, which will take a while, we should finalize how we are going to deal with this.

Looking at the deployment page in sandbox for a Lotek receiver, there is a UTC offset field. A few things:

-	The help icon hover text isn't set yet.

-	I don’t know if it will be entirely clear to everyone what value people are expected to enter. I think most people will get it right, but I am equally sure some people won’t. Maybe we can add something like “E.g., if you receiver clock is set to Eastern Daylight Time, enter a UTC offset of -4.”. Also, is it the clock of the receiver that matters, or the time people set for their data export?

 
-	Finally, we should make sure that this value is available in R, and we need to figure out how we are going to instruct people to make the correction, or whether we provide a script that can do so. My biggest concern with modifying the data itself is that new data will keep coming in for the same deployments, and we’ll then have a mix of corrected and uncorrected data, with no way to assess which is which. Doing so would require track at a record level (or perhaps more correctly at a batch level) which ones have been modified. My preference would be to handle this in R with a function.

**Comment by steffilazerte** [comment]
Perhaps I haven't understood completely, but why not deal with this before the users get their data in R? Have fields like: `time`, `offset`, `original time`. `time` = `original time` - `offset` (or however the math works). 

If there is no offset, `time` and `original time` are the same. If the `offset` is wrong, advanced users have the `original time` and can modify their data accordingly. Everyone uses the `time` field for anything they do. 

Or is it too computationally challenging to constantly be applying this calculation on the server?

I can also create a small R function that will do this as the data is downloaded, with the option for the users to apply it to their whole data base independently.

**Comment by cjardine-bsc** [comment]
Lucas- Can you please generate some help icon text. Including details on what offset they should enter?

Steffi: There is a utcOffset file in the receivers deployment R view and sample data. Can we have that added to the R package (if not already)?

R function: I was thinking the same RE adding new columns to the existing tables. I.E. tsCorrected tsStartCorrected tsEndCorrected etc. That way we don't need to track which rows have been fixed and which have not. However, because offsets can be updated in the metadata (receiver deployment) we can't just fix the times when the data comes in (since we may have to go back and change the corrections when metadata is refreshed). So I think it needs to be done as a function (correct me if I'm wrong and you think you can incorporate this into the update when metadata=TRUE). 

I think this is the list of fields that will need to be corrected for each batchID where the offset applies. Best to let Denis et all confirm before you move ahead. 

Activity:
hourBin
*Are we going so far as to update day and month? Do we need the day and month in this table? We don't keep it anywhere else?

Batches:
tsStart
tsEnd

GPS:
gpsts

Hits:
ts

Pulse Counts:
hourbin

Runs:
tsBegin
tsEnd

**Comment by steffilazerte** [comment]
> Steffi: There is a utcOffset file in the receivers deployment R view and sample data. Can we have that added to the R package (if not already)?

This field (not file?) is present in `recvDeps` for current version of `motus`.

> R function: I was thinking the same RE adding new columns to the existing tables. I.E. tsCorrected tsStartCorrected tsEndCorrected etc. That way we don't need to track which rows have been fixed and which have not. However, because offsets can be updated in the metadata (receiver deployment) we can't just fix the times when the data comes in (since we may have to go back and change the corrections when metadata is refreshed). So I think it needs to be done as a function (correct me if I'm wrong and you think you can incorporate this into the update when metadata=TRUE).

I think we can do both. We can have a function that the user can call manually to force the calculation, but we can also included it at the end of the `tagme()` if `forceMeta = TRUE` (assuming you meant `forceMeta` instead of `metadata = TRUE`?). Right now that is how the `activity()` function works. It is called by `tagme()` but is also available for users to call manually.

**Comment by denislepage** [comment]
Yes, converting closer to the source would be theoretically easier. But also messy/expensive. Users will have the same problems, anyway. I am not sure we’re ready to move yet on any implementation. Let’s only make sure we provide the information to users for now.

Here’s a list of topics that would need to be covered for dealing with this on the server (probably about the same on the R side):


-          we could potentially track at the batch level whether a correction has been applied yet or not. This is not a perfect solution because batches don’t always perfectly overlap with deployments and in theory, you could have half of a batch matching a deployment where a correction is needed, and the other half matching another deployment that doesn’t require the correction. Tracking this with individual hits would be a lot more granular, but also much more expensive.



-          changes would presumably best be done before any summaries are generated, immediately after imported from sgdata, or even within motusServer/tag finder, or while we are importing it. But this only works when we have the correction available, which may not be known until after the data has been processed. If we make the correction in sgdata, then we potentially lose the ability to track the fact that we have made the correction, so I would exclude that option. Doing the correction during the data import seems the most appealing. Doing this assumes that we can rely on the receiver metadata as we import data:



o   pull the batch

o   use the motusDeviceID and tsStart/tsEnd values to resolve which deployment(s) this overlaps

o   if there is an offset correction, apply it as the data is being read/inserted

o   indicate in the batch (or for individual hits) that a correction was made. If tracked at the batch level, we would also have to track which deployment was used as a reference. For hits, we already do this in the taghits_deploy_id  table, do it would make the most sense to track the changes in that table also.



-          the biggest complication, by far, involves changes to the metadata offset made after the import. When users correct the offset for a receiver deployment:

o   if there are other changes to the deployment, those should be addressed first (e.g. matching hitID’s and deployID based on new deployment dates)

o   we must then build a list of batchID’s or hitID’s where the offset no longer match between the metadata and the data (e.g. a.deployID = b.deployID and a.offset <> b.offset).

o   all the associated records in the det tables must then be updated (batches, runs, taghits, taghits_deploy_id, gps, gps_deploy_id, pulse_counts, ). Unfortunately, for batches and runs, it may not be as simple as doing a subtraction/addition, because the correction may only apply to a portion of the batch or run, so new bounds would need to be calculated.

o   once the corrections are made, new data summaries (runs, daily, activity and tracks) would need to be computed for the batches involved.


-          Given the volume of data, I think making the changes to the various tables will be prohibitively costly. I briefly toyed with the idea of only doing changes during import when the correction is known, but that would leave the data in an unstable state where only some of the records have been corrected, and having no better solution to deal with those that haven’t been yet.


-          One more deal-breaking issue is that making the correction on the server after the fact would require the users to download the data again. Regardless of what we do on the server, we would then also have to keep track of the changes that have been made on the client side (i.e. did they import the data after or before the server correction was made), and I have no idea how we would signal to the client package that some batches need to be updated (well, I do have an idea, but I don’t think it’d be worth it).

Yikes!! Given all this, I am not almost certain we should make those corrections on the server. Given that we are already linking the hits to the receiver deployment in the view, it means that the offset will be available and I think that we should simply limit ourselves to add the offset field to the alltags view. We could take this one step further and add a new ts field in the same view that provides the correction (e.g. tsCorr = ts when offset = 0). I am willing to entertain the idea of making the corrections directly in the R tables, but I am not convinced that the complications outlined above make it worthwhile, and some of the data summaries wouldn’t necessarily be possible to recreated locally (e.g. activity).

To note, with the alltags view approach, the linkage with the activity table (by hourBin) should still be made on the basis of the unconverted ts value, though it is not going to be as precise (in theory, you “could” have a mix of corrected and uncorrected data falling in the same hourBin, but that will likely be exceptional).

**Comment by steffilazerte** [comment]
I've been doing some sample calculations and looking into the various approaches from the perspective of changes in the R package.

I think we have two, sequential steps we can do. We should definitely do the first, and maybe, later, do the second.

### First (and simplest)
Adjust the `alltags` view to have the `utcOffset` and a corrected `ts`. This will allow uses to use the corrected value in their analyses, while leaving the original value for all the table joins. In this case, the corrected `ts` would never be used by anthing internal (expect perhaps the helper functions for plotting, etc.).

The benefit is that I think we can do this just by altering the function that creates the `alltags` view.

Downside is that it will only be as current as the metadata, so users should be encouraged to update the metadata.

**Steps**  
- Add `recvUtcOffset` (from `utcOffset`) to alltags view
- Calculate `tsCorrected` from `ts` and `recvUtcOffset` in alltags view


### Second (more complex)
Create corrected `ts` fields for every table that has a problematic timestamp. This would NOT change the existing `ts` fields but would rather introduce new, corrected fields (eg., we would have `tsStart` and would then add `tsStartCorr`) as @cjardine-bsc suggested. This is more complex as it adds quite a few new fields. It would also have to be run every time the user downloads new data.

How common is it for users to conduct analysis with the raw tables? If it's uncommon, I'd either not implement this at all, or make it optional (have a function available that users can choose to use, or not). If it's very common, I'd add it to the data update step (`tagme()`).

**Steps** 
- Create an offsets index from hits (`ts`, `batchID`), batches (`batchID`, `deviceID`), and recvDeps (`deviceID`, `tsStart`, `tsEnd`, `utcOffset`) tables
- Use this index to add corrected timestamps to all tables:
    - activity (`year`, `month`, `day`, `hourBin`) -> If we correct any, I think we need to correct them all (otherwise get rid of month, and day ;), but we technically might still need to correct year, on very rare occasions) 
    - batches (`tsStart`, `tsEnd`, `ts`)
    - gps (`ts`, `gpsts`) [both?]
    - hits (`ts`)
    - nodeData (`ts`) [when we have this table]
    - recvDeps (`tsStart`, `tsEnd`)
    - runs (`tsBegin`, `tsEnd`)
    - tagDeps (`tsStart`?, `tsEnd`?) [are these timestamps affected by the receivers `utcOffset`?]

Looks like `hourbin` in `pulseCounts` is a receivers database, but I'll need someone to give me access to a receiver on Sandbox to test that out.

### Should I:
1. Wait
2. Implement the first option
3. Implement the first and second options, the second as a stand alone function
4. Implement the first and second options, the second as part of the data update (`tagme()`)

**Comment by denislepage** [comment]
Yes, that seems like a good summary.

We should definitely do the first option, regardless. I am presuming that when the offset = 0 (or missing), the tsCorrected is then equal to ts, rather than NA. As far as I can assess the ts field is the only one that needs to be corrected in alltags.

I guess we also have the option of linking hits to deployments on the basis of the corrected ts (i.e. when resolving the tag or receiver deployment ID), but that could potentially slow down even further the alltags view, and it’s probably not enough of a concern overall (only impacts the few hours around the time of the start or end of the deployments), so I would ignore this.  I am not sure that deployments tsBegin and tsEnd are also that precise anyway.

The link between hits and gps (resolved within alltags) would still work on the original ts values, as both tables suffer the same offset issue, so no changes needed there in alltags.

The second option is indeed more daunting, and probably not that useful. For the most part, it is probably safe to assume that the offset correction also needs to be applied the same way to data like runs (runs start/end is possible the other place where this matters, along with the ts in gps table). Metadata would not be impacted, at least not in a consistent way (metadata may also suffer an offset problem independently, but I wouldn’t worry about that).

Some tables, like activity, which depends on hourBin, could potentially be corrected (e.g. subtract 4 hours to dateBin). That would pose a rare problem in Newfoundland with a half-hour offset, where calculations would have to be redone to separate the data into new hourBins, and in cases where the corrected dateBin may already exist. Again, not something we should worry too much about, but then the link between the hits and the activity table should be done on the basis of the uncorrected ts in hits. We should provide an example in the book of how to see the activity metrics associated with each hit records (calculate hourBin in hits to link to activity).

Of your list below, tsBegin and tsEnd in recvDeps and tagDeps would *not* be impacted by the offset problem.

Anyway, I think I am strongly leaning to only correcting the single ts field in alltags, and let people sort it out if they want to use raw tables or a custom-made view, and perhaps provide a few examples in the book about how to make custom combinations of tables.

**Comment by steffilazerte** [comment]
Okay, I've added this to `alltags` we now have two more columns:

- `recvUtcOffset` (`utcOffset` from `recvDeps` table)
- `tsCorrected` (either `ts` if `recvUtcOffset` is NA, or `ts` - `recvUtcOffset` * 60 * 60)

For example,
```
ts = 1562650929 (2019-07-09 05:42:08)
recvUtcOffset = -5
```

Therefore 
```
tsCorrected = 1562650929 - (-5)*60*60
tsCorrected = 1562668929 (2019-07-09 10:42:08)
```

Does that calculation make sense? Always gotta double check the time change calculations!

**Comment by denislepage** [comment]
Is there anything we want to do on this for now? Can't think of anything other than testing. I am closing preemptively. Someone can take the blame for reopening...  Can someone (Lucas?) check that the values work as expected in the R sandbox branch?
