### ISSUE TITLE
Project 10 receiver data upload does not produce output plots and has no tag detections

### ISSUE THREAD

**Issue by leberrigan** [MotusDev/Motus-TO-DO#481]
The most recent upload on April 21 (receiver deployment 5155, device 23) did not produce any output plots and had no detections:
https://sgdata.motus.org/status?jobID=447278

Previous upload from April 15 had active tag detections up until data was downloaded that day. It's very likely there were detections after April 15 so what's going on?

**Comment by Hussell** [comment]
> Running tag finder on receiver SG-1614BBBK1659 boot session 436 (resumed) Got 285 (unfiltered) detections.

So detections were, in fact, found. Plots weren't produced because the user uploaded with project ID = 2. The tagfinder only produces summary plots for deployments in the project, and there aren't any for that receiver during the time period covered in the upload. (This receiver has been used by project 2 in the past, and also by project 197. The upload just didn't contain any data from those years.) The uploaded data all falls within an ongoing deployment for project 10, so it's unlikely there's any missing deployment metadata. Seems like the user just uploaded with the wrong project ID. This has no further effect beyond the plots not being generated.

**Comment by leberrigan** [comment]
Ah, I see! I know it's not a biggie, but is there any way to get around this? It seems quite common for folks to accidentally upload to the wrong project (just take a look at the number of uploads I and others have made on project 137!).

**Comment by Hussell** [comment]
I've rerun that one boot session with project ID = 10, which re-creates the plot for the whole deployment, but I don't see a way for a regular user to do it.
