### ISSUE TITLE
Recently Uploaded Data not Present in Motus Database - All projects

### ISSUE THREAD

**Issue by leberrigan** [MotusDev/Motus-TO-DO#499]
All data recently uploaded to project 10 is not showing up in anywhere in the Motus database. Is this related to #446?

Uploaded data does not appear in jobs list when searched for in sgdata.motus.org, but **does** appear in the jobs list on motus.org/data/project/sgJobs.
Output plot produced after upload shows there _should_ be data, but nothing can be found on web interface or in sqlite database.

**Examples**
Data uploaded June 2. Missing data since last upload on Apr 5, 2019: https://sgdata.motus.org/download/10/SG-2516BBBK1E0D-2018_Taylr_SBL_WestLight_2_hourly_tags.png
Data uploaded June 2. Missing data since last upload on Apr 4, 2019: https://sgdata.motus.org/download/10/SG-4001BBBK1190-2019_Taylr_SBL_EL_hourly_tags.png

**Comment by cjardine-bsc** [comment]
Yes. this is because I had the imports from sensorgnome paused over the weekend as I tried to work through the backlog of processing prTaghitsDeployIDNew. 

There are still 4million records left to process on live, and 20million on sandbox. I'll restart the queue so the new data can import while I'm looking into why this proc is now taking so long.
