### ISSUE TITLE
Receiver Map - Remember Position when Navigating Back/Forward

### ISSUE THREAD

**Issue by leberrigan** [MotusDev/Motus-TO-DO#505]
When navigating receivers map, clicking on a link in the receiver popup navigates you to a new page. Navigating back to the map resets the map to the world view - is there a way to make the map reload to the position you were in before?

An alternative and simpler solution that could be used in the mean time is to just make the links in the popup open a new tab - that would be very helpful!

**Comment by Hussell** [comment]
Works for me, at least until my cache fills up. Are you doing this on a phone? Which browser?

Since users with a mouse can choose whether or not to open a link in a new tab (left-click vs. middle-click), it's usually considered too annoying to override the default behaviour and cause every type of click to open a new tab, at least without some sort of visible cue or warning.

**Comment by leberrigan** [comment]
I only use a mouse with these maps maybe 10% and I think that's pretty common among users. You're right that it's annoying always have tabs open even if you don't want them to, but I think it's more important to have that for now. In the end it would be best to have it not open a new tab, but to reset the map position once you return to the map by navigating back/forward a page.

**Comment by Hussell** [comment]
Yes, and that's how it works for me. Are you doing this on a phone? Which browser?

**Comment by leberrigan** [comment]
On my phone I use Chrome. On my laptop I tend to use Firefox. I also frequently have many tabs open so that's probably limiting my cache?
