### ISSUE TITLE
Tag Deployments in Antarctica

### ISSUE THREAD

**Issue by leberrigan** [MotusDev/Motus-TO-DO#524]
[Tag deployment map](https://motus.org/data/tag/deployment/map) shows several deployments in Antarctica or even further 'south'. Those in the Antarctic are likely transposed lat/lon which can be fixed by contacting PIs (me), but it shouldn't be possible for deployments to occur beyond the Antarctic, unless they've managed to navigate through a 4th spatial dimension.

**Comment by Hussell** [comment]
https://en.wikipedia.org/wiki/Web_Mercator_projection#Formulas

"Because the Mercator projects the poles at infinity, Google Maps cannot show the poles. Instead it cuts off coverage at 85.051129° north and south."

So those tag deployments are, technically, being displayed in the correct place, it's just that Google Maps doesn't show imagery from there because it would just be a tiny area around the pole enlarged and distorted to fill the space. Until we have real deployments above 85N or below 85S I'm not going to worry about it.

**Comment by denislepage** [comment]
The markers on that map are showing the default drop pin. Is that how it was set up? Can it be changed?

Question: how do we even get to that map? Is this still being tested?

**Comment by Hussell** [comment]
Yes, that was how it was set up. Yes, it can be changed. (But why?)

Links to that map are present on the public tables of tag deployments (e.g. https://motus.org/data/projectTagDeployments?id=132 for project 132) and on individual deployment pages (e.g. the tag deployment that's currently near the south pole: https://motus.org/data/tagDeployment?id=12039).

**Comment by denislepage** [comment]
I missed that this was the same map used for individual tag deployments.

The map with all deployments from all projects doesn’t seem to be linked directly from the menus anywhere. I’m not sure there is a reason to, but I just wasn’t sure what I was looking at.

When there are more than a few markers, the default markers are bulky and they makes the page looks like it is still a work in progress. I’m not sure I would present the gray markers from other projects when looking at a specific project. Is there a value in this?

I also just inverted the coordinates for those 3 deployments: 10237,12028,12039
