### ISSUE TITLE
Receiver List glitches - 'Receiver Type' not listed in main receiver list despite being correctly assigned

### ISSUE THREAD

**Issue by StuMackenzie** [MotusDev/Motus-TO-DO#527]
Most earlier projects have this problem in one place or another.

In some cases I was able to re select receiver type to 'select' then the correct receiver type, save, and it would correct, but not in all cases. eg. receivers: Project 48 - CTT-867459049274913

Note that the receivers that can't be changed do not have a ID or Device Key for whatever reason.

Also: From Receiver list. 'Edit' button and 'Edit deployment' button both return 'edit deployment' page

**Comment by StuMackenzie** [comment]
Project 48 - SG-CFAFRPI34BE5, SG-CFAFRPI34BE5, SG-621DRPI38D78, SG-5C53RPI33F6B, SG-BFEBRPI34958, SG-E55BRPI3D04C

**Comment by denislepage** [comment]
This is because we have the receiver type in 2 places, and the page mentioned refers to the one in sensors_hash_keys, not sensors. I think we should change that reference, so it displays the value entered by the user (in sensors). 

I added a bunch of missing receiver types in sensors_hash_keys, but they were all things registered a couple years ago. Not sure if we have the process in place now to make sure new registrations are consistent. We should confirm. There are a few remaining receivers in hash keys with no type, mostly Lotek ones. That will need to be addressed.

Also, I think this was mentioned, but I don't think users should be able to change the receiver type once the receiver number was locked in.

**Comment by pmorrill** [comment]
I have adjusted in sandbox so that the value reported is pulled from the sensors table (first) but uses the sensors_hash_key field if the sensors.receiver_type field is null.

**Comment by StuMackenzie** [comment]
Not sure if this is the same issue, or if it'll be fixed in the next update, but receiver type listed in these tables - https://motus.org/data/project/recvs?projectID=145, doesn't match was is in the actual edit receiver properties table. Probably a few miss-matches for us to deal with.

**Comment by pmorrill** [comment]
We could fix this. The string displayed in the deployments table is a shortened 'key' that is used as a reference in the database: it maps directly to the 'friendly' string that is shown in the dropdown box when you edit a receiver. The query that pulls up the list of deployments / receivers would need adjustment to resolve the friendly version for display.

**Comment by cjardine-bsc** [comment]
I've made this change to vwBase_receivers_deployments in sandbox. We'll have to check that that doesn't have any unintended consequences.

**Comment by Hussell** [comment]
So in vwBase_receivers_deployments the lookup key has been replaced by the English description? That doesn't make sense to me.

**Comment by cjardine-bsc** [comment]
the descriptions for English and French are the exact same for receiver type, with the exception of "Unknown"

**Comment by pmorrill** [comment]
Stu's original question was about the web interface - that does not rely on the underlying views. I don't think anyone has expressed concern about the data in the R package (?) or elsewhere.

In anycase, what I was suggesting was just that I fix it for the web interface, by tweaking the query to include the join.

Also: this discussion is off the original topic: different issue entirely.

**Comment by pmorrill** [comment]
I have checked in a sandbox change to the sql that drives the recv list in our mgmt tools, so that it pulls the 'receiver_descr' field from lk_receiver_type. I think that this is all that is needed here. We will ignore language issues for now (though, 'unknown' translates to 'Inconnu' - the other values are language-agnostic).

**Comment by pmorrill** [comment]
Can this be closed, now that we have launched beta8 to live? Stu / Josh - does the receiver type show now consistently?

**Comment by StuMackenzie** [comment]
I think we're good now.
