### ISSUE TITLE
Reprocessing Florida Receivers

### ISSUE THREAD

**Issue by leberrigan** [MotusDev/Motus-TO-DO#540]
The following receivers need to be reprocessed due to tag metadata not being updated until 2 months after they were deployed:

<details>
<summary>Table</summary>

motusRecvID | recvProjectID | receiverID | recvDeployID | deploymentName
-- | -- | -- | -- | --
1606 | 90 | SG-3115BBBK1319 | 4276 | Eastpoint ANERR Dock
2929 | 243 | SG-FA87RPI3C5D6 | 5077 | FLAQ
2344 | 4 | SG-3886RPI240C5 | 4843 | Florida Panther NWR, FL
2345 | 4 | SG-1814BBBK0769 | 4495 | Ten Thousand Islands NWR, FL
2181 | 166 | SG-4116BBBK1114 | 4330 | FDSHQ
1647 | 90 | SG-3115BBBK0698 | 4277 | St. George Island ANERR Nick's Hole
1646 | 90 | SG-3115BBBK1151 | 4557 | St. George Island ANERR Unit 4
1608 | 90 | SG-3115BBBK1190 | 4558 | Box R WMA
2042 | 90 | SG-3115BBBK1339 | 4559 | East Bay Fire Tower Station
1604 | 90 | SG-3115BBBK1117 | 4560 | Carrabelle THSF Headquarters
2070 | 90 | SG-3214BBBK4822 | 4563 | Sumatra Weather Station ANF
2072 | 90 | SG-3115BBBK1152 | 4564 | Tate's Hell SF Deep Creek
1607 | 90 | SG-3115BBBK1246 | 4568 | Bradwell Game Farm ANF
2071 | 90 | SG-3214BBBK5447 | 4567 | Telogia Creek
2431 | 90 | SG-2814BBBK1244 | 4578 | Wakulla Work Station
2068 | 90 | SG-3214BBBK6221 | 4586 | Wilma Work Station ANF
2512 | 145 | Lotek-D000605 | 4706 | UNF
2342 | 4 | SG-CE03RPI23C18 | 4492 | Loxahatchee NWR, FL
1605 | 90 | SG-3115BBBK1140 | 4631 | Private Property - St. George Island
1593 | 90 | SG-3115BBBK1128 | 4565 | Howard's Creek
2344 | 4 | SG-3886RPI240C5 | 4494 | Florida Panther NWR, FL
2135 | 155 | SG-F37DRPI38476 | 4025 | FL_East_Boca
2181 | 166 | SG-4116BBBK1114 | 4329 | FDSHQ
2036 | 19 | SG-4116BBBK0351 | 3824 | Watermelon Pond WMA
1614 | 19 | SG-3114BBBK2156 | 2953 | Lower Suwannee Refuge
1616 | 19 | SG-3114BBBK2178 | 2955 | Payne's Prairie
2037 | 19 | SG-2916BBBK0723 | 3822 | Gold Head Branch SP
1615 | 19 | SG-3114BBBK2336 | 2954 | Dunn's Creek
1617 | 19 | SG-3114BBBK2277 | 2956 | Favre-Dyke
1647 | 90 | SG-3115BBBK0698 | 3835 | St. George Island ANERR Nick's Hole
1606 | 90 | SG-3115BBBK1319 | 3853 | Eastpoint ANERR Dock
2181 | 166 | SG-4116BBBK1114 | 4151 | FDSHQ
1604 | 90 | SG-3115BBBK1117 | 3873 | Carrabelle THSF Headquarters
2068 | 90 | SG-3214BBBK6221 | 3883 | Bradwell Game Farm ANF
1605 | 90 | SG-3115BBBK1140 | 3836 | FSU Marine Lab
1593 | 90 | SG-3115BBBK1128 | 3889 | Wakulla Work Station ANF
1608 | 90 | SG-3115BBBK1190 | 3833 | Box R WMA
2042 | 90 | SG-3115BBBK1339 | 3839 | East Bay Fire Tower Station
1646 | 90 | SG-3115BBBK1151 | 3854 | St. George Island ANERR Unit 4
2072 | 90 | SG-3115BBBK1152 | 3890 | Tate's Hell SF Deep Creek
1607 | 90 | SG-3115BBBK1246 | 3882 | Apalachicola Work Station ANF
2069 | 90 | SG-3214BBBK7267 | 3884 | Wilma Work Station ANF
2071 | 90 | SG-3214BBBK5447 | 3886 | Telogia Creek
2070 | 90 | SG-3214BBBK4822 | 3885 | Sumatra Weather Station ANF
1994 | 96 | SG-1415BBBK0494 | 3770 | FGCU Grounds
1606 | 90 | SG-3115BBBK1319 | 3439 | Eastpoint ANERR Dock
1646 | 90 | SG-3115BBBK1151 | 3832 | St. George Island ANERR Unit 4
1606 | 90 | SG-3115BBBK1319 | 2920 | Eastpoint ANERR Dock
1607 | 90 | SG-3115BBBK1246 | 2921 | St. Vincent NWR
1646 | 90 | SG-3115BBBK1151 | 3001 | St. George Island ANERR Unit 4
1593 | 90 | SG-3115BBBK1128 | 2899 | Howard's Creek
1605 | 90 | SG-3115BBBK1140 | 2919 | East Bay Fire Tower Station
1608 | 90 | SG-3115BBBK1190 | 2922 | Box R WMA
1647 | 90 | SG-3115BBBK0698 | 3003 | The Sandtrap
1604 | 90 | SG-3115BBBK1117 | 2918 | Carrabelle THSF Headquarters
1647 | 90 | SG-3115BBBK0698 | 3002 | The Sandtrap
2048 | 4 | SG-1814BBBK0607 | 3849 | St. Marks NWR, FL
1994 | 96 | SG-1415BBBK0494 | 4030 | FGCU Grounds
1614 | 19 | SG-3114BBBK2156 | 4319 | LowerSuwanee 2
1617 | 19 | SG-3114BBBK2277 | 4321 | DunnsCreek 2
2036 | 19 | SG-4116BBBK0351 | 4323 | Watermelon Pond WMA 2
1616 | 19 | SG-3114BBBK2178 | 4320 | PaynesPrairie 2
2037 | 19 | SG-2916BBBK0723 | 4322 | Gold Head Branch SP 2
1615 | 19 | SG-3114BBBK2336 | 4465 | Faver-Dyke2
2341 | 4 | SG-36AFRPI21CDB | 4491 | Chassahowitzka NWR, FL
2135 | 155 | SG-F37DRPI38476 | 4485 | FL_East_Boca
2343 | 4 | SG-AF50RPI35384 | 4493 | Hobe Sound NWR, FL
2346 | 4 | SG-E195RPI30020 | 4496 | Ding Darling NWR, FL
2510 | 145 | Lotek-D000595 | 4704 | Lighthouse Point
2513 | 145 | Lotek-D000593 | 4707 | Washington Oaks
2509 | 145 | Lotek-D000601 | 4703 | GTM NERR
2508 | 145 | Lotek-D000604 | 4702 | Ft. Clinch
2511 | 145 | Lotek-D000606 | 4705 | Little Talbot
2419 | 184 | Lotek-D000635 | 4642 | Zoo Miami
2342 | 4 | SG-CE03RPI23C18 | 4804 | Loxahatchee NWR, FL
2803 | 4 | SG-F964RPI3EF7C | 5006 | Crocodile Lake NWR
2931 | 4 | SG-3D2FRPI306C5 | 5079 | Pelican Island NWR, FL
2971 | 4 | SG-6A5BRPI37CB4 | 5110 | Ten Thousand Islands NWR, FL
2344 | 4 | SG-3886RPI240C5 | 4844 | Florida Panther NWR, FL
2944 | 166 | SG-0816BBBK0272 | 5086 | FORT DE SOTO HQ, FL
2984 | 244 | SG-99E7RPI38C38 | 5126 | Rookery Bay, Shell Island Rd
3081 | 257 | SG-D9F5RPI3955E | 5254 | Kingsley Plantation
3239 | 275 | SG-9571RPI35CBA | 5362 | Vero Beach High School

</details>

**Comment by Hussell** [comment]
After sorting and de-duplicating:

project ID | receiver | next scheduled rerun (estimated) | all 2018-2019 data rerun since 2019-08-22?
-- | -- | -- | --
  4 | SG-1814BBBK0607 | 2019-10-04 | ?
  4 | SG-1814BBBK0769 | 2019-10-05 | ?
  4 | SG-36AFRPI21CDB | 2019-10-09 | ?
  4 | SG-3886RPI240C5 | 2019-10-23 | ?
  4 | SG-3D2FRPI306C5 | 2020-01-19 | ?
  4 | SG-6A5BRPI37CB4 | 2019-10-22 | ?
  4 | SG-AF50RPI35384 | 2019-09-29 | ?
  4 | SG-CE03RPI23C18 | 2019-10-14 | ?
  4 | SG-E195RPI30020 | 2019-08-25 | ?
  4 | SG-F964RPI3EF7C | 2019-09-09 | ?
 19 | SG-2916BBBK0723 | 2019-10-08 | ?
 19 | SG-3114BBBK2156 | 2019-10-09 | ?
 19 | SG-3114BBBK2178 | 2019-10-23 | ?
 19 | SG-3114BBBK2277 | 2019-10-08 | ?
 19 | SG-3114BBBK2336 | 2019-12-19 | ?
 19 | SG-4116BBBK0351 | 2019-08-22 | ?
 90 | SG-2814BBBK1244 | 2020-06-29 | ?
 90 | SG-3115BBBK0698 | 2020-06-30 | ?
 90 | SG-3115BBBK1117 | 2020-06-30 | ?
 90 | SG-3115BBBK1128 | 2020-08-13 | ?
 90 | SG-3115BBBK1140 | 2020-08-07 | ?
 90 | SG-3115BBBK1151 | 2020-07-17 | ?
 90 | SG-3115BBBK1152 | 2019-09-03 | ?
 90 | SG-3115BBBK1190 | 2019-08-31 | ?
 90 | SG-3115BBBK1246 | 2020-06-29 | ?
 90 | SG-3115BBBK1319 | 2019-09-30 | ?
 90 | SG-3115BBBK1339 | 2020-06-30 | ?
 90 | SG-3214BBBK4822 | 2019-10-21 | ?
 90 | SG-3214BBBK5447 | 2020-09-23 | ?
 90 | SG-3214BBBK6221 | 2020-09-20 | ?
 90 | SG-3214BBBK7267 | 2020-03-19 | ?
 96 | SG-1415BBBK0494 | 2019-11-13 | ?
145 |   Lotek-D000593 | 2019-12-02 | ?
145 |   Lotek-D000595 | 2019-12-04 | ?
145 |   Lotek-D000601 | 2020-01-21 | ?
145 |   Lotek-D000604 | 2019-12-09 | ?
145 |   Lotek-D000605 | 2019-10-26 | ?
145 |   Lotek-D000606 | 2019-12-13 | ?
155 | SG-F37DRPI38476 | 2020-09-19 | ?
166 | SG-0816BBBK0272 | 2019-09-04 | ?
166 | SG-4116BBBK1114 | 2020-06-14 | ?
184 |   Lotek-D000635 | 2019-09-21 | ?
243 | SG-FA87RPI3C5D6 | 2019-10-06 | ?
244 | SG-99E7RPI38C38 | 2019-11-26 | ?
257 | SG-D9F5RPI3955E | 2019-08-21 | ?
275 | SG-9571RPI35CBA | 2019-09-06 | ?

**Comment by leberrigan** [comment]
Hey just checking in - any luck getting these reprocessed or is the queue occupied?

**Comment by StuMackenzie** [comment]
Queue is locked until we can sgdata running again

**Comment by Hussell** [comment]
Done!
