### ISSUE TITLE
API  receiver/register broken

### ISSUE THREAD

**Issue by jbrzusto** [MotusDev/Motus-TO-DO#55]
I'm trying to register a receiver by serial number, and obtain the motus deviceID it gets assigned.

Here's the call:

    https://motus.org/api/receiver/register

with parameter `json`:
```JSON
{"serialNo":"Lotek-153",
"hash":"48D67DCE8CC16CD2920A920BD94A0CD376D5F32E",
"date":"20170827121753",
"fmt":"json",
"login":"john",
"pword":"XXXXX",
"secretKey":"D9D49670D4DA70357CA09F583F711D91E1A9CAC2",
"serno":"SG-0815BBBK1352"}
```
I've tried this in various ways, with and without the additional `serno`, or using serno
to represent 'serialNo', etc.  I get either `Bad Request` or `Unauthorized`
I also can't get it to work with the v 1.0 API.

Likely the problem is I'm doing something wrong, but I can't find the current API documentation
or sandbox at these URLs where they used to be:

   https://sandbox.motus.org/api
   https://beta.motus.org/api

(these just take me to the main motus page, even if I'm already logged in).
Perhaps something in the transition to https broke this?

I'm going to go ahead and assign my own deviceIDs to the following receivers like so, because they don't appear to be registered and I need deviceIDs to merge their data.

serno | motusDeviceID
---|---
Lotek-153 | 913
Lotek-223 | ~~914~~ **was already 911**
Lotek-D000439 | 915
Lotek-D000440 | 916
Lotek-D000441 | 917
Lotek-D000442 | 918

**Comment by pmorrill** [comment]
One thing: The version 2 api requires that you submit a parameter for receiverType (eg: SENSORGNOME | LOTEKSRX600 | LOTEKSRX800 | LOTEKSRXDL). This is because we validate the serno parameter against this, using regex patterns that we discussed in some depth early summer.

Your request package should look something like this:

{
"serno":"Lotek-153",
"receiverType":"LOTEKSRX800",
"date":"...",
"hash":"asdfasdfasdf.",
"secretKey":"D9D49670D4DA70357CA09F583F711D91E1A9CAC2",
"login":"john",
"pword":"xxxxxxxxxxxx"
}

Note that there was a bug in the reg code as well, which probably explains the sporadic nature of the fails on this call. The fix for that issue was just checked in, so hopefully we can test tomorrow on beta server and if tings are good, move that to live.

BTW: I have preliminary api documentation almost ready here: it's rough, but should help you out.

**Comment by jbrzusto** [comment]
Are you validating against the "latest" scheme cobbled together from what Lotek has told us:

```R
   bareno = substring(serno, 7)
    if (substr(bareno, 1, 1) == "D") {
        model = "SRX800D"
    }
    else if (bareno >= "9000A") {
        model = "SRX400A"
    }
    else if (bareno >= "8000") {
        model = "SRX-DL"
    }
    else if (bareno >= "6000") {
        model = "SRX600"
    }
    else if (as.integer(bareno) >= 391) {
        model = "SRX800M/MD"
    }
    else {
        model = "SRX800"
    }
    return(model)
}
```

**Comment by pmorrill** [comment]
For the moment, I have turned off receiver type / id validation in the api. We'll get Denis and Catherine to check the validation regex patterns before we turn it back on.

We will deploy to live today, I believe. But if this change (turning off validation) doesn't make it into the live server, you can register against the beta server.

**Comment by denislepage** [comment]
These are the 3 Lotek receiver types that are currently supported by Motus, along with their regex patterns. 

LOTEKSRX600	^Lotek-6[0-9]{3}$
LOTEKSRX800	^Lotek-[0-9]{3}$
LOTEKSRXDL	^(Lotek-8[0-9]{3})|(Lotek-D[0-9]{6})$

The example above (Lotek-153, and receiver type LOTEKSRX800) should validate. However, I am also seeing some receiver types in the pseudo-code for the first time, and not all are supported in Motus.

If I am assuming that the receiver type passed to the Motus API = "LOTEK" + model, then, these 4 models will fail:

model = "SRX800D"
model = "SRX400A"
model = "SRX-DL" (note the hyphen in this one, but otherwise the same as in Motus)
model = "SRX800M/MD"

Only those 2 are supported of the list above:

model = "SRX600"
model = "SRX800"

I am not sure I can easily derive the regex patterns from the code above if we need to add new receiver types. In any case, all Lotek receiver numbers submitted to Motus are going to be prefixed with Lotek-xxxxx, so the only part of the regex that would vary is the suffix xxxxx. Right? The rules should be based on the rules that we establish to concatenate the serial numbers, not the Lotek scheme directly.

**Comment by jbrzusto** [comment]
The serial number is read directly from DTA files, which are written by the receiver.
So since that's apparently the only use for this API, is there any reason to send the
receiver type as well?

**Comment by jbrzusto** [comment]
I'm still not able to register a receiver, and there are 82 receivers awaiting registration.
Until they can be registered, the data can't be merged into the main database, and so are
not available via the dataServer.

This (sanitized) request:
```
https://motus.org/api/receiver/register?json=%7B%22serno%22%3A%22SG-2715BBBK0539%22%2C%22hash%22%3A%222F3C662816F95E34005A35673AC0A584BF1CED07%22%2C%22date%22%3A%2220170915130717%22%2C%22fmt%22%3A%22json%22%2C%22login%22%3A%22john%22%2C%22pword%22%3A%22XXX%22%2C%22secretKey%22%3A%22XXX%22%2C%22receiverType%22%3A%22SENSORGNOME%22%7D"
```
which has this (sanitized) json payload:
```json
{"serno":"SG-2715BBBK0539","hash":"2F3C662816F95E34005A35673AC0A584BF1CED07",
"date":"20170915130717","fmt":"json","login":"john","pword":"XXX",
"secretKey":"XXX","receiverType":"SENSORGNOME"}
```
gives this reply:
```
                  Content-Length                     Content-Type 
                           "144" "application/json;charset=UTF-8" 
                          Server                     X-Powered-By 
             "Microsoft-IIS/7.5"                        "ASP.NET" 
                            Date                           status 
 "Fri, 15 Sep 2017 13:08:55 GMT"                            "400" 
                   statusMessage 
               "Bad Request\r\n" 
```

**Comment by denislepage** [comment]
The primary issue is that the regex may fail it the receiver type isn’t supported or missing when people try to edit their metadata (after registration), and that people who try to enter their receiver number manually to match an existing receiver will be prevented from doing so if it runs afoul of the regex.

We could let you initially register these receivers, but that only delays the problem, because we are now having to deal with receivers numbers that will eventually break the regex.  IE, if someone tries to register the receiver to a new project, they have to enter the number manually, and they can’t if it’s unsupported.

For as long as we want to use regex to validate user manual entries, I can’t think of a way by which we can stop maintaining the list of receivers and their regex up to date. I realize it’s a bit of a pain if this has to be revised regularly, but the alternative is going back to letting people enter invalid serial numbers manually. We could have regex rules that are a little more lax to trade off convenience (for us) and error rates.

We should try to minimize how many steps are required to maintain that list of receivers, or even allow you to add new receiver types and/or regex yourself. I am not sure how often this needs to happen, or what it represents at your end, but the system we now have in place in the metadata side has almost eliminated receiver number errors completely here, which was previously a significant problem, and I would be reluctant to go back to not having validation. If the API doesn’t already do so, we should give a little more explicit errors, whether the issue is an unrecognized receiver type, or an unsupported regex.

I am still not sure we have a good long-term model for receiver (and tags) registration at the moment, but it may be a while before we address this properly.

It may be easier to talk over the phone.

Denis

**Comment by denislepage** [comment]
We’ll look into it asap.

Do you have an excel table for those? I can add them manually today if you email them to me directly.

Do they also need to be assigned to a project (with a motusRecvID), or simply registered for you to have a deviceID? The later is simpler. If the issue is the regex, we can worry about that as a next step.

Denis

**Comment by jbrzusto** [comment]
Can we make sure these ones (which I self-assigned deviceIDs for) are
in the DB:
```
   serno 	  motusDeviceID
   Lotek-153 	   913
   Lotek-223 	   911
   Lotek-D000439   915
   Lotek-D000440   916
   Lotek-D000441   917
   Lotek-D000442   918
```
and these need device IDs
```
   SG-0816BBBK0907
   SG-0816BBBK0909
   SG-1215BBBK1025
   SG-1215BBBK1743
   SG-1315BBBK0112
   SG-1315BBBK0139
   SG-1613BBBK0229
   SG-1613BBBK0241
   SG-1613BBBK0275
   SG-1613BBBK0284
   SG-1613BBBK0319
   SG-1613BBBK0429
   SG-1613BBBK2181
   SG-1613BBBK2198
   SG-1614BBBK1920
   SG-1716BBBK1423
   SG-1813BBBK3074
   SG-1814BBBK0000
   SG-1816BBBK2137
   SG-1915BBBK0215
   SG-2115BBBK0227
   SG-2115BBBK0361
   SG-2115BBBK0544
   SG-2313BBBK3402
   SG-2315BBBK2C08
   SG-2516BBBK055B
   SG-2614BBBK0831
   SG-2715BBBK0877
   SG-2715BBBK2776
   SG-2ADERPI213CF
   SG-3115BBBK1A2E
   SG-3214BBBK0619
   SG-3214BBBK6254
   SG-3214BBBK9102
   SG-3414BBBK1634
   SG-3615BBBK03B3
   SG-3B5DRPI3D814
   SG-4001BBBK1430
   SG-4001BBBK1980
   SG-4001BBBK2170
   SG-4002BBBK0560
   SG-4002BBBK0990
   SG-4005BBBK3850
   SG-4616BBBK2363
   SG-4815BBBK1147
   SG-4815BBBK20A0
   SG-5014BBBK16FA
   SG-5113BBBK0279
   SG-5113BBBK0382
   SG-5113BBBK1655
   SG-5113BBBK1899
   SG-5113BBBK2663
   SG-5113BBBK2790
   SG-5113BBBK2970
   SG-5113BBBK3063
   SG-5113BBBK3095
   SG-5113BBBK3117
   SG-5113BBBK3120
   SG-5113BBBK3123
   SG-5214BBBK08D8
   SG-5304RPI3AAED
   SG-6E1DRPI38E44
   SG-AC03RPI26DD9
   SG-EF34RPI2B402
   SG-F124RPI261F7
   SG-FC8FRPI235EA
   SG-F124RPI261F7
```

**Comment by denislepage** [comment]
The first 6 are already registered with different ID’s.

id            receiverID
830         LOTEK-D000442
890         LOTEK-D000440
911         LOTEK-223
913         LOTEK-D000439
914         LOTEK-D000441
915         LOTEK-153

For the others, registering also requires a unique sensor hash key as a minimum (something that may no longer be necessary, as this was meant to authenticate communications from receivers?). But of the 67 listed below, only 2 are not already in the database (SG-1814BBBK0000 and SG-4815BBBK1147) and one is listed twice (SG-F124RPI261F7), so this is likely the problem. I have seen the occasional duplicate errors coming in, but I couldn’t track it to a process causing it, so the API will need better handling, and the problem may also be that your queries are not returning those numbers for yet unknown reasons.

Can you try registering the 2 missing ones above and see if that works? You should only be able to do that once. If you don’t get an ID back, and can’t query it through the API, I can look them up for you.

5              SG-1613BBBK0275
6              SG-1613BBBK2198
48           SG-1614BBBK1920
68           SG-2313BBBK3402
70           SG-2614BBBK0831
82           SG-3214BBBK0619
110         SG-3214BBBK6254
138         SG-3214BBBK9102
140         SG-3414BBBK1634
162         SG-4001BBBK1430
175         SG-4001BBBK1980
178         SG-4001BBBK2170
210         SG-4002BBBK0560
238         SG-4005BBBK3850
255         SG-5113BBBK0382
271         SG-5113BBBK2663
309         SG-5113BBBK3063
320         SG-5113BBBK3095
332         SG-5113BBBK3117
334         SG-5113BBBK3120
335         SG-5113BBBK3123
657         SG-4002BBBK0990
676         SG-4815BBBK20A0
679         SG-5113BBBK1655
680         SG-5113BBBK1899
709         SG-0816BBBK0907
710         SG-0816BBBK0909
712         SG-1215BBBK1025
714         SG-1613BBBK0229
715         SG-1613BBBK0241
716         SG-1613BBBK0284
717         SG-1613BBBK0319
718         SG-1613BBBK0429
719         SG-1613BBBK2181
723         SG-1716BBBK1423
724         SG-1813BBBK3074
726         SG-1915BBBK0215
728         SG-2115BBBK0227
729         SG-2115BBBK0361
730         SG-2115BBBK0544
733         SG-2715BBBK0877
734         SG-2715BBBK2776
736         SG-3115BBBK1A2E
740         SG-5014BBBK16FA
779         SG-2315BBBK2C08
785         SG-5113BBBK0279
786         SG-5113BBBK2790
787         SG-5113BBBK2970
788         SG-1315BBBK0139
812         SG-5214BBBK08D8
813         SG-2ADERPI213CF
814         SG-EF34RPI2B402
839         SG-AC03RPI26DD9
849         SG-1816BBBK2137
850         SG-4616BBBK2363
855         SG-1315BBBK0112
867         SG-1215BBBK1743
882         SG-3615BBBK03B3
885         SG-6E1DRPI38E44
893         SG-3B5DRPI3D814
894         SG-5304RPI3AAED
909         SG-2516BBBK055B
935         SG-F124RPI261F7
936         SG-FC8FRPI235EA

**Comment by pmorrill** [comment]
Normally, registering an existing sensor should give an 'Already exists' error, but that does not always seem to be the case. I have managed to trace one possible source of the issue, which leads to 'Unknown server error' reports - which are not very helpful.

If you look at the proc (prInsertSensorsHashKeys), there is one branch of the logic that does not set the response variable at all. If that output var is not set the calling code bails and reports the 'Unknown server error' to the client.

In fact, that branch should look like this I think:

ELSE IF @receiver_type IS NOT NULL
      BEGIN
              if NOT EXISTS ( select receiver_type from lk_receiver_type where receiver_type = @receiver_type)
                    SET @response = 'invalid-receiver-type'
              else
              begin
                    update sensors_hash_keys set receiver_type = @receiver_type
                    where receiverID = @serial and secret_key = @key and receiver_type IS NULL
                    set @response = 'receiver-type-added'
              end
      END

I've tested this in my local system and it does solve at least one possible source of frustrations. But it should also be adjusted so that the block only executes IF the receiver_type field *does* need updating. If it already exists and is correct, then the generic SET @response = 'serial-exists' would be more appropriate.

**Comment by denislepage** [comment]
Right, I think we should assume that John is going to always try to register a receiver without having to check if it exists or not. That’s part of the automated process, so we have to be able to handle this without creating an insert error at our end.

I think my assumption early on was that that initial registration step for the deviceID was only going to be attempted once for new receivers.

The status message we return to John should be different, but a new registration and an existing registration should both return the deviceID. One could confirm successful registration and the other should say that this already exists, but for John’s purposes, the distinction between the 2 may not matter unless he is keeping a list at his end and needs to decide whether to add the new one to it or not.

What we would need to know however is how to handle cases where a registration tries to enter an existing serial number, but a different secret key. Presumably an error, that assumes that John keeps track of the list, as I initially expected.

That process of course is separate from the receiver registration with a project, which I am assuming currently requires a second API call. Not sure there is a need or interest in allowing the 2 things to happen in a single call (i.e. adding a project number parameter to the initial call that also provides the secret key unique to the receiver).

**Comment by jbrzusto** [comment]
Still not working:

```bash
curl --data-urlencode json="{\"serno\":\"Lotek-153\",\"date\":\"20171124134639\",\"fmt\":\"json\",\"login\":\"john\",\"pword\":\"XXX\",\"secretkey\":\"XXX\",\"receiverType\":\"LOTEKSRX800\"}" https://motus.org/api/receiver/register
```
=>
```json
{"version":"2.0","errorCode":"auth-error","errorMsg":"Missing authentication parameters"}
```
If I do exactly the same call as above to the api/user/validate, it works (to validate user), proving that
the error message is wrong.

This issue needs a much higher priority than it has been receiving.  There will be no data available from
the dataServer for any receiver which does not have a valid deviceID.  That is dozens of receivers.
Moreover, even the summary plots being generated by the old server for such receivers are being
misfiled because no deployment records are being returned for them by the list sensor deployments API entry.

**Comment by pmorrill** [comment]
I'm taking a look john. I had no idea this was still outstanding.

**Comment by pmorrill** [comment]
John: when I submit this package (using YOUR login and password) to the motus.org api I get a different error:

{"version":"2.0","errorCode":"unknown-error","errorMsg":"An unknown server error occurred"}

Can you try again and verify the error that you report above? The authentication error that you report makes no sense to me. The more likely issue is something in the proc that handles the insertion. I am looking into that until I hear back from you.

**Comment by jbrzusto** [comment]
Just retried with updated date field and the same result is returned, exactly as above.
And if I cursor up, replace "receiver/register" with "user/validate", and hit enter again, then it 
succeeds (as a user/validate call, of course).

**Comment by pmorrill** [comment]
John: it looks like this call needs a hash in the request. My client adds it in automatically. **If possible try adding "hash":"xxxxxxxxxxxxxx"**

where the hash value is
serno + '_' + date + '_' + sharedMasterKey

Note that since you have no secretKey for the device yet, the master key is used instead.

Adding this field (if possible) should get you past the auth-error response, and you will likely see 'unknown server error...' as I do.

I am trying to track that problem down.

**Comment by pmorrill** [comment]
BTW the comment above, when saved, was stripped of underscores. The hash is create from

concat (serno, underscore, date, underscore, masterkey)

**Comment by jbrzusto** [comment]
Sorry, thought we got rid of the hash requirement.  Regardless, trying it again using the same code
that has always generated that hash still gives me:

{"version":"2.0","errorCode":"auth-error","errorMsg":"Invalid authentication parameters"}

Moreover, trying against the v1.0 API gives a content-free reply, but with these headers:
```
HTTP/1.1 302 Found
Content-Length: 0
Location: https://motus.org/data/api/v1.0/registersensor.jsp
Server: Microsoft-IIS/7.5
X-Powered-By: ASP.NET
Date: Fri, 24 Nov 2017 16:58:35 GMT
```

**Comment by pmorrill** [comment]
We still require the hash, but certainly wold like to simplify when we have time.

All the same, note that you are getting a new error ('Invalid' as opposed to 'missing'). Can you post a specific request you send in?

**Comment by jbrzusto** [comment]
{"serno":"Lotek-153","hash":"9A0B8F1C6F6BABE1D4AB1CDDBA4C2D3B84A8DFA6","date":"20171124165845","fmt":"json","login":"john","pword":"X","secretKey":"X","receiverType":"LOTEKSRX800"}

gives the above error.

When I try using a separate "serno" field (the one involved in the hash of) and "serialNo" field (the one for the receiver being registered, which is how the v 1.0 API worked; i.e.:
curl -D - --data-urlencode json="{\"serno\":\"SG-0815BBBK1352\",\"hash\":\"AAA4112677C9435519698B6655ACEC105A2FF82E\",\"date\":\"20171124172546\",\"fmt\":\"json\",\"login\":\"john\",\"pword\":\"XXX\",\"secretKey\":\"D9D49670D4DA70357CA09F583F711D91E1A9CAC2\",\"receiverType\":\"SENSORGNOME\",\"serialNo\":\"Lotek-153\"}" https://motus.org/api/receiver/register
 I get this:
```
HTTP/1.1 500 Internal Server Error
Content-Length: 91
Content-Type: application/json;charset=UTF-8
Server: Microsoft-IIS/7.5
X-Powered-By: ASP.NET
Date: Fri, 24 Nov 2017 17:25:02 GMT

{"version":"2.0","errorCode":"unknown-error","errorMsg":"An unknown server error occurred"}
```
when I try the same thing against the old v1.0 API URL:
```
curl -D - --data-urlencode json="{\"serno\":\"SG-0815BBBK1352\",\"hash\":\"AAA4112677C9435519698B6655ACEC105A2FF82E\",\"date\":\"20171124172546\",\"fmt\":\"json\",\"login\":\"john\",\"pword\":\"XXX\",\"secretKey\":\"D9D49670D4DA70357CA09F583F711D91E1A9CAC2\",\"receiverType\":\"SENSORGNOME\",\"serialNo\":\"Lotek-153\"}" https://motus.org/data/api/v1.0/registersensor.jsp
```
I get apparent success:
```
HTTP/1.1 200 OK
Content-Length: 10
Content-Type: application/json;charset=UTF-8
Server: Microsoft-IIS/7.5
Set-Cookie: JSESSIONID=5ACC59308338BE98442E2F65504D1E28; Path=/; Secure; HttpOnly
X-Powered-By: ASP.NET
Date: Fri, 24 Nov 2017 17:26:50 GMT
```
But no deviceID is returned by the API, and when I subsequently call the list_sensors or list_sensor_deps APIs, the receiver "Lotek-153" is still not present.

**Comment by pmorrill** [comment]
Here is where we seem to have arrived:

1. the receiver/register call still requires the "hash" parameter as did the v1 call. This may change in future (we have dropped the hash requirement for many of the calls in v2 - see below re documentation)

2. There is a problem in the api that calls the PROC to insert, and this is our fault on our side: miscommunication or my forgetfulness. One way or the other. I have just checked in a fix for this problem in beta code. This is what leads to the 'Unknown server error' response you see above.

3. In v2.0, the hash that you create needs to be based on the serno you are registering ("Lotek-153" in this case). I don't understand where the SENSORGNOME (SG) serNo comes in at all.

4. I am going to set up a git doc to transfer the notes on v2 to a common location, so we can track changes more easily. I'll be verifying the content as I move existing notes into that location. This will take a little time to get in place.

**Comment by jbrzusto** [comment]
Client code changes to match this calling convention committed as [d2b1e50a32](https://github.com/jbrzusto/motusServer/commit/d2b1e50a32ae26e38a15711e35a990fbf352371c).

**Comment by jbrzusto** [comment]
Still not working with this payload:
```json
{
   "serno": "Lotek-153",
   "hash": "87207D1CFAE431108347C633517B0106EBD943CE",
   "date": "20171128181417",
   "fmt": "json",
   "login": "john",
   "pword": "XXX",
   "secretKey": "D9D49670D4DA70357CA09F583F711D91E1A9CAC2",
   "receiverType": "LOTEKSRX800"
}
```
=>
```json
{"version":"2.0","errorCode":"auth-error","errorMsg":"Invalid authentication parameters"}
```
(I will generate a new secret key for this receiver once this is working)

**Comment by jbrzusto** [comment]
Looks like the hash on your side was being calculated with the natural-cased serial number
"Lotek-153", while the 1.0 API (and my client) used the upper-cased version "LOTEK-153".

Regardless, I can confirm this now works for a new receiver on the beta server.
Please delete the fake "SG-FFFFRPI3FFFF" (deviceID = 947) that I just tested with.

**Comment by pmorrill** [comment]
I am happy to switch to an upper case version of the recv id when creating the hash: not sure why this changed. It makes sense to standardize to ucase, so I will look at that.

**Comment by cjardine-bsc** [comment]
Device ID 947 has been deleted.
