### ISSUE TITLE
Need tool so motus staff can set temporary web notifications for users in various places

### ISSUE THREAD

**Issue by denislepage** [MotusDev/Motus-TO-DO#557]
We need a list of places where this could make sense, but this probably should be database driven and available to be triggered under the admin tools. It could be a customizable text fragment that gets inserted say at the top of the main project page, or on the upload page, that warns users about ongoing issues or problems, for instance.

Say the upload page looks for the value of a text fragment called "txUserNotificationUpload". If the current text is missing or null, no message is displayed. 

We'd then need a page that allows admins to easily find and edit the possible notifications and makes sure that the fragment object is updated.

Something like that.

**Comment by cjardine-bsc** [comment]
Paul, if I recall correctly I owe you a DB table for this. 

id int
message nvarchar(max)
message_fr nvarchar(max)
time_start datetime
time_end datetime
user_id int
page lookup to a table describing which page-groups it will apply to

We'll then need a lk_page table with a few options. Lucas can you suggest some logical groupings?

Anything else?

**Comment by pmorrill** [comment]
This is a beta10 item, so less urgent than the launch (lunch) tasks. I think that we will want to target pages as logical groups, but also as individual pages. The latter can be done using the specific page servlet context string (e.g.: '/project/tags/template'), rather than from a lookup table. However, we may need to consider support for an array of such page contexts?

**Comment by denislepage** [comment]
Moving to the "ideas" project and closing for now.
