### ISSUE TITLE
list of dual mode sensor gnomes

### ISSUE THREAD

**Issue by denislepage** [MotusDev/Motus-TO-DO#558]
This is the list of dual mode sensor gnomes using the dongle and the version of the software that mixes the 2 types of tags in the same files. Those have to be scanned individually for new data. They are maintained in motus_sandbox.dbo.sensor_dual_mode_temp for the moment, and this is the table the reading script relies on (the date last_checked is the most recent file found for each).

receiverID
SG-1215BBBK1174
SG-1234BBBK5678
SG-1234RPI35678
SG-1914BBBK0855
SG-1914BBBK0893
SG-26D1RPI3534C
SG-2712BB000003
SG-2712BB000151
SG-2916BBBK0723
SG-3114BBBK2156
SG-3114BBBK2178
SG-3114BBBK2277
SG-3214BBBK0604
SG-3214BBBK1004
SG-4001BBBK2220
SG-4116BBBK0351
SG-5113BBBK2969
SG-5C53RPI33F6B
SG-621DRPI38D78
SG-732ARPI38C19
SG-B2A0RPI391E2
SG-BFEBRPI34958
SG-C440RPI3A81A

**Comment by StuMackenzie** [comment]
Expected data from Winkler projects (tag file in email) is on: 
SG-1914BBBK0893
SG-1914BBBK0855

**Comment by denislepage** [comment]
We don't have a good number of the TRES tags from 2019, but I think we have all the others at least in the tags table (some details may be missing on metadata particularly - to check). 

The few that we have I expect where registered as part of the data processing input, so they'll still need to be tied to a project. The sooner we can add them to the list of valid tags and/or update their details, the better.

The detections for those 2 receivers (and the others) should be available from the sandbox R package already and soon from beta and live.

**Comment by StuMackenzie** [comment]
We'll upload the metadata and see what comes out the other end.

**Comment by cjardine-bsc** [comment]
On it.

**Comment by jsayers-bsc** [comment]
Below is a list of SG receiver deployments that have either a CTT or XCVR dongle. This list includes many, but not all, of those that Denis listed previously. And there are some in Denis's list that don't show up in this query based on their dongle type. I'm not sure if those receivers that only have funcubes can actually be collecting CTT tag data, or maybe the deployment metadata is incorrect? 

drop table if exists #dualmode

select receiverID, b.[name] , project_id, b.dt_start, b.dt_end into #dualmode from sensor_antennas a
left join sensor_deployments b on b.id = a.deployment_id
left join sensors c on c.id	= b.sensor_id
where (a.dongle_type like '%CTT%' OR a.dongle_type like 'XCVR')
	and receiverID like 'SG%'
group by receiverID, b.[name],  b.dt_start, b.dt_end, project_id
order by project_id

select * from #dualmode


receiverID | name | project_id | dt_start | dt_end
-- | -- | -- | -- | --
SG-0FBARPI359DA | Holiday Beach | 1 | 2020-03-01 00:00:00.0000000 +00:00 | NULL
SG-0FBARPI359DA | Test-RPI359DA | 1 | 2019-11-05 00:00:00.0000000 +00:00 | 2019-12-01 23:59:00.0000000 +00:00
SG-1253RPI32253 | Hentz | 1 | 2020-12-09 15:00:00.0000000 +00:00 | NULL
SG-1253RPI32253 | Killbear | 1 | 2020-10-05 00:00:00.0000000 +00:00 | 2020-11-04 21:00:00.0000000 +00:00
SG-1ACBRPI38EBA | Point Pelee | 1 | 2020-08-04 01:00:00.0000000 +00:00 | NULL
SG-3214BBBK8447 | Test-BBK8447 | 1 | 2020-09-23 00:00:00.0000000 +00:00 | NULL
SG-4000BBBK9640 | Test-BBBK9640 | 1 | 2019-11-05 00:00:00.0000000 +00:00 | 2020-01-01 23:59:00.0000000 +00:00
SG-5113BBBK2799 | Test-BBBK2799 | 1 | 2019-11-05 00:00:00.0000000 +00:00 | 2019-12-20 00:00:00.0000000 +00:00
SG-6159RPI3A6F5 | Alderville | 1 | 2020-10-14 13:00:00.0000000 +00:00 | NULL
SG-6159RPI3A6F5 | Turkey Point | 1 | 2020-07-02 12:00:00.0000000 +00:00 | 2020-08-20 23:59:00.0000000 +00:00
SG-6D9DRPI38AFF | Sandbanks | 1 | 2020-03-09 00:00:00.0000000 +00:00 | NULL
SG-76A4RPI35380 | Maple Leaf | 1 | 2020-06-09 00:00:00.0000000 +00:00 | 2021-03-21 23:59:00.0000000 +00:00
SG-76A4RPI35380 | Test-RPI35380 | 1 | 2020-01-15 00:00:00.0000000 +00:00 | 2020-06-08 00:00:00.0000000 +00:00
SG-9006RPI3CE4D | Test-RPI3CE4D | 1 | 2020-02-10 20:00:00.0000000 +00:00 | NULL
SG-91EBRPI3E583 | Alderville | 1 | 2019-11-25 16:00:00.0000000 +00:00 | 2020-10-14 16:00:00.0000000 +00:00
SG-91EBRPI3E583 | Test-RPI3E583 | 1 | 2019-11-05 00:00:00.0000000 +00:00 | 2019-11-25 00:00:00.0000000 +00:00
SG-A0CFRPI3F8E7 | Darlington | 1 | 2020-09-22 00:00:00.0000000 +00:00 | NULL
SG-A0CFRPI3F8E7 | Test-RPI3F8E7 | 1 | 2020-07-13 00:00:00.0000000 +00:00 | 2020-09-21 23:50:00.0000000 +00:00
SG-A6B8RPI388E1 | Russell Reid PS | 1 | 2020-02-24 15:01:00.0000000 +00:00 | NULL
SG-AB4DRPI3E6A8 | Lennox OPG | 1 | 2020-10-23 00:00:00.0000000 +00:00 | NULL
SG-D2D4RPI32C60 | Test-RPI32C60 | 1 | 2020-02-01 00:00:00.0000000 +00:00 | 2020-10-21 00:00:00.0000000 +00:00
SG-D6AFRPI35189 | Grundy | 1 | 2020-11-04 15:00:00.0000000 +00:00 | NULL
SG-D6AFRPI35189 | Test-35189 | 1 | 2020-10-20 00:00:00.0000000 +00:00 | 2020-11-03 23:59:00.0000000 +00:00
SG-1315BBBK0083 | Pte-Moreault | 3 | 2019-07-16 09:00:00.0000000 +00:00 | 2019-11-19 23:59:00.0000000 +00:00
SG-433CRPI3B3B3 | Office, Cape Romain NWR, SC | 4 | 2020-09-15 19:45:00.0000000 +00:00 | NULL
SG-2916BBBK0723 | Gold Head Branch SP 2 | 19 | 2017-10-05 18:41:00.0000000 +00:00 | NULL
SG-2920RPI32323 | TEST | 19 | 2021-02-09 14:00:00.0000000 +00:00 | NULL
SG-3114BBBK2156 | LowerSuwanee 2 | 19 | 2017-10-05 14:58:00.0000000 +00:00 | NULL
SG-3114BBBK2178 | PaynesPrairie 2 | 19 | 2017-10-05 18:38:00.0000000 +00:00 | 2021-02-09 12:00:00.0000000 +00:00
SG-3114BBBK2277 | DunnsCreek 2 | 19 | 2017-10-05 16:40:00.0000000 +00:00 | NULL
SG-3114BBBK2336 | Faver-Dyke2 | 19 | 2018-01-06 12:00:00.0000000 +00:00 | 2018-05-08 12:00:00.0000000 +00:00
SG-4116BBBK0351 | Watermelon Pond WMA 2 | 19 | 2017-10-05 17:09:00.0000000 +00:00 | NULL
SG-0E38RPI3CAD0 | PARC Honey Hut | 35 | 2020-03-18 13:02:00.0000000 +00:00 | 2020-12-14 19:41:00.0000000 +00:00
SG-1215BBBK1794 | PARC Honey Hut | 35 | 2020-03-18 13:00:00.0000000 +00:00 | 2020-03-18 13:01:00.0000000 +00:00
SG-1234RPI35678 | Assateague Test Tower | 48 | 2019-03-01 00:00:00.0000000 +00:00 | 2019-07-23 23:59:00.0000000 +00:00
SG-26D1RPI3534C | Ford Island | 48 | 2019-05-30 22:05:00.0000000 +00:00 | NULL
SG-2914BBBK0347 | Marshlands 2 | 48 | 2018-05-10 12:10:00.0000000 +00:00 | 2019-08-02 23:59:00.0000000 +00:00
SG-5C53RPI33F6B | Summit | 48 | 2019-05-30 00:59:00.0000000 +00:00 | NULL
SG-621DRPI38D78 | Mt. Davis | 48 | 2019-04-23 17:00:00.0000000 +00:00 | NULL
SG-732ARPI38C19 | Assateague State Park | 48 | 2018-12-27 00:00:00.0000000 +00:00 | 2019-04-19 14:30:00.0000000 +00:00
SG-7A74RPI30932 | Poplar Island Cell 2 Dike | 48 | 2020-07-27 12:00:00.0000000 +00:00 | 2020-10-22 23:59:00.0000000 +00:00
SG-B2A0RPI391E2 | SGL 74 | 48 | 2019-05-31 22:54:00.0000000 +00:00 | NULL
SG-BFEBRPI34958 | Plumer | 48 | 2019-06-17 17:31:00.0000000 +00:00 | NULL
SG-C440RPI3A81A | Wopsy | 48 | 2019-05-28 16:25:00.0000000 +00:00 | NULL
SG-0816BBBK0241 | Matagorda | 120 | 2017-11-02 00:00:00.0000000 +00:00 | NULL
SG-3116BBBK0755 | Port O'Connor | 120 | 2017-12-28 00:00:00.0000000 +00:00 | NULL
SG-2712BB000003 | Maraca | 124 | 2018-12-05 08:00:00.0000000 +00:00 | NULL
SG-2712BB000151 | Apeu | 124 | 2018-12-17 12:00:00.0000000 +00:00 | NULL
SG-3DC6RPI3B9EE | Pozo Colorado - Ruta 5 | 125 | 2020-12-13 09:30:00.0000000 +00:00 | NULL
SG-1914BBBK0855 | Morgan Rd. Office 1 | 152 | 2017-09-26 09:30:00.0000000 +00:00 | NULL
SG-1914BBBK0893 | MontezumaNWR#1 | 152 | 2017-10-12 00:00:00.0000000 +00:00 | NULL
SG-C6B8RPI367F8 | El Jaguar | 258 | 2020-01-17 22:00:00.0000000 +00:00 | NULL
SG-4804RPI3D20C | Chestnut 2 | 290 | 2020-10-09 15:00:00.0000000 +00:00 | 2020-10-09 23:59:00.0000000 +00:00
SG-932ERPI37889 | Nemours Wildlife Foundation_ACE Basin_SC | 376 | 2021-02-01 17:00:00.0000000 +00:00 | NULL

It appears that there is CTT tag data for only 3 of these receivers based on det_batches_runs_tags -- just a few hundred runs dating back to 2020 and 2019s. And in each case only from before the start of the deployment (and with the receiver considered Project 0?). I'm not positive that's the best place/way to look for this but you'd think there would be more runs with CTT tags by now since these detection data has apparently been coming over from CTT for a few weeks now.... 

select top 1000 
	a.batchID, 
	a.runID, 
	dbo.ts2datetime(b.tsBegin) as ts_Begin,
	[source], 
	motusDeviceID,
	receiverID,
	b.projectID as receiver_project_I_think,
	c.id as tag_id,
	mfg_id,
	c.project_id as tag_project
	from det_batches_runs_tags a
left join det_batches b on b.batchID = a.batchID
left join tags c on c.id = a.motusTagID
left join sensors_hash_keys d on d.id = b.motusDeviceID 
where receiverID in 
(select distinct(receiverID) from #dualmode)
and manufacturer = 'CTT'
order by tsBegin desc

This still doesn't address the question of software version -- how many of these SG's are running the older software patch that lumps all tag data into one file. I do know that most if not all of the Project 1 receivers have the newer software...

**Comment by denislepage** [comment]
You should make sure to run your det table queries on sandbox. It should have all the data backlog now. Sandbox won't have the most recent metadata though, so those should still be run on live.

**Comment by denislepage** [comment]
This takes a little while to run (10 minutes), but it integrates data on sandbox with your top table on deployments (in live). It may be worth adding the receivers below that do not have hits to the manual scanning list (no data in min/max hits).

use motus
GO

WITH CTE AS (
select b.id, receiverID, b.name, project_id, b.dt_start, b.dt_end from sensor_antennas a WITH(NOLOCK)
left join sensor_deployments b  WITH(NOLOCK) on b.id = a.deployment_id
left join sensors c  WITH(NOLOCK) on c.id = b.sensor_id
where (a.dongle_type like '%CTT%' OR a.dongle_type like 'XCVR')
and receiverID like 'SG%'
group by b.id, receiverID, b.[name], b.dt_start, b.dt_end, project_id
)
select b.id,
receiverID, b.name, project_id, b.dt_start, b.dt_end,
dbo.ts2datetime(MIN(a.ts)) as min_hit, dbo.ts2datetime(MAX(a.ts)) as max_hit from motus_sandbox.dbo.det_taghits_deploy_id a  WITH(NOLOCK)
right join motus_sandbox.dbo.det_batches c on a.batchID = c.batchID and c.source = 'ctt'
right join CTE b on a.recvDeployID = b.id
group by b.id, receiverID, b.name, project_id, b.dt_start, b.dt_end


id

receiverID

name

project_id

dt_start

dt_end

min_hit

max_hit

4286

SG-1914BBBK0855

Morgan Rd. Office 1

152

2017-09-26

2017-11-20

2020-04-10

4319

SG-3114BBBK2156

LowerSuwanee 2

19

2017-10-05

2018-01-12

2020-06-03

4320

SG-3114BBBK2178

PaynesPrairie 2

19

2017-10-05

2021-02-09

2018-01-06

2019-05-08

4321

SG-3114BBBK2277

DunnsCreek 2

19

2017-10-05

2018-01-12

2019-05-29

4322

SG-2916BBBK0723

Gold Head Branch SP 2

19

2017-10-05

2018-01-10

2019-02-09

4323

SG-4116BBBK0351

Watermelon Pond WMA 2

19

2017-10-05

2018-04-30

2019-01-24

4340

SG-1914BBBK0893

MontezumaNWR#1

152

2017-10-12

2017-11-10

2019-09-22

4379

SG-0816BBBK0241

Matagorda

120

2017-11-02

4451

SG-3116BBBK0755

Port O'Connor

120

2017-12-28

4465

SG-3114BBBK2336

Faver-Dyke2

19

2018-01-06

2018-05-08

2018-01-16

2018-01-19

4722

SG-2914BBBK0347

Marshlands 2

48

2018-05-10

2019-08-02

5045

SG-732ARPI38C19

Assateague State Park

48

2018-12-27

2019-04-19

5072

SG-2712BB000003

Maraca

124

2018-12-05

5073

SG-2712BB000151

Apeu

124

2018-12-17

5217

SG-621DRPI38D78

Mt. Davis

48

2019-04-23

5221

SG-1234RPI35678

Assateague Test Tower

48

2019-03-01

2019-07-23

5319

SG-5C53RPI33F6B

Summit

48

2019-05-30

5320

SG-26D1RPI3534C

Ford Island

48

2019-05-30

5321

SG-B2A0RPI391E2

SGL 74

48

2019-05-31

5330

SG-BFEBRPI34958

Plumer

48

2019-06-17

5331

SG-C440RPI3A81A

Wopsy

48

2019-05-28

5578

SG-4804RPI3D20C

Chestnut 2

290

2020-10-09

2020-10-09

5709

SG-1315BBBK0083

Pte-Moreault

3

2019-07-16

2019-11-19

5776

SG-4000BBBK9640

Test-BBBK9640

1

2019-11-05

2020-01-01

5777

SG-0FBARPI359DA

Test-RPI359DA

1

2019-11-05

2019-12-01

2019-11-08

2019-12-01

5778

SG-5113BBBK2799

Test-BBBK2799

1

2019-11-05

2019-12-20

5779

SG-91EBRPI3E583

Test-RPI3E583

1

2019-11-05

2019-11-25

2019-11-06

2019-11-18

5822

SG-91EBRPI3E583

Alderville

1

2019-11-25

2020-10-14

5897

SG-C6B8RPI367F8

El Jaguar

258

2020-01-17

5914

SG-9006RPI3CE4D

Test-RPI3CE4D

1

2020-02-10

2020-02-10

2020-02-12

5924

SG-A6B8RPI388E1

Russell Reid PS

1

2020-02-24

5926

SG-D2D4RPI32C60

Test-RPI32C60

1

2020-02-01

2020-10-21

5942

SG-6D9DRPI38AFF

Sandbanks

1

2020-03-09

5980

SG-1215BBBK1794

PARC Honey Hut

35

2020-03-18

2020-03-18

5982

SG-0E38RPI3CAD0

PARC Honey Hut

35

2020-03-18

2020-12-14

6005

SG-76A4RPI35380

Test-RPI35380

1

2020-01-15

2020-06-08

6011

SG-0FBARPI359DA

Holiday Beach

1

2020-03-01

6073

SG-76A4RPI35380

Maple Leaf

1

2020-06-09

2021-03-21

6114

SG-6159RPI3A6F5

Turkey Point

1

2020-07-02

2020-08-20

6117

SG-A0CFRPI3F8E7

Test-RPI3F8E7

1

2020-07-13

2020-09-21

6167

SG-7A74RPI30932

Poplar Island Cell 2 Dike

48

2020-07-27

2020-10-22

6197

SG-1ACBRPI38EBA

Point Pelee

1

2020-08-04

7305

SG-433CRPI3B3B3

Office, Cape Romain NWR, SC

4

2020-09-15

7316

SG-A0CFRPI3F8E7

Darlington

1

2020-09-22

7320

SG-3214BBBK8447

Test-BBK8447

1

2020-09-23

7334

SG-1253RPI32253

Killbear

1

2020-10-05

2020-11-04

7372

SG-6159RPI3A6F5

Alderville

1

2020-10-14

7399

SG-D6AFRPI35189

Test-35189

1

2020-10-20

2020-11-03

7434

SG-D6AFRPI35189

Grundy

1

2020-11-04

7446

SG-AB4DRPI3E6A8

Lennox OPG

1

2020-10-23

7472

SG-1253RPI32253

Hentz

1

2020-12-09

7480

SG-3DC6RPI3B9EE

Pozo Colorado - Ruta 5

125

2020-12-13

7532

SG-932ERPI37889

Nemours Wildlife Foundation_ACE Basin_SC

376

2021-02-01

7533

SG-2920RPI32323

TEST

19

2021-02-09


There are also 6 SG receivers for which we have CTT data, but that are not in the list above, so the metadata is likely incomplete. This is limited only to receivers where CTT hits were seen.

select b.receiverID, dbo.ts2datetime(MIN(tsBegin)), dbo.ts2datetime(MAX(tsEnd)) from motus_sandbox.dbo.det_batches a inner join motus_sandbox.dbo.sensors_hash_keys b on a.motusDeviceID = b.id
where a.source = 'CTT' and b.receiverID like 'SG%' and a.numHits > 0
group by b.receiverID

receiverID

min

max

metadata

SG-1215BBBK1174

2018-05-12

2018-11-11

Not found

SG-4116BBBK0351

2018-04-30

2019-01-25

SG-3214BBBK1004

2017-06-06

2018-09-03

Not found

SG-3114BBBK2336

2018-01-16

2018-01-20

SG-3114BBBK2178

2018-01-06

2019-05-09

SG-9006RPI3CE4D

2020-02-10

2020-02-12

SG-1914BBBK0855

2017-11-20

2020-04-11

SG-2916BBBK0723

2018-01-10

2019-02-09

SG-3114BBBK2277

2018-01-12

2019-05-30

SG-1914BBBK0893

2017-11-10

2019-09-23

SG-0FBARPI359DA

1970-01-01

2019-12-01

SG-1ACBRPI38EBA

2019-12-20

2020-04-09

SG-5113BBBK2969

2018-05-20

2019-05-14

Not found

SG-7A74RPI30932

2020-07-14

2020-07-14

SG-FC39RPI398F9

2000-01-01

2000-01-12

Not found

SG-91EBRPI3E583

2019-11-06

2019-11-18

SG-3114BBBK2156

2018-01-12

2020-06-04

SG-3214BBBK0604

2018-05-16

2019-05-05

Not found

SG-4001BBBK2220

2018-05-15

2018-09-02

Not found



There are some 8 more cases where they have detected no data.

select b.receiverID, dbo.ts2datetime(MIN(tsBegin)), dbo.ts2datetime(MAX(tsEnd)) from motus_sandbox.dbo.det_batches a inner join motus_sandbox.dbo.sensors_hash_keys b on a.motusDeviceID = b.id
where a.source = 'CTT' and b.receiverID like 'SG%' ---and a.numHits > 0
group by b.receiverID

**Comment by jsayers-bsc** [comment]
Right, the sandbox. Is is just because this is dual-mode CTT data that Sandbox is ahead of Live? I'm not entirely clear on how those two databases related to each other...

**Comment by denislepage** [comment]
Dual mode files only exist in sandbox for now until we can deploy at least the motus-base/org/bsc/process classes in beta.

But metadata should be most up to date in motus, so you need to check on both databases.

**Comment by jsayers-bsc** [comment]
Re file format for older CTT compatibility patches... 

This deployment (https://motus.org/data/receiverDeployment?id=7625) was on for a few days collecting and uploading CTT data using the 2018 patch (the newer one doesn't actually work).

This is the naming scheme for CTT data files: `Prince Edward Point-5113BBBK2799-003013-2021-04-02T14-18-24.3850T-lifetag.csv.gz`

Is the file format collected by these something we can work with, or are already looking for? Just wondering whether we can recommend using this patch to make BB dual-mode, or whether we have to go back to CTT to fix whatever issue causes the newer patch not to work.

**Comment by leberrigan** [comment]
@denislepage Can we close?

**Comment by denislepage** [comment]
Yup. As far as I can tell, we haven't seen any data from dual mode receivers using the old format in quite some time. The scripts that checks in the data files was turned off some months ago. There are still outstanding issues regarding dual mode data, but different from this thread.
