### ISSUE TITLE
Missing antenna number in beta

### ISSUE THREAD

**Issue by denislepage** [MotusDev/Motus-TO-DO#566]
In the receiver deployment page, I noticed earlier today with Josh that antenna numbers are not longer showing in the beta version. Things are fine in sandbox and live.

https://beta.motus.org/data/receiver/deployment/edit?projectID=2&id=703&projectID=2&id=703

![image](https://user-images.githubusercontent.com/21110542/65808909-d865af80-e165-11e9-8452-209d68b56865.png)

**Comment by cjardine-bsc** [comment]
I think this is expected until we update that field in the live database. It's currently one of the things that is out of sync because making the change would break the live pages. 

I have this included in the scripting that needs to happen before we launch beta9 (at least it will be included once I can get back in the database!)

**Comment by pmorrill** [comment]
This should be ok now. Maybe @jsayers-bsc could check it in Live then mark this closed?
