### ISSUE TITLE
Noah Perlut Project 104  - tag registrations missing

### ISSUE THREAD

**Issue by StuMackenzie** [MotusDev/Motus-TO-DO#573]
Follow up on tag registrations to project 104 within https://github.com/MotusDev/Motus-TO-DO/issues/554

**Comment by StuMackenzie** [comment]
Related to issue#

First, a few of the tags that I sent you are not up on my page (these do not include the two that you said were bad recordings).  These include tags: 101, 102, 105, & 110.  Any thoughts on what happened to these?  Second, the tag registration page is not working so I sent in a few more (n=4) via a file share.

**Comment by Hussell** [comment]
I see all of those tags on his page. I'm assuming he's looking at https://motus.org/data/project/tags?projectID=104 or https://motus.org/data/projectTags?id=104

Also, tag registration is working for everyone else, and I'm not seeing any uploaded files for project 104 since the previous tag registration, so a description of the actions being taken, with URLs, is necessary before I can assist.

**Comment by StuMackenzie** [comment]
Sorry - didn't have time to look into it before I posted. Followed up. I suspect he may have not selected 'see all tags in this view'

**Comment by StuMackenzie** [comment]
Collaborator submitted 4 new registrations last week that are not showing up ? Did we receive any? I think this should include 107 and 108 which are missing from the last batch of registrations.

**Comment by Hussell** [comment]
I don't see any new uploads for project 104, nor do I see any new tags in the table on their tag management page.

**Comment by StuMackenzie** [comment]
re-uploaded missing tags and issue reconciled.
