### ISSUE TITLE
Project 103 Tag registration issue

### ISSUE THREAD

**Issue by StuMackenzie** [MotusDev/Motus-TO-DO#576]
Collaborator recently  registered 8 nanotags for AMKE. Tag 162 uploaded with an incorrect burst interval. The interval should be 7.1s but was registered at 14.2, so it seems one of the bursts was missed.  All others look ok.

Josh has recordings of 162 if they should be re-run.

**Comment by leberrigan** [comment]
The recording quality seemed  a bit poor so I tried a few things to see if that impeding tag finder’s ability to detect a signal:

1.	Truncated the recording so it only included 3 tag ID pulses (removing the ‘off’ blip at the end).
2.	Silenced the background noise by reducing the amplitude between bursts
3.	Amplified the signal of the individual pulses

But no dice… I keep getting the error ‘Only 1 detection of id 162 found in file tag162.wav, so I can't estimate burst interval’.

The strange thing is that I also measured the interval between each pulse within a burst and got a consistent number:
-	0.057 s between pulses 1 and 2
-	0.054 s between pulses 2 and 3
-	0.127 s between pulses 3 and 4

So why can’t it recognize the other bursts?

Looking closer at each pulse, they aren’t very ‘clean’ sinusoids – the period seems to broaden near the end of the pulse.

Below are screenshots from Audacity of each pulse within a burst (in sequence) stacked on top of each other for comparison.

### **Tag 162, Burst 1**
![tag162_burst1](https://user-images.githubusercontent.com/35931796/67123683-67933f80-f1c7-11e9-8b41-5d5b13cba734.png)

### **Tag 162, Burst 2**
![tag162_burst2](https://user-images.githubusercontent.com/35931796/67123714-7c6fd300-f1c7-11e9-8b76-29036f74d771.png)


---
In comparison, see a 'normal' tag that uploaded without issue (from project 259).
###**Tag 169, Burst 1**
![tag169_burst1-proj259](https://user-images.githubusercontent.com/35931796/67123741-901b3980-f1c7-11e9-9615-6499b048773e.png)

**Comment by denislepage** [comment]
There’s a note in the archive instructions that talk about wonky pulses. Not sure if this is pertinent.

https://archived.sensorgnome.org/VHF_Tag_Registration/

Beware of Bad Pulses (SensorGnome users only)
[Edit section]<https://archived.sensorgnome.org/VHF_Tag_Registration/>

The registration procedure is usually straightforward, but occasionally, the match between the tag's
actual transmit frequency and the listen frequency on the funcubedongle is too(!) good, which can lead
to wonky-looking pulses because the funcubedongle has trouble staying locked on the tag's frequency
(this issue is not unique to the funcubedongle).
The symptom is pulses with missing top or bottom legs, such as the second in this burst:

[tag_registration_showing_bad_pulse.png]<https://archived.sensorgnome.org/@api/deki/files/12/=tag_registration_showing_bad_pulse.png>

If you see this, try re-tuning the funcubedongle frequency to 2 kHz (rather than 4kHz)
below the nominal tag frequency (e.g. 166.378 MHz for a nominal 166.380 MHz), then re-record
the bursts.  Repeat this procedure in 2 kHz steps until you get a set of bursts with symmetric
spikes for all pulses.
Make note of this by changing the filename so it includes a '@FFF.FFF<mailto:%27@FFF.FFF>' portion indicating
the frequency to which the funcube was tuned when you recorded the tag.  e.g.:
If the original name would have been:

tag435.wav

then the new name should be:

tag435@166.378.wav

to indicate that the funcube was tuned to 166.378 when the tag was re-recorded.  Without the
  @FFF.FFF portion, it is assumed the funcube was tuned 4kHz below the nominal tag frequency.

**Comment by Hussell** [comment]
Josh managed to successfully register tag 162 as 162.4. There are tags 162, 162.1, and 162.2 in the system. I guess they should be deleted?

**Comment by cjardine-bsc** [comment]
I have merges the three incorrect tags into 43105

**Comment by jsayers-bsc** [comment]
So were there two issues here? — an issue with the recording, and another error that occurred while uploading the most recent edit?

The last version I submitted was an edited version of the second recording, where I clipped out the first burst (which visually seemed to have a 5th pulse in one of the bursts). I feel like I already did that though on one of the earlier upload attempts (though maybe it was the first one that I edited).

I wonder how frequently such a burst aberration occurs (assuming that’s what happened), either in this tag or in tags generally…

**Comment by leberrigan** [comment]
I think the original recording was initially too messy for tag finder to pick anything out. I clipped out all but three bursts which ended up having only 1 that could be decoded by tag finder. Perhaps it was just a matter of selecting the three best bursts and I just picked the wrong ones?

It would be good to get our hands on one of these tags to see what's actually happening. It's either the receiver or the transmitter that's causing the issue.

In terms of the merging tags, that's just what we do when there are duplicate tags registered to a project (instead of deleting anything).

**Comment by jsayers-bsc** [comment]
She actually recorded these with a Lotek receiver.

I am noticing now that it is explicitly stated here<https://archived.sensorgnome.org/VHF_Tag_Registration/> that registration with Lotek receivers is not supported. So clearly it can work, but not reliably. Question is whether it would have any effect on the detectability of those tags later. I tend to think not, but if the recording was made using a different system than the one that will be listening for it, then perhaps.
