### ISSUE TITLE
timezone offsets (again)

### ISSUE THREAD

**Issue by steffilazerte** [MotusDev/Motus-TO-DO#581]
I've been adding information regarding the `utcOffsets` to the motus R book and it has me thinking.

To match hits to a receiver in the `alltags` view, timestamps from the `hits` table are compared to `tsStart` and `tsEnd` from the `recvDeps` table: If the timestamp is between the start and end times, it is assigned to that receiver.

From what @denislepage said [here](https://github.com/MotusDev/Motus-TO-DO/issues/478#issuecomment-533743571), `tsStart` and `tsEnd` in the `recvDeps` table are not affected by any timezone offsets.

Therefore, if there is an incorrect timezone (i.e. `utcOffset` is not NA/NULL) then the `ts` from `hits` is in a different timezone than the `tsStart` and `tsEnd` from `recevDeps`, right? This probably wont affect many hits, but it will affect ones near the end points.

Soooooo:

Should the hits be assigned a receiver by going through the batches table? ie. by batchID, rather than by timestamp? A hit belongs to a batch, and a batch belongs to a receiver, right?

Am I making any sense?

**Comment by leberrigan** [comment]
Most of this is above me, but I thought I should add that `tsStart` and `tsEnd` are set by users when they start and end receiver deployments. While we emphasize these times should be in UTC, I know this hasn't always been followed so they can potentially be in local times.

**Comment by denislepage** [comment]
I have posted some notes earlier today about a possible way to address this at the source (#591). If that works, we can probably manually correct all data we have in our database rather than ask users to do so or assign this to the R package.

I’d suggest we put this one on pause for now until we sort this out.

We will still need to create a proc in sql server to apply the correction for affected data imported before we had the exception in place in sgdata, but I’d also wait to confirm that my idea will work to see which way we go.

**Comment by steffilazerte** [comment]
Even better!

**Comment by steffilazerte** [comment]
@denislepage is this something we've got a handle on? What is the status of ts corrected UTC offsets?

**Comment by denislepage** [comment]
I’ve lost track, to be honest.
