### ISSUE TITLE
Output products not included in recent data upload email notifications

### ISSUE THREAD

**Issue by jsayers-bsc** [MotusDev/Motus-TO-DO#587]
The notification email for the last several data uploads I've made has not included the usual products list (plots, rds file, etc).

Below is an example.

![image](https://user-images.githubusercontent.com/55001144/67490124-bb2ae080-f640-11e9-915e-80171d63360e.png)

But there definitely have been new detections in the recent upload.

![image](https://user-images.githubusercontent.com/55001144/67490271-f9280480-f640-11e9-96b4-0dda93707c7e.png)

This has been the case with all uploads I've made in the last several days. Anyone know why this might be happening?

**Comment by Hussell** [comment]
This is deliberate, due to #507.

Between Oct. 1st and Oct. 21 (this Monday), I reran 254 receivers over the course of 15 work days. Since I turned off plot generation first thing on Tuesday morning, I've rerun 127 receivers over 2.5 work days. So, rerunning things is going at roughly 3 times the previous rate. In other words, plot generation was using about 2/3rds of the processing time for all uploads and reruns.

So: good news! The reruns of stuff uploaded during September, which had to be rerun because tag registrations were delayed during that time, are done. I'm currently rerunning things which should have been rerun around Sept. 12th, so about a month and a half behind schedule. At the new rate, reruns might be back on schedule sometime in the first week of November. Previously I was not expecting to be finished the September reruns until mid-November and not back on schedule until Christmas.

On the other hand, we're going to be receiving a lot of complaints about the plots not being updated any longer. We can discuss further on the call today.

**Comment by denislepage** [comment]
We should make a post to the group, and discuss what alternatives we can put in place.

**Comment by Hussell** [comment]
From Lucas, here's a draft of the message to be sent to the mailing list:

Dear Motus Collaborators,

We have temporarily halted the production of receiver plot graphics to reduce the strain on our processing servers. These are the graphics typically linked in notification emails and provided through our SGData server. We understand users often rely on these plots for quick diagnostics after uploading their data and we are working on creating a new method for plot production that is less resource-heavy. At this time, we suggest users use other tools already available on the Motus website:
* To see which tags have been detected, please use the publicly available interface in Explore Data > Projects and select the receiver of choice.Please note these data are filtered so you may not see everything.
  * You will need to download data through the Motus R package to view all your unfiltered data.
* To inspect antenna activity, you can review the receiver timeline under Manage Data > Receivers and select 'Edit Receiver Properties' for the receiver of choice. The receiver timeline can be viewed by clicking on 'Receiver Timeline' in the top-right corner.

Thank you for your patience,

Lucas Berrigan

**Comment by StuMackenzie** [comment]
Assuming that providing direct links to the areas below would be complicated, I think the following generic message would be fine. If direct links can be provided than that would be the preference, but not if its super time consuming for the time being. 

Something like
"
Thank-you for the upload - it has been processed.

To see which tags may have been detected, please use the publicly available interface in Explore Data > Projects and select the receiver of choice. Note these data are filtered so you may not see every detection.
       
Unfiltered data is available through the Motus R package (link to book).

To inspect antenna and GPS activity, you can review the receiver timeline under Manage Data > Receivers and select 'Edit Receiver Properties' for the receiver of choice. The receiver timeline can be viewed by clicking on 'Receiver Timeline' in the top-right corner.

You can also check the detailed log for processing errors and warnings, here:

    https://sgdata.motus.org/status?jobID=1746492 (*change to relevant link)

Processing Summary:

File uploaded: 2_2019-10-23T23-52-53.907_SGdata_Galeta_2019-04-19.zip
Will run tag finder on 16 receiver boot sessions

(*change to relevant link/summary details*)

 Regards,

The Motus Team

**Comment by jsayers-bsc** [comment]
Yes If direct links could easily included that would be a big time saver, and really provide pretty fill the same role as the previous plots.

Personally I find most useful the Table of detected tags, and the Timeline of the receiver. Between those two there is a great snapshot of the performance of the receiver as well as any tags detected (and species and associated projects, etc).

Of course, that’s if including that direct link is a simple and straightforward matter!

The blurb provided by Lucas gives a good update and will answer most questions users have.



On Oct 25, 2019, at 11:31 AM, SMackenzie <notifications@github.com> wrote:

﻿

Assuming that providing direct links to the areas below would be complicated, I think the following generic message would be fine. If direct links can be provided than that would be the preference, but not if its super time consuming for the time being.

Something like
"
Thank-you for the upload - it has been processed.

To see which tags may have been detected, please use the publicly available interface in Explore Data > Projects and select the receiver of choice. Note these data are filtered so you may not see every detection.

Unfiltered data is available through the Motus R package (link to book).

To inspect antenna and GPS activity, you can review the receiver timeline under Manage Data > Receivers and select 'Edit Receiver Properties' for the receiver of choice. The receiver timeline can be viewed by clicking on 'Receiver Timeline' in the top-right corner.

You can also check the detailed log for processing errors and warnings, here:

https://sgdata.motus.org/status?jobID=1746492 (*change to relevant link)


Processing Summary:

File uploaded: 2_2019-10-23T23-52-53.907_SGdata_Galeta_2019-04-19.zip
Will run tag finder on 16 receiver boot sessions

(change to relevant link/summary details)

Regards,

The Motus Team

**Comment by Hussell** [comment]
Direct links are relatively easy, the tricky bit is that due to the way things are structured the email template is used for every upload, including tag registrations, and the only things which can differ between the emails are the parts in the job summary.

So, here's what the email might look like:

Thank-you for the upload - it has been processed.

You should check the detailed log for processing errors and warnings, here:

    https://sgdata.motus.org/status?jobID=1764966

Any product(s) are listed here:

    (none)

Processing Summary:

File uploaded: 547_2019-10-25T13-56-55.946_Wimindji.rar
Will run tag finder on 30 receiver boot sessions
SG-6E1DRPI38E44: a plot of activity for this receiver can be viewed at https://motus.org/data/receiver/timeline?id=3145
A table of the most recently detected tags for deployment #5301 can be viewed at https://motus.org/data/receiverDeploymentDetections?o=0d&id=5301
SG-7E34RPI3A1A2: a plot of activity for this receiver can be viewed at https://motus.org/data/receiver/timeline?id=3273
A table of the most recently detected tags for deployment #5412 can be viewed at https://motus.org/data/receiverDeploymentDetections?o=0d&id=5412
There may be a delay between the time this job finishes and the time when new information appears on the website and is available through the R package, which varies depending on how much data has been submitted recently. Typical delays are ~20 minutes, and only rarely more than an hour. Also, please note that detections on the website are filtered, so you may not be able to see every detection there. Unfiltered data is available through the Motus R package. (See https://motus.org/MotusRBook/)

 Regards,

 The people at Motus.
