### ISSUE TITLE
Tag Deployment Bulk Uploader Makes Duplicates

### ISSUE THREAD

**Issue by leberrigan** [MotusDev/Motus-TO-DO#594]
Moved from email.

**Project 197**: Tag deployments have been duplicated (some) or triplicated (most) during bulk uploads. 
Tag deployments were downloaded using the bulk upload tool and reused the same file each time they had more metadata to add. Without re-downloading the tag deployments between each upload, the tagDeployID’s remained blank so ‘Motus’ assumed they were all new deployments. 

They now want the duplicated deployments deleted, but I can’t do it manually ([**admin option to delete isn't working**](https://github.com/MotusDev/Motus-TO-DO/issues/595)). The issue is that all the detection data has also been triplicated so downloads are 3x slower.

To fix this we can:
1. Prevent users from using the old tag deployment file.
2. Check for overlapping deployment dates before accepting a new deployment. 

The latter option should be in place regardless so that might be all we need to do.

**Comment by cjardine-bsc** [comment]
We should ensure the instructions flag this well: https://motus.org/wp-content/uploads/2017/08/Tag-Metadata-Upload-Instructions.pdf

We should also probably edit the text fragment on this page: https://motus.org/data/project/tags/template?projectID=137to remind users to download a new template each time so they are working with up-to-date IDs and metadata. 

"Begin Upload

Navigate to your edited template below. This tool will validate your data for any issues. You will be required to fix any errors and review warnings before your data is added to the database." 

One final thing we could do, which might be best, is automatically provide the new template to them when they receive confirmation of the successful upload. That new template will include all the new IDs. If we want to go that way we can ask Paul how complicated that would be.

**Comment by leberrigan** [comment]
Issue is still a problem today

**Comment by eageldart** [comment]
If there isn't already, maybe we want to add information somewhere on the website (instructions for bulk upload, or guides) to strongly encourage people to download a fresh tag deployment excel sheet each time they want to make updates. I will look in the motus guides to see if there is anywhere I can add this information.

**Comment by cjardine-bsc** [comment]
Yeah, those places are covered in my comment above. @leberrigan or @j-sayers or @ajmacdonald3 can one of you make those changes?

In the mean time I'm going to try and figure out how to stop this from happening. I'm down a rabbit hole.

**Comment by denislepage** [comment]
A problem can happen if people are uploading outdated files, which can risk overwriting more recent data.

I’m wondering if a solution could be to have a date field in each row (timestamp would be ideal), which is basically the time of the export. If people try to import using a file that is too old, we could potentially warn them?  Something like:

Warning: 100 records were created from an export that is more than 10 days old. If you have updated your metadata, your upload may overwrite information with outdated details.

We could potentially also check if any of the affected records have been updated more recently that the timestamps contained in the file.

Warning: 10 records were created from an export that is older than the most recent changes you made to your metadata. If you continue, your recent changes will be overwritten by the content of your new upload.

I’m not clear how this problem is creating duplicates, but it can certainly overwrite data in a way that was not intended.

**Comment by cjardine-bsc** [comment]
I started looking into this, specifically: "Check for overlapping deployment dates before accepting a new deployment."

It looks like I did consider this because I do have a check in place that should have prevented these duplicates. It combines all the deployments in the upload with all the deployments in the database and checks for overlaps or multiple pending deployments. There must be a hole in my code somewhere. I'm just having trouble finding it. The code seems solid and when I test its correctly flagging problems. So I don't know how they managed to still import the bad data.

--check for pending deployments on a tag that has a new deployment being created. 
INSERT INTO api_errors (apiBatchId,rowNum,error_code,field_name)
SELECT Distinct @apiBatchID, ISNULL(a.rowNum,b.rownum), 'api_tag_pending', 'deploymentStatus'
FROM #temp_deployments2 a inner join #temp_deployments2 b on a.tagID = b.tagID
WHERE a.deploymentStatus = 0 and b.deploymentStatus in (1,2,0) 
and a.tagDeployId IS NOT NULL AND b.tagDeployId IS NULL

OH!! For Pete's sake. 'api_tag_pending' is set as a warning, not as an error. So the user could just ignore it and import as many duplicates as they wanted. I'm guessing that was the problem here (at least I hope). I've upgraded the warning to an error, which hopefully should prevent this. But please flag if anyone manages to create a duplicate deployment again.
