### ISSUE TITLE
Networked RPi SensorGnome regularly connecting to the server, but not syncing data

### ISSUE THREAD

**Issue by jsayers-bsc** [MotusDev/Motus-TO-DO#599]
Receiver SG-CCD3RPI30FD2 is connected to the internet via Ethernet and has been regularly [connecting to the server](https://sensorgnome.org/status/). However, no data is being synced on any of these connections.

By all accounts it actually have never synced since being set up

![image](https://user-images.githubusercontent.com/55001144/67958878-41f63500-fbce-11e9-8225-e134347c739e.png)

I rebooted the station when I was there, hoping that would help since it often does, but there has been no change. Still regular connections, but no data sync.

**Comment by Hussell** [comment]
SG-CCD3RPI30FD2 had sync jobs from 2019-04-26 through 2019-05-14, but every single one reported no new files. Since then there have been no successful connections. So, no, no data from that receiver has ever come in through the internet. The manual upload Josh submitted last week worked, though. So there might be some configuration problem with the internet connection, e.g. it could be looking in the wrong place for new files.

**Comment by jsayers-bsc** [comment]
Hmm.. Maybe then the simplest thing is to replace it in the spring with a receiver known to be properly connecting and syncing data, then troubleshoot this one out of the field.

------ Original Message ------
