### ISSUE TITLE
Receiver tuned to 150.1 MHz reporting tags from 166.380 MHz

### ISSUE THREAD

**Issue by leberrigan** [MotusDev/Motus-TO-DO#614]
Similar to #520, station from project 113 has detections from tags of the wrong frequency  (all dongles are listed as being tuned to 150.1 MHz):
https://motus.org/data/receiver/deployment/detections/timeline?year=2019&id=5621

**Comment by Hussell** [comment]
This is a networked receiver. It has been uploading since Sept. 16th, but we had no metadata until later, so it was assigned to project 0 and tag finder defaulted to the N. American frequency. It's now known to be part of project 113, and the tag finder is searching for tags listed at 150.1 MHz. I'm rerunning the earlier batches now, so the bad data should disappear shortly.

**Comment by Hussell** [comment]
Done. All tags are now from Europe, as expected.

Note 1: under the normal schedule, these batches would have been rerun next week anyway.

Note 2: this deployment has an end date, yet (currently) has status 2, active, because the end date is (currently) in the future. Not relevant to this issue, I think, but see #611.
