### ISSUE TITLE
Investigate optimal performance of RTL-SDR dongles and documentation

### ISSUE THREAD

**Issue by StuMackenzie** [MotusDev/Motus-TO-DO#615]
I'm not going to get all of this right, but...

Funcubes are tuned 4 KHz lower at 166.376 MHz.  which is an optimal range to detect tags for funcubes.

We know that RTL-SDR's do not perform as well as Funcubes, but we're not entirely sure, and we also don't know what if any 'tuning' has or can occur with RTL-SDR's. 

It's entirely possible that the poor performance is based on them not being optimized or tuned properly.

Food for thought for now. There is a need to consolidate these notes re. RTL-SDR performance into one place. Perhaps moving notes/test from Adam Smith would be a good first step as well as finding any documentation from John.

**Comment by adamdsmith** [comment]
The deployment.txt file also tunes RTL-SDRs 4 kHz low, which certainly seems reasonable based on some experimentation of detecting nanotags using the [RTEU software](https://radio-tracking.eu/). There's a definite "blind spot" at the tuned frequency as there is with FCD.

It also seems clear to me now that at VHF frequencies an LNA seems to do more harm than good. So if FUNcubes are out due to expense the NooElec SMArt seems a reasonable alternative.  I've got a few stations running SMArtees with an LNA and they pretty much refuse to detect anything...

FWIW, I think the LNA could work with CTT dongles, but as far as I know they don't have a bias tee option so you'd have to feed them power separately.

**Comment by adamdsmith** [comment]
Two other things to consider:

1. Sampling rate. NooElec RTL-SDRs, and presumably others compatible with the SG, sample at 240 Mhz. For FCD we use firmware that samples at 48 MHz. While the deployment.txt file indicates the RTL-SDR's sample rate is 48 MHz, I don't think the SG software alters the actual sample rate of the device. Instead, I believe John's solution to get it to 48 MHz was to average every 5 samples to downsample RTL-SDRs to 48 MHz. Not sure what implications that might have on the tag signal. Presumably the RTL-SDR could be set to sample natively at 48k, though I suspect John had a good reason for not doing this---maybe it was too difficult to access the sample rate parameter generally across multiple SDR manufacturers?

2. RTL-SDR gain setting: John puts this at 40.2 dB in the deployment.txt file. That seems reasonable to avoid excess noise, but may be worth experimenting with lower or higher values to see where SNR starts to drop.

**Comment by dfloer** [comment]
@StuMackenzie I think some tests to characterize the RTL-SDR performance versus the FunCube Pro+ dongle is also worthwhile. I've noticed a lot of variation between cheap RTL-SDRs, as well as ones that use an E4000 instead of an R820T2 tuner chip. I have also found that tuning is important.

@adamdsmith When you were testing LNAs with RTL-SDRs, did you adjust the SDR's gain?

1. As for the RTL-SDR sample rate, the minimum rate that the RTL-SDR's tuner supports is 225.001kHz, so a downsample factor of 5x to get to 45kHz seems reasonable.

2. 40.2dB gain seems like a reasonable baseline, but I think that some (maybe most) sites would need some tuning to optimize gain parameters. What works best at one site may not work as well at other sites. Ideally, I'd like to have some sort of way to automate this tuning, but that's a little ways off yet.

**Comment by adamdsmith** [comment]
@dfloer Yes, the SMArtee XTR uses the E4000 chip and clearly didn't perform well as I set up the test. 

I'm sure with tuning the SDRs could approach the FCD, but I don't expect most users will be up to that task. It was for that reason I didn't manipulate much of the deployment.txt file, including the SDR or FCD gain during the tests with LNA. 

The only parameters I changed were:
1. Lowering the SDR SNR ratio to 6 to match the FCD setting; and
2. Turning on the FCD bias tee for LNA testing

**Comment by leberrigan** [comment]
@StuMackenzie, what do you think about using this winter to do some more testing on RTL-SDR? During our last check of the year we can swap out 1 FCD for an RTL-SDR at a random selection of stations so we can collect data over the winter on background noise. I don't know how you feel about keeping them installed for spring migration, but we could decide that later.

**Comment by StuMackenzie** [comment]
Closed in deference to https://github.com/MotusDev/Motus-TO-DO/issues/625
