### ISSUE TITLE
Radio Dongle Performance Documentation

### ISSUE THREAD

**Issue by leberrigan** [MotusDev/Motus-TO-DO#625]
An extension of #615, but this is to get information for _all_ dongles currently used in the network.

I am currently in the process of [filling in documentation across the Motus website](https://beta.motus.org/antennas/#dongles) and this is one area I think we need to expand on. 

The table below is an example of what I was hoping to include. We don't need an fully comprehensive list at this time, we can adapt that as information comes in. 

Can information be placed here as it comes in? Thanks!

  | Price (USD) | Something | Something | Power Usage
-- | -- | -- | -- | --
FUNcube Pro | Unavailable | Unknown | Unknown | Unknown
FUNcube Pro Plus | $200 | Unknown | Unknown | 1.05 W
RTL-SDR | $20 | Unknown | Unknown | 1.75 W
NESDR Smart (???) | $25 | Unknown | Unknown | Unknown
CTT | $100 | Unknown | Unknown | Unknown

**Comment by StuMackenzie** [comment]
Something = Range - it would have to be a +,-, good, bad. something more general

Something = power consumption

Something = reliability

Something = ...,

**Comment by adamdsmith** [comment]
By my measurements attached to an 1/4 wave omni, assuming 5.1V on a Raspberry Pi 3, though I did not have an active tag nearby

I'll test the CTT dongle once I get one in hand. I'll also measure FCD power consumption on a SensorStation tomorrow and update this...

Receiver | Price (USD) | Power Usage 
-- | -- | --
FUNcube Pro Plus | $225 | 0.92 W
RTL-SDR blog V3 | $20 | 1.53 W
NESDR SMArt | $25 | 1.43 W
NESDR SMArtee | $25 | 1.43 W
CTT | $100 | will test

**Comment by dfloer** [comment]
I'd like to clarify that the RTL-SDR is a class of inexpensive SDRs, so I'd be explicit about each model, as I've noticed some variability across different versions. So for the second entry, maybe either make it more generic and give it a range (price: $20-$50, for example) or make it explicit if it's implying the RTL-SDR blog V3 device.

For Stu's suggestion of range, do we have a good feel for what that looks like? I could go to a park and see how far out I can reliably detect with a selection of SDRs.
Reliability may be hard to gauge.

Power usage number from the devices on hand (measured using a Klein ET920):
NESDR Smart v4: 1.54W in use, <0.25W idle.
NESDR Smart XTR: 1W in use, 0.6W idle.
Funcube Pro+: 0.8W in use,  0.8W idle (with 48kHz firmware).
RTL-SDR Blog V3: 1.5W in use, 0.7W idle.
CTT: <0.25W in use, <0.25W idle (quick test).
The minimum that the meter can report is 50mA.

**Comment by leberrigan** [comment]
Thanks everyone - I'll add this to the table.

I don't think range makes sense to add since it will ultimately depend on the type of antenna used.

Eventually we might want to include some more details once we get them: 
 - Typical noise figure/SNR
 - Number of tag bursts detected at close range (no antenna) out of a 1000 with 1, 2, or 3 tags present
 - DC spike?
 - Reliability


Receiver | Price (USD) | Power in use | Power while idle | Reliability | Typical Noise Figure
-- | -- | -- | -- | -- | --
FUNcube   Pro Plus | $225 | 0.8 W (48 kHz) | 0.8 W (48 kHz) | Very reliable | 3.5 dB @ 145 MHz
RTL-SDR   blog V3 | $22 | 1.5 W | 0.7 W | Unknown | ~5 dB @ 144.3 MHz
NESDR   SMArt v4 | $24 | 1.54 W | <0.25 W | Unknown | Unknown
NESDR   SMArtee | $26 | 1.43 W |   | Unknown | Unknown
NESDR Smart XTR |   | 1 W | 0.6 W |   |  
CTT | $100 | <0.25 W | <0.25 W | Unknown | Unknown

**Comment by adamdsmith** [comment]
It's worth pointing out that the SMArtee and SMArtee XTR have always-on bias tee. That means the receivers will not work, and will likely be ruined, when using any DC-grounded antenna. The PLC-1669 isn't DC-grounded, so it still will work, but that can't be said of other options. Also in limited tests the XTR did not perform well against the SMArtee.

**Comment by dfloer** [comment]
@adamdsmith Good point. The documentation will need to make clear not to use non-switchable bias tee SDRs, or if they are used, to use s DC block (or LNA, though this doesn't appear to be currently supported) to keep from damaging the SDR.

@leberrigan Might be worth it to put in the antennas section whether or not they're safe to use with bias tee enabled SDRs?

**Comment by StuMackenzie** [comment]
Reinvigorating this discussion. I think we may have enough data now to try some kind of broad scale analysis between FunCubes and RTL-SDRs generally. It may not be super revealing because it may not be because of the dongle that a station is quiet or loud, but it would be worth looking at.

I know @adamdsmith had looked at some of his stations, but is there any documentation without having to dig too hard?

May be a good side project for one of the Luc's techs, or add it to our list.

@leberrigan @ajmacdonald3

**Comment by leberrigan** [comment]
Great idea. This would be a pretty straight forward task for my tech. Would be good to compare other things at the same time like antenna model and cable type, if there's enough data for that.

**Comment by StuMackenzie** [comment]
Yup. All that stuff.

____________________

**Comment by adamdsmith** [comment]
We've got a few Pi-based stations that have 1/2 FCD and 1/2 RTL due to power limitations. They may be up for a comparison. The best candidate to start with would be [Mackay Island](https://motus.org/data/receiver/timeline?id=2296&year=2020), which had several tags on the landscape around the tower for quite a while last fall and has had a couple flybys since this spring spring, and [Bulls Island](https://motus.org/data/receiver/timeline?id=3008&year=2019).

You can typically tell which port uses which dongle based on Motus activity profiles. The RTLs *appear* to be less noisy on Motus activity plots, but typically have higher noise floors in reality. John suggested the apparent lack of noise on these plots could be due to the way the code [downsamples the RTL feed by averaging consecutive samples](https://github.com/MotusDev/Motus-TO-DO/issues/615#issuecomment-553009143), though that was only speculation.

And since it's somewhat relevant, I'll put the results of a very small controlled comparison of the dongles I attempted last year. The tests could use more replicates and more scenarios.

I put a 1/4 wave VHF omni on a 10' mast and put two tags, 5' above ground on wooden stakes, at 25 and 50 m from the omni with wide open line of sight. I oriented the tags/antennas as if in flight passing by the station (i.e., tag antenna oriented perpendicular to the station antenna if it had been a Yagi). No ground plane on the tags. I also put a tag at 100 m but it was detected so infrequently that I scrapped it.

I tweaked the SG deployment file so FCD and RTLSDRs all operated at SNR == 6. This is the FCD default. RTLSDR default is SNR == 10.

I tested brand new receivers as follows:

- NooElec SMArt (2 units; bias T LNA not supported)
- NooElec SMArtee (2 units; bias T always on)
- NooElec SMArtee XTR (2 units; bias T always on)
- RTLSDR blog V3 (1 unit; bias T not currently supported on SG; software-enabled)
- FUNcube Pro Plus (1 unit; bias T available via deployment file)

For the tests using a LNA, I used the RTLSDR blog bias T powered unit. In all tests, I plugged the receiver directly into the SG (no USB extension cable).

I swapped receiver setups in and out every 2 minutes, giving me 10-11 opportunities at hits on the 11.3s pulse-width tags (NTQB2-4-2S). 

Here's the signal strength results (points are jittered to help with clarity):
![fcd_rtl_comparison_sigstrength](https://user-images.githubusercontent.com/3195855/92285059-621f1080-eed1-11ea-98ff-dc815f19961c.png)

And the SNR results:
![fcd_rtl_comparison](https://user-images.githubusercontent.com/3195855/92284502-1750c900-eed0-11ea-9d57-4c07420d6958.png)

Conclusions:

- FCD was similar, if not modestly better, to the SMArt and SMArtee. Signal strength was actually considerably higher on the RTLs (except for the XTR), but after factoring in noise floor FCD typically had the highest and most consistent SNR.
- There was the expected variation in SDR performance between replicates of the same RTLSDR model, up to 5-8 db SNR. With only 1 FCD tested, I couldn't evaluate their inter-unit performance.
- LNA really didn't help much, if at all. This makes sense based on what I've come to learn---that at VHF frequencies, LNA benefits are not expected to be great due to external atmospheric noise driving the system.
- The SMArtee XTR is not to be used...
- Among RTLSDRS, the cheaper SMArt, with no LNA, seems to stand up to the FCD pretty well and avoids the complication of always-on bias T in the SMArtee. Though the SMArtees will work with the PLC-1669 without a bias T powered LNA, they will *NOT* work with DC grounded antennas unless a bias T powered LNA (or DC block) is present.

With all that said, I'm still a bit skeptical of the SDRs. In the field, our FCD stations typically seem to outperform our SDR stations. In fact, we have a couple of stations with SDRs/LNAs that for the life of me I can't figure out why they're not detecting passing birds, to the point I'm about to upgrade all stations to FCDs. I also suspect there's a bit less consistency in quality among SDRs, though I haven't noticed it too much with a couple of big-ish SMArt and SMArtee orders.

**Comment by dfloer** [comment]
Thanks for doing these detailed tests!

I haven't dug deeply into it, but in a brief inspection of the pulse detection code, it seems more optimized for the FCDs than it does the RTL-SDRs. I don't know what effect this has in the real world. In general, the pulse detection is something I'd like to address, because overall, the pulse detection code could use a lot of work to improve detection rates/ranges and lower the number of false detections.

For the LNA tests, where you using a filter or not? If so, was it before of after the LNA? If not, I'd highly suggest testing the LNA with an appropriate filter on both sides. An LNA should help, even at VHF frequencies, but in general, LNAs need good filtering to work well.

I just ran a quick test with a Smart XTR and an LNA without filtering (I don't have an appropriate filter on hand and making one isn't quick). Reception of the Lotek tag got _worse_ due to noise. I suspect that a filter would make a large difference, based on experience with filters on other low-signal strength sources, such as satellite reception.

Another thing I'd love to look into is that there are a wide variety of SDRs in the same price range as the FCD that had drastically improved performance characteristics, though some of them may be out of the needed power envelope for a solar site.

I'm not sure how much of a difference noise makes, or how to usefully model it for you tests, but it could be useful to have an SDR recording the range around the tags with an omni antenna to get an idea of what the noise floor looks like in the area.
I know that the Sable Island station is right next to a two-way radio system that is only slight off frequency, and I suspect it's what is causing a lot of interference issues.

Minor nitpick, SDR is Software Defined Radio, which both the FCDs and RTL-SDRs are.

**Comment by adamdsmith** [comment]
> I haven't dug deeply into it, but in a brief inspection of the pulse detection code, it seems more optimized for the FCDs than it does the RTL-SDRs. I don't know what effect this has in the real world. In general, the pulse detection is something I'd like to address, because overall, the pulse detection code could use a lot of work to improve detection rates/ranges and lower the number of false detections.

In multiple chats with John B, he seemed to think there was a lot of signal processing work to be done that could greatly extend the FCD detection range. But I believe there was a general lack of time to work on the processing this side of the FCD as well as the frustration that the FCD software was not available for closer inspection or tag detection customization/optimization. Indeed, Phil once mentioned that in practice they never even got around to exploring how tweaking the deployment settings in the FCD would affect things. (I have attempted several times to get students to do this, but it never happened)

   > For the LNA tests, where you using a filter or not? If so, was it before of after the LNA? If not, I'd highly suggest testing the LNA with an appropriate filter on both sides. An LNA should help, even at VHF frequencies, but in general, LNAs need good filtering to work well.

No filters. I didn't think there was an affordable option that was reasonably narrow for our purposes. Most of our stations with high noise are likely due to nearby VHF (e.g., marine) that a filter wouldn't help with. That's not to say it wouldn't help. I'd defer to your experience.

   > I'm not sure how much of a difference noise makes, or how to usefully model it for you tests, but it could be useful to have an SDR recording the range around the tags with an omni antenna to get an idea of what the noise floor looks like in the area.

Not sure I follow completely but teah, I should have recorded that from SDR# or similar during the test but didn't. I doubt it influenced the test results, though, since the only thing that changed in each window was the SDR used. The tags and antenna were fixed throughout the test.

   > Minor nitpick, SDR is Software Defined Radio, which both the FCDs and RTL-SDRs are.

Yes, pardon the typo. I meant RTL... :)

**Comment by adamdsmith** [comment]
> Another thing I'd love to look into is that there are a wide variety of SDRs in the same price range as the FCD that had drastically improved performance characteristics, though some of them may be out of the needed power envelope for a solar site.

Out of curiosity, are you thinking AirSpy HF+ here?

**Comment by dfloer** [comment]
> Out of curiosity, are you thinking AirSpy HF+ here?
Yeah, that's one of the ones that looks like a good candidate because it's built for that frequency range, but stuff like the LimeSDR Mini could also work.

**Comment by dfloer** [comment]
> In multiple chats with John B, he seemed to think there was a lot of signal processing work to be done that could greatly extend the FCD detection range. But I believe there was a general lack of time to work on the processing this side of the FCD as well as the frustration that the FCD software was not available for closer inspection or tag detection customization/optimization. Indeed, Phil once mentioned that in practice they never even got around to exploring how tweaking the deployment settings in the FCD would affect things. (I have attempted several times to get students to do this, but it never happened)

One of the biggest things I can see (and John B. recognized this) is that the Lotek tag pulses all have the same phase (and in my limited testing, I've also observed this). Phase information could help to drastically lower the number of false detections, though this would also mean updating tag finder.

> No filters. I didn't think there was an affordable option that was reasonably narrow for our purposes. Most of our stations with high noise are likely due to nearby VHF (e.g., marine) that a filter wouldn't help with. That's not to say it wouldn't help. I'd defer to your experience.

I was kinda hoping you'd found a filter that wasn't super expensive, because I wasn't finding any. Not an easy prospect, but a PCB based microstrip filter, once designed, could likely be produced for very low unit costs. It's just the design and testing work to get there.

One other thing to note is that the filter can also help with harmonics from sources that are further away from the center frequency you're tuned to, and can also help keep things like a strong FM signal from leaking across the frontend in the SDR, though I've only personally observed this happening in RTL-SDRs, it _could_ be a real problem.
 
> Not sure I follow completely but teah, I should have recorded that from SDR# or similar during the test but didn't. I doubt it influenced the test results, though, since the only thing that changed in each window was the SDR used. The tags and antenna were fixed throughout the test.

I agree that it probably didn't affect the test a bunch, but there could also be intermittent sources that only affected certain tests, like someone keying up a radio repeater but otherwise not talking.

**Comment by StuMackenzie** [comment]
See also and merge https://github.com/MotusDev/Motus-TO-DO/issues/615

**Comment by dfloer** [comment]
Capturing some basic testing notes here.

166.380MHz tests (N/T = Not Tested):
|Test|Nesdr Smart|Nesdr Smart XTR|RTL Blog V3|FunCube Pro Plus|
|-|-|-|-|-|
|Noise Floor - no connection (dBFS)|-52|N/T|N/T|-92|
Work in progress, I'll update this as I run more tests.
