### ISSUE TITLE
Default project when logging in

### ISSUE THREAD

**Issue by jsayers-bsc** [MotusDev/Motus-TO-DO#629]
Is there a way to set a default project to be selected upon first logging in? 

The default seems to be the first in alphabetical order, which is Project 137: Abiotic and biotic influences on Snowfinch.

I do have a bookmark for Project 1, which is what I would normally be logging in to, but depending on how the site is accessed, occasionally I unwittingly get defaulted into 137 (occasionally uploading into there as well, which, according to the [jobs list](https://motus.org/data/project/sgJobs?projectID=137), I'm not the first to do!)

**Comment by Hussell** [comment]
We administrators have to deal with this, because we've got special access to all projects. The vast majority of users are only registered with a few projects, and those are the only ones they can accidentally select.

So this is somewhat low on the priority list, because there are only a few administrators. On the other hand, it must be annoying for the real members of project 137. I'll look for anything obvious which can be done easily.

**Comment by jsayers-bsc** [comment]
Yes it's a very small pool of people who confront this to be sure!

Though I suppose anyone associated with multiple projects will always find it defaulting to the first one in the alphabetical list, regardless of which one they are "more" involved with. Then again, most people don't spend the better part of every day somewhere on the site!

**Comment by denislepage** [comment]
Adding a column in the user profile that tracks the last project may be a useful usability enhancement. This could easily be added as a new column in user_properties and modified whenever a project is changed.
