### ISSUE TITLE
Error when registering tags, yet tag in question appears in the tag records

### ISSUE THREAD

**Issue by j-sayers** [MotusDev/Motus-TO-DO#630]
Project 294 is attempting to register tags and inquired about confirmation.

Their tag records appear to show all 4 tags

![image](https://user-images.githubusercontent.com/55001144/69443687-ecb8c980-0d1c-11ea-8694-33c731b275d7.png)

But when the log is viewed, there is an error associated with the first tag

![image](https://user-images.githubusercontent.com/55001144/69443659-e296cb00-0d1c-11ea-8655-22179c6292ed.png)

This would seem to indicate that this would have been a duplicate record, yet the tag is in their database. They have not uploaded this file previously is the thing, and in fact this is their first successful upload.

**Comment by cjardine-bsc** [comment]
Drat. 

Here is the sequence of events leading to this: 

1. Because we need to keep the tag_ids between the sandbox and live in sync, when a tag is registered to live we also register it to sandbox. 
2. However, sometimes a project that exists in live does not yet exist in sandbox (since projects are not synced between the two). 
3. If we tried to register a tag to sandbox to a project that doesn't exist in sandbox we would get an error. Instead, when the project does not exist in sandbox, we register the tag to project zero instead. 
4. In this case, the tag mfg_id had already been registered to project 0 in sandbox within this date-bin. Causing a primary key error. 

There are three solutions I can think of:

1. Sync projects between live and sandbox whenever a new project is created so we never need to register tags to project 0. 
2. Remove primary key from the tags table in sandbox. 
3. Remove foreign key on tags.project_id in sandbox so tags can be registered there to projects that do not exist. 

Right now the tables between sandbox and live are not out of sync in terms of new tag_ids, but tag_id 43288 is missing from sandbox. It will need to be re-inserted once we decide which of the three options above we'd like to implement. 

Josh, this won't impact project 294 in any way, and they can proceed with deployments for those tags. Thanks for flagging this though.

**Comment by jsayers-bsc** [comment]
Well good to know, and thanks for the clarification! Darn unintended consequences.
