### ISSUE TITLE
Main Motus Map Upgrades

### ISSUE THREAD

**Issue by StuMackenzie** [MotusDev/Motus-TO-DO#637]
We’ve talked about adding the capability to see which stations are up to date at a glance, but haven’t implemented anything yet. I’d like to see us proceed with this.

Whether it’s just the default setting for the base map, or a separate/function built into the current map or a link to a copy of the current receiver map.

Something along the lines of:
Green - online - data received in the last 24 hr
Yellow - data received in the last 3 months
Orange - data received in the last 6 months - 9 months?
Red - data received > 1 yr ago

**Comment by leberrigan** [comment]
Colour blind friendly colours aren't the greatest for signifying importance so maybe we should add a radio input so users can switch to colour blind friendly colours if they want to. That depends on how important you think that is, Jeremy.

**Comment by jsayers-bsc** [comment]
We really only need to see this information for deployments considered "active" on the map. So if someone uses the slider on the map to visualize the stations that were active at various points in the past, the Last Data data sort of becomes irrelevant, then maybe the display style simply reverts to the existing dots. I don't know if that simplifies implementation of this into the existing map or not...

I feel like 3 categories would be sufficient with the various colours (or appropriate equivalent)
- Green: Data within the last 3 months 
- Yellow: Data within the last 6 months
- Red: More than 1 years from today since last data received

My feeling is that another category for data in the last 24 hours may give a false impression that anything less than that is starting to verge into into delinquency. But the truly connected receivers are a small portion of the network right now so in most cases data within the last 3 months likely does indicate stations that are just fine.

**Comment by StuMackenzie** [comment]
I agree with the categories except that I do think we need to prepare to be able to identify live stations - so that that have updated in the last 7 days, or a separate colour/indicator for those that are connected. It should be based on live data not a custom list though.

**Comment by StuMackenzie** [comment]
Glad to see this on sandbox. @Hussell - Can we please add the function to the main Manage Projects Menu? It's kind of buried where it is now.
Under Manage your Receivers, or within the line of text in that menu item - "Receiver Status Map"

**Comment by leberrigan** [comment]
I've noticed if we install a new computer somewhere it show up as red. This can be fixed if we use the site ID to get the most recent data, not deployment or receiver ID. 

Also, I think we should set new sites with no data to grey. 

We may want to change the colour scheme to reflect the expected station check schedule. For the larger networks, this is 3-4 times per year but right now those stations are showing up as yellow which to me says 'warning'. For this reason, I think we should add another 'friendly' colour between 30-90 days to indicate it's normal:

Date range | Colour | Hex
-- | -- | --
<30 days | Green | #00FF00
30-90 days | Light green | #DDFF00
90-180 days | Yellow | #FFFF00
180-365 days | Orange | #FFDD00
.>365 days | Red | #FF0000
No data | Grey | #DDDDD

---

In terms of colour blindness, we should expect an average of 1 person in 20 not being able to tell the difference between red and green in this scale (i.e.; this map would not be useful). Here's a new colour scheme that can be offered as an alternative, or perhaps its similar enough that we can just replace it.

### [Colour-blind friendly colours](https://colorbrewer2.org/#type=diverging&scheme=RdYlBu&n=5)

Date range | Colour | Hex
-- | -- | --
<30 days | Blue | #2C7BB6
30-90 days | Light blue | #ABD9E9
90-180 days | Light yellow | #FFFFBF
180-365 days | Orange | #FDAE61
.>365 days | Red | #D7191C
No data | Grey | #DDDDD

**Comment by denislepage** [comment]
I would just use one set of colours. I think the proposed ones look fine. Here's how they translate

![image](https://user-images.githubusercontent.com/21110542/90046587-aa665c80-dc9e-11ea-8104-d334c686ace1.png)

**Comment by leberrigan** [comment]
Here's another issue: it looks like the receiver will be pink (i.e., 'no data') if you add a new deployment, not just a new computer. We're going to have a lot of sites with 'no data' if we keep it like this. I guess this brings up the issue of summarizing data by station (i.e., 'site')!

**Comment by leberrigan** [comment]
@Hussell, would it take much time to add this functionality to the [main receivers map](https://motus.org/data/receiversMap)? Stu and I were talking and think this should be visible to everyone considering it helps researchers quickly determine where to expect data, etc.

I think we should add this as a toggle option since it would still be useful at times to see the map with all stations looking equal (that is, as the original yellow dot).

**Comment by StuMackenzie** [comment]
Broadening this issue to include Main Map upgrades overall:

1) Station summaries based on site definitions, not deployments. May require implementation of the 'station' identifier first? Or the option? Show site summaries, show deployment summaries, show station summaries. Station summaries should be default.

2) Option to see station status map across all projects from the main project map.

**Comment by Hussell** [comment]
See #698 for sites/stations/locations vs. deployments.

**Comment by StuMackenzie** [comment]
Unresolved - Still needs to be a more prominent feature. 
- option on main map or, link to public version on the main map page somewhere.
- filter option on the new Explore Data pages, or specifically in a Project Mgmt Tool

**Comment by leberrigan** [comment]
It's been done. We'll also be doing something different in the explore dashboard.
