### ISSUE TITLE
Add 'Date of Last Data' Column to Receiver Deployments CSV

### ISSUE THREAD

**Issue by leberrigan** [MotusDev/Motus-TO-DO#638]
As mentioned in the call today, can we put a column for the timestamp of the most recent data to the 'receiver-deployments.csv'? This should be most recent radio pulse or GPS hit, not tag detection because we want to know the last time someone downloaded data from the receiver.

I think there are two places where the CSV is accessed and this column should be added to both, if those files are indeed different:
 - Manage Data > Download Project Data
 - Explore Data > Download Data

**Comment by cjardine-bsc** [comment]
Hiya, 

I looked into this a little today. 

This is something that's quite doable for active sensor deployments (of which there can only ever be one per deviceID). Unfortunately, things get substantially more complicated if you'd like this information displayed for terminated deployments, and I'm not sure how efficient I can make it. 

UNLESS, instead of using the tsEnd from the batches table, I use the max ts from the GPS table. This assumes that every deployment is recording GPS data. 

**10 minute pass** 

Which I now know is a false assumption. This would only work for 2800 of the 3400 deployments we have: 

WITH GPS as ( SELECT  max([ts]) as ts,[recvDeployID]
FROM [motus].[dbo].[det_gps_deploy_id]
GROUP BY  [recvDeployID])
Select * from GPS a 
right join sensor_deployments b 
on a.recvDeployID =b.id 

So not the best, but better than only having this for active deployments, perhaps. 


**wait 10 min**

Looking deeper, most batches don't have gps fixes, so this is a poor method. 

 WITH GPS as ( SELECT  [batchID] ,max([ts]) as ts,[recvDeployID]
FROM [motus].[dbo].[det_gps_deploy_id]
GROUP BY  [batchID], [recvDeployID]
) 
Select b.batchID, b.motusDeviceID, ISNULL(max(a.ts), max(tsend)), recvDeployID  from GPS a 
right join det_batches b on a.batchID =b.batchID 
group by b.batchID, b.motusDeviceID, a.recvDeployID
order by batchID, motusDeviceID 

**wait 10 min**

This might be helpful for terminated deployments, it basically shows if there is a batch that overlaps the deployment end date for that receiver. This, UNION-ED to a query for active deployments might give us what we need. 

SELECT motusDeviceID, a.id as sensorDeployID,a.dt_start as deployment_start,  a.dt_end as deployment_end, dbo.ts2datetime(MAX(tsEnd)) as max_batch_end
  FROM [motus].[dbo].[sensor_deployments] a
  inner join sensors b on a.sensor_id =b.id
  inner join sensors_hash_keys c on b.receiverID = c.receiverID 
  right join det_batches d on c.id=d.motusDeviceID and ( a.ts_end between d.tsBegin and d.tsEnd)
  group by motusDeviceID, a.id, a.dt_end, a.dt_start 
  order by motusDeviceID, sensorDeployID 

I'll look into this more fully on Monday. 

The alternative to the gymnastics above would be to create a new det_table (yay?) either det_batches_deploy_id (which would be complicated in cases where the batch overlaps multiple deployments)  or det_pulse_count_deploy_id. Which would slow down our processing when assigning deploy_ids, not ideal, but it would work.

**Comment by jsayers-bsc** [comment]
It may be that this really is only necessary for active deployments...?

Certainly when it comes to [viewing this informing on the map](https://github.com/MotusDev/Motus-TO-DO/issues/637#issue-533330050) (which would be coming from the same query?), we are only interested in those deployments currently considered active. One of the main reasons this is useful is visualizing at a glance just how active some of these "active" stations are, since many will not have had data uploaded in a very long time, and some may be inactive, but where metadata has not been updated. 

I tend to think the same would be true for the .csv export, and that the date of last data upload isn't all that useful for deployments that are already terminated. Though maybe I don't have the use in mind that @leberrigan does....

**Comment by leberrigan** [comment]
Yes, generally this will be used for active receivers only, but I can see some value in having these data for terminated deployments. Sometimes people forget to upload the last chunk of data when terminating a deployment. I can't imagine that happens very often though so maybe it's not the highest priority? Something we should discuss..

**Comment by cjardine-bsc** [comment]
To start, here is the list of all sensor deployments that have not seen new data for over 180 days. Some of these were last uploaded in 2016 and can almost certainly be closed. Fun cleaning for @jsayers-bsc  (sorry!)

[deployments_180daysSinceLastUpload.xlsx](https://github.com/MotusDev/Motus-TO-DO/files/3958115/deployments_180daysSinceLastUpload.xlsx)

I'm creating a new data issue for these now.

**Comment by cjardine-bsc** [comment]
Take a look and let me know your edits: 

https://sandbox.motus.org/data/issues?id=40#v_sensor_no_recent_data

Once you're happy we can translate the descriptions and post to live.

**Comment by jsayers-bsc** [comment]
The error message looks good. Is there any value do we think of making a tiered error message, one for 6 months and a more severe one for a year? Or just keep it as 6 months... 

@cjardine-bsc can you share you query?

**Comment by cjardine-bsc** [comment]
Sounds like Stu had a few edits to the message. I'll wait to send for translation. 

Up to you if you want multiple levels. I can do either. 

The query is part of prDataValidation, I'll send relevant code via email.

**Comment by StuMackenzie** [comment]
Text:
"
These deployments are active, but it has been over 180 days since detection data from these deployments has been uploaded to the Motus database. If this station is still active we recommend attempting to visit this station soon to ensure functionality and download any detection data. If the station is no longer active, please ensure that any terminated deployments have their End Date populated correctly on the deployment management page."

Semantics, but I wonder if 180d is too short for this error. Might want to make it a year. Or a warning after 180 days, error after a year

**Comment by jsayers-bsc** [comment]
I agree that Warning for 180 days and Error for 1 year would probably be better

**Comment by cjardine-bsc** [comment]
No prob. Do you want to draft two different texts and I'll get that in place.

**Comment by StuMackenzie** [comment]
Warning:
These deployments are active, but it has been over 180 days since detection data from these deployments has been uploaded to the Motus database. If this station is still active we recommend attempting to visit this station soon to ensure functionality and download any detection data. If the station is no longer active, please ensure that any terminated deployments have their End Date populated correctly on the deployment management page."


Error:

These deployments are active, but it has been over 1 year since detection data from these deployments has been uploaded to the Motus database. If this station is still active we recommend attempting to visit this station soon to ensure functionality and download any detection data. If the station is no longer active, please ensure that any terminated deployments have their End Date populated correctly on the deployment management page."

**Comment by cjardine-bsc** [comment]
We need the text split between "error description" and "fix instructions" 

Like so?

Warning:
These deployments are active, but it has been over 180 days since detection data from these deployments has been uploaded to the Motus database. 

If this station is still active we recommend attempting to visit this station soon to ensure functionality and download any detection data. If the station is no longer active, please ensure that any terminated deployments have their End Date populated correctly on the deployment management page.

Critical Error:
These deployments are active, but it has been over 1 year since detection data from these deployments has been uploaded to the Motus database. 

If this station is still active we recommend attempting to visit this station soon to ensure functionality and download any detection data. If the station is no longer active, please ensure that any terminated deployments have their End Date populated correctly on the deployment management page.

**Comment by jsayers-bsc** [comment]
Just opened the Manage Data page in sandbox and wondered why we had so many more errors! It's because of the "No Recent Detection Data for Active Deployment".

I guess none of us responded to this last message!

Yes it looks like all the other error messages are broken up that way (makes it more readable too).

**Comment by jsayers-bsc** [comment]
Actually, can these be sorted by time since last data upload?

**Comment by cjardine-bsc** [comment]
@Hussell Would need to look into that. 

If you're happy with the error descr can we send them for translation? That's the last step before we can post this to live.

**Comment by cjardine-bsc** [comment]
@StuMackenzie @jsayers-bsc 

Can be sent for translation?

**Comment by StuMackenzie** [comment]
I think this is good to go to translation! Thanks @cjardine-bsc 

Warning:

These deployments are active, but it has been **over 180 days** since detection data from these deployments has been uploaded to the Motus database.

If this station is still active we recommend attempting to visit this station soon to ensure functionality and download any detection data. If the station is no longer active, please ensure that any terminated deployments have their End Date populated correctly on the deployment management page.

Critical Error:

These deployments are active, but it has been over **1 year** since detection data from these deployments has been uploaded to the Motus database.

If this station is still active we recommend attempting to visit this station soon to ensure functionality and download any detection data. If the station is no longer active, please ensure that any terminated deployments have their End Date populated correctly on the deployment management page.

**Comment by cjardine-bsc** [comment]
Deployed to live. @jsayers-bsc test and close?

**Comment by jsayers-bsc** [comment]
That's live, great. 

- Can we sort these by date ascending so that the most serious are at the top of the list? I believe this is something @Hussell can do? 
- The original request here was to add the date of last data upload to the _csv_. Is that something we still have use for? @leberrigan what do you think?

**Comment by Hussell** [comment]
@cjardine-bsc The issues are sorted by the columns string, string2, and string3 in the adm_validation_errors table, so to change the order you'll have to swap string and string2 where issues of type v_sensor_no_recent_data180 and v_sensor_no_recent_data365 are generated in prDataValidation_pr, and switch where the strings are inserted in the error code. The latter can be done like so:

update adm_error_code
set error_descr = 'Receiver deployment ID : %5$d, Deployment %2$s, Last Detection Data Upload %1$s',
error_descr_fr = 'ID de déploiement de récepteur: %5$d, déploiement: %2$s, dernier téléchargement de données de détection: %1$s'
where error_code in ('v_sensor_no_recent_data180', 'v_sensor_no_recent_data365')

**Comment by Hussell** [comment]
Also, note that you'll have to change the date from the "Oct 15 2015 2:51PM" format to "2015-10-15" so it sorts in a useful order. I don't think it's necessary to keep the exact time of day in the error message.
