### ISSUE TITLE
Inconsistencies when displaying Map of Tag detections 

### ISSUE THREAD

**Issue by jsayers-bsc** [MotusDev/Motus-TO-DO#644]
There are some inconsistencies when viewing tag detections based on whether or not the user is signed in. Specifically this deals with the map showing all the receivers a tag was detected by. 

Using this [CONI ](https://motus.org/data/tagDeployment?id=17265)as an example. When not logged in and someone clicks on "Show detections in a:"

**Map**: only the first location is displayed
**Table**: all receivers are displayed
**Timeline**: nothing is displayed, except a message saying that access level is less than required due to not being logged in

**Comment by jsayers-bsc** [comment]
@cjardine-bsc explained this is due to varying permission levels due for receivers and detections. Which makes sense.

Odd that I never noticed it before. Ross mentioned recently that the maps weren't always working for him, another user emailed saying the same, and then I noticed it myself! So I figured something was up. Guess not :)

Could we have a similar warning message on the Map indicating that there is limited data being displayed due to login status? 

There actually do still seem to be some inconsistencies though. Though the map only shows the first detection due while not logged in, the other detections seem to be easily accessible by clicking through on each receiver in the Table page, even while not logged in.

**Comment by Hussell** [comment]
Yes, this is the same thing. The table only whether a tag was detected on a given day. That's public. The timeline shows exact detection times (well, whether a tag was detected within 2 minutes, which is 1 pixel on the timeline). To see that you have to be logged in. The map shows the location where the tag was put on, which is public, and the track, which uses the exact detection times. That's why the map only shows the first dot when you aren't logged in. For some tags we don't have the initial banding location, so nothing is displayed on those maps when you aren't logged in.

**Comment by Hussell** [comment]
#705
