### ISSUE TITLE
Notification Centre Bug/Clarification?

### ISSUE THREAD

**Issue by StuMackenzie** [MotusDev/Motus-TO-DO#646]
Using Project 204 as an example.

It is not clear how to confirm actual start dates - see tag errors. Original date was set to future - since been fixed. Error still exists. No clear way to 'confirm', or instructions on how to 'confirm'.

**Comment by cjardine-bsc** [comment]
Project 204 has no errors: https://motus.org/data/issues?id=204 

Was this resolved?

I think to confirm the start date all you need to do is edit the deployment. Paul can confirm.

**Comment by StuMackenzie** [comment]
Whoops - meant project 294.

**Comment by cjardine-bsc** [comment]
Hey, When you click on the deployment the below message explains how to confirm the start date. 

![image](https://user-images.githubusercontent.com/22172758/71685564-8c6e6c00-2d4d-11ea-8b4d-0a9f3443228b.png)

I tried saving deployment 27257 (for tag 43291) and confirm_dt_start wasn't updated. I think this is because it is a test tag and doesn't have a species (@pmorrill  can you look into that?). 

The other errors for this project are legitimate, there are no species for them. The user needs to populate the metadata and then that should update the confirm_dt_start field.

**Comment by pmorrill** [comment]
Yes - this deployment needs the species. However, we have discussed changes that would allow data fields to be updated even if there are still some fields in error / missing..... That too would help in a situation like this, but moving to that behaviour is part of CANARIE-3 work,
