### ISSUE TITLE
Incorrect dates in Lotek DTA file

### ISSUE THREAD

**Issue by j-sayers** [MotusDev/Motus-TO-DO#654]
I recently uploaded a .dta file from a Lotek receiver for Project 161. I got the email notification back, which said that there was no new data (this is the first time data from this receiver has been uploaded), and the Last Data Uploaded data didn't update either (currently there isn't one).

Upon looking closer at the .dta data file it seems that the dates got messed up somehow. There are a few detections from a couple months prior to their deployment starting (likely a test run). Then all the actual data starts in 1963-10-29 and starts counting from there, into 1964. 

I'm not familiar enough with Lotek receivers from a user's perspective to know if/how the date might have gotten changed, or if it's a problem with the receiver.

But I'm wondering what can be done about the existing data file. Since any detections fall way outside any real deployment period, nothing would be detected. In theory there would be the possibility of correcting the incorrect time stamps if we could determine the real time when the recording started. The Project might have that precise date, then we could update the .dta file and re-upload. 

**I'm curious if something like this has happened before and how it was dealt with.** 

I would also like to confirm a couple other things. There was "no new data" in the uploaded file, and the Last Data Upload date was never updated. Are both of those due to the fact that all of the dates in the .dta file predated the deployment start time? It seems that something should have happened with the file, even if the dates were wonky.

FYI this is job ID 2222664

**Comment by Hussell** [comment]
In job 2222615, a few minutes earlier, you uploaded exactly the same file - 10_28_fieldbarn.DTA - which is why the tag finder reported "the .DTA files have no new data, so the tag finder will not be run". This doesn't help answer your question about the dates, but it might resolve some confusion.

**Comment by jsayers-bsc** [comment]
Ha, yeah that would solve that little bit. I recall that now. It was several weeks actually and I just searched through my mail for the data file to get the notification. Guess I missed that part!

On Jan 9, 2020, at 16:10, Jeremy Hussell <notifications@github.com> wrote:

﻿

In job 2222615, a few minutes earlier, you uploaded exactly the same file - 10_28_fieldbarn.DTA - which is why the tag finder reported "the .DTA files have no new data, so the tag finder will not be run". This doesn't help answer your question about the dates, but it might resolve some confusion.

**Comment by Hussell** [comment]
The last probably-correct date in the file is 06/13/19  10:01:13.5105, so this is certainly an example of a <a href='https://en.wikipedia.org/wiki/GPS_Week_Number_Rollover'>GPS week number rollover</a> error.

**Comment by jsayers-bsc** [comment]
I'm not too familiar with the GPS Rollover issue but was just doing some reading about it (also from the other git threads). It appears that the date of the issue was very specific to the date of April 6/7 2019. The seemingly valid dates here are from June 2019, so maybe the date switch to 1963 was caused by something else?

**Comment by Hussell** [comment]
https://xkcd.com/1179/

**Comment by jsayers-bsc** [comment]
It’s a little crazy the dates in the data files are actually recorded in that format to begin with!
