### ISSUE TITLE
False detections of CTT tags can match real deployed tags

### ISSUE THREAD

**Issue by jsayers-bsc** [MotusDev/Motus-TO-DO#659]
Though the CTT tags use a different coding method than Nanotags, false positives do occur. Rather than just being background noise that may or may not resolve to a pattern that appears to be a tag, when CTT false detections show up, they _appear_ both in the web interface and raw data to be proper tags, complete with ID. Which can be confusing if you aren't expecting them!

Over the course of testing the SensorStations I noticed quite a few of these false detections show up. Usually they share the beginning few digits with one of the 1-4 real CTT testing tags here, but with the final few digits altered. Lucas has noticed the same when running his SS. Bob mentioned there is a known effect where in some cases the end of the code could get corrupted and interpreted as a different code. For instance 61330766 could become 61330000.

![image](https://user-images.githubusercontent.com/55001144/72572479-ab621780-3890-11ea-9bec-d4fa3430df01.png)
_Only four of the CTT detections above (the 8 digit codes) are actually real tags present during this test._

The idea, as I understand it, is that, once passed back to CTT, the detection data will be cross-referenced with the list of actual known tag ID's and any that don't match will be presumed false and removed.

I never made much more of the this until a few days ago, when detection data was uploaded to CTT and passed back over to Motus. Upon looking at the detection data it seems that at least some of these false detections in fact the ID's of real deployed tags.

[Here are detections from one of the SensorStations deployed at BSC](https://motus.org/data/receiverDeploymentDetections?id=5771). You can see our 4 test tags, but you can also see a handful of other detections. In fact 7 of the "false" codes seemed to match real deployments. They do appear to be real deployments and not tests since there are band numbers in the deployment records.

A similar pattern can be seen in the [SS that Lucas has been running as a test](https://motus.org/data/receiverDeploymentDetections?id=5880), which recently uploaded its data. He's had 2 test tags running, which you can see in his detections. But there are also many other tags which appear to be false positives that matched the ID of a real tag.

It's unclear how common this. We've picked up false tags now on all our stations, as has Lucas. But many of these are the same codes "detected" by the stations in New Brunswick and in Ontario, so it's related to particular tag IDs. Though Lucas's has picked up some others too, that never showed up here.

Obviously false positives of a couple different kinds occur with the Nanotags, and they can't always be readily identified or dealt with as well as we'd like. But we have a better understanding of how and why they occur ("we" collectively, not so much me personally!). The false positives with CTT tags likely have a different root cause and may have to be dealt with differently as well. I've passed this all along to CTT as well just so they also are aware of this. I'll add any information from them here as a comment.

**Comment by denislepage** [comment]
Correct that we are relying on CTT to filter out any detection that doesn’t relate to a known tag based on their list. Any raw data that we get ourselves gets passed to CTT and they send them back to us.

The theory is that if tag numbers of false positives are random, you should get 1 in 4 billion chance of matching a real specific tag for every hit (times however many CTT tags are in the system). Say there’s 10,000 tags (we’re not there yet), that means that you’d get by change 1 false positive of a known tag for every 400,000 hits.

They are doing already a lot of filtering on the receiver dongle itself, which has reduced by a couple order of magnitude the number of detections (presumably most of them false) compared to early Cornell versions.

I would thus still strongly recommend treating single hits with caution. But, if things are entirely random, the probability of getting 2 or more detections of the same false positive in consecutive detections should be astronomically small. Based on the above, the chance of having 2 consecutive detections of the same number that matches a real tag by chance should be 400,000 times 4 billion.

Granted, not everything is necessarily random. Some tag numbers may be more likely than others just by the nature of the encoding.

Anyway, my point is that single false detections are probably unavoidable. Even if they are rare, we also get lots of data. Using the concept of run length is still a valid way to minimize the probability of false detections. My intuition is that the amount of suspect detections should fall dramatically if you only look at run lengths of 2 or more, but this remains to be looked at.

Also, I should point out that the runs in the case of CTT are build slightly differently than Lotek’s. The code makes no assumptions or validation of the intervals between bursts. The code simply puts all detections of a given tag number in the same run so that consecutive detections are not made more than a few minutes apart. I’d have to look up what value I used, but this was picked arbitrarily (by me). In most cases, the runs that we are interested in will be consecutive bursts every second or so. Conditions for a valid single hit should be relatively rare.

**Comment by cjardine-bsc** [comment]
This lends the questions of whether we should set the motus filter = 1 for run length = 1 for CTT tags. 

Discuss?

**Comment by StuMackenzie** [comment]
Thanks for opening this can Catherine. First thing is that I think we should punt it to CTT to see what they think? Second, test ourselves and see what we think. Part of me thinks we should keep it the same, especially for public outputs. Users can then view and use all data if they wish.

**Comment by denislepage** [comment]
No, probably not yet, and not unless we have evidence that there are enough of them to be problematic. I suspect many (most?) will be valid detections. Users will just have to be made aware. We also don’t know for sure that my rules about runs for CTT data are doing what I think they are.

Something we’ll need to explore.

**Comment by denislepage** [comment]
Right. I guess the filter = 1 would only hide the data from public output, but still make it available to users in the R package.

There’s probably a good rationale to do that, but we probably need a bit more intel.

**Comment by jsayers-bsc** [comment]
There do seem to be a fair number of codes making it through via the R package that are just false detections. By a "fair number" I mean about 30 to 40 in a one or two month period... I'm not sure if that's a lot, or a little. But it doesn't seem that CTT is strictly comparing codes that are "detected" with codes known to exist on real tags and eliminating the ones that don't match. There may be a very good reason for that, but that's not what _appears_ to be happening anyway.

About a third of those tags have hits with runLen > 3, sometimes by quite a lot (up into the tens of thousands). However, of those, most are filtered out by whether there is a deployID. So of the false detections that matched real deployments for this particular receiver, all but one was filtered out by runLen > 3, so that's good. The exception is a doozy: [61330000](https://motus.org/data/tagDeployment?id=26388), which seems to be "detected" quite regularly every time CTT tags are listened for (on the ~10 receivers we've tried). 

What filter is being applied on the [detections table](https://motus.org/data/receiverDeploymentDetections?id=5771) then, and does it currently differ for CTT tags? As far as I can tell now, only one of those CTT tags has run length > 3.  Either way it looks like many more likely bogus detections show up in the public view for CTT tags than with Nanotags. That's really obvious for this [deployment](https://motus.org/data/receiverDeploymentDetections?id=5880)!

There is the question of how many real tags exist with codes that match commonly corrupted sequences. We've seen several already, but most look like they can be filtered out by run length. Maybe 61330000 is unique...?

**Comment by leberrigan** [comment]
I have just gone through the data collected by the station at my place [CTT-867762040716513](https://motus.org/data/receiver/deployment/detections/timeline?id=5880&year=2020). These data were downloaded through the Motus R package. The only tags that are actually present are **61337F00** and **6134342D**.

Here are some more plots to chew on:
![CTT_detectionCounts](https://user-images.githubusercontent.com/35931796/75478855-03eb0100-5975-11ea-9fef-ae482c2764a6.png)
![CTT_detectionRunLengths](https://user-images.githubusercontent.com/35931796/75479068-55938b80-5975-11ea-8729-55e766472ac2.png)

In total there are 49 false tags 'detected', 4 of which only share the first 2 digits with the true tags. Two of those four tags have run lengths that are greater than 10.

**Comment by jsayers-bsc** [comment]
The [filtered tag detection summary](https://motus.org/data/receiver/deployment/detections/timeline?id=5880&year=2019) should give an indication of how many of those false positives matched real deployed tags (assuming they are real tags as they have band numbers associated with the deployments). There is some overlap between the two years. One of our test tags that was here at BSC the whole time showed up there for an afternoon apparently! 

But then again, and oddly, neither physical Life Tag you mentioned shows up in either the detections [timeline ](https://motus.org/data/receiver/deployment/detections/timeline?id=5880&year=2020)or [table](https://motus.org/data/receiverDeploymentDetections?id=5880).  

When I summarize the tags detected with runLen > 3 I get something that looks a lot like the tags present in your plots, not surprisingly. But why is there so much difference between this and the public detections?

![image](https://user-images.githubusercontent.com/55001144/75485280-68f42600-5978-11ea-99a3-7bc80b8c3ad5.png)

**Comment by StuMackenzie** [comment]
Closed in deference to https://github.com/MotusDev/Motus-TO-DO/issues/853 unless separate action can be identified.
