### ISSUE TITLE
Suggested modifications to Nodes entry page

### ISSUE THREAD

**Issue by jsayers-bsc** [MotusDev/Motus-TO-DO#661]
After entering Nodes for the first time I have a few comments and suggested modifications to make the process simpler.

- Currently every time a new node is entered and page is saved, it reverts to the Antennas tab, instead of back to the Nodes tab.
- Nodes can add up pretty quickly. This one I was looking at had 27 at one SensorStation. A "Select All" option would be helpful for deleting 
- Bulk entry, such as by uploading a csv, would be useful as well.
- There is no way to enter dates. Generally these would match the deployment but there may be many situations where the node dates do not match the deployment dates.
- Can we clarify what ID should be entered, the CTT_ID or the Local_ID. I'm assuming it should be CTT_ID but am not positive.
![image](https://user-images.githubusercontent.com/55001144/72728002-56f1bd00-3b5a-11ea-9868-2cce16da8eaa.png)

**Comment by jsayers-bsc** [comment]
As discussed yesterday, it would also be helpful to copy Node data over along with antennas, location, etc, whenever a deployment is copied from a previous deployment.

**Comment by pmorrill** [comment]
I have updated the interface to fix your first point above: the tab should be 'remembered' after you save node data (test this on beta server).

But like you, I have no idea which number is being entered as 'Node Number'. Catherine or Denis can answer, please?

Which ever it is, we should also set a pattern match against it so that we control the 'valid' entry of that field. Tell me what the pattern would be.

**Comment by denislepage** [comment]
I think we resolved this on the call today, but nodeNum is the alpha code (max 8 chars), which is called CTT_ID in the table above.

Where does this table come from? Who generated this Local_ID field? It seems like there’s a risk that people will use that number instead of the CTT_ID. We should also check with Bob whether strict numeric values are valid CTT_ID, and if not, we could make them invalid. If the table is a standard that people will often use, we could add a reference to CTT_ID in the interface to reduce the risk of confusion.

I know we had talked about talked in the past. Those are still in the table. Are we currently allowing them in the web edit page? When people move their nodes around regularly, the recommendation is probably to treat them as “mobile” and rely on node GPS data. But for those that are stationary, or may not exactly match the deployments, we either have the option of forcing a new complete deployment, or allowing date ranges that are constrained within the deployment dates.

I think my preference is for the latter (allowing dates), but I know there were arguments against it in earlier discussions.

Adding the ability to upload node data in CSV format would indeed be great! Are we including the node table as part of our CSV template download yet? That should be the basis of allowing uploads.

**Comment by pmorrill** [comment]
Is it reasonable to convert the node numbers all to UPPER case when we save them? That looks to be the  convention, in the table above.

**Comment by cjardine-bsc** [comment]
We have data in det_node_data that have nodeNumber as strict numeric values. 

I suspect the local_id in Josh's table came from an email from CTT with node configurations for existing sensor deployments. I'm hoping the users never see this, but we'd need to ask CTT. 

The CTT ids we get via an automated process come in as part of the registration process for sensors and tags, but not nodes. I we've not set up a registration process for the nodes themselves (I'm not sure we would want to). The users populate their node metadata on the deployment via the motus website. 

The CTT ids we get for sensors and tags are stored in the api_import_tables but are never visible to the user. 

@pmorrill you and I should work together to look into bulk node deployment uploads once we've finalized the node metadata management page.

**Comment by denislepage** [comment]
Took me a while to check, but the incoming ID for nodes appears to be lowercase. I can’t guarantee that it is consistent.

I think we should actively make sure they are of the same case in both the data and the metadata, or it will create issues in R (case-sensitive).

Given that the data appears at least mainly lower-case, I would go with lower-case for everything. I can make sure to enforce that in the data import, though it may be worth checking with CTT and ask if they have a recommendation, or suggest that they should also be consistent.

**Comment by jsayers-bsc** [comment]
That's great how the page does not revert once saved! Minor irritation averted :)

One thing that becomes clear very quickly: manually entering these is very tedious (not to mention prone to errors). Some method of bulk entry is probably the biggest improvement that could be made. But I don't know if any of us have seen how the node data (such as the table David provided) comes off the SensorStation, or if it even does at all, though I'm assuming that table wasn't manually entered.

A few other things...

- Now that we know which of the two ID numbers to use for entry (CTT_ID), maybe we can reflect that in the column header for that data entry field (or at least elaborate in the tool tip).

- Select All option for deleting nodes would be helpful, but that's definitely lower priority.

**Comment by pmorrill** [comment]
Re: bulk node data upload. The procedure we have used for deployments is to allow the PI to first download, then edit, a csv template for their deployments. This allows us to control the format. The PI can change existing records, delete, or add new records.

I think this is what we want to do for node data as well. And possibly for antenna data?

@cjardine-bsc @denislepage Should the downloaded template for nodes be basis of entire project? Or should we just allow a receiver-specific download? (We could support both easily enough I suppose).

I can get the template download built, then an upload in sandbox, then @cjardine-bsc can do some magic in the database to update records, etc.

**Comment by jsayers-bsc** [comment]
Closing until we have more dealings with nodes and no if/how to improve this
