### ISSUE TITLE
Whip, monopole, and omni antennas on the website...

### ISSUE THREAD

**Issue by jsayers-bsc** [MotusDev/Motus-TO-DO#666]
Project 304 has a receiver with one whip (omnidirectional) antenna. In the [deployment record](https://motus.org/data/receiver/deployment/edit?projectID=304&id=5889), a bearing was required, which they left as 0. Given that, it then showed up in the receiver map (when ranges are shown) as if it was a directional antenna pointing north. 

I'm not sure if they tried but were unable to change it, but when I deleted the bearing it worked fine, and the antenna range then showed up as a circle. 

That has raised a few questions, comments, and suggestions:

- There is no "omnidirectional" option explicitly in the antenna list. [This has come up before](https://github.com/MotusDev/Motus-TO-DO/issues/401), but it still feels that the word "omni" should be in here somewhere. Just about everyone refers to their non-directional antennas as "omni" antennas, are often confused when they don't see any antenna listed as omnidirectional in the list. 
- Can either Monopole or Whip ever _not_ be omnidirectional? I suspect not, and if that's the case maybe we can change these to something like "Whip (omnidirectional)" and "Monopole (omnidirectional)" for clarity?
- I'm personally unsure of the difference implied between monopole and whip antennas (a whip antenna is in fact a kind of monpole antenna). Given some of the comments I've received I suspect many people share my confusion and have selected one when they meant the other. The individual mentioned above selected Monopole for some receivers and Whip for another, though I suspect they are referring to an identical set up and just clicked something different when creating one of the deployments. Is there any way we can clarify this beyond the one line in the drop down?
- Any antenna that is omnidirectional probably should just have the bearing field greyed out. I suspect that was the case at some point since directionality for each antenna type is recorded
- Monopole and whip are shown with greatly different ranges in the map, even with the height is defined the same.

![image](https://user-images.githubusercontent.com/55001144/73289033-fd2c6b00-41c9-11ea-93e9-3af61e2b9b28.png)

Uppermost receiver has a "whip" antenna at 35m

![image](https://user-images.githubusercontent.com/55001144/73289139-2a791900-41ca-11ea-854e-e4b0b9ae6315.png)

Uppermost receiver has a "monopole" antenna at 35m

**Comment by cjardine-bsc** [comment]
Lets let Stu or Lucas weigh in and if they agree I'll change the antenna descr provided.

**Comment by StuMackenzie** [comment]
All the suggestions for clarity seem fine. There shouldn't ever be a direction for omni/whip/monos - they point up.

We don't have a good gauge of what the detection range for omni's should be. What's the current numbers used?

Whips are just the little guys, or ones that would be placed on a car, but even them they're omni's.

**Comment by cjardine-bsc** [comment]
Lookup updated.

**Comment by Hussell** [comment]
Omnidirectional antennas have a really short range compared to directional antennas. The ones listed as "monopole" are displayed better on the map, the whip antennas with no bearing given are just getting a generic circle with ~15km radius. (The map was made before we had an option for whip antennas, so it's just reverting to the generic behaviour for an unknown or missing type of antenna with no bearing. In practice missing antenna types at that time almost always turned out to be yagi-9s, which have a roughly 15km range.)

**Comment by StuMackenzie** [comment]
We should probably give  all these types the same range. That OK? 500 m would be generous until we have more detailed information.

**Comment by Hussell** [comment]
Josh, I've changed the display of some types of receivers on the beta server. Have a look for anything I missed. https://beta.motus.org/data/receiversMap

**Comment by StuMackenzie** [comment]
On the  receiver map - Can we align 434 MHz antenna ranges with those found on 166 MHz based on the number of elements? Can we see the table of current ranges used and we’ll suggest some mods?

**Comment by jsayers-bsc** [comment]
Reopened #666 eh. Do you really want to revisit this or is this all because it’s Halloween weekend? :)

________________________________

**Comment by StuMackenzie** [comment]
What we’re displaying now is not an accurate representation.

S

____________________

**Comment by Hussell** [comment]
The current system is this:
 * If there are no antennas listed then show a 15km radius circle.
 * If an antenna type is "omni-mast", "omni-whip", "j-pole", or "monopole" then show a small circle (~1.6km radius).
 * If an antenna has no bearing then show a 15km radius circle.
 * If an antenna type is "yagi-9-laird", "yagi-9", "yagi-9-maple", "custom-9", or "yagi-8" then show a yagi-9 pattern (narrower than yagi-5, slightly less than 20km range).
 * If an antenna type is "yagi-6", "yagi-5", "custom-6", or "yagi-4" then show a yagi-5 pattern (wider than yagi-9, slightly more than 10km range).
 * Otherwise show a fake antenna pattern (a geometric shape which vaguely resembles a real antenna lobe pattern, ~10km range).

The fake geometric antenna shape was originally used for every antenna with a bearing, before we got our hands on the yagi-9, yagi-5, and omnidirectional antenna patterns. We're showing the yagi-9 pattern for yagi-8s, and the yagi-5 pattern for yagi-4s and yagi-6s, because they would be similar enough, and we don't have patterns for them. We're also showing yagi-9 and yagi-5 patterns for custom-9 and custom-6 antennas respectively, though the similarity is more questionable.

The patterns are ranges (signal gain relative to a reference range) at each angle (relative to the bearing of the antenna), so a list of 360 gains (actually 181 since the patterns are symmetric), with interpolation between degrees. The patterns (including the omnidirectional range) all came from the same source, now forgotten.

Current antenna types in the database are:

type|count
-|-
yagi-9-laird|4176
yagi-9|2728
yagi-6|1189
yagi-5|572
omni-whip|394
custom|344
yagi-9-maple|304
omni-mast|237
custom-9|213
yagi-3|207
yagi-8|185
none|156
monopole|127
custom-6|100
j-pole|88
yagi-4|51
NULL|27

It would be helpful to have patterns for yagi-6, yagi-3, yagi-8, and yagi-4, in descending order of priority. It would be helpful to know of any known differences in range between the various types of omni-directional antennas. It would be helpful to know if there are any common antenna types hidden in those 600+ "custom" antennas, and to have patterns for the most common ones. If there's a difference in range depending on the frequency the antenna is listening for, it would be helpful to have an equation for that.

**Comment by StuMackenzie** [comment]
Thanks this is all helpful. All questions that we don't have answers to.

S
