### ISSUE TITLE
Adding Spanish language option to Motus

### ISSUE THREAD

**Issue by leberrigan** [MotusDev/Motus-TO-DO#688]
With the growing network in Latin America, there is an increasing demand for Spanish on the Motus website. Is is a easy to add a third language option to the website? Obviously we will need to get all the text translated before we make this option available, but I thought I'd ask this to get the ball rolling.

**Comment by Hussell** [comment]
I've done my best to make sure it will be easy to add a third language, nonetheless there are many places where we'll need to change code to do a third thing once there's a third language. The first step would be to add Spanish placeholders for all text fragments on the sandbox, probably from Google Translate, do the minimal viable code changes needed for a new language, then do a systematic review of every page in sandbox looking for English (or French) remaining on Spanish pages, making the necessary changes for each page as we go.

Many of the required changes aren't in the code, but in the database, where we have many tables with a pair of columns containing an English description and a French description of something. Rather than add a third column on every one of those tables, I think we should take this opportunity to replace them with a text fragment key for the description. That would allow us to replace a lot of language-specific code (e.g. If French then select description_fr else select description_en, which would need to be changed anyway) with text-fragment based handling which won't need to be changed every time we add a language, and would make it a lot easier to be certain we haven't missed anything which needs to be translated. (Even now, I'm not certain all the error messages, data issues messages, and lookup table descriptions are in sync, and that's just with two languages.)

**Comment by denislepage** [comment]
Yes, I would support moving to fragments if we decide to support a third language+, but this is not a small task, with at least 60 fields that exist now in both languages.

It's relatively easy to extract the list of fields from the information schema, looking for any field names that end with _fr.

Adding new text_id fields to those tables, and generating new fragments could all be automated relatively simply in the database. Changing the software to switch to those fields is potentially where most of work resides.

Before we jump on this, a first priority step would be to create documentation, I think. Someone would have to volunteer to take this on or find funding.

**Comment by leberrigan** [comment]
To be clear, we need not translate the entire website at once. We still need to attract an audience before Latin American researchers begin jumping on board. The main thing to start with will be the public pages.

What type documentation are you asking for? To describe text fragments?

**Comment by denislepage** [comment]
No, I meant the same as you. The documentation for users on the Word Press site that are not part of the research platform: PDF, web pages, etc. Based on current needs, I am not convinced there is a need to fully translate the management tools in multiple languages anytime soon. There's plenty of other things we can start picking at, I agree.

**Comment by StuMackenzie** [comment]
Closing because we all know it to be a need/want.

**Comment by Hussell** [comment]
First step done: all text fragments now have a Spanish placeholder. The rest can and should wait until after beta10 goes live.
