### ISSUE TITLE
Our registered/deployed test tags show up in the plots as NO_PROJ#999999 M.0

### ISSUE THREAD

**Issue by j-sayers** [MotusDev/Motus-TO-DO#694]
We've had several test tags here over the past couple months and I've been noticing that they often appear in the data as NO_PROJ#999999 M.0. These are tags that are registered and have deployments. 

For instance, [tagID 43243](https://motus.org/data/tags/edit?projectID=1&id=43243), which has been active here for the past week or so, shows up with this full name in the [plot](https://motus.org/data/receiver/deployment/plot/?id=5926). Downloaded via R, it has the expected full-name.

fullID | tagProjID | totalHits | minRunLen | maxRunLen
-- | -- | -- | -- | --
MotusON#4.2:10.1@166.38(M.43243) | 1 | 17723 | 4 | 3077
CTTTEST#4:10.1@166.38(M.34335) | 251 | 17723 | 4 | 3077
?proj?-0#9:19.3 | 231 | 5 | 5 | 5
 
(The 3rd tag is one of the ones mentioned [here](https://github.com/MotusDev/Motus-TO-DO/issues/693), that was registered with a default deployment but that didn't end up with a deployment)

The CTTTest tag has identical properties apparently. 

Which brings up another point with may or may not be relevant: none of these test tags are unique. We have two groups of identical tags. I've also noticed this NO_PROJ#999999 M.0 id at another [deployment ](https://motus.org/data/receiver/deployment/plot/?id=4986)where we sent one of these test tags. 

I also don't recall these test tags showing up in the detection tables, though other test tags do.

**Comment by jsayers-bsc** [comment]
A bit more about the other deployment I mentioned above, who we sent a test tag to...

![image](https://user-images.githubusercontent.com/55001144/75820456-5f006780-5d6a-11ea-8f9a-82773de68bff.png)

At the bottom (row 18) you can see their Test Tag, with its proper fullID. Below that you can see one of our test tags, which was here the whole time, but since its properties are identical, it's also being "detected" here. It also shows up with its proper fullID.

But in the detection plot, all we see is one count of NO_PROJ#999999 M.0. The real test tag does not show up in the [detection table](https://motus.org/data/receiverDeploymentDetections?id=4986) (and neither does the ghost tag, unsurprisingly).

There's probably an obvious reason why this is happening that I'm just missing...

**Comment by Hussell** [comment]
NO_PROJ is the project code for project 0, and 999999 is the fake manufacturer's code for tag ID 0, which is assigned to project 0. I'll investigate more tomorrow, but it looks like the first layer of this puzzle is that the tag ID being returned is 0.

**Comment by Hussell** [comment]
The two tags with identical properties result in an ambiguous detection: the tagfinder can't tell which of those two tags it should be, since they're deployed simultaneously. In the daily summary table (det_taghits_daily) all ambiguous detections are reported as tag ID 0. So all ambiguous detections are lumped together under NO_PROJ#999999 M.0.

**Comment by StuMackenzie** [comment]
We may want to discuss handling this issue more eloquently. 

There are and always will be numerous identical test tags with overlapping deployments across multiple project. We can try to start being more prescriptive about what codes we allow or use for this. Currently it’s mostly 3 &4.

Stu

____________________

**Comment by jsayers-bsc** [comment]
Interesting that they are assigned to NO_PROJ#999999 M.0 in the detections plot, appear with their proper fullID in the R package, and don't appear at all in the detections table. I suppose is due to various levels of filtering, which makes sense now that I know what's going on...

But this does raise some issues...

As Stu mentioned, most of the designated test tags are only one ID. This makes sense from the perspective of not wasting ID's on tags that will never be deployed on birds. Designated test tags are usually large, with maximum battery life, so they can be used for extended periods.

But as these are all identical, they end up a ambiguous tags. Not a problem in and of itself since these are never intended to be deployed. But those who are using them, _do_ want to see the tags in the detections table / plot so that they can confirm the station is operating, etc.

**Comment by cjardine-bsc** [comment]
They are probably tags that have been merged. In those cases they would come to us as ambigs, but we resolve them upon import to our DB. 

But the plots are made from the MariaDB I believe, where they would still be ambigs.

**Comment by Hussell** [comment]
These plots aren't made from the MariaDB, they're made from the daily summary table on our side. See [#507](https://github.com/MotusDev/Motus-TO-DO/issues/507#issuecomment-553603010).

**Comment by jsayers-bsc** [comment]
I don't believe the tags in question have ever been merged. They were all registered at the same time, and despite having identical properties on paper, I recorded and registered them all individually.

**Comment by jsayers-bsc** [comment]
Seeing some strange stuff with one of our test tags. This is the solar tag (one of a dozen identical ones). So far only one is registered and I've been trying to confirm that each individual tag is detected as that tag.

I noticed the tag show up in the detections table a couple days ago, but since then there has been nothing new. But oddly, while the proper name shows up in the detection table, in R the tag only shows up with fullID **?proj?-0#:0.0** and no associated projectID either. 

In the DB, the tag detections appear as they should, though motusFilter seems to alternate between 0 and NULL with no obvious pattern. Sample below... there are some records with motusFilter = NULL with n_hits > 2 that aren't in this sample, though most of the NULL motusFilter records have higher n_hits values...

![image](https://user-images.githubusercontent.com/55001144/78698179-eee88280-78cf-11ea-8f8d-28f48f754ca2.png)

![image](https://user-images.githubusercontent.com/55001144/78698282-18a1a980-78d0-11ea-8262-5232c1ec3011.png)



tag_project | tag_deploy_id | batch_id | run_id | min_date | n_hits | ambigID | motusFilter
-- | -- | -- | -- | -- | -- | -- | --
322 | 27722 | 999170 | 64853669 | 2020-04-03 | 437 | NULL | NULL
322 | 27722 | 999170 | 64853670 | 2020-04-03 | 3 | NULL | 0
322 | 27722 | 999170 | 64853671 | 2020-04-03 | 2 | NULL | 0
322 | 27722 | 999170 | 64853672 | 2020-04-03 | 3 | NULL | 0
322 | 27722 | 999252 | 64853672 | 2020-04-03 | 3 | NULL | 0
322 | 27722 | 999252 | 64853991 | 2020-04-03 | 11 | NULL | NULL
322 | 27722 | 999252 | 64853993 | 2020-04-03 | 50 | NULL | NULL
322 | 27722 | 999252 | 64853995 | 2020-04-03 | 2 | NULL | 0
322 | 27722 | 999252 | 64853996 | 2020-04-03 | 2 | NULL | 0
322 | 27722 | 999252 | 64853997 | 2020-04-03 | 3 | NULL | 0
322 | 27722 | 999252 | 64853999 | 2020-04-03 | 18 | NULL | NULL
322 | 27722 | 999252 | 64854000 | 2020-04-03 | 51 | NULL | NULL
322 | 27722 | 999252 | 64854002 | 2020-04-03 | 4 | NULL | NULL
322 | 27722 | 999252 | 64854003 | 2020-04-03 | 687 | NULL | NULL
322 | 27722 | 999786 | 64854003 | 2020-04-03 | 5088 | NULL | NULL
322 | 27722 | 999786 | 64877245 | 2020-04-03 | 2 | NULL | 0
322 | 27722 | 999786 | 64877247 | 2020-04-03 | 279 | NULL | NULL
322 | 27722 | 999786 | 64877248 | 2020-04-03 | 4 | NULL | NULL
322 | 27722 | 999786 | 64877249 | 2020-04-03 | 46 | NULL | NULL
322 | 27722 | 999786 | 64877250 | 2020-04-03 | 2 | NULL | 0
322 | 27722 | 999786 | 64877251 | 2020-04-03 | 9 | NULL | NULL
322 | 27722 | 999786 | 64877253 | 2020-04-03 | 428 | NULL | NULL
322 | 27722 | 1000005 | 64877253 | 2020-04-03 | 2263 | NULL | NULL
322 | 27722 | 1000005 | 64887305 | 2020-04-04 | 23 | NULL | NULL
322 | 27722 | 1000005 | 64887307 | 2020-04-04 | 2 | NULL | NULL
322 | 27722 | 1000005 | 64887308 | 2020-04-04 | 23 | NULL | NULL
322 | 27722 | 1000005 | 64887310 | 2020-04-04 | 2 | NULL | NULL
322 | 27722 | 1000005 | 64887312 | 2020-04-04 | 324 | NULL | NULL
322 | 27722 | 1000226 | 64887312 | 2020-04-04 | 2845 | NULL | NULL
322 | 27722 | 1000226 | 64887957 | 2020-04-04 | 3 | NULL | 0
322 | 27722 | 1000226 | 64887958 | 2020-04-04 | 11 | NULL | NULL
322 | 27722 | 1000226 | 64887960 | 2020-04-04 | 2 | NULL | 0
322 | 27722 | 1000226 | 64887961 | 2020-04-04 | 3 | NULL | 0
322 | 27722 | 1000226 | 64887962 | 2020-04-04 | 74 | NULL | NULL
322 | 27722 | 1000485 | 64887962 | 2020-04-04 | 2811 | NULL | NULL
322 | 27722 | 1000485 | 64888719 | 2020-04-04 | 5 | NULL | NULL
322 | 27722 | 1000485 | 64888720 | 2020-04-04 | 2 | NULL | 0
322 | 27722 | 1000485 | 64888722 | 2020-04-04 | 6 | NULL | NULL
322 | 27722 | 1000485 | 64888724 | 2020-04-04 | 8 | NULL | NULL
322 | 27722 | 1000485 | 64888727 | 2020-04-04 | 6 | NULL | NULL

**Comment by jsayers-bsc** [comment]
Does anyone know how `NO_PROJ#999999 M.0` relates to `?proj?-0#:0.0`?

**Comment by jsayers-bsc** [comment]
Better documentation of tag IDs would be helpful.
