### ISSUE TITLE
Process for re-running search for corrected tag deployment?

### ISSUE THREAD

**Issue by adamdsmith** [MotusDev/Motus-TO-DO#702]
This is likely answered elsewhere, but a search proved fruitless. 

What's the process/schedule for a complete rerun of tagfinder to accommodate updates to tag deployments? I had associated a deployment with the wrong tag so in that particular case tagfinder was looking for the wrong tag. This is obviously not urgent.

**Comment by Hussell** [comment]
We have enough archived data now that a complete rerun, though technically possible, would take several months and prevent any new data from being run at the same time. Instead we are rerunning smaller blocks of data on a schedule based on how old the data is and how long ago it was last run. The main reason we do this is because tag deployments get corrected after-the-fact in relatively large absolute numbers (though small as a percentage of all tag deployments). Currently almost all receiver data is rerun ~2 months after it comes in, and older data is rerun less and less frequently the older it gets. This week there are 85 receivers which will have some part of their data rerun, and in January and February 883 and 526 blocks of data were rerun, respectively. (Many of those were rerun manually and multiple times, as part of debugging - I don't have a quick way to separate out why each block of data was rerun, after the fact. More debugging reruns have been done these past two months than normal, as part of sorting out the overlapping boot numbers issue.)

So, if the tag you changed was deployed less than 2 months ago then you can expect most detections will appear within 2 months. Anything older than that will take longer to be rerun, but eventually it will all get done.

In some cases I can still manually rerun a span of data from a small region in a reasonable amount of time, and I'll continue to consider such requests on a case-by-case basis. For these it helps a lot if you can send me a list of the tag IDs you're looking for so I can narrow the reruns to just the span of time the tags could plausibly have been active, and a list of the receivers where they might reasonably have been detected.

**Comment by adamdsmith** [comment]
Thanks for the explanation. Again, it's not urgent as it's a single tag, but I'll get you a list of plausible recvDeployIDs and a date range.

**Comment by adamdsmith** [comment]
@Hussell At your convenience, here is a [list of relevant receiver deployment IDs](https://github.com/MotusDev/Motus-TO-DO/files/4345249/rekn_receiver_deployments_of_interest.xlsx)
 to search for tag 21970, from 2019-05-06 through 2019-11-01. Thanks!
