### ISSUE TITLE
Tracks and timelines only visible to logged in user

### ISSUE THREAD

**Issue by leberrigan** [MotusDev/Motus-TO-DO#705]
This is related to #685 as discussed last week. We need to change permissions for both tag detection timelines and tracks so that they are publicly available. Currently:
- The public can only see the banding location when looking at individual tracks. There is no explanation that you need to log in, either so most collaborators just assume they don't have any detections or they get confused.
- The public can't see any detections, but at least there is a disclaimer explaining this.

I think we agreed on the last call that these need to be opened up to the public.

**Comment by Hussell** [comment]
The data comes from the views, and the access to the semi-public data causing the issue is controlled by the securables "taghits", "gps", and "receivers_logs". So in lk_securables we'll have to lower min_access_level from 1 to 0 to allow non-administrators to make the data publicly accessible, and lower default_access_level from 1 to 0 to make the data public by default for all future projects.

Then we'll have to decide whether to make the data public for existing projects, by changing the settings recorded in projects_securables. Currently there are 13 projects which have set a higher access level for taghits, 2 which have made it public (which could only have been done by an administrator), and 223 with the default access level. There are 7 projects which have set a higher access level for gps and 5 which have made it public. There are 4 projects which have set a higher access level for receivers_logs and 9 which have made it public.

I don't recall reaching consensus on whether or not we should notify all the projects that we're going to change their settings, or whether we should change all projects' settings or just the ones on the default level.

**Comment by Hussell** [comment]
Alternately, or additionally, everywhere data is accessed, add code to differentiate between "no data exists" and "data exists, but you can't see it" and inform the user about which case is occurring. A (very) few of the pages created more recently already do this.

**Comment by leberrigan** [comment]
Thanks Jeremy. Now I have a two more questions!

- Why is it that these data are visible to _any_ logged in user, not just collaborators on a project? It seems like this level of data access is only present for these two cases (tracks and timelines). I ask this again because it seems strange to me that logged in users have access to these securables, but only collaborators have access to tag hits and data downloaded thru R.

- Why is it that we still have the ['View Tracks'](https://motus.org/data/tracksSearch) publicly accessible when it shows the exact same amount of information as the individual tracks?

---

So what do we have to do to make these changes happen?

> I don't recall reaching consensus on whether or not we should notify all the projects that we're going to change their settings, or whether we should change all projects' settings or just the ones on the default level.

Let's decide on this today:

  **Question 1:** Notify all projects that settings are changing -or- ASK if settings can be changed

  **Question 2:** Change all projects -or- just ones with default settings for those securables

**Comment by Hussell** [comment]
One of our goals for this year is to make the R package consistent with everything else. It's way more restrictive about what you can and can't download than anything else, mostly through inertia due to a lack of R programmers.

The "View Tracks" thing originally had the same limitations, but it frustrated everyone so much during the testing phase, before it was released, for us to agree to make it an exception to the normal rules. (You aren't the only one who has wanted to make all of this simpler and more consistent. We just keep getting pulled onto other things.)

**Comment by leberrigan** [comment]
For the time being, you can use the following to refer people to tracks: https://motus.org/data/tracksMap?t=20709

Just change the number at the end with a tag deployment ID of interest.

**Comment by jsayers-bsc** [comment]
Related question from earlier: https://github.com/MotusDev/Motus-TO-DO/issues/644

**Comment by Hussell** [comment]
https://beta.motus.org/data/track?tagDeploymentId=17265

**Comment by Hussell** [comment]
I forgot to ask, do we want an exception for the timelines as well?
