### ISSUE TITLE
Missing summary data - Project 48, Deployment 5498

### ISSUE THREAD

**Issue by StuMackenzie** [MotusDev/Motus-TO-DO#713]
Project 48:
Deployment 5498
Serial: CTT-864459049297849

One of our receivers with a sensorstation, showed data from February 2020, which is now gone and only March data is showing for 2020. This is the receiver, https://motus.org/data/receiverDeploymentDetections?id=5498
and here is an image of the what data was showing in February.

![image](https://user-images.githubusercontent.com/21124211/79144653-53eb1f00-7d8d-11ea-8db4-6e3f48717ab0.png)

 Please respond to Alison Fetterman <avfetterman@gmail.com>

**Comment by jsayers-bsc** [comment]
This looks a lot like one of the false detection events (most occur on the same day).

I checked this date range in R and none of tags had a runLen > 2. They would have showed up here due to the [filtering issue](https://github.com/MotusDev/Motus-TO-DO/issues/707). That's why they disappeared once the fix was applied. 

I'll let her know.
