### ISSUE TITLE
Open access to antenna and GPS activity tables

### ISSUE THREAD

**Issue by leberrigan** [MotusDev/Motus-TO-DO#723]
Continuing with [our theme](https://github.com/MotusDev/Motus-TO-DO/issues/720), I think we should be giving open access to the 'activity' and 'gps' tables for each project. Unless I'm missing something, these don't reveal any information tied to securables so it shouldn't be an issue.

This comes up after a collaborator recently reached out to gain access to projects for this purpose. They would like use antenna activity and GPS data to make a timeline of when stations were actually functioning so they can come up with some metric for probability of detection. If anyone has a good idea of how that could be done differently with data that already is available, do let me know!

**Comment by StuMackenzie** [comment]
thumbs up emoji

**Comment by cjardine-bsc** [comment]
We are including gps as public for the "data summary" access level in our new system (thanks to D-boss!) and I think I'd consider activity data under the sensor deployment securable, so this would fit in the structure we're implementing (yay!). 

I'm guessing you are thinking of having this in the R package? We'd need a new call beyond tagme if we were to do this, since it would need to include validation on both public projects and summary project. 

I'm not sure if the call itself would be by project or receiver or....all? 

A good topic for our next Thursday motus party.

**Comment by cjardine-bsc** [comment]
Next steps:

We need to either create a new function or add an option to the metadata function that will download all records from the vwR_Batches_activity view and vwR_Gps_for_receiver views into R. @pmorrill 

Add a new field to the antenna metadata table in R called antFreq. I've added this field to vwR_Metadata_for_receivers_antDeps, @steffilazerte can you incorporate that field into the R package?

Thanks!

**Comment by steffilazerte** [comment]
It's been added to sandbox!

**Comment by pmorrill** [comment]
Adding these entrypoint to the api. However, for the purpose of pagination, I believe we need to now paginate on the basis of:

R_Batches_Activity
- batchId
- ant*
- hourbin*

R_Gps_for_receiver
- batchId
- gpsId / ts*

* these are already part of the pagination on the queries

Does that seem right Catherine? It means the R-client will need to keep track of the latest/current batchId and submit it back as a parameter when calling for the next page.

**Comment by pmorrill** [comment]
The new entrypoints are:

/api/activity_for_all?json={ }

json structure includes:
- authToken
- batchId (from last call, defaults to zero for pagination)
- ant (from last call, for pagination)
- hourBin (from last call, for pagination)

/api/gps_for_receiver_all?json={ }

json structure includes
- authToken
- gpsId (from last call, for pagination)

**Comment by leberrigan** [comment]
So we just brought this up again in today's conversation, but it sounds like we're still at the stage of deciding whether or not to add a new function. Are we ready to just go ahead on making a function?

**Comment by cjardine-bsc** [comment]
I believe so yes. This would be for @steffilazerte

**Comment by denislepage** [comment]
I think we do. We mainly need to define the properties of the function.

I’m presuming that each request will be limited to a single receiver (deployment?), and we should plan to limit the time range. Additionally, we should think of a way to query for a list of deployments that match some geographic + time criteria.

This isn’t necessarily a straightforward query because I don’t think we have deployment ID’s associated with batches, so we’d have to involve the gps_deploy_id or the hits_deploy_id tables.

I see a few possible approaches:

The simplest is that users have to specify a receiver ID and a time range. The downside is that 1) they need to figure out all the receiver ID’s that are of potential interest to them and 2) the overall period for a given receiver may include data from deployments that fall outside the geographic area they may be interested in, so the date ranges would have to be customized for each receiver. On the database side, this is relatively simple and only requires figuring out a list of batchID’s overlapping the start and end times. That puts the onus on the user to sort out that to query, which isn’t great.

An improvement would be to get a list of receivers that have any deployment over a geographic area and time interval and get the full list of batches from those, regardless of whether they relate to a different deployment. It would give users all the data they need, but also some data they don’t need. That is still relatively straightforward on the database/API side to sort out.

A better version would be to filter the batches by receiver deployments. We could first get a list of all deployment ID’s matching geographic and time criteria simply by querying the metadata records, and then look for batches that match the range of each deployment. I don’t think we would need to provide partial batches, but rather download the entire batch if it overlaps the date requested. The downside to this approach is that it relies on having complete and accurate metadata, so that could potentially perpetuate the issues rather than help fix them.

The Cadillac (Tesla?) version would be to use the actual GPS data. In a way, this is easier as we could directly query the gps table based on the date and geographic criteria, since both elements are in the gps table. The problem with this is that it doesn’t allow filtering the activity table, so we would need to obtain a list of batchID from the GPS query, and then use that to apply to the activity table. That may still be the most accurate option, but we’d have to try it. I don’t think we should try to limit the join to hourBin, since there may be period where we have activity data but no GPS. Using batchID would be better, and we could apply the date filter in both places:

                #get GPS
select * from det_gps b where b.lat between @se_lat and @nw_lat and b.lon between @nw_lon and @se_lon and b.ts between @ts1 and ts2

                #get activity
Select * from det_activity a where exists (select gps_id from det_gps b where a.batchID = b.batchID and b.lat between @se_lat and @nw_lat and b.lon between @nw_lon and @se_lon and b.ts between @ts1 and ts2)
and hourBin  between dbo.hourBin(@ts1) and dbo.hourBin(@ts2)

I think I would go with one of the latter 2 options. The last one will likely require some new indexing.

Never so simple, eh?

**Comment by cjardine-bsc** [comment]
@steffilazerte This is a lower priority task for after you've added the new fields to the r package to support CTT data. 

Once that's done, we are ready for you to start working on this. We're going to begin with a simple unfiltered call that will download all GPS data and a separate call for all activity data. Don't worry yet about Denis' post above. We'll incorporate filtering as a phase II feature. 

Information on the API entry points is available above. Let me know if you need any further detail or instructions.

**Comment by steffilazerte** [comment]
Got it!

**Comment by steffilazerte** [comment]
I can get started on the function to make the request but I have a question about where this data is to be stored. 

Would these be new tables added to an existing motus database? Existing databases currently have `activity` and `gps` tables, so now we'd be adding `activityAll` and `gpsAll` tables, for example?

However, since these are independent of a specific project or receiver, perhaps there should be a new database to hold this kind of data...?

**Comment by cjardine-bsc** [comment]
Excellent question. 

I think I'm in favour of adding it to new tables in the existing motus database, but I'd look to @leberrigan to provide feedback on what is most useful to users.

**Comment by denislepage** [comment]
It may be worth giving people the choice.

They could either provide a db connection object, or a new file name. For simplicity, you could then simply create the entire schema with all the tables, etc.

Would that work?

**Comment by steffilazerte** [comment]
I could, but it might be simpler to choose one and stick to it. It's not difficult to implement, it just might make updating things later on more complex.

**Comment by denislepage** [comment]
CJ, are you creating a new views for GPS and activity that includes details about the receivers (join of batches and GPS)? If not, then the import needs to first get all the batchID’s, which won’t work with our existing calls.

I think separate views that do the join and tables would be better (gpsAll and activityAll sound fine).

I generally think people would want to use this in conjunction with their project data, so if we have to pick one option, I’d probably prefer for the data to go in an existing motus database. Are we allowing them to download the data as CSV (not that we should, I’m curious).

**Comment by cjardine-bsc** [comment]
No, we're using the existing views vwR_Batches_activity and vwR_Gps_for_receiver. Paul has set up two new entry points 

/api/activity_for_all?json={ } 
/api/gps_for_receiver_all?json={ }

There is already a call that provides all receiver deployment data (right?)

**Comment by denislepage** [comment]
GPS only has a batchID, so you need batches to resolve to the receiver number.

**Comment by cjardine-bsc** [comment]
Dang. Denis is right. 

@pmorrill and @steffilazerte I've added recvDeployID to vwR_Gps_for_receiver in sandbox.

vwR_Batches_activity had motusDeviceID which can be joined to vwR_Metadata_for_receivers_recvDeps so I don't think any changes are needed for that one.

**Comment by steffilazerte** [comment]
@pmorrill I'm accessing the activity for all entry point (`custom/activity_for_all`). No matter what values I submit for `batchID`, `ant` or `hourBin`, I get the same set of data (10000 rows starting with `batchID` 53):

```
 batchID motusDeviceID ant year month day hourBin numTags pulseCount numRuns numHits run2 run3 run4 run5 run6 run7plus
1      53           486   1 2015     9  25  400872       1         28       1       7    0    0    0    0    0        1
2      53           486   1 2015     9  30  401014       1         24       1       5    0    0    0    1    0        0
3      53           486   1 2015    10   8  401204       1         24       1       6    0    0    0    0    1        0
4      53           486  -1 2015     9  30  401014       1          8       1       2    1    0    0    0    0        0
5      53           486  -1 2015    10   8  401204       1         24       1       4    0    0    1    0    0        0
6      53           486   2 2015     9  30  401012       1         12       1       3    0    1    0    0    0        0
```

I assumed that pagination would work by my submitting the last `batchID` (integer), `ant` (character) and `hourBin` (integer), or have I misunderstood?

**Comment by denislepage** [comment]
the rules for pagination on multiple fields can be a bit fancy, so there’s a reasonable chance that we are not getting them right. I also just noticed that the negative antenna may potentially be missed if use ant = 0 as a starting point.

One solution to consider is to add a new unique ID key field like we did on the GPS table a while back, which would make pagination much easier.

Otherwise, the rule is something like this (untested):

(batchID > @batch
OR (batchID = @batch and (ant > @ant or @ant = 0))
OR (batchID = @batch and ant = @ant and hourBin > @hourbin)
)
and projectID = @projectID
order by batchID, ant, hourBin

I don’t know if this is part of a proc or custom code. A proc would be ideal.

If we can fix the pagination rule, that might be my preferred choice over add a new key.

**Comment by pmorrill** [comment]
Here's what I am using in the code (we query a view for this data). I am not sure why you are including @ant = 0 in the above version. This looks like it should work - what am I missing?

WHERE batchId > ?
   OR (batchId = ? and (ant > ? OR (ant = ? AND hourbin > ?))

**Comment by pmorrill** [comment]
BTW: ant port is interpreted as a String, since it is stored as varchar in database. The negative sign is a little weird in the above, as we are ordering as:

ORDER BY batchId,ant,hourbin

**Comment by pmorrill** [comment]
I have run some tests against the sandbox (which is the only place this entrypoint is available right now), and it does seem to be working better for me than for Steffi.

@steffilazerte are you working against the sandbox for this testing?

I think that it is time to move this function up to beta code branch: we can discuss this on Thursday's call.

**Comment by denislepage** [comment]
We should confirm if in a string field, -1 comes before or after 0.

My point was that adding  "OR ? = 0" would insure that when the antenna small than 0 will also be included when 0 is provided as the starting point. (unless there are more than 10,000 consecutive rows with a negative ant). Otherwise, I think you'd always be missing negative antennae records for the batchID provided to the API call.

I'd have to play more with this to be sure.

WHERE batchId > ?
OR (batchId = ? and (ant > ? OR ? = 0 OR (ant = ? AND hourbin > ?))

**Comment by pmorrill** [comment]
But, @ant is a string, so will never be 0. In fact, the defaults for all 3 elements are:

@batchId => 0
@ant => ''
@hourbin => 0

**Comment by denislepage** [comment]
I guess I was assuming that the initial call steffi was making was using 0 as the default initial antenna. But, on the initial call, the batchID is zero and the other parameters are irrelevant anyway (initial condition will be batchID > 0, which applies to everything), so that should be good, right?

Any subsequent paging calls should normally use values of the last row returned, which is determined based on the sorted string ant field. As long we we’re not trying to convert the string to a number in SQL commands, I think we’re also ok there.

So, that one seems ok then, but that is a separate issue from what Steffi had raised initially, and I am not sure we have figured that one yet. Your code looks ok, so I am not sure what is happening yet.

**Comment by steffilazerte** [comment]
Ah I think I figured it out, the server expects `batchId` whereas I was sending `batchID`.
I could change what I send, super easy, but I think we should probably update what the entry point expects to `batchID` as that's what the rest of the entry points use (right?).

**Comment by steffilazerte** [comment]
I was able to paginate and access 55738 Activity records, does that sound about right? For some reason I thought there'd be waaaaay more. It was nice and quick though!

**Comment by pmorrill** [comment]
Wow - good catch Steffi. I looked at that code myself and missed it. I work in another project that uses the batchId convention, and typed in the wrong version I guess! I will switch it to the motus standard batchID

**Comment by steffilazerte** [comment]
So I've moved on to all GPS and am getting an error of "Failed to generate GPS coordinates for receiver."

I'm sending the query to "custom/gps_for_receiver_all" and it includes `gpsID` = 0 (or `gpsId` = 0, both result in the same error) for pagination.

What have I missed? Thanks!

**Comment by cjardine-bsc** [comment]
I just saw some errors come in related to this. 

Looks like you're looking for a table that doesn't exist: Sample_R_Gps_for_receiver

We only have sample_r_gps_for_tag_project since we do not allow access to the sample data by receiverID. 

Cheers, 


Error type = 7 - Low-level Database error Error Code = 208 SQL = SELECT top (10000) * FROM Sample_R_Gps_for_receiver a  WITH(NOLOCK)  WHERE a.gpsID > ? and exists(select a.batchID from vwR_Batches_for_receiver_project b where b.batchID=a.batchID and version = 2) ORDER BY a.gpsID Description = API Context prepared statement (Made it to result set wrapper)

Browser info:null
Auth type = null
Method = POST
Query = null
Uri = /api/sgdata/custom/gps_for_receiver_all
All parameters:
	content-length = 123
	content-type = application/x-www-form-urlencoded
	accept = application/json
	Accept-Encoding = deflate, gzip, br
	host = sandbox.motus.org
	user-agent = http://github.com/MotusWTS/motus


Stack trace:
com.microsoft.sqlserver.jdbc.SQLServerException: Invalid object name 'Sample_R_Gps_for_receiver'.

**Comment by steffilazerte** [comment]
So this is a server side issue then? I don't specify the table, that's up to the API entry point... right?

**Comment by pmorrill** [comment]
It looks to be server-side, yes. We will sort it out early next week.

**Comment by pmorrill** [comment]
The question is, will the user see this problem? We have no sample data for 'by receiver' queries. How was this query generated? Is it part of the tagme(projectId) function logic? I'm not up-to-date on the way the client is using this GPS data, or when it queries for it.

**Comment by steffilazerte** [comment]
Ugh it's the motus.sample project problem again, you'd think I'd remember by now not to use this for testing!

At any rate, I would argue that this is a problem for users if this applies to data sets without GPS points. I think it would be better to return 0.

But if this is specifically a motus.sample project-related problem I can work around it, no problem!

**Comment by steffilazerte** [comment]
@StuMackenzie I'm embarrassed to say I'm still working on this 😞

**Comment by steffilazerte** [comment]
`gpsAll()` and `activityAll()` are now available in motus sandbox. Tables `gpsAll` and `activityAll` are created by default but users need to deliberately use the functions to populate them (`gpsAll()` in particular is quite slow). 

- [X] Added to `motus` package
- [ ] update the MotusRbook
