### ISSUE TITLE
UTC Offset questions

### ISSUE THREAD

**Issue by j-sayers** [MotusDev/Motus-TO-DO#725]
Someone recently emailed with some questions about how to deal with the UTC Offset for Lotek receivers. This person took over the project from the previous manager, and thought the deployments are all now finished, the new manager has realized that the timezone was never set to UTC for most of those deployments. 

[This closed issue](https://github.com/MotusDev/Motus-TO-DO/issues/478) does a good job of outlining the problem and the chosen solution. But I'm still left with some questions/comments...

- Phil mentioned the fact that deployments can and do straddle daylight savings time changes, but I didn't see (maybe I just didn't notice) the best general practice here. If, as in this case, it is found that terminated deployments _do_ straddle changes in daylight savings, should that deployment be split up into several new terminated deployments, each of which has a start and end date that corresponds to the changes in DST? Or do Lotek receivers account for DST in their timezone settings? Since that would essentially be a local time zone minus the DST, I tend to think not, but who knows.

- The example of the offset correction used in the popup on the website says that, in order to correct for Eastern Daylight Time, enter a UTC offset of -4. But as pointed out to me, this seems very strange! If the time on the Lotek receiver was recorded in Eastern Daylight Time and we want to correct it to UTC, we do not subtract 4, but _rather add 4_. In reading down through the issue mentioned above I see that the calculation is `tsCorrected = ts - UtcOffset * 60 * 60`, so in other words roughly UTC = EDT - (-4). But since the user knows that the object is to convert their local timezone to UTC, they are presented with what appears to be an incorrect example. I'm assuming there is an underlying reason why this is the case, but in any event clarifying the message to the user may be helpful.

- Lastly, there doesn't actually appear to be any documentation or explanation in the R Book as to what the UtcOffset does or how to use it.

**Comment by steffilazerte** [comment]
It's not in the MotusRBook because as I started adding details I [ran into some questions](#581). @denislepage said to hold off as there might be a way of addressing this server-side. But I'm not sure where we are with that.

**Comment by denislepage** [comment]
This is all very confusing, and we should check again whether Lotek is planning to include the time zone information in their export strings. That would potentially resolve the issue for good.

I think it’s important that we ask people to enter the offset in the metadata in a way that is consistent with the UTC offsets (e.g. EST = -5). It does seem like the example below is backward, which doesn’t help the confusion.

It’s not clear to me how Lotek units are correcting (or not) for time saving. E.g. if you have data that straddles the time saving change, is the data adjusted in consequence, or simply provided based on the offset that the user asks for at the time of the export? That’s an important issue to resolve. If they are not correcting it, then we only need to know what offset they’ve used to export the data, which is what we do now, and do not need to worry about time change. Do we have a unit that we can confirm, or do we need to ask Lotek?

With the function that I developed that is explained in the previous linked issue #478, we could potentially calculate offsets and time saving corrections based on coordinates. That would mean that we only need to ask users to indicate whether their data needs correction or not once in the R package, and we would then provide the information needed to do so for each receiver.  If you know that the data needs correction, and that the receiver is in the America/Toronto time zone, you potentially have all you need. But again, it won’t necessarily match what Lotek units are providing, and what the user asked for, and there’s the added issue of mobile receivers (a start location, which I think we ask for, would be enough).

I’m not sure it can work because of the issues above, but if we provided the time zone for a receiver deployment and identified those that needed correction, you could calculate the offset with this: https://www.rdocumentation.org/packages/oce/versions/0.1-82/topics/GMT.offset.from.tz

**Comment by jsayers-bsc** [comment]
I know we have a newer Lotek receiver in the Motus shop, but I haven’t personally used it. I’m not actually around either to test it out. I did find this is the SRX Manual, basically the only place where GMT/UTC is mentioned. 

![2020-05-23_073633](https://user-images.githubusercontent.com/55001144/82729929-dbe81100-9cc9-11ea-82fa-2777c95afe20.png)

I’m not sure why a GMT correction would be required for the clock to update properly since they say that internally the receiver operates in GMT… Maybe there are just two  ways of setting the display time to local, either by entering a GMT correction, or by entering the local time itself.

There is no mention in the manual of “Daylight Savings Time”, “DST”, “timezone”, “time zone”, or “zone”. It would appear that that’s not accounted for, which means that the users would have to manually change that time every time DST comes around or have their displayed data off by an hour half the year. Daylight Savings Time is just such a headache!

But maybe it’s still worth confirming this directly with Lotek?

Something else that just came to mind that’s affected by this:

In examples in the R Book, we generally use the “ts” field any time we are filtering by time blocks. But it seems that **the default should be to use tsCorrected field instead**, especially if the .motus file is Project tags, which could very well include detections by Lotek receivers with corrected time zones.

**Comment by leberrigan** [comment]
I can see folks manually setting the time whenever daylight savings occurs and not realize the problems it could cause. Especially if manually tracking with the SRX.

---

I think part of this can be explained if we assume the manual is just poorly written:
> **The receiver uses local date and time in combination with the GMT correction set so that data can be displayed in local time ...**

The logic...
> **[Local time] + [GMT correction] = [Local time]**

...does not compute.

So lets go back to the section on GMT correction:
> In order for the **GPS feature** of the receiver to update its clock **properly**, it must know the **GMT correction** for the receivers location,

First of all, _nobody_ calls it "GMT correction". A Google search for this term returns < ~4k results.
Second, 'GPS feature' is really just a GPS to anybody who uses them.
Third, the word 'properly' seems to refer to local time.
This leads me to believe that whoever wrote this was not the most familiar with this equipment or timezones or both.

---

I have no idea what it's referring to when saying it needs GMT offset and local date/time to display things in local time. WHY???

**Comment by denislepage** [comment]
But daily saving adjustment is presumably not done automatically by the unit?

**Comment by denislepage** [comment]
The correct term we should use and record in the metadata is UTC offset, otherwise it becomes way to confusing. These are well-known values (e.g. EDT = -4).

The correct equation for converting incorrect ts (ts’) then becomes:

ts = ts’ – ([UTC offset] * 3600 )
Where ts is the corrected timestamp, ts’ is the incorrect value provided by Motus, UTC offset is the offset in hours from UTC, and 3600 for converting hours to seconds.

If the data is incorrectly using say a local Eastern Daylight (offset = -4), then the ts is 4 hours behind, so this adds 4 hours to the provided ts.

If people are smart enough to be changing the offset to conform to daily saving, they REALLY need to be rather using UTC. We can’t stress this strongly enough. Make it bold, colored, flashing and add glitter if you need to in the R book. The above is just a patch, not a solution that people should implement moving forward.

If they happen to have deployments set with different offsets due to DST, then they need to split their deployments accordingly. We can’t guess which people did and which didn’t adjust for DST.

Who is having a crack at the changes in the R book? Lucas or me, I am presuming.

**Comment by steffilazerte** [comment]
> Make it bold, colored, flashing and add glitter if you need to in the R book.

1990's here we come!

>Who is having a crack at the changes in the R book? Lucas or me, I am presuming.

What changes, exactly? If you mean regarding the `utc_offset` and `ts_corrected` fields, that's something I can do (I think I have a draft somewhere). But if it's about the initial metadata setup, then probably one of you two.

**Comment by adamdsmith** [comment]
Sorry to crash the thread, but is there a place to report receivers (all Lotek of course) that seem to have incorrect `tsCorrected` times, probably due to utcOffset corrections? I didn't see a relevant open or closed issue. The apparent timestamp error is based on recorded detection times by nearby SG receivers.

**Comment by denislepage** [comment]
Who is having a crack at the changes in the R book? Lucas or me, I am presuming.

What changes, exactly? If you mean regarding the utc_offset and ts_corrected fields, that's something I can do (I think I have a draft somewhere). But if it's about the initial metadata setup, then probably one of you two.

It probably needs to be in both places. The station set up instructions and the metadata corrections (I’m going to rely on Lucas or Josh), and how to apply the corrections in R (Steffi, if you are good).

**Comment by denislepage** [comment]
We track this information in the receiver deployment metadata.

If you have a list, send it along, we can make sure the values are added to the database. I’m not sure who between Lucas or Josh has been handling this so far. If the list of long enough, we can also update the database directly.

We’re only allowing 1 offset value per deployment, so if people have adjusted the clock half way, then we likely need to split their deployment. Please provide values in local offset (e.g. Eastern Daily Savings = -4)

If you only have a potential list that still needs to be confirmed, send what you have anyway.

**Comment by adamdsmith** [comment]
Don't have many, and these will need confirmation. 

Actually, the vast majority of times I am questioning are May 2018 deployments from Project 145, which I've listed here. Not sure if it's worth checking 2017 and 2019 deployments.

RecvSiteName | DeploymentID | Deployment Start | expected local offset
-- | -- | -- | --
Clare | 4687 | 5/4/2018 | -4
South Tawas | 4688 | 5/1/2018 | -4
Mack Lake | 4689 | 5/2/2018 | -4
No Pablo | 4690 | 5/2/2018 | -4
North Tawas | 4691 | 5/3/2018 | -4
Ogemaw | 4692 | 5/2/2018 | -4
Red Oak | 4693 | 5/2/2018 | -4
Fletcher | 4694 | 5/1/2018 | -4
St. Helen | 4696 | 5/1/2018 | -4
Clear Lake | 4697 | 5/3/2018 | -4

Additional stations to confirm:

RecvSiteName | DeploymentID | Deployment Start | expected local offset
-- | -- | -- | --
Pointe Mouillee | 4285 | 9/23/2017 | -4
Darby | 4262 | 8/17/2017 | -4
Winous Point 2016 | 3116 | 5/24/2016 | -4

**Comment by adamdsmith** [comment]
Is there a way I can go about determining whether to shift detection times for the above stations? For the Project 145 stations, no offset correction is identified but one seems justified based on timestamps from relatively nearby SG stations (and estimated flight speeds). For the Project 64 stations, an offset correction identified but it seems unnecessary.

**Comment by denislepage** [comment]
The way you are doing it now is the only we have, based on bird activity and nearby receivers.

If you have corrections you think should be made on the offset records, please do send them along, along with a minimum time range you know to be affected if you can. The main concern I have is about those deployments where the offset has changed without a new deployment created. We could end up fixing things back and forth on the basis of conflicting information, so we may need a way to document this and create new deployments where needed.

Perhaps a document in the git repo where we can annotate corrections, or something like that, or a comment in the deployment itself when corrections are made, mainly the period over which the corrected offset was determined.

**Comment by adamdsmith** [comment]
Alright... The project 145 issue should be straightforward. Those deployments are all temporary and started anew each year. Wonder if we can check with Nathan about whether he might have downloaded the data in something other than UTC in 2018. I'm less enthusiastic about troubleshooting the project 64 stations...
