### ISSUE TITLE
Community R Repository?

### ISSUE THREAD

**Issue by leberrigan** [MotusDev/Motus-TO-DO#729]
Have we considered opening a repository for collaborators to share their R scripts? 

This could be a very helpful tool for collaborators who are often writing the same scripts to do the same thing and also for those who aren't the most familiar with R programming. 

If we are to implement this, we will need to know how involved we want to be (how much moderation?), how much time we expect it will take to implement/operate, and who is on board to help operate it. 

I think if we went with GitHub it would be possible to get a number of collaborators involved, especially if we 'seed' the repository with some of our own scripts at the start (e.g.: station reports). We could eventually do something where we incorporate popular scripts into the R package.

This would involve:
 - Opening a repository for community scripts on GitHub.
 - Decide on who is responsible for the master branch.
 - Providing _clear_ instructions on how to install and use GitHub with R and provide links to licensing.
 - Add links to the repository throughout the R book and Motus website to make collaborators aware of its existence.

**Comment by denislepage** [comment]
I think we can probably set a repository for that purpose (contributions?).

The best way for this to work would be for a contributor to create a fork on their own account, and when they are ready to share, make a merge request. That way, we don’t need to control user permissions and we have a chance to review at least minimally what people are sharing, but not necessarily check or test the code per se.

I would encourage users to make each their own folder within the repo and we could provide guidelines about what documentation should be shared (preferably in rmd format). If people don’t want to use github, they can also just send us the files to put in a folder for them.

A question is whether we’d allow other people to make edits to someone else’s code. Presumably so for minor bug fixes at the very least.

Anything that is worthwhile could eventually be integrated into the package or the book. I don’t think we can or should require that the code for this repo be formally done as a package, and that would keep the process open to more people.

If there is a good amount of uptake, we can see how we want to structure this a bit more, but I am not sure how much there will be for now. It’d be great if it happens.

Potential instructions (rough outline):


-          create a fork of the contributions repository in your github account (link to instructions)

-          create a new root folder with your name or a topic if necessary

-          commit your changes to github

-          when you are ready to share, make a merge request (link to instructions).

-          before making more changes, keep your fork current with the most recent changes (including possible fixes to your own code made by others). (link to instructions)

-          requirements:

o   please include at least 1 readme.Rmd file that provides summary instructions on how to use your scripts and some examples.

o   the entire repository is being shared under a XXX license. If you would like your contribution to be acknowledged, please include details in the readme.Rmd file or at the top of your scripts (provide example)

o   make write your code in a way that easily be replicated by someone else, to the extent possible

o   sample datasets that cannot be acquired through the motus package are preferably shared as small RDS data files. Data files (above XXX) should be stored someone else (WHERE?).

**Comment by ajmacdonald3** [comment]
I've started a [repository](https://github.com/ajmacdonald3/Motus-community-scripts) on my own page and I can transfer it to the Motus github whenever. I put a small example script and readme in to start. Currently the detailed instructions link leads nowhere. Do you think most people will use github through Rstudio/do we want to write the instructions this way to encourage this?

**Comment by StuMackenzie** [comment]
Great, thanks Amie. It's hard to tell how most people will be using github, but it's probably safe to say Rstudio will be used. We don't want to get into the habit of writing instructions in many different ways, so probably best that we keep it generic as possible.

**Comment by denislepage** [comment]
Git repos can be accessed in many different ways. I think writing our instructions based on RStudio probably makes the most sense, since they can test their code there and push them to github, as well as download the entire updated repository with everyone else's contributions.

I suspect we'll want to have people create a fork on their own account and make pull requests that someone from our team should approve. Regular trusted contributors could be granted permissions to push to the master repo.

An alternative for those not too interested in dealing with forks and pulls is to just send us a zip file with their files for publishing.

**Comment by ajmacdonald3** [comment]
Sounds good. I'll work on putting together some more detailed instructions on syncing github with RStudio, forking the repo and then submitting a pull request.

**Comment by ajmacdonald3** [comment]
The [Motus community scripts](https://github.com/MotusWTS/Motus-community-scripts) repository is up on the MotusWTS github. I wrote some [instructions on contributing scripts](https://github.com/MotusWTS/Motus-community-scripts/blob/master/contribution_instructions.md) and tested them out by forking a copy and then submitting a pull request and it seemed to work. If others have scripts to add to start seeding the repository and making sure the process works, you should be able to now. One thing I didn't do was write instructions on keeping the local copy of your fork current with the upstream main repository on MotusWTS - when I did a little reading about it, it seemed like keeping those synced might require some git coding in the shell, which I wasn't sure folks would want to do. I just suggested that if they had made their fork a while ago and were coming back to it later to make new changes that they should make sure their fork is current so they don't miss changes that have been made in the interim. Maybe we could add more detailed instructions on this later if there is a good amount of uptake and it seems like it might be an issue.

**Comment by leberrigan** [comment]
Awesome work, Amy! Instructions look great and straight forward. I'll report back once I've had a chance to test out the process.

**Comment by StuMackenzie** [comment]
As soon as you're ready, we should make a post to the Motus list to try and populate it further.  Or frame it like a beta if people are keen to contribute., and then we can continue development. I may have missed this, but I don't know if some kind of an index of what 'functions' are available. I'm not sure what that would look like.

**Comment by denislepage** [comment]
It may be worth highlighting the license level attached to the repo. I’m happy with GPL as it is now.
https://github.com/MotusWTS/Motus-community-scripts/blob/master/LICENSE

**Comment by leberrigan** [comment]
I have just added a new folder of scripts for the station reports on there. I have several other scripts I can add on there:

- [ ] Technician Station Reports
- [ ] Landowner Station Reports
- [ ] 'Animate Track' function (uses MoveVis)
- [ ] Link global weather data to detections using RNCEP
- [ ] Other bits and bobs.

In addition, I have two repositories on GitHub for my thesis chapters - perhaps there's a place for stuff like this so folks can publish scripts used in publications. I don't think this would be the appropriate place for it, but maybe we can think of a way we could link to everyone's repositories? These are mine, for instance:
- [ ] Cumulative vs. net displacement: https://github.com/leberrigan/displacement
- [ ] Nocturnal flight behaviour: https://github.com/leberrigan/flights

Lastly, Jeremy made a good point in the call today that we should include example scripts from the Motus R Package. I think to keep things simple to start, it's fair to simply copy and paste what's online, but it'd be good to eventually have something nicely packaged so it's easy for beginners to follow. Perhaps that could be in folder labelled 'example-scripts'.

**Comment by ajmacdonald3** [comment]
Awesome, thanks Lucas! Looks good. Not sure why, but your pull request went to my fork instead of the main repository on the MotusWTS github. No problem, I just sent it over to the main repository, but for the next scripts it might be good to have your fork linked to the main one (https://github.com/MotusWTS/Motus-community-scripts) in case my fork gets out of date. Could also be that I've set something up wrong and pull requests are going to my fork for some reason, I'll look into it.

Here's a draft note we can send around when ready to a starting group of folks we know have worked Motus data a lot, as discussed yesterday:

---

Hi everyone,

We have started a [repository](https://github.com/MotusWTS/Motus-community-scripts) for Motus users to share their R scripts for working with Motus data if they are interested. The goal of this repository is to provide new (and seasoned) Motus users with examples of scripts that might serve as building blocks for their own analyses, so they have resources to learn from beyond the Motus R Book. We also hope that contributing scripts for performing fairly common tasks with Motus data may reduce folks duplicating efforts by starting scripts from scratch when another Motus user might already have a similar script they are willing to share.

We have begun adding some of our own scripts to the repository and we wondered if you, as folks who have done significant work with Motus data, might have any code you are willing to share. We realize that everyone is busy and we don't want to ask you to spend too much time on this, so scripts do not need to be running perfectly with sample data, as long as the purpose of the script and how it works is clear. We also recognize that your scripts are your work, and you are not obliged to share them if you do not want to. If you are able to share, the repository includes [instructions](https://github.com/MotusWTS/Motus-community-scripts/blob/master/contribution_instructions.md) on how to submit scripts over github, but if you prefer, you can email us a zip file instead and we will upload them.

Thanks very much for considering this request.

---

I'm happy to send it out once we have a list of who to start with, unless it should come from the motus email.

**Comment by denislepage** [comment]
We should make sure to point out that forks should be based on the motusWTS repo. I suspect this is what happened here.

**Comment by denislepage** [comment]
I think the draft letter looks good. I don’t think I have anything to add. We might sit on it a bit longer until we have a bit more material ready, but otherwise, it looks great.

**Comment by leberrigan** [comment]
Ugh, yes, that was my mistake! I'll start sending requests to your account ;).
