### ISSUE TITLE
Manage Users: users not visible

### ISSUE THREAD

**Issue by Hussell** [MotusDev/Motus-TO-DO#73]
Navigate to the Manage Users page for a project you have update authority on. Hit the logout link in the upper right, and log in again. The list of users is empty until you go to the Manage Users page for a different project (many users don't have another project).

Note that you can still add a user to the project while the users are not visible.

**Comment by pmorrill** [comment]
Possible fix committed to master branch.

**Comment by Hussell** [comment]
Deployed to sandbox, but no change on this issue.

**Comment by pmorrill** [comment]
Denis: when a user signs out then back in while on the Project Users management page, the code that builds the Project Users list encounters a org.bsc.exceptions.LockedObjectException when it tries to instantiate the first user. Has the garbage collection just not cleaned up yet? 

The problem seems to be a bit sporadic: at times I am able to repeat the operation several times without issues. But it usually throws the exception.

**Comment by Hussell** [comment]
In ProjectBean, when the list of MotusProjectUsers is created, all of them are created locked. The lock doesn't expire unless you explicitly call removeLock() or wait 30 minutes. So if two people try to manage the same project's users at the same time, or two projects which happen to share a user, or if one person switches to a project that has the same user (e.g. Motus Ontario Array and Motus Atlantic Array), or logs out and logs in again, then a LockedObjectException happens.

So, I changed ProjectBean to create all MotusProjectUsers unlocked (so, in read-only mode). Everything seems to work now, including adding and removing users from a project and editing their project-level permissions. Fix is deployed to beta and sandbox.
