### ISSUE TITLE
Project Conflict - noisy problem stations that need fixing

### ISSUE THREAD

**Issue by StuMackenzie** [MotusDev/Motus-TO-DO#739]
I'm not sure how best to fix this one, but something is wonky. I suspect aliasing. Great candidate to try and investigate and clean up.

**For station -** [Torrance C (ID# 5521)](https://motus.org/data/receiverDeploymentDetections?id=5521)

- whimbrel detections from this location are bad
- any taylor swallows are bad
- all VIRA are suspect (especially those in july and august)
- REKN are suspect - some could be OK, but we'd have to look for migrants 
- Ovenbird and Gallinule likely bad
- piping plover and common tern also bad

**For station **
[Torrance B (ID# 4777)](https://motus.org/data/receiverDeploymentDetections?id=4777)

(this one is even worse)
- whimbrel bad
- vira - bad
- SEPL's likely bad
- RUTU - likely bad
- REKN Bad - except for clear migrants like - https://motus.org/data/track?tagDeploymentId=22732
- ROTE - bad
- REPH likely bad
- PIPL Bad
- OVEN - probably bad
- COTE bad
- COGA - bad
- CHSW - probably bad
- 

-

**Comment by leberrigan** [comment]
I think this is a tag aliasing issue like in #667. This site is dominated by detections of tags from NorrisLabNightjars, all of which have a 4.7 second burst interval. All the odd detections at these stations also have the same burst interval and only occur when multiple nightjar tags are also being detected.

I find the deployment plots more informative for this sort of thing:
- [Torrance B](https://motus.org/data/receiver/deployment/plot/SG%2D2516BBBK2068-2018%20MotusON%2C%20Torrance%20B.png?id=4777&n=100&firstTag=0)
- [Torrance C](https://motus.org/data/receiver/deployment/plot/SG%2D4001BBBK2170-2019%20MotusON%2C%20Torrance%20C.png?id=5521&n=100&firstTag=0)

There is also a detection for "NoProj#999999 M.0" at Torrence C - what on earth is that???

**Comment by jsayers-bsc** [comment]
> There is also a detection for "NoProj#999999 M.0" at Torrence C - what on earth is that???

When I've seen this recently it was related to having multiple identical test tags all registered individually, resulting in them being ambiguous tags. Because the ID can't be resolved, they show up with this fullID in the detection plots (and not at all in detection tables). The detected ID should show up in the R data though, along with the associated ambig ID's. I'd guess that's what's going on here too.

Jeremy described what's going on [here](https://github.com/MotusDev/Motus-TO-DO/issues/694). 

Actually, tags from the NorrisNightjars project as well as Tonra's, PARC, TaylorSwallows were frequent fliers during those[ "false positive" events](https://github.com/MotusDev/Motus-TO-DO/issues/674) which have been noticed at several stations before. (In this case the NorrisLabNightjars are legit, or at least most of them are.) I hadn't noticed the BI's previously, but if they were similar to these (very short length) that may go quite a ways to explaining why so many of these tags were "detected" during those events. Though at the Torrance stations it's due to the presence of a large number of real tags, whereas the others may have been due to a brief spike in background noise.

**Comment by StuMackenzie** [comment]
Closing in deference to #610 Still requires documentation, solution, etc.
