### ISSUE TITLE
Registering Sensor on Sandbox

### ISSUE THREAD

**Issue by cjardine-bsc** [MotusDev/Motus-TO-DO#744]
Hi Folks, 

I'm trying to trace an insertion into the procs queue that is causing a DB error. The procedure is submitted to the procs queue by a trigger on the sensors table. The issue is only happening in Sandbox. 

As part of my testing I attempted to register a sensor via the sandbox website:

![image](https://user-images.githubusercontent.com/22172758/85477268-dbfc5a80-b56e-11ea-8821-163628f0eb9d.png)

And I'm receiving the following error:

![image](https://user-images.githubusercontent.com/22172758/85477312-f0405780-b56e-11ea-9655-12d0e4d87ed9.png)

The problem doesn't seem to be happening on the live site. Just to be sure that it's not a database problem I've gone through and done a compare and sync of the two databases. The problem is persisting, suggesting it might be a bug on the sandbox page. There hasn't been a sensor registered to the sandbox database since Oct 2019.

**Comment by Hussell** [comment]
The new receiver is successfully being created - hence the green message - in motus but not in motus_sandbox, so when it tries to load the page it can't find the new receiver - hence the red message. prInsertSensors on motus_sandbox may be the culprit. None of the webpage code related to this has been updated since January.

I didn't realize that registering a new receiver on sandbox would affect the main database, so the receiver with id = 3952 and serial number SG-0000BBBK0000 should be deleted.

**Comment by cjardine-bsc** [comment]
Thanks for checking. You're right that there was a problem in prInsertSensors, it was registering the sensor into the sensor table in live, not sandbox (tisk tisk). 

I fixed that (huzzah!) but it didn't solve the issue (boo). 

Now registering a sensor successfully:

select * from motus_sandbox.dbo.sensors
where receiverID = 'SG-0000BBBK0000' 

However the red message still appears. 

![image](https://user-images.githubusercontent.com/22172758/85778624-9c9d4d80-b6d7-11ea-890c-79c5d0e1e6f8.png)

Note the odd reveiver ID the error is referencing: 552602 which is different than the correct sensor ID 3345
