### ISSUE TITLE
Processing SensorStation Data

### ISSUE THREAD

**Issue by cjardine-bsc** [MotusDev/Motus-TO-DO#759]
Amie uploaded some test data from her sensor station through the Motus web interface today (job IDs below) for motusDeviesID 1805. 

![image](https://user-images.githubusercontent.com/22172758/87100926-7234af80-c202-11ea-8e2e-bfc2685fbd73.png)

Looking at the det_batches table there are not yet any batches present for this deviceID. Just wanted to sanity check that we can upload lotek data from sensor stations this way?

**Comment by StuMackenzie** [comment]
I thought so, but as far as I know haven’t extensively tested - Josh would know. Amie, should this data have both life and nanotag s?

____________________

**Comment by ajmacdonald3** [comment]
Yes - I uploaded both nanotag and lifetag data. Can you upload lifetag data the same way? The SensorStation was definitely detecting the lifetag, I could see it on the web interface. I think it's detecting the nanotag too because there were live pulses coming in, but I wanted to make sure that wasn't just noise. In part this was also to check that the test lotek solar nanotag Josh sent me was still activated. I checked through the R package too, but since there are no batches yet, there was nothing to download.

**Comment by StuMackenzie** [comment]
Good to test. We’ll probably have to wait for these units to connect, or, use this opportunity to test our own processing.  Not sure if Jeremy can look ? 

I think the receiver would have to have a deployment?

____________________

**Comment by denislepage** [comment]
I looked more closely at Bob’s email, and he says that the SG files collected by CTT base stations v2 are now in the new folder that we aren’t pulling from yet.  The other folder he created is for CTT tags on v2 receivers.

I’m not clear if anything is left to retrieve on the other S3 folder, but I am not seeing anything in the most recent logs. No SG data files have been coming in since 30 June, and no CTT files have been coming in since 6 July. Bob had hinted that he could merge the 2 SG folders if we wanted, and I suspect he has now done so.  I don’t know if that also applied to CTT data , but now that we’re not seeing any data, he may have.

No word yet on dual mode files, which makes sense given that we haven’t started pushing them in the new format. Those are still going to the old key.

We’ll need to update our document about data paths. And find where that document is. And get a bigger boat.

**Comment by jsayers-bsc** [comment]
I uploaded Lotek data the other day from a SS and everything looked fine detections wise. At least, it was as expected and there was no obvious reason to dig in further into batches tables etc. The Nanotag data on the SS Is structured in the same way as on an SG so there really shouldn’t be any difference as far as tagfinder is concerned. (I haven’t looked into the job ids below; this is just a comment from my phone.)

On Jul 9, 2020, at 20:05, SMackenzie <notifications@github.com> wrote:

﻿

I thought so, but as far as I know haven’t extensively tested - Josh would know. Amie, should this data have both life and nanotag s?

____________________

**Comment by Hussell** [comment]
The import process on beta has been stuck since Wed. afternoon, which is why the test data hasn't come over yet.

**Comment by cjardine-bsc** [comment]
@ajmacdonald3 Your data has been imported! You should be able to pull it in through R now.

**Comment by ajmacdonald3** [comment]
Great, thanks everyone! The lotek test tag data is there, so it's being detected by the sensorstation. The CTT lifetag data is not, but I assume that's because CTT hasn't synced with Motus in the last few days, as Denis mentioned above.
