### ISSUE TITLE
check for deployment overlaps - https://motus.org/api/tag/deploy

### ISSUE THREAD

**Issue by denislepage** [MotusDev/Motus-TO-DO#76]
The tag/deploy API needs to check that the deployment submitted doesn't conflict with an existing deployment of the same tag.

This is probably how I would do it (needs testing, and also should be used for sensors):

In [prAPIImportTagDeployments], add following:

<pre>IF EXISTS (select id from tags_deployments a where tag_id = @tag_id and 
(@tsStart between dbo.datetime2ts(a.dt_start) and ISNULL(dbo.datetime2ts(a.dt_end),@sysdt) OR 
@tsEnd between dbo.datetime2ts(a.dt_start) and ISNULL(dbo.datetime2ts(a.dt_end),@sysdt)))
BEGIN
      SET @code = 'deployment-overlaps'
      RETURN
END</pre>

**Comment by Hussell** [comment]
Detecting overlaps is tricky. For example, if a new deployment completely contains an old deployment (new start before old start and new end after old end), the code above would not notice.

select id
from tags_deployments a
where a.tag_id = @tag_id
and @tsStart is not null
and a.dt_start is not null
and (a.dt_end is null or @tsStart < dbo.datetime2ts(a.dt_end))
and (@tsEnd is null or @tsEnd > dbo.datetime2ts(a.dt_start))

The code above allows one deployment to start at exactly the same time another begins. Change < to <= and > to >= if that shouldn't be allowed.

**Comment by cjardine-bsc** [comment]
The prAPIImportTagDeployments proc should only be called when a new tag is registered. So I'm unclear how it's managing to write two deployments for the same tag_id. Since the tag_id is generated as part of the process. 

From the website, the prCheckTagDeploymentConflicts is designed to prevent duplicate tag deployments from being created. That proc was using the status field, and was therefore not properly reporting deployment conflicts. I've removed the status field from this proc and it is working correctly again. 

While I don't *think* it should be needed in the API, I've included a call to this proc in prAPIImportTagDeployments just to be safe (why not?). 

I'm following up with Paul now on implementing the computed status field in live so these little problems stop cropping up.

**Comment by Hussell** [comment]
While everything is down I have a moment to explain my code:

There are three cases when one deployment overlaps with another:
1) start1 is between start2 and end2
2) end1 is between start2 and end2
3) start1 is before start2 and end1 is after end2

But there are only two cases for when two deployments do _not_ overlap:
1) end1 is before start2
2) start1 is after end2

So the fastest way to check for overlaps is to invert the conditions for not overlapping:
not (end1 < start2 OR start1 > end2)
Which is equivalent to:
end1 >= start2 AND start1 <= end2
