### ISSUE TITLE
Track project access through Motus R-client

### ISSUE THREAD

**Issue by pmorrill** [MotusDev/Motus-TO-DO#762]
From denis' email (Jul 10):

We need to provide information about ways by which we track usage. Data users would also need to access that their name (and email?) will be available to project data owners. That seems like a reasonable approach?

We talked about this, but can we set up a new table (sorry CJ) to track individual tagme requests?

I think it would need to have an ID, the user_id of the requester, the timedate of the request, the project_id, and the receiver number used with tag me. We would obviously not need to track every paging call. Do we need steffi to add a new parameters in the original tagme request?

If we want to track how much data is being accessed (e.g. number of batches, runs or hits), then another option is to return the request ID to the R client, and have it be used in subsequent paging call, so we can add up the numbers across pages. The initial call would have no request ID, and then the remainder of the calls would have it.

**Comment by pmorrill** [comment]
We already have implicit transaction variable that will allow us to 'see' the initial request coming in (and distinguish it from subsequent page request on the same initial). I think that we can just use the 'lastRecord' variable that the R-client passes back to set up the page: if it is null or 0 then we are starting a new request (and can log it). Otherwise we are continuing an existing request.

When those subsequent requests for pages come in, we could open up the log record and augment the data count (records,). It would be tough to track runs / batches - since these categories cut across pages.

If @cjardine-bsc creates the table in sandbox, I can experiment with this.

**Comment by StuMackenzie** [comment]
This discussion makes me wonder whether we need to confirm that ‘any’ registered user, not just project PI’s have read and agree to the collaboration policy. This may already be the case, but i don’t think so.

Update to the collaboration policy will have to include a section on third party data use.

This is a tangent, but we also haven’t discussed the ability for consultants and industry to mine Motus data. ‘Open’ data aside, I’m less comfortable with this, as will most PI’s without a fee. Open to research, not profit.

S

____________________

**Comment by denislepage** [comment]
An option to consider is to offer various CC licensing options for making the data public, or just pick one for all projects when they are shared. There are a few options, but I think we want to limit our options to no more than 2 choices, maybe 3:

No Rights Reserved (CC0): https://creativecommons.org/choose/zero/
Attribution: https://creativecommons.org/licenses/by/4.0
Attribution, ShareAlike: https://creativecommons.org/licenses/by/4.0
Attribution, non-commercial : https://creativecommons.org/licenses/by-nc/4.0
Attribution, non-commercial , ShareAlike: https://creativecommons.org/licenses/by-nc-sa/4.0

I do have concerns however that the distinction between commercial and non-commercial isn’t as clear-cut that we would hope. ShareAlike adds the requirement that anyone using and modifying the data is required to make their output public, which I think is something we want to promote, though it’s a bit unclear what that means in practice, since the scripts written to transform the data would not apply, and these are really the most valuable.

There’s also the question about what we do with metadata. I think we need to pick one option that applies to all projects, or it would be incredibly complicated for anyone to sort through. We can consider the same for data (I would then use Non-commercial, ShareAlike), but some people may want their raw data to be available for commercial use.

Here are the possible options I would consider, from most to least restrictive. I think we’ll want to narrow down the options for users. The ones with * are the ones I would be likely be offering/picking.

Metadata (including summary data):

-          Attribution-Non-commercial-ShareAlike

-          * Attribution-ShareAlike

-          Attribution

-          No Rights Reserved

Data:

-          * Attribution-Non-commercial-ShareAlike

-          * Attribution-ShareAlike

-          Attribution

A related issue for R scripts that people share, is that we should indicate what licensing they fall under. I think GitHub allows us to specify this.

**Comment by cjardine-bsc** [comment]
Back to Paul's original request you'll find a new table in sandbox called user_tagme

[id]
,[user_id]
 ,[request_date]
 ,[project_id]
,[receiverID]

Would you like the ID field to be an auto increment identity or will you be populating that yourself? Happy with either, just let me know.

**Comment by pmorrill** [comment]
The id can be auto-increment. But, I think we may also need the 'token' in this table. We support a user having multiple sessions concurrently (different tokens), so maybe just in case, a varchar(100) could hold that value in case we decide to make updates on paginated calls...... Including the token will ensure the correct record is found if we need to update it at all. (Admittedly, this is for future dev)

**Comment by cjardine-bsc** [comment]
You got it.

**Comment by steffilazerte** [comment]
I'm not quite clear on what is needed from me. Do I need to add a `lastRecord` variable to the api requests? If so, what exactly is this supposed to be?

**Comment by pmorrill** [comment]
No - don't need to add anything. I may have mis-named the variable. It is whatever value you send back when asking for a second page of data. I will look it up tomorrow and report back!

**Comment by pmorrill** [comment]
To clarify @steffilazerte  =>The field that I was referring to is called 'batchId' for the /batchesForTagProject entry-point. I am just going to use it to distinguish between initial calls to the entry-point, and subsequent calls for data pages (in which case it is greater than zero).

**Comment by steffilazerte** [comment]
Ah sounds good!

**Comment by pmorrill** [comment]
Sandbox only: I have added simple R-client request logging. It is triggered only on the initial page of data for either tagme(projectId) or tagme(receiverId).

There is an admin tool to view the logs here:

https://sandbox.motus.org/data/admin/sgAccessSummary

Can someone point an R-client at the sandbox and test this?

**Comment by denislepage** [comment]
I have tagme'd project 12 on sandbox, and the record is showing up in the table.

**Comment by denislepage** [comment]
Did a bit more testing. If I interrupt R, and start again with the same project, no new records are created. If I restart R and start again for the same project, no new records are created either. When I try a different project, it confirms that the token associated with my session is the same. I thought we were generating new tokens? Are you only keeping one record per project and token? If so, it should probably have at least 1 record per date.

**Comment by pmorrill** [comment]
There is no restriction on the number of records per token. The only restriction is that if you are not starting a **new** request it will not get logged.

The api sees any request that includes a non-zero batch id as a continuation of another request. Is the R-client picking up where it left off maybe? (sending a non-zero batch id)

**Comment by denislepage** [comment]
Ah, then the behaviour is the one expected, but perhaps not exactly the one we want. I though every user call to tagme would be logged (but not paging calls).

One possible approach maybe to track the last batch number and/or the last access date. E.g., you’d have to check the user_tagme table for every “batch” API request (no need for runs, hits, etc.), and update the date and/or the batchID. I think date last accessed would be sufficient, though batchID would give a better indication that the data was fully downloaded, rather than interrupted right at the start.

**Comment by pmorrill** [comment]
@leberrigan The request logging summary tool is here:

https://beta.motus.org/data/admin/sgAccessSummary

**Comment by leberrigan** [comment]
### Beta AND Sandbox
The tests below were conducted on both the Beta and Sandbox server. 

#### Download from a project
 - Only makes a record if download is allowed to complete (as far as I can tell).
 - Doesn't make records for certain projects, even if download is complete:
    - Projects 1 and 26 don't make records 
    - Strangely, project 26 _did_ make a record when I accessed it last week
    - Projects 137, 157, make records

#### Download from a receiver
 - I wasn't able to get any records to appear. I tried downloading the complete database of the following receivers:
   - SG-4005BBBK3230
   - SG-5113BBBK0324
   - SG-1614BBBK1787
   - SG-5113BBBK3139
   - SG-3214BBBK6472
   - SG-3214BBBK5558
