### ISSUE TITLE
Dealing with "Tag detections outside of Deployment" error triggered prior to actual registration/deployment

### ISSUE THREAD

**Issue by j-sayers** [MotusDev/Motus-TO-DO#777]
Project 335 recently brought to our attention data issues regarding [15 tags with detections outside deployments](https://motus.org/data/issues?id=335#v_tag_hits_no_deploy). 

Thing is, the detections occurred before they had even registered these tags so they couldn't have been from a test period. Upon a closer look, nearly all of the "detections" have a runLen of 2, with a couple others at 3 or 4.  Likely the pulses here were just random noise until they registered their tags and the stations in question were re-processed.

But it doesn't seem like suspect detections should flag data issues in the first place, or maybe that the same filters that apply to public output should apply to triggering data issues on tags detections? (though maybe that risks bypassing issue notifications where they really ought to be.)

What are people's thoughts on this? Is this something we should change, or is it by design?

**Comment by cjardine-bsc** [comment]
Interesting series of events. 

My guess is that they registered the tags without deployments, the receiver was run and logged detections, then they created deployments. 

I'd like to check the logic of that though. Jeremy, can you look into re-running the receivers in question and make sure those bad detections disappear?  (once we get you set up on the new server of course)

That issue should maybe just be set as a warning, not an error. Alternatively we could look into only triggering this error when there are detections of longer run lengths from outside the deployment, to reduce the risk of flagging an error for false detections.

**Comment by leberrigan** [comment]
I have seen this behaviour in the past as well. [Project 204](https://motus.org/data/issues?id=204) has the same issue, but the PI is certain they did not have the tag active during this time so it must be false positives.

**Comment by cjardine-bsc** [comment]
Yeah, I don't question that they are false positives.

**Comment by StuMackenzie** [comment]
Presumably resolved unless an action can be identified.

**Comment by jsayers-bsc** [comment]
This issue has come up with other projects and I'd like to suggest we provide a way of dealing with these that goes beyond hitting "ignore" in the data issues page. 

The problem is that people don't always register their tags nor create deployments at the proper time. Because of this we send an error message in the Data Issues page any time one of the tags currently on their project is detected outside a defined deployment period. 

But there are some occasions where the error cannot apply, such as when the so called detection occurred before the project even acquired the tags, or during a period when they are confident the tags weren't deployed. In these cases, you can't resolve the error by creating a deployment that covers the period, leaving the only option as "Ignore". 

This isn't ideal because "Ignore" seems more appropriate for non-urgent issues, like adding landowner contacts, instead of errors that aren't actually errors. And, as happened recently, there may be "detections" of these tags (due to aliasing or noise) during a period we know they weren't active. Ignoring the issue leaves the aliased hits 

It would be nice to have an option of dealing with these in the Data Issues page that:

1) resolves the issue on the Issues page without resorting to "ignore" and 
2) applies a flag to the hits in question so that they identified as "suspect" (#749)

**Comment by jsayers-bsc** [comment]
Re our call yesterday of updating the error message with a bit more context...

I don't see this message in either the text fragments or error messages. Is there somewhere else I should be looking for this? 

I was just going to add one line to the end to make it: 

> These tags have detections that fall outside of any current tag deployment. 
> 
> Please modify or create deployment(s) that capture these detections. If these detections occurred during testing, please create a deployment and mark it as a test. **If the detections occurred before you received or activated your tags, you can "Ignore" these errors.**

I was going to add a bit more description, but we may be changing this behaviour anyway. With Lotek tags soon being auto registered we may not use dateBin at all, and only use deployment dates, lest we flood the system with false detections. So just the one line addition may be fine for now...

**Comment by cjardine-bsc** [comment]
added in English
