### ISSUE TITLE
start/end dates in receiver-deployments.csv

### ISSUE THREAD

**Issue by zcrysler** [MotusDev/Motus-TO-DO#78]
How come some dtStart/dtEnd dates have +/- a few hours at the end?  It looks like it's adjusting to local time from the UTC time that was entered online - but only in recent deployments.  I think the file should download with everything in UTC as it appears online.

Eg. recvDeployID 3560
start date online: 2016-11-19 00:00
dtStart when I download the receiver-deployments.csv from https://motus.org/data/downloads: 2016-11-18 19:00:00   -05:00
tsStart also corresponds to the automatically corrected to local time of "2016-11-18 19:00:00"

The correction seems to be based on my current location, not the location of receiver deployment, eg. recvDeployID 4109 has a correction of -04:00 but it's location is UTC -06:00, or recvDeployID 4241 which is also corrected to -04:00 but it's location is UTC +02:00

**Comment by denislepage** [comment]
The deployment dates are stored and provided as datetimeoffsets, which mean they are explicitly providing the time zone. E.g. 2016-11-19 00:00:00 +00:00.

If you are opening the file in a program such as R, it may well attempt to display the time based on your computer settings. They are likely properly stored in the dataframe. This should be strictly a display issue, but you have to be careful if you are trying to do something with the date expressed as a string in local time. I think POSIX is typically the format with which you should work with dates in R.

This behaviour is going to be software dependent.

**Comment by zcrysler** [comment]
The times I provided with the +/- hours were from the .csv I opened directly after downloading the file from the site.  When I read them into R the dtStart also shows those +/- hours, and the tsStart columns are the dates with the +/- hours incorporated into them already which means that the tsStart includes different timezones which are indistinguishable from each other.  Even choosing to use the dtStart, it is read into R as a factor and when converting to POSIXct you have to specify the timezone, which you can't do as is unless you separate that column, make the time adjustment so that they are all in the same timezone, and then convert to POSIXct.

Since we ask that users enter the date/time as UTC, wouldn't it make sense that it's all downloaded in UTC to keep things clear and simple?

My main issues are:
1) not all dates in the .csv include the time offset from what is entered online, so they have NOT been all uniformly altered to my local timezone: when I download the receiver-deployment.csv, older deployments list the UTC time entered online with no changes, new deployments list the local time +/- UTC offset (local time for where data is downloaded not local time for where the deployment is)
See motusRecvID 383, recvDeployID 681 has a dtStart identical to what is online, recvDeployID 3560 offsets it by 5 hours, these receivers are at the same site.  So the file I download has dates in different timezones that you can't distinguish unless you look online.

2) the time offset changes it to my local time with +/- hours to UTC, not the local time of the receiver deployment

**Comment by denislepage** [comment]
OK, I see that the deployment start and end times are sometimes stored with a different offset in the database. We shouldn’t allow this. I suspect this may originate from the bulk metadata uploads?

Denis

**Comment by zcrysler** [comment]
It can't be from bulk uploads since this is happening in receiver deployments

**Comment by pmorrill** [comment]
I have checked the basic data save procedures, and the datetimeoffsets are correctly stored. But, the web interface was storing them along with the offset (-04:00). So, for example, 2017-09-20 20:00 (UTC) was stored as '2017-09-20 16:00 -04:00'. This is correct and fully interpret-able. But I can change the save operation to force the datetimeoffsets to store as if they are UTC (2017-09-20 20:00 +00:00).

Again: it begs the question: why are we using datetimeoffsets here rather than just DateTime fields (which aways store as UTC I believe)? The purpose of the datetimeoffsets field type is to allow storage of timezone information - which we are not using. What am I missing here?

**Comment by denislepage** [comment]
If we are storing them with different offsets, then I think we should be standardizing them to UTC at the very least on the output side, otherwise it is confusing.

I’m not sure I understand however how they are being stored with an offset of -04:00? For deployment ID 4328 for instance, the database has 2017-10-06 05:22:00.0000000 -04:00, and it is correctly displayed as 09:22 UTC on the web. But if someone entered 09:22 initially, why is it being stored as 05:22 -04:00?

My preference would be to store all time offsets as UTC (+00:00) from the get-go. Subject to verification, this example should set the offset to UTC for existing data, once we have the code resolved.

update sensor_deployments set dt_start =
TODATETIMEOFFSET(DATEADD(MINUTE, -datepart(TZOFFSET,dt_start), dt_start),
'+00:00') from sensor_deployments where datepart(TZOFFSET,dt_start) <> 0

**Comment by Hussell** [comment]
Note that when creating a new receiver deployment, the UTC start date is treated differently than when you edit it. The behaviour should be the same in both cases, I think, whatever is done.

The datetimeoffset type stores a **local** time plus its offset from UTC. UTC times are stored with an offset of +00:00. So, to answer Paul's question, the database is using the datetimeoffset type so that we could - in theory - deal with people entering local times. However, we've pretty much standardized on requiring that all times be entered in UTC, dumping the problem of doing the conversion from local times onto the people doing data entry. In practice, there are a lot of date/times for receivers that were entered as if they were UTC, but were _not_ converted from local time. In particular, a lot were just given a time of midnight UTC because the exact time wasn't recorded, but then mangled by the bug(s), and are now stored as 20:00:00 -04:00.

How it _should_ behave:

- when entering a UTC time, use the UTC offset (zero)
- when entering a local time, use the offset of the deployment location (requires a lookup)
- never use the offset of the client where the data was entered or of the server (which is what's happening now, and the reason for the -04:00 and -05:00 offsets)
- when displaying a date-time, be certain to convert to the desired display timezone (e.g. to UTC from a datetimeoffset)

Since the existing offsets are wrong, someone (possibly Catherine? possibly me?) will have to figure out how to convert the ones in the database back to UTC (i.e. with an offset of +00:00). In the short term, the bugs Zoe noticed can be fixed by converting the datetimeoffsets to UTC before display or download.

**Comment by denislepage** [comment]
We should only allow UTC offset.

Inserting values manually in SQL may explain how some times were entered in different offsets, but I am not entirely certain.

I sent the code earlier on how to fix the offsets.

Denis Lepage
http://avibase.ca
http://ebird.ca


-------- Original message --------

**Comment by pmorrill** [comment]
So: what Jeremy is saying is that the datetimeoffses are there for future use. (As I say - overkill at the moment, but maybe you will use them later).

I have set the code to force offsets to be 00:00 when saving from the web mgmt tools. Have not looked at the api deployment creation procs yet. The times come in as unix timestamps there, and are fed into prAPIImportSensors and prAPIImportTagDeployments. Maybe Catherine or Denis can confirm the handling there? It might be fine.

**Comment by denislepage** [comment]
Hi,


even if we force all offsets to +00:00 (UTC), there is still value in using the datetimeoffset now. Converting to and from ts with datetime doesn't work without that, because the server assumes that all time are local Eastern Time, even though we meant for them to be representing UTC.


That was the initial reason to switch from datetime to datetimeoffset.


Denis


________________________________

**Comment by Hussell** [comment]
Editing a deployment appears to be working correctly now. However, when creating a new deployment, the time I enter is saved as a time four hours earlier, with an offset of +00:00.

**Comment by Hussell** [comment]
Offsets are all +00:00 when entering data now, but receiver-deployments.csv still shows non-zero offsets. This could be fixed by converting datetimeoffsets to UTC before download, or by converting all the datetimeoffsets currently in the database to UTC, or both. Probably both would be best?

**Comment by cjardine-bsc** [comment]
Oh….that’s my job! Thief!!!

Sorry I’ve been ignoring motus. Distracted. Today is a motus day though! Loose ends should be tidied by the end of today.

Catherine Jardine
Ph: (604)-350-1972
www.birdscanada.org

**Comment by denislepage** [comment]
Done, in both databases, for both tags and receivers.

update sensor_deployments set dt_start =
TODATETIMEOFFSET(DATEADD(MINUTE, -datepart(TZOFFSET,dt_start), dt_start),
'+00:00') from sensor_deployments where datepart(TZOFFSET,dt_start) <> 0

update sensor_deployments set dt_end =
TODATETIMEOFFSET(DATEADD(MINUTE, -datepart(TZOFFSET,dt_end), dt_end),
'+00:00') from sensor_deployments where datepart(TZOFFSET,dt_end) <> 0

update tags_deployments set dt_start =
TODATETIMEOFFSET(DATEADD(MINUTE, -datepart(TZOFFSET,dt_start), dt_start),
'+00:00') from tags_deployments where datepart(TZOFFSET,dt_start) <> 0

update tags_deployments set dt_end =
TODATETIMEOFFSET(DATEADD(MINUTE, -datepart(TZOFFSET,dt_end), dt_end),
'+00:00') from tags_deployments where datepart(TZOFFSET,dt_end) <> 0

**Comment by denislepage** [comment]
Is the code now fixed for both tags and receivers?

**Comment by Hussell** [comment]
The input code is fixed, and the data are fixed, but the output code isn't fixed.
