### ISSUE TITLE
European receivers detecting North American tags

### ISSUE THREAD

**Issue by j-sayers** [MotusDev/Motus-TO-DO#784]
Project 113 recently emailed about 4 receivers that are detecting Sora and VIRA instead of the bats they have recently tagged. 

This may be same issue this [project experienced earlier](https://github.com/MotusDev/Motus-TO-DO/issues/614) where networked receivers were assigned to Project 0 prior to the updating of metadata etc. 

The receivers affected are these ones:

![image](https://user-images.githubusercontent.com/55001144/91341560-ab6fb180-e7a7-11ea-90c5-26b8b265c935.png)

At least, those are the receivers one of their tagged bats was misidentified at. It's possible there are other receivers affected that they haven't noticed yet.

If this is what happened I'm curious about the steps involved. 

- In another related issue, Jeremy mentioned that the frequency is for a receiver is reported in the data, but only once per boot session. I've never noticed this myself; it must just be buried in one of the txt files?

- I'm also curious where the default frequency is stored in the db? It doesn't appear to in the deployment record, or associated with sensors of sensor_hash_keys. Obviously I'm just missing it somewhere, but I'm curious where.

- If this same sequence of events was involved here, is it safe to assume this is likely to happen for any networked receiver set up outside North America since data will often be uploaded prior to metadata entry?

**Comment by denislepage** [comment]
The frequency is a property of the antennae in the deployments. I am almost certain however that tag finder doesn’t rely on that, but is rather looking for frequency setting records at the start of a boot session. Those should typically appear in the first few files when a new boot session starts, and will be prefixed with an S.

These are detailed here, though I don’t think it’s 100% comprehensive.
https://github.com/MotusWTS/motusServer/blob/master/inst/doc/motus_data_formats.md

I dug a bit and found a new type of entry: -w. No idea what that is.

S,1500142915.672,3,-w,0x07,0,0,

I’ve been trying to find for a place where these values are all documented, but so far no luck. The values I believe are set in the receiver deployment file that people place on their units. The values for the S lines are either copied from there, or measured in real-time by SG. There’s a default file that people are expected to change https://github.com/sensorgnome-org/sensorgnome/blob/rpi/master/defaultDeployment.txt

I think Jeremy has a way to override problems when incorrect settings are used, but it has to be entered manually.

**Comment by jsayers-bsc** [comment]
Project 113 has confirmed that the deployment files are all properly configured for 150.1, including dongles and the "default frequency" parameter at the bottom of the file.

@Hussell  Are you able to check if something similar to previous issues is happening here and somehow somewhere these are still being reported and processed as 166?

**Comment by dfloer** [comment]
> 
> I dug a bit and found a new type of entry: -w. No idea what that is. S,1500142915.672,3,-w,0x07,0,0,

While not pertinent to this problem, it looks like it's settings for the FCP+ and is saying the IF gain is 0.
From here: https://github.com/sensorgnome-org/sensorgnome-control/blob/77d8ba9b2cf1ba6d3eef895fe7e2155c3f6ccd73/master/usbaudio.js#L40

**Comment by denislepage** [comment]
Great! I added the entry to the list with a link to the repo. I didn’t think to search in sensorgnome-control. I still haven’t found where the other parameters are, but there aren’t probably too many missing.

**Comment by Hussell** [comment]
This is indeed the same issue as #614. If there are no deployments for the receiver then the tag finder usually uses the default frequency, i.e. the one for North America. The deployments for these receivers were created after the receiver data was uploaded. When the data is rerun, the tag finder will know about the deployments, and thus know which frequency to look for. I'll rerun these receivers this week.

Please remind the good people at project 113 to keep their metadata up-to-date.

**Comment by jsayers-bsc** [comment]
Great, thanks!

I wonder going forward if this is something we can address preemptively? It's rare that a deployment record would be created before the actual deployment began and in the case of networked receivers, they will start syncing data pretty quickly. So this is likely to be a recurring issue for those deploying networked receivers outside North America.

**Comment by denislepage** [comment]
Ideally, people would be forced to confirm the requirements of the file, but we obviously cannot risk having broken deployments with no proper frequency set.

Dale, do you anticipate having ways for people to see and potentially modify the config locally or remotely? Seems like some key things like frequency should be prominently obvious, and ideally, the interface would nag them until they’ve confirmed or changed the default value.

**Comment by jsayers-bsc** [comment]
There is a section at the bottom of the deployment.txt file that includes params about default frequency. I’m not sure how that relates to the “default frequency” discussed earlier. This would seem to relate to this very subject, but maybe the parameters here aren’t ever written to those settings lines in data files so they just never make their way off the receiver. Or maybe it’s something different entirely (though what?). Either way, in this case, the receivers in question have this set to 150.1 MHz.

    "module_options": {
        "find_tags": {
            "params": [
                "--default-freq", 166.380,
                "--pulse-slop", 1.5
            ],
            "enabled": true
        }
    }

**Comment by jsayers-bsc** [comment]
The problematic receivers have been reprocessed and the issue is resolved. Thanks!

This is likely to be a recurring issue though. A deployment record will nearly always be created after the deployment has already begun, and in the case of connected receivers that means that data syncing will already have occurred. 

In this case the parameters in the deployment.txt file were all correct so the correct values would have been present in the detection files. It's possible that the deployment.txt file was modified and updated after turning the receiver on at the deployment location (something I often do) so the first upload may still have had the default 166 values. 

So whether the default frequency comes from the deployment record or the deployment.txt file, this is likely to happen again for new networked receivers outside the Western Hemisphere.

**Comment by StuMackenzie** [comment]
Has there been correspondence/followup with the project(s)?

We need to find a way so that this doesn't happen.

**Comment by jsayers-bsc** [comment]
> 
> Has there been correspondence/followup with the project(s)?
>
Yes

**Comment by denislepage** [comment]
@dfloer can you think of a way to force/encourage/facilitate the setting of the frequency in the manifest file. The default frequency is important (leaving it out would make the problem worse, not better), but it's also causing issues outside North America.

**Comment by dfloer** [comment]
I'm not sure how well this'll work, but if the SG has a GPS (and they all should, right?) then the SG could be set up in a way to pull the location from the GPS, compare it against something simple (maybe bounding boxes) and set the frequency automatically based on the location of the SG.

**Comment by Hussell** [comment]
The four receivers at the top were all rerun while I was on vacation, and the plots look OK to me now:
https://motus.org/data/receiver/deployment/plot?id=6164
https://motus.org/data/receiver/deployment/plot?id=6195
https://motus.org/data/receiver/deployment/plot?id=7224
https://motus.org/data/receiver/deployment/plot?id=7230

**Comment by jsayers-bsc** [comment]
Recently received another email from them about a [North American bird showing up on their receivers](https://motus.org/data/receiverDeploymentDetections?id=7315). 

As it stands, this is going to be a recurring issue for projects like this, where networked receivers are deployed outside the Western Hemisphere. This isn't a matter of people being tardy with metadata but simply because the networked receivers start syncing very quickly and data will almost always be synced prior to a deployment record being created. These folks in particularly have lots of receivers, nearly all of which are online, they seem to move them often (or at least create new deployments often), and they regularly disseminate summary data to their partners. Their frustration with repeatedly seeing these issues has come through in their recent emails.

Is there any way we can address this at processing time rather than waiting for a receiver re-run to happen after metadata has been entered? Though it's more of an issue with networked receivers, which will almost always send data before a deployment record exists, it still would be ideal to deal with this further upstream if possible. 

There will usually be GPS information present in the detection data, and while it can't always be trusted entirely, it's probably good enough in nearly every case to separate between the major regions where different frequencies are used. Or maybe it's too resource heavy to check these and use it to adjust a default frequency? I really don't know how it would work or whose skills would need to be applied here (@Hussell?), but there must be some way we can address this given that the first batch of data from networked receivers will nearly always precede the deployment record.

**Comment by denislepage** [comment]
Ideally, networked receivers would provide that information when they are initially registered.
I don’t know enough about how the process of adding new networked receiver works, and whether some of the metadata could be collected at registration time.

I suspect the registration is entirely based on the first time data comes in, which makes this more difficult to intercept, and it may or may not have the data it needs anyway at that time.

A few questions that I would want answered:


-          Are the antenna frequencies provided as part of the receiver manifest file (the one that people can enter their site name in)?

-          How are people being instructed to download that file? Can we build a web form that creates a customized manifest file, or offer a download option from the deployment page (problem being that deployments would only need to be created as pending for the purpose of creating the manifest)?

-          Is this information captured in the initial data rows of the gz data files? The answer I heard recently was not consistently, perhaps, or not at all.

-          How are we using that information? Does tag finder use that information, assuming it exists, or does it need to be added manually to the override table by Jeremy?

Requiring that people enter the right information in the manifest file is error-prone. Having a console where people are required to confirm some of these values would be preferable, though still not error free. But then, we also need to make sure that the information flows to the right place.

**Comment by jsayers-bsc** [comment]
Yes antenna frequencies are entered in the deployment.txt file and it's from here that the settings lines in the gz data files are set each reboot. At least I think that's what's intended. After this issue was originally opened I played around with a receiver, changing the frequency values in the deployment.txt file and they were indeed later represented in the gz file.

There is a also section at the bottom of the deployment.txt manifest file that seems to modify the default frequency parameter of the tag finder. When speaking with them earlier, they confirmed the antenna and default frequencies in the file were set correctly. But maybe they didn't set them correctly quickly enough.

I believe it is an hour from the 1st check in until the first data sync, so that would presumably allow enough time in most cases for the deployment.txt file to be updated, then the receiver rebooted?

In this case, maybe it took them several days. Actually looking at some of the earlier job logs does seem to point to this. This receiver has data for a few weeks prior to the start of the actual deployment on 2020-09-21. It isn't until 2020-09-22 that the default frequency override shows up in the job log.

![image](https://user-images.githubusercontent.com/55001144/96337139-bbdb3480-1052-11eb-90eb-53fcda8f6704.png)

The terminology here doesn't help the confusion because we have the deployment record and the deployment.txt file and both contain user-modified values for antenna frequency.

**Comment by Hussell** [comment]
<a href='https://motus.org/data/receiver/deployment/plot?id=7315'>SG-D22CRPI39DC5 has been rerun</a>.

What's going on here makes no sense at all. The North American bird started showing up in data processed on Oct. 13th, by which time the frequency override had long been in effect. I'm beginning to suspect there's a serious bug here, with connected receivers re-using the first set of parameters they receive until a reboot or a rerun. It would explain a few things, if true, and would mostly affect connected receivers outside North America.

Digging into the code, there is a parameter "resume", which equals true when processing any data from a boot number for which we already have data, and equals false on reruns and the first batch of a boot number. Tracing this into the tag finder's C++ code, I do see some de-serialization of saved state when resume==true, but I'm quickly running head-first into my unfamiliarity with C++ in general and this code-base in particular.

**Comment by jsayers-bsc** [comment]
Thanks @Hussell, no more Virginia Rails at this station now, which is good.

And I think this has identified what was going on in #799 as well. More on that in that issue's page...

**Comment by dfloer** [comment]
I logged into the SG in question, and `deployment.txt` (last modified 02-Sep-2020) lists the station's name as "Wageningen Marine Research" while status is showing "WUR Vlieland Kazerne" and doesn't have a serial number listed there. Frequency there is set to "150.096".

I can also see that it was having some GPS problems for a week and a half after it was set up.

**Comment by jsayers-bsc** [comment]
So this most recent once (#946) wasn't a new receiver deployment at all. It's been active since 2019 and has detected European tags throughout that period until recently.

**Comment by jsayers-bsc** [comment]
In [#942](https://github.com/MotusDev/Motus-TO-DO/issues/942#issuecomment-815874199) I suggested querying in taghits_runs for sensors in a whitelist that have detections of 166 MHz tags. That probably works in cases where there are active tags with the same properties on 166 MHz as 150.1 MHz. But in cases where there are no corresponding tags on 166 MHz this doesn't work since tag finder doesn't even return anything.

The best way to determine whether a receiver is Europe is the GPS location collected by the receiver itself. Could we have a regular database process to check new GPS records for those that contain lat / lon corresponding more or less to Europe (lat then check the default frequency? That might not be straightforward since I don't think the default frequency is stored in the same database (?) but maybe we could at least consult a table that corresponds to the list Jeremy keeps? Even if the default frequency needs to be updated manually we may be able to identify and correct these within 24 hours or so.

**Comment by Hussell** [comment]
The default frequency is correct in these cases, but there's some sort of bug causing the default frequency to be ignored until the the receiver is rerun. So the fix is either going to be fixing the bug, or rapidly rerunning new receivers (or new boot sessions, or new deployments; still not sure what's triggering this). Reiterating: the default frequencies for each project, stored in a database used by the tag finder, are complete and correct when this happens.

**Comment by jsayers-bsc** [comment]
Obviously an actual fix would be ideal but in advance of that may we can at least catch and resolve these more quickly.

If one of these receivers has detected a tag that has a 166 counterpart it seems fairly simple

select distinct(sensor_id) from det_taghits_runs a
left join tags b on b.id = a.tag_id
left join sensors c on c.id = a.sensor_id
where c.project_id = 113 and nom_freq > 166 and nom_freq < 167 

This doesn't work if a receiver starts uploading before it's been registered (though we'd catch it soon hopefully) and doesn't catch cases where there are no hits yet or hits from tags that have no 166 counterparts. But it would catch most much more quickly -- like the new one reported today by Project 113.

**Comment by StuMackenzie** [comment]
Has the current issue been resolved so we can get back to them telling them it's corrected for the time being and we're working on a permanent fix. We might as well be honest that it's a bug deep in the code that we're working to isolate and fix, or implement a workaround.

**Comment by jsayers-bsc** [comment]
This is the latest Project 113 receiver to be have the parameter override ignored: https://motus.org/data/receiverDeploymentDetections?id=7975

The log in sgdata clearly shows that the frequency parameter override is present but for some reason it has no effect.

> Log for 8418772
> 
> Running tag finder on receiver SG-0402RPI32799 boot session 5 (resumed)
> Got parameter overrides: --default_freq 150.096
> Got 0 (unfiltered) detections between 2021-08-24 11:36:10.038 and 2021-08-24 12:53:45.400.

**Comment by jsayers-bsc** [comment]
Is it possible to set up some sort of trigger or alert that at least brings our attention to these before the researchers see them? It would only work for receivers registered to projects on the "European list" and only in cases where they detect tags that have active counterparts on 166 MHz. But in the absence of a complete fix we could resolve them before being asked to do so.

**Comment by cjardine-bsc** [comment]
@jsayers-bsc  can you bring this up on our Thursday call this week?

**Comment by leberrigan** [comment]
@j-sayers, is this still an issue?
