### ISSUE TITLE
Port not set for networked receiver; no data being sent to database

### ISSUE THREAD

**Issue by jsayers-bsc** [MotusDev/Motus-TO-DO#785]
Project 223 has an issue with one of their networked receivers ([SG-14D1RPI39753](https://motus.org/data/receivers/edit?projectID=223&id=3419)), where it has not had a port assigned.

It has been syncing data regularly and up-to-date (though the last connection is several days previous, oddly). However no data has made its way into the database for some time.  

It appears to be the only receiver on sensorgnome.org/status without a port assigned.

**Comment by jsayers-bsc** [comment]
@dfloer Is there anything here that jumps out to you?

**Comment by dfloer** [comment]
I took a look, and nothing looks immediately wrong on the sensorgnome.org end, so it may be an issue with the SG or with connectivity to/from the SG.

**Comment by denislepage** [comment]
I can also confirm that the most recent data files in the file_repo are from 23 July 2020. @Hussell do you know if files from synced receivers are being saved in their original compressed format like uploads are? I looked under the uploads folder, which are divided based on the user ID of the person uploading, but the only files available under your user ID are the SG files coming from CTT SensorStation, and I am not seeing connected receiver files there. Do you know if they are stored somewhere else before being unpacked to the file_repo folder?

**Comment by Hussell** [comment]
So far as I'm aware, the files from connected receivers are uploaded as they appear in the file-repo, not bundled-together in an archive.

The tag finder has been complaining about the missing port number for that receiver since 2020-04-30. A few manual uploads have been done since then, the last on 2020-07-23.

There's no record on sgdata of a port or public/private key pair for SG-14D1RPI39753. I'm not sure how those are registered, but since new connected receivers keep coming online, it must be getting done often. So, someone probably needs to re-do whatever process is done to connect a new receiver.

**Comment by Hussell** [comment]
SG-14D1RPI39753 is now connecting on port 40031 instead of failing to connect to port 0. This happened after a brief outage of sensorgnome.org, so the issue may have been resolved by a restart there.

**Comment by dfloer** [comment]
Well, that's good to know. Maybe we should have a scheduled maintenance window where we just restart the server to clear things like this up?
