### ISSUE TITLE
41 of 98 tag recordings failed due to "No tag detected" error

### ISSUE THREAD

**Issue by jsayers-bsc** [MotusDev/Motus-TO-DO#800]
Project 113 recently uploaded 98 tags for registration and all but 21 of them failed. Aside from a few "couldn't estimate BI error" errors, which are not uncommon, nearly half had a **"No tags detected in recording"** errors. Off the top of my head, I don't know if I've even seen that error yet with any tag registrations I've tried. 

I have seen the originals and though they are a tad short in length, they all look and sound fine, with no discernible difference between those that successfully registered and those where no tag recording was detected. I tried uploading just a few of them and had the same error.

They have tried re-recording a few with much longer lengths and some of those have been successful, so it seems that the recording itself has something to do with it. But to have nearly half of the tag recordings come back with a "no tag detected" error in the first place seems very strange. At the same time they are noticing that some of their receivers are not detecting tags that should be in the vicinity, and are wondering if the two issues are related.

**Comment by jsayers-bsc** [comment]
The files look and sound fine at a glance however @leberrigan noticed that in many of the recordings, one pulse is missing from one burst. Since there are only 3 bursts per recording, one faulty burst could easily prevent a tag id from being detected at all. There are some files that failed that don't have this obvious issue, but presumably it's something similar but just not as conspicuous to the eye. 

![image](https://user-images.githubusercontent.com/55001144/92781277-f8d84b00-f371-11ea-92b1-bbc75e59e4c4.png)

**Comment by leberrigan** [comment]
# Update

- Remaining tags have been manually registered according to specs provided by Lotek.
- More issues have been detected with these recordings which seem to indicate a tag fault (see below).
- Some of the burst intervals provided by Lotek don't match up with the burst intervals in the tag recordings.
  - I will have to measure the BI of the manually registered tags before we can correct them.
- The recorded burst intervals of some tags are non primes, which may or may not be consequential.
  - There are 44 tags registered with a prime factor (4.1) of one of these burst intervals which have the same frequency and were registered this year. Fortunately, none of these tags have the same Lotek ID.


## More tag issues

#### A closer inspection of these recordings shows that some pulses are emitted at the wrong time:
![image](https://user-images.githubusercontent.com/35931796/93462995-7e518300-f8bd-11ea-8695-6d81860bcaa9.png)


#### And some pulses only last for 2 ms instead of 2.5 ms:
![image](https://user-images.githubusercontent.com/35931796/93464085-fe2c1d00-f8be-11ea-87f4-b45f7c834848.png)



This results in some bursts being skipped because it can't recognize the burst any more. Bart had initially uploaded recordings with three bursts and all the failed recordings had **"no tags detected in recording"** as the error meaning no bursts were recognized. Bart re-recorded the tags and included many bursts instead of just three per recorded which was more successful, but there were still many errors, this with the error **"Unable to get a good estimate of burst interval"**. This error is triggered when the [standard deviation of all burst intervals (_bi.sd_) in the recording is greater than 5 ms](https://github.com/MotusWTS/motusServer/blob/b0c8e409f8320b3ed84221e05917ab4e7e4475aa/R/handleRegisterTags.R#L249). I measured the burst intervals of several of these failed recordings and they all have a much lower _bi.sd_ than required (~0.1-0.2 ms) which means this error could only triggered if some of the bursts were missed. 

---

## Erroneous burst intervals on spec sheets

Denis manually registered tags for us based on the specs provided by Lotek, but some of the tags were already registered to the project so the registration failed. These tags were already registered using recordings and their burst intervals differed by at least 0.1 to 0.2 seconds which is large enough that tag finder would not recognize them.

Motus Tag ID | Lotek ID | Spec Sheet BI | Recorded BI | BI diff
-- | -- | -- | -- | --
48506 | 476 | 7.9 | 7.72179985 | 0.1782
48507 | 481 | 7.9 | 7.68450022 | 0.2155
48508 | 486 | 8.3 | 8.22000027 | 0.08
48509 | 493 | 8.3 | 8.18900013 | 0.111
48510 | 494 | 8.3 | 8.18799973 | 0.112

There are several other tags that were manually registered with a BI of 7.9 or 8.3 that we will have to correct by measuring the burst intervals in the recordings.

The recorded BI of these tags are not prime numbers and may alias with tags of BI. Their prime factors are 0.2, 0.7, 1.1, and 4.1 and only 4.1 has any other tags with similar BI, about 162 currently registered. Of these 162, 44 are using the same frequency (150.1 MHz) and were registered this year: 14 registered to project 318 in 1st quarter and 30 registered to project 339 in 3rd quarter. Fortunately, all tags have a different Lotek ID so there should not be an issue with aliasing unless multiple tags are present at the same location and time (type 2 aliasing).

**Comment by leberrigan** [comment]
I had the chance to measure the burst intervals of all the recordings provided by Bart. Here are the results.

As you can see below, this seems to be a recording setup - when they use a different FUNcube, it gets better. 

The plot below shows the difference between the expected and observed burst intervals for each tag, with the expected being the value provided by Lotek on the tag spec sheet and the observed being the value measured in the recordings. This is done as a box plot as at least 2 burst intervals were measured per tag. Two plots are split based on FUNcube dongle that was used (1st recording and second).
![project113_BI-diff3](https://user-images.githubusercontent.com/35931796/93828954-da603280-fc42-11ea-9b6f-81d8428d1c8d.png)

Here is the average BI measurement for each tag: 
![project113_BI2](https://user-images.githubusercontent.com/35931796/93828985-e9df7b80-fc42-11ea-8ad4-c7690d2ab309.png)

We can see there is clearly something going on with with tags 340-515, but we'll have to ask Bart about the rec

tagID | bi.sd | bi | passes.validation | n.bursts | bi.lotek | missing.pulses | bi.diff
-- | -- | -- | -- | -- | -- | -- | --
314 | 0 | 5.9 | TRUE | 4 | 5.9 | 0 | 0
315 | 0.005774 | 5.903333 | FALSE | 4 | 5.9 | 0 | -0.00333
316 | 0.008165 | 5.88 | FALSE | 5 | 5.9 | 0 | 0.02
317 | 1.09E-15 | 5.9 | TRUE | 4 | 5.9 | 0 | 8.88E-16
319 | 0.005 | 5.8975 | TRUE | 5 | 5.9 | 0 | 0.0025
320 | 1.09E-15 | 5.9 | TRUE | 4 | 5.9 | 0 | 8.88E-16
321 | 1.78E-15 | 5.9 | TRUE | 4 | 5.9 | 0 | 0
322 | 0.01 | 5.895 | FALSE | 5 | 5.9 | 0 | 0.005
323 | 0.35125 | 5.668333 | FALSE | 7 | 5.9 | 0 | 0.231667
324 | 0 | 5.9 | TRUE | 4 | 5.9 | 0 | 0
325 | 0.005774 | 5.903333 | FALSE | 4 | 5.9 | 0 | -0.00333
326 | 0.006901 | 6.098571 | FALSE | 8 | 6.1 | 0 | 0.001429
327 | 8.88E-16 | 6.1 | TRUE | 6 | 6.1 | 0 | -8.88E-16
329 | 0.008367 | 6.095 | FALSE | 7 | 6.1 | 0 | 0.005
330 | 1.30E-15 | 6.1 | TRUE | 9 | 6.1 | 0 | -8.88E-16
331 | 0.013663 | 6.096667 | FALSE | 7 | 6.1 | 0 | 0.003333
332 | 1.43E-15 | 6.1 | TRUE | 7 | 6.1 | 0 | -8.88E-16
334 | 0.015492 | 6.09 | FALSE | 7 | 6.1 | 0 | 0.01
335 | 0.024014 | 6.088333 | FALSE | 7 | 6.1 | 0 | 0.011667
336 | 0.017607 | 6.095 | FALSE | 7 | 6.1 | 0 | 0.005
338 | 0.004082 | 6.098333 | TRUE | 7 | 6.1 | 0 | 0.001667
340 | 0.056569 | 6.07 | FALSE | 3 | 6.7 | 1 | 0.63
341 | 0.077782 | 6.045 | FALSE | 3 | 6.7 | 3 | 0.655
342 | 0.028284 | 5.98 | FALSE | 3 | 6.7 | 2 | 0.72
343 | 0.007071 | 5.965 | FALSE | 3 | 6.7 | 0 | 0.735
345 | 0.042426 | 6.05 | FALSE | 3 | 6.7 | 0 | 0.65
346 | 0.091924 | 5.945 | FALSE | 3 | 6.7 | 0 | 0.755
349 | 0.028284 | 6.62 | FALSE | 3 | 6.7 | 0 | 0.08
350 | 0.06364 | 6.325 | FALSE | 3 | 6.7 | 0 | 0.375
450 | 0.050332 | 6.856667 | FALSE | 4 | 7.1 | 0 | 0.243333
451 | 0.084853 | 6.75 | FALSE | 3 | 7.1 | 0 | 0.35
458 | 0.007071 | 6.765 | FALSE | 3 | 7.1 | 0 | 0.335
463 | 0.028284 | 6.55 | FALSE | 3 | 7.3 | 0 | 0.75
464 | 0.021213 | 6.855 | FALSE | 3 | 7.3 | 1 | 0.445
465 | 0.077782 | 6.565 | FALSE | 3 | 7.3 | 2 | 0.735
468 | 0.042426 | 6.94 | FALSE | 3 | 7.3 | 0 | 0.36
470 | 0.070711 | 6.49 | FALSE | 3 | 7.3 | 1 | 0.81
477 | 0.021213 | 7.235 | FALSE | 3 | 7.9 | 0 | 0.665
478 | 0.056569 | 7.12 | FALSE | 3 | 7.9 | 0 | 0.78
479 | 0.056569 | 7.04 | FALSE | 3 | 7.9 | 2 | 0.86
480 | 0.007071 | 7.225 | FALSE | 3 | 7.9 | 0 | 0.675
482 | 0.106066 | 7.065 | FALSE | 3 | 7.9 | 2 | 0.835
487 | 0.014142 | 7.48 | FALSE | 3 | 8.3 | 0 | 0.82
488 | 8.88E-16 | 7.42 | TRUE | 3 | 8.3 | 0 | 0.88
490 | 0.014142 | 7.42 | FALSE | 3 | 8.3 | 0 | 0.88
491 | 0.205061 | 7.685 | FALSE | 3 | 8.3 | 1 | 0.615
495 | 0.007071 | 7.635 | FALSE | 3 | 8.3 | 0 | 0.665
497 | 0.021213 | 7.525 | FALSE | 3 | 8.3 | 0 | 0.775
508 | 0.021213 | 7.935 | FALSE | 3 | 8.9 | 0 | 0.965
509 | 0.070711 | 8.32 | FALSE | 3 | 8.9 | 1 | 0.58
513 | 0.021213 | 8.455 | FALSE | 3 | 8.9 | 0 | 0.445
514 | 0.058595 | 8.546667 | FALSE | 4 | 8.9 | 0 | 0.353333
515 | 0.021213 | 8.215 | FALSE | 3 | 8.9 | 0 | 0.685

**Comment by leberrigan** [comment]
I got some more recordings today and added them to the plots:
![project113_BI-diff4](https://user-images.githubusercontent.com/35931796/94180558-93598380-fe74-11ea-99c9-5a29aac64119.png)
![project113_BI3](https://user-images.githubusercontent.com/35931796/94180560-93598380-fe74-11ea-94fb-0545df22b94a.png)

**Comment by leberrigan** [comment]
Tags have been registered manually and we will keep them like that. While the initial recordings of these tags differed significantly in Burst Interval from the specifications, subsequent recordings of the same tags appear to be much closer. We believe that all these issues are related to the recordings and not the tags themselves.

Lotek has sent 30 additional tags and recorded them with a FUNcube to verify they were functioning as expected. These burst intervals were all close to the expected values, except for one from tag 139 (5.51 seconds instead of 5.9 seconds). We assume this is not a tag issue and just a recording problem. 
![lotek_test_02OCT20_tags134-240](https://user-images.githubusercontent.com/35931796/95201362-359f3280-07b6-11eb-9e63-96ecb0ddeda2.png)
