### ISSUE TITLE
Manual register CTT receivers

### ISSUE THREAD

**Issue by StuMackenzie** [MotusDev/Motus-TO-DO#804]
If a collaborator manually registers a CTT receiver that hasn't yet been assigned, will that be overridden if CTT submits a registration through the API.

Or basically what happens here?

**Comment by denislepage** [comment]
We’re covered.

If the receiver is already in our database due to detections being found, they are only under project 0. When registration comes in later from the API by CTT, the project is updated from 0 to whatever is provided. There are no longer a receiver in project 0.

If the receiver is already listed under any specific project(s) (manual registration), and the API tries to register it: 1) nothing happens if the receiver already has the receiver.  2) the receiver is added to the new project if it doesn’t already exist, but any existing entries in other projects are maintained.

If the API tries to register an entirely new receiver, it goes straight to the project provided, and does not pass zero (nor collect $200).

So, the sooner people can register their receiver and create deployments, the better.
