### ISSUE TITLE
Lotek Tag registration API Issues

### ISSUE THREAD

**Issue by pmorrill** [MotusDev/Motus-TO-DO#809]
Lotek has now sent a preferred JSON format for the incoming tag registration package. I will adapt our handler to work with the new format, next week.

@cjardine-bsc should expect to make some changes to the procedure (prAPIImportTagsLotek) and possibly the raw data table (api_import_tag_lotek_raw) to accommodate the package.

First task: during test, Denis wants to turn off the part of the procedure that actually moves tag data into the 'tags' table.

**Comment by pmorrill** [comment]
For reference, here is the example format sent by Lotek:

{
    "Sales_Order": "SO99999",
    "Work_Order": "R172999",
    "Model": "NTQB2-6-2",
    "Nom_Frequency_MHz": "166.38",
    "Codeset": "Lotek6M:2020",
    "Coding": "Coded",
    "DSP": "Non-DSP",
    "MOTUS": "True",
    "MOTUS_Project_ID": "123456",
    "Tag_Life": "Long Life:1111",
    "Test_Results": {
        "635": {
            "ID": 635,
            "Serial_no": "NQ9999990",
            "Nom_BI": "4.3",
            "Test_time": "2020/03/25 12:49:17",
            "Freq_MHz": "166.3796MHz",
            "Power_dBm": "-23.2dBm",
            "Deltas": "[124.5   156.236 131.824][124.5   156.236 131.824][124.5   156.236 131.824][124.5   156.236 131.824]",
            "Burst_Int": "[4.3008][4.2968][4.3015]"
        },
        "675": {
            "ID": 675,
            "Serial_no": "NQ9999991",
            "Nom_BI": "4.3",
            "Test_time": "2020/03/25 12:52:47",
            "Freq_MHz": "166.3798MHz",
            "Power_dBm": "-21.4dBm",
            "Deltas": "[139.148 151.352  58.588][139.144 151.356  58.588][139.148 151.352  58.588][139.148 151.352  58.588]",
            "Burst_Int": "[4.2995][4.2927][4.3047]"
        },
        "732": {
            "ID": 732,
            "Serial_no": "NQ9999992",
            "Nom_BI": "4.3",
            "Test_time": "2020/03/25 12:54:18",
            "Freq_MHz": "166.3798MHz",
            "Power_dBm": "-24.3dBm",
            "Deltas": "[158.676 156.236  34.176][158.676 156.232  34.18 ][158.676 156.236  34.176][158.676 156.232  34.18 ]",
            "Burst_Int": "[4.3004][4.3027][4.3007]"
        }
    }
}

**Comment by pmorrill** [comment]
**Issues with this format**

-----------
They should not be including units on any of the numeric values. This just makes parsing unnecessarily difficult. e.g.:

"Freq_MHz": "166.3798MHz",
"Power_dBm": "-21.4dBm",

-----------
The "Test_Results" is an object, whereas a JSON array of objects would be easier to handle (no information is added by structuring it as an object).

-----------
I no longer understand how to interpret the 'Deltas' and the 'Burst_Int' fields.

-----------
The Deltas field is using a strange syntax: square braces are separating the data sets inside a String. Why not stick to JSON for this, and make the Delta's an array of json arrays of doubles (for example)??

-----------
The Burst_Int field, also uses square braces inside a String. Why not just make it an array of double??

**Comment by denislepage** [comment]
Here’s a list of elements we should try to validate with incoming tag registration, and possible action. In all cases, a warning/error should be returned to Lotek in the response, and also sent by email to both Lotek and us (address tbd). We’ll also need to define a procedure about how those issues get addressed.

I would likely be useful to have a user contact name or email to follow up with them directly, perhaps. If the project is wrong, we’d have to ask Lotek, and then follow up with the user, or have Lotek follow up and get back to us, which isn’t efficient. I’ll email them with the format issues you asked about above also.

We probably want to store all the fields they are pushing, in case they are useful to track down issues (e.g . Sales Order and tag serial numbers) on their end.

Tags remain in the api table and are not pushed to the tags table in the following situation. Some of them would hopefully be checked by Lotek before they attempt registration, and we may never see them:


-          Unknown tag model

-          Unknown codeset name (we’ll need to parse out/convert the :2020 portions to Lotek6M alone).

-          Unknown project ID

-          Tag number not part of the codeset

-          Bursts that have less or more than 3 pulse intervals.

-          Frequency that is different from the nominal by more than the allowed slop

-          Standard deviation of the pulses or bursts that exceed the allowed slop

-          Average of burst intervals exceed the allowed slop compared to the nominal value

-          Pulse intervals not matching the expected codeset values.

-          Whether the tag number and interval is already in use

-          Whether the tag is already registered (same serial number perhaps?)

-          Anything else?

**Comment by cjardine-bsc** [comment]
To start with I've commented out the section that adds the tag to the DB in motus_sandbox.dbo.prAPIImportTagsLotek so you can begin testing there while I work on altering the proc to accommodate the above changes.

**Comment by pmorrill** [comment]
Data validation will be done either in the Java code or in the DB procedure. In general, it would be better to put it in the proc., where we can. I believe that most of the items above can be dealt with that way. The exception is "Bursts that have less or more than 3 pulse intervals.", which is probably best done in the java code.

Catherine, can you confirm that the remainder can be handled in the procedure? We then have to decide on the error messages to hand back. The procedure should return something like 'fail-excessive-pulse-interval-variance' etc.....

BTW: we should make the 'code' output parameter larger. it is only varchar(20). Same in the procedure for registering ctt tags. (We had a truncated error message recently)

**Comment by cjardine-bsc** [comment]
From Denis:

It would be useful to save at least one of their identifier in our api table, so we can trace any problems. 

Sales order perhaps?

**Comment by denislepage** [comment]
One problem with using an output parameter is that we’d probably want a full list of all issues rather than the first arbitrary one it comes across.

I think the output parameters of a proc cannot be a table. Table valued functions do, but it’s probably not worth doing here.

A couple options are possible. Either we 1) concatenate the response into a single field or return a result set with multiple rows at each tag insert, or 2) (likely my preference) store all the errors in a permanent table that is read after the batch is all inserted.

In the second option, you would need to get a unique batch ID first, then insert all rows of that batch (or we could rely on their purchase order #), then query the error table for generating the final report using the batch ID. Even if you were reporting multiple problems per proc call using the other methods, they would still have to be aggregated into a complete report that covers all tags. Storing the errors more permanently may also be a good way for us to identify recurring issues.

**Comment by cjardine-bsc** [comment]
As it happens we already have that mostly set up with api_main and api_errors.  I've changed motus_sandbox.[dbo].[prAPIImportTagsLotek] to insert any errors into ap_errors. Paul, you can test this in sandbox now, if the @code comes back as 'fail' you'll want to query the api_errors table where apiImportId = @import_id for the list of problems with the registration. 

A few additional things:

RE: Tag number not part of the codeset

Where is this metadata stored? I suspect we should add these to tags_mfg_params 

RE:  Frequency that is different from the nominal by more than the allowed slop
RE:  Standard deviation of the pulses or bursts that exceed the allowed slop
RE:  Average of burst intervals exceed the allowed slop compared to the nominal value

What is our allowed slop?

Still to implement:

-          Pulse intervals not matching the expected codeset values.
We will need to add Codeset6 to tags_mfg_params

-          Whether the tag number and interval is already in use
We should decide on what the "grace period" we will use. I.e. if an existing tag will run out it's lifespan in XX number of days registering a new tag is A-Okay. 

-          Whether the tag is already registered (same serial number perhaps?)

**Comment by pmorrill** [comment]
I actually think that using a table to hold these errors is over-kill. First, we don't really expect to see errors once the system is working: this is Lotek registering, and if they cannot validate and register their own tags reliably, I'd be a bit surprised.

Secondly, I intend to cook up an email to the PI / projectUserEmail recipient, to report on success or failure. For this, I will be writing code to resolve the error 'codes' into real English, using the adm_error_code table. It would be perfectly fine to return the 'code' as a varchar(256) with pipe delimiters in the event of multiple errors on a tag:

`failure_missing_something|failure_excessive_burst_variance`

I realize that there is already a table for errors, but querying that is certainly more elaborate than just splitting a delimited string.

**Comment by pmorrill** [comment]
However, cooperative as always, I have created code to query the api_errors table based on importId and it seems to be working on my dev system. @denislepage and @cjardine-bsc should both have received simple error reporting emails as samples from my recent tests.

**Comment by cjardine-bsc** [comment]
I have indeed seen those emails (example below).  I'm guessing the tag ID included is the mfg_id? I think we'd also want the projectID included. 


Email:

Motus has experienced a problem registering at least one Lotek tag in the recent batch. Please see details below.


Tag ID: 675
	Error: This tag failed to register in Motus => Package parsed but not imported; fail
	Error: fail-unk-codeset
	Error: fail-unk-project

Tag ID: 732
	Error: This tag failed to register in Motus => Package parsed but not imported; fail
	Error: fail-unk-codeset
	Error: fail-unk-project

Tag ID: 635
	Error: This tag failed to register in Motus => Package parsed but not imported; fail
	Error: fail-unk-codeset
	Error: fail-unk-project

**Comment by pmorrill** [comment]
Agreed. I am just setting up the framework so far. I think we should report based on the 'Sales_Order' field for Lotek's usage, and the project Id for our own. I will probably give a more thorough summary of the data, in anycase.

We can talk about details on the call tomorrow.

**Comment by cjardine-bsc** [comment]
Notes for Catherine from Catherine. 

https://github.com/MotusDev/Motus-TO-DO/issues/465

30 day grace period

Denis will send spreadsheet of new codeset burst patterns to Catherine

**Comment by denislepage** [comment]
I had a quick chat with Dave@lotek yesterday.

I think this was captured in his email, but what their testing has found is that the WAV recording seems to be the problematic part. He could say his this was an issue with the FunCube or Audacity (I guess the USB protocol is the other possibility), but the variation in burst intervals and missed pulses both seem to come from missed packets of data. It’s as if you are hitting pause on the recording. They were able to replicate the same problem in their labs with the same setup, but that the tags were otherwise showing fine with their oscillometer and using the SRX. I think he said that all problem intervals were shorter than expected, never longer, which would be consistent.

It’s not necessarily due to a faulty FunCube, though faulty FunCube may be more prone to this. He thinks we may be able to replicate this by recording with Audacity while overloading your CPU with other processes, which would create these missed periods where Audacity is unable to capture data. 

My thinking is that even if the same was happening on the SensorGnome (which I don’t know), the impact would not be the same. That’s because all pulses are timestamped. At worst, we’d be missing pulses, but lack of recording in between burst would not impact the burst interval like it does on the wav file, where data isn’t timestamped.

Once we move to API registration, the problem should go away, basically.

**Comment by StuMackenzie** [comment]
As far as I can tell this can be closed.

**Comment by cjardine-bsc** [comment]
Sorry Stu, I still need this one open too. A few additional data checks listed here that I want to incorporate into the process.

**Comment by ajmacdonald3** [comment]
@cjardine-bsc, here are the tagIDs for the test tags (project 322) I manually registered that were also registered automatically by Lotek:

tagID
--
53444
53443
53442
53441
53440
53439
53424
53423
53422
53421

**Comment by cjardine-bsc** [comment]
Thanks. Here are the differences between your registrations and lotek's. They are very slight. 

Tagging @StuMackenzie and @denislepage for interest.


  | period | period_sd | pulse_len | param1 | param2 | param3 | param4 | param5 | param6
-- | -- | -- | -- | -- | -- | -- | -- | -- | --
difference | 0.00023 | 0.000808 | 0 | -0.002 | -0.002 | -0.002 | 0.002 | 0.002 | 0
difference | 0.00023 | 0.001405 | 0 | -0.003 | -0.002 | -0.004 | 0.002309 | 0 | 0.002
difference | 0.000599 | 0.001253 | 0 | -0.001 | -0.004 | -0.005 | 0 | 0.002 | 0.002
difference | -3.1E-05 | 0.003443 | 0 | -0.001 | -0.004 | -0.009 | 0 | 0 | 0.002
difference | -0.0006 | 0.001572 | 0 | -0.001 | -0.003 | -0.002 | 0 | 0 | 0
difference | 0.0002 | 0.001353 | 0 | -0.003 | -0.002 | -0.004 | 0.002309 | 0 | 0.002
difference | -0.00037 | 0.002554 | 0 | -0.005 | -0.001 | -0.006 | 0 | 0 | 0
difference | 0.0018 | 0.001153 | 0 | -0.002 | -0.003 | -0.01 | 0.002 | 0.002 | 0
difference | 0.00317 | 0.00814 | 0 | -0.002 | -0.002 | -0.002 | 0.002 | 0.002 | 0
difference | 0.00247 | 0.004806 | 0 | -0.003 | -0.002 | -0.005 | 0.002309 | 0 | 0

**Comment by cjardine-bsc** [comment]
RE: I’m not sure of the units here,

The units are the same as the units of the variable. I just subtracted the values from one tag from that of the other. 

Re: Are the pulse differences between the values provided by Lotek and the actual burst measured by tag finder, or with the theoretical burst (which is never achieved with high precision). 

These are differences between the 10 tags Amie recorded and registered and their corresponding lotek registrations. So the actual bursts measured by tagfinder. 

RE: What we should also look at (more importantly) are the burst intervals in all detections, not just those during the registration. We should probably assume that Lotek values are more accurate and may be closer to the average BI reported in the field for any tag, which may actually indicate that the manual registration process is the flawed one.

That would require going to the raw receiver files. This information is not transferred to us from tagfinder.

**Comment by denislepage** [comment]
We store burst intervals in seconds, and pulse intervals in ms. Assuming your measures are the same units, pulses sound totally fine, but I wonder about bursts.

0.004 seconds is the max slop allowed on tags. Can you perhaps email me the JSON file shared by Lotek?

We don’t have the pulses without going to the original files, but the burst interval is simply the difference between 2 hits. That is the value that seem to be cutting it close too.

**Comment by cjardine-bsc** [comment]
Tagfinder Registration: 

select * from tags 
where id in (53444,
53443,
53442,
53441,
53440,
53439,
53424,
53423,
53422,
53421
) 

Lotek Registration:

/****** Script for SelectTopNRows command from SSMS  ******/
SELECT * 
  FROM [motus].[dbo].[api_import_tags]
  where id in (48734,
48735,
48736,
48737,
48738,
48739,
48740,
48741,
48742,
48743) 

You're using Burst Interval to refer to Period and saying that period is only allowed a slop of 0.004 seconds? That's way lower than I would have expected given, but you're right, that's a bit tight given these numbers. 

The raw values are in [api_import_tag_lotek_raw]. Though now I'm realizing that those are missing tag_ids since we're not pushing them to the tags table and because lotek has been re-running its test there are duplicates. 

SELECT * 
  FROM [motus].[dbo].[api_import_tag_lotek_raw]
  where mfg_id in (1,2,3,4) 
  
  I don't have the JSON files for these guys.

**Comment by pmorrill** [comment]
Should we add a foreign key to link the raw data to the processed registration records, at least until we are generating actual tag_id values for the registrations?

**Comment by cjardine-bsc** [comment]
we should! Let user import_id (api_batch_id) it is already and output parameter of prAPIImportTagsLotek

I've added it to the table.

**Comment by ajmacdonald3** [comment]
Project 213 has some new tags registered as NTQB2-4-2S that are actually NTQB2-4-2S-M tags. If I remember correctly, the -M means they're the new codeset? Does it matter that they were registered without the -M, and if so, can we update those tag registrations or do they need to re-register? I'm wondering if these will not match the automatic registrations from Lotek because of this.
