### ISSUE TITLE
Motus API error when trying to download data

### ISSUE THREAD

**Issue by j-sayers** [MotusDev/Motus-TO-DO#816]
I've been recently getting this error when trying to download data:

> Error: Login failed with error message
> 'Motus API request failed [500]
> Internal Server Error'

I suspect a notification has already been sent but I thought I should post anyway

**Comment by jsayers-bsc** [comment]
Recently Project 117/3 has been getting this error repeatedly when trying to download Receiver data. They can download Project tag data just fine, but not a receiver. Multiple members of the project have the same issue over a period of several days. I can't replicate it however, even when downloading their data with a non-admin account.

I see this error from time to time and it's one of those "just try again later" errors. Is there anything in particular that this error refers to or is it more of a generic one?

**Comment by jsayers-bsc** [comment]
Just heard an update from the collaborators. This error is only seen **when trying to download a receiver that does not exist locally**.

> > rcpt <- "SG-7C5CRPI38C3C"
>  # Here: in this case, the file already existed because you had sent it to me – and it works!
> > sql.motus <- tagme(rcpt, new=T, update = T, dir = "D:/GuideMotus/RData")
> Warning in tagme(rcpt, new = T, update = T, dir = "D:/GuideMotus/RData") :
>   Database D:/GuideMotus/RData/SG-7C5CRPI38C3C.motus already exists, so I'm ignoring the 'new=TRUE' option
> Checking for new data for receiver SG-7C5CRPI38C3C (deviceID: 1673)
> activity:     4 new batch records to check
> batchID  1967069 (#     1 of      4): got     18 activity records
> batchID  1967069 (#     1 of      4): got      0 activity records
> batchID  1967070 (#     2 of      4): got      0 activity records
> batchID  1967071 (#     3 of      4): got      0 activity records
> batchID  1967072 (#     4 of      4): got      0 activity records
> Downloaded 18 activity records
> nodeData:     0 new batch records to check
> # Here: in this case, the file doesn’t exist - and it creates an error
> >  sql.motus <- tagme(rcpt, new=T, update = T, dir = "D:/")
> Erreur : Motus API request failed [500]
> Internal Server Error
> > 
>

**Comment by steffilazerte** [comment]
First things first, @jsayers-bsc just to be clear, they've updated to the most recent version of motus? 

If they run `packageVersion("motus")` it should be 4.0.6.

**Comment by steffilazerte** [comment]
The internal server error is definitely an error on the API side, but it could be caused by how the R package asks for data. I asked about updating the package because a change in the API meant that R was sending the wrong information, which *could* result in a server error. That was recently fixed (#955), so first things first, make sure they're updated!

The fact that it works when there is an existing motus data base, might not mean there is no problem, but rather the problem is side-stepped. With the existing data base, the messages show that there are no new hits to download, so if the problem was in the hits, it wouldn't show up. I suspect that if the problem is in the hits, providing a data base isn't actually solving the problem, it's just delaying it until there are new hits to download... but I don't really know.

@pmorrill @cjardine-bsc @denislepage Is there a server/API log that could be used to see what's going on, if someone where able to tell you the date/time of the issue?

**Comment by pmorrill** [comment]
We have no server-side logs. But, when you see a HTTP 500 returned, the CONTENT of that response should be a JSON payload, that carries a more specific error message. That message might help us track this down.

The msg itself would not be useful for the end-user, but if there was a way to view the content of the response for debugging purposes..... (In a browser, I'd just trace the response using the developer tools, but in R you'd want to use R-studio and capture the response payload for viewing, with a break-point for example)

**Comment by steffilazerte** [comment]
Hmm, that's a good point, perhaps I can capture the message as a log file or something so people can send that to us. I can look at it myself, but only if I can replicate the problem!
