### ISSUE TITLE
tellme: Server not responding - 06 Oct 2020

### ISSUE THREAD

**Issue by leberrigan** [MotusDev/Motus-TO-DO#821]
All morning I've been trying to download data through R from the live server and I keep getting timed out:
> Error: Login failed with error message
> 'The server is not responding, please try again later.'

Temporary issue, or do we need to report to the Motus Google Group?

**Comment by denislepage** [comment]
Saw errors today related to this proc, which counts how many records are available before it tries to download them.

prR_Size_receiver(?,?,?,?,?,?,?)

Do you have the receiver number you were trying to access? Were the problems only related to that 1 receiver, or more?

**Comment by leberrigan** [comment]
It turns out this is related to the _tellme_ function -- _tagme_ appears to be working fine.

I've noticed the same issue with one other person using the _tellme_ function as well.

These are the different tests I have done:
1. motus@master: motusServerURL <- "https://motus.org/api"
2. motus@master: motusServerURL <- "https://sandbox.motus.org/api"
3. motus@sandbox: motusServerURL <- "https://motus.org/api"
4. motus@sandbox: motusServerURL <- "https://sandbox.motus.org/api"

**Comment by denislepage** [comment]
We will need a specific receiver(s). The proc is timing out, but it can depend on the exact parameters used.

Are you getting this also for tag projects?

**Comment by steffilazerte** [comment]
Hi @leberrigan, I suspect this is a server side issue. To be clear, could you try the following:

If your problem is with a receiver find your device id (replace XXX with the receiver, i.e. CTT-A8D3250A4A97)
```
motus:::srvDeviceIDForReceiver("XXX")
```
Then access the `tellme()` counts directly (replace XXX with the deviceID returned by the previous step)
```
motus:::srvSizeOfUpdateForReceiver(deviceID = XXX, batchID = 0)
```

If your problem is with a project (replace XXX with your projectID)
```
motus:::srvSizeOfUpdateForTagProject(projectID = XXX, batchID = 0)
```

The `srvSizeOfUpdateForXXXX()` functions are the internal functions that send the server requests for `tellme()`. However, from your error message, it almost looks like a login issue?

**Comment by leberrigan** [comment]
Looks like whatever issue that existed is fixed now. I was testing with several receivers, but SG-1614BBBK1919 and SG-4005BBBK3230 were some.

> motus:::srvDeviceIDForReceiver(recv.serno)
            serno deviceID
1 SG-4005BBBK3230      235

**Comment by denislepage** [comment]
The proc was slow due to trying to count rows in the hits table (the hits R view, actually). I have switched to counting instead the sum of numHits from the batch table. That approach works ok for receivers queries, since batches contain each only 1 receiver. We may have to find another solution for the tellme for tag projects.

**Comment by denislepage** [comment]
I also think we should also switch the counting in prR_Size_tag_project to summing the len field in runs.

I found however a small discrepancy in the total count, due to some records missing in hits.

SELECT SUM(LEN) FROM vwR_Runs_for_tag_project a WHERE a.projectID = 1 and a.batchID > 1379059
= 298589
SELECT count(*) FROM vwR_Hits_for_tag_project a  WHERE a.projectID = 1 and a.batchID > 1379059
= 298542

The difference is due to 1 of the sample picked above missing in vwR_hits.

select * from vwR_Runs_for_tag_project where batchID = 1386613 and projectID = 1
select * from vwR_Hits_for_tag_project where batchID = 1386613 and projectID = 1

That batch covers 3 projects in runs, but only one is returned in hits.

It's a small difference, and I think we should use runs, but @cjardine-bsc  should probably examine the discrepancy.

I have changed the receiver size proc in both DB's, but only changed it in sandbox for tag projects. @cjardine-bsc  also should plan to make the change in live.

In both cases, there is a dramatic improvement in speed. They both complete in a few seconds now, as opposed to about 15 minutes when counting records in the hits table.

**Comment by denislepage** [comment]
Another change I made that may help access to data from r is the use of NOLOCK on the det tables throughout the R views (not any of the metadata tables). Only in sandbox for now. We'll probably need to do a bit of testing, but we should be safe to allow dirty reads in this case.

**Comment by leberrigan** [comment]
It seems like the issue has come up again. Same receivers, but this time it's for both _tellme_ and _tagme_.
```
recv.serno <- 'SG-4005BBBK3230' #

> sql <- tellme(projRecv = recv.serno, dir = dir)
The server did not respond within 120s. Trying again...
Error: The server is not responding, please try again later.

> sql <- tagme(projRecv = recv.serno, update = T, forceMeta = T, dir = dir)
Checking for new data for receiver SG-4005BBBK3230 (deviceID: 235)
The server did not respond within 120s. Trying again...
Error: The server is not responding, please try again later.
```

**Comment by steffilazerte** [comment]
This is definitely a server issue and not an R client one. Unfortunately I run into these delays fairly regularly :slightly_frowning_face:

**Comment by steffilazerte** [comment]
Is this still an issue? Or is this a transient problem as the server becomes overloaded?

I.e. can we close this, or is this something that needs to be explored further, server-side?
