### ISSUE TITLE
Map of Receivers overlays oldest station on top of newest stations

### ISSUE THREAD

**Issue by j-sayers** [MotusDev/Motus-TO-DO#822]
When modifying the slider on the Receivers Map to show terminated deployments, the ordering of pins results in older deployments overlaying newer deployments. 

In cases where there is still an active deployment at a particular location this often causes much confusion since people will only see a terminated deployment, and not the current one.

**Can this order be swapped so that the most recent deployment is always shown on top where multiple deployments exist at the same location?** 

Actually, _only_ loading on the map the most recent deployment would be just as good since only one marker can be selected anyway if they overlap perfectly. 

Something like marker clusterer is an option. Though my own opinion is that clustering is counterproductive unless markers overlap completely (otherwise it results in inconsistent and inaccurate location information depending on zoom level, which I personally feel is quite counterproductive).

**Comment by Hussell** [comment]
The slider shows the state of things in the past, when the now-terminated deployments were active and the current deployments didn't exist yet. It's physically impossible to have two deployments of the same receiver at the same time, so unless there are or were multiple receivers deployed at the same location, there's only ever one deployment at a given location (barring errors in the metadata).

**Comment by jsayers-bsc** [comment]
True but multiple deployments at the same physical local do exist. The map will only show one of these if they overlap perfectly, and currently it shows the oldest one. It would be more useful if it showed the most recent one instead of the oldest.

I just noticed a similar thing the other day when swapping a receiver, resulting in two deployments at the exact same physical location on the very same day. It was the oldest, terminated, deployment that was displayed whereas the newer active deployment was not displayed.
