### ISSUE TITLE
Some receiver deployments not showing up in `alltags`

### ISSUE THREAD

**Issue by adamdsmith** [MotusDev/Motus-TO-DO#838]
Previously when summarizing the detections from our small network of stations (Project 4), I would iterate through each receiver by it's serial number, store the data in its own `.motus` file, and then consolidate. For example, 

```r
cedi <- tagme("SG-3115BBBK0782", update = TRUE, dir = "data", forceMeta = TRUE) %>%
    tbl("alltags") %>%
    collect()
```
Hoping to streamline, I've transitioned to the more efficient download for the entire project and then filter by our receiver project ID:

```r
r4 <- tagme(4, update = TRUE, dir = "data", forceMeta = TRUE) %>%
    tbl("alltags") %>%
    filter(recvProjID == 4) %>%
    collect()
```

But several receivers, including some with substantial numbers of detections (such as the first example above), no longer show up with detections in `alltags`. 

Is there any reason some receivers would fail to be included in the project-wide download? Hope I'm not missing something very obvious here.

**Comment by jsayers-bsc** [comment]
I believe the issue here is that when you download by Project number you will only get tags in your project, so it will only include receivers that your tags have been detected by.

**Comment by adamdsmith** [comment]
That doesn't seem to be the case. What comes from `alltags` using the overarching project includes detections from almost all of our receivers, most of which have never detected any of our own tags.

**Comment by jsayers-bsc** [comment]
That's interesting. At least how this is described in the R Book, the two databases do represent different data. That's been my experience, but maybe there are some inconsistencies there?

> 3.2 Database types
> There are two types of tag detection databases available for download:
> 
> receiver database: includes all detections of any registered tags from a single receiver. A receiver database has a name like SG-1234BBBK5678.motus, where the name is the serial number of the receiver.
> 
> project database: includes all detections of your registered tags from across the Motus network. A tag project database has a name like project-123.motus, where the number is the Motus project ID.
> 
> These two databases correspond to the basic model of data sharing:
> 
> you get all detections of anyone’s tags by your receivers (i.e., one receiver tag database for each receiver you deploy).
> 
> you get all detections of your tags by anyone’s receivers (i.e., one project tag database for each of your Motus projects).

**Comment by cjardine-bsc** [comment]
Hey Adam, 

Just to clarify, when you run tagme(4) do you get tag detections from tags NOT registered to project 4?

**Comment by adamdsmith** [comment]
Oddly, yes. But only from a single project (200), and only a few dozen records. And they all come from detections by project 175.

```r
r4 <- tagme(4, update = FALSE, dir = "Data")
tags <- tbl(r4, "alltags") %>%
  filter(tagProjID != 4) %>%
  collect()
table(tags$tagProjID)
#>
#> 200
#> 56 

rcv <- filter(tags, recvProjID != 4)
table(rcv$recvProjID)
#>
#> 175
#> 56 
```

**Comment by denislepage** [comment]
Not sure if this is a new download or an older motus file?

Wondering if this is a case where tags have been moved across projects, but you downloaded the data before that. The metadata would be updated, but the detections would remain there.

**Comment by adamdsmith** [comment]
I believe this is a relatively new download (fresh in the last 6 months). 

Adam

**Comment by cjardine-bsc** [comment]
Interesting. Can you give me one of the tag_ids from project 200? I'll do some sleuthing!

**Comment by adamdsmith** [comment]
Only two of them show up in there: 29921 and 29925

**Comment by cjardine-bsc** [comment]
Thanks for bringing that to light Adam. An interesting little mystery you uncovered. 

The root of it is that at some point these two tags were identified as ambiguous with two tags in project 4. 

SELECT * FROM [motus].[dbo].[det_ambig_tags]
 where ambigID in (-3775,-3778) 

ambigID	tagNo	motusTagID
-3778	1	29925
-3778	2	36614
-3775	1	29921
-3775	2	36610

SELECT *FROM [motus].[dbo].[tags] where id in (29925,36614,29921,36610) 

id | project_id | mfg_id | date_bin | type | codeset | manufacturer | model | nom_freq | period
-- | -- | -- | -- | -- | -- | -- | -- | -- | --
29921 | 200 | 186 | 2017 | ID | Lotek4 | Lotek | NTQB-4-2 | 166.38 | 19.895
29925 | 200 | 190 | 2017 | ID | Lotek4 | Lotek | NTQB-4-2 | 166.38 | 19.895
36610 | 4 | 186 | 2019 | ID | Lotek4 | Lotek | NTQB2-5-1 | 166.38 | 19.8978
36614 | 4 | 190 | 2019 | ID | Lotek4 | Lotek | NTQB2-5-1 | 166.38 | 19.8978

However, no runs in the DB are currently identified as ambiguous for those pairs of tags (almost certainly due to updated metadata and re-runned receiver data). So this is a rare case, where the ambig has been resolved but the R package is returning the records as ambiguous still. 

SELECT * FROM [motus].[dbo].[det_runs] where ambigID in (-3775,-3778) 

If this file is from 6 months ago, it's possible that ambiguity has been resolved in that time period; since you downloaded the data. Can I ask what batchID the delinquent runs have?

**Comment by adamdsmith** [comment]
The `batchID`s are:

c(878594L, 879756L, 925385L, 928283L, 928984L, 931370L, 933995L, 
935224L, 936959L, 950356L, 954785L, 955059L, 955138L, 1022097L, 
1050854L, 1051101L, 1053338L, 1053496L, 1062855L, 1085651L, 1090360L, 
1104521L, 1119877L, 1120989L, 1121124L)

**Comment by cjardine-bsc** [comment]
Yup that sorts it out. All those batches have been deprecated and re-run. You should see them on the list of deprecated batches in your R download (presuming we've pushed that feature to live?).

**Comment by adamdsmith** [comment]
Thanks @cjardine-bsc
