### ISSUE TITLE
Can't upload data because of constant connection errors?

### ISSUE THREAD

**Issue by leberrigan** [MotusDev/Motus-TO-DO#848]
I've been trying to upload data for the past two days without any luck because everything is extremely sluggish. Not sure what's going on here, but both the verification step and uploads are freezing enough that I haven't been able to successfully upload anything. 

Also, whenever a partial copy exists on the server, it will ALWAYS corrupt if I choose either option (resume or start new). If I choose to start new upload, it will repeatedly corrupt until I choose resume upload. Once the resume upload corrupts then I can upload a file as if it's new. However, none of this is working right now because I'm constantly getting connection errors mid-upload.

**Comment by jsayers-bsc** [comment]
Similar issues here, even more than the usual interruptions. Lately Ryan has been trying to upload data from several local stations and has been getting the following error, which is different than the one I usually see.

![Uploading 7F971556-072F-4734-8FC3-7E29F024300D.jpeg…]()

**Comment by jsayers-bsc** [comment]
On mobile and not sure that image came through. Trying again...

Strangely, Ryan reports getting the “resume upload” option even for a brand new file. 

![D26A339B-DFB7-41B6-B0EC-BBD26A3CFDE3](https://user-images.githubusercontent.com/55001144/98950468-05d6ff00-24c7-11eb-9693-940cc7f662b8.jpeg)

**Comment by leberrigan** [comment]
I believe this can happen if you press the upload button twice accidentally.

**Comment by jsayers-bsc** [comment]
Clicking the upload button _definitely_ causes problems,  and it's very easy to do since there is often a very long lag between clicking and when the webpage responds. In extreme cases, up to a minute. I am in the habit of clicking once, then moving on to something else (e.g. #791). 

I don't recognize this particular error message though. At least, if I've seen it it's been a while.

**Comment by jsayers-bsc** [comment]
BTW I am only passing along Ryan's comments so am not really sure what he's doing, and whether it's related to the connection issues Lucas was having. I did just pass along the tidbit about not clicking twice, so that may help...

**Comment by denislepage** [comment]
A simple script might be enough to prevent double clicks.

**Comment by pmorrill** [comment]
Yes - I thought we already had something present to disable the upload button once it was clicked once.... I will look into it.

**Comment by jsayers-bsc** [comment]
I tried uploading a 1 GB file...

It all went normally for the first 96% or so. 

Then I got a vague "Connection error" message (my screenshot didn't save so I can't share it).

Oddly though, when I returned to the browser after taking the screenshot the upload started again. Then the progress bar got up to around 98% when I got the usual "The file has been corrupted during upload. Please re-zip the file and upload again."

![image](https://user-images.githubusercontent.com/55001144/99135264-7ed17600-25ef-11eb-9610-2ec171a5bd48.png)

As I usually do when I see this error, I selected Verify File again. After that was completed I was informed that the file was new (? no prompt to restart the previous upload) and the process worked fine.

So that was all a little stranger than usual!

**Comment by pmorrill** [comment]
I adjusted the tool in sandbox and beta branches, to prevent a 2nd click of the 'Upload for processing' button, until the upload is successful. If there is an error in the upload (connection broken), the 'Upload' button should remain disabled, until you re-run the 'Verify' check. Or refresh the page. Someone needs to upload a file to the beta server to see this. It won't fix the connection / corruption issues, but it should prevent the user from trying to upload the same file again without verifying it again.

In my testing, as long as I re-verify a file after an interrupted upload, I can select either 'resume' or 'start over' options and it seems to work. But I am on a local network only and not using the NAS drives or sending my files to sgserver.

**Comment by StuMackenzie** [comment]
resolved?
