### ISSUE TITLE
Motus Filter Discsussion

### ISSUE THREAD

**Issue by leberrigan** [MotusDev/Motus-TO-DO#855]
Could we use polygons of species ranges as a way to flag detections that would appear in public view? BirdLife International publishes these ranges in a format that could be adapted: http://datazone.birdlife.org/species/requestdis

I can see this done in a couple ways:
 1) Create a list of possible species for every station. Anything detected here that is _not_ on the list gets flagged.
 2) Each time a bird is detected at a station check whether its range falls in the range map.

There could be issues with projects where vagrants are being tagged ('Bell Vagrants (#98)') since we would all their detections to be flagged. Perhaps we could create exceptions for tag that are deployed in locations that fall outside of expected ranges?

**Comment by cjardine-bsc** [comment]
I've added checklist_id to the sensors_sites_stations table and created two new tables (checklists_ebird, checklists_filters_ebird) in motus_sandbox. 

Denis you should be good to do a little testing of your java proc to bring over checklists from ebird based on locations entered into the sensors_sites_stations table.

**Comment by denislepage** [comment]
Cool. It was just as easy as I hoped it could be (jinxed!). I added a couple procs that were handling the inserts and updates, and it now seems to be working.

Paul, this is a sample script:

MotusProjInfo projInfo = <get the projInfo>
String ebirdLogin = resources.get("ebirdLogin");
String ebirdPW = resources.get("ebirdPW");
double lat = 47.0;
double long = -78.0;
EbirdAPI api = new EbirdAPI(ebirdLogin, ebirdPW, projInfo, false);
JsonObject obj = api.readChecklistID(lat, long, true);
String checklistID = obj.get("checklistId").getAsString();

The checklistId will be a value starting with CLxxxxx (e.g. CL26034)

I created a dedicated Motus user in eBird (all API calls are authenticated), and placed the credentials in motus/web/WEB-INF/bsc_resources.xlm (ebirdLogin and ebirdPW).
In the API constructor, the last boolean parameter (isDevelopment) determines if we use the live API or not. I was thinking we could use development, but then our user may disappear once in a while, and the filters may not be as up to date, so let’s stick with the live API.

In the readChecklistID method, the boolean is what determines whether we save the filter data locally. This is always a 2-step process: 1) use the coordinates to get the checklistID, 2) if update = true, and the last updated date is more recent than our cache, update the local cache. I just tested it and it seems to work in sandbox (from my local machine). To avoid delaying the saving of deployment, we could skip the second step and populate the cache through the procs queue.

CJ, to save some time, you can probably pre-populate the tables above with the data we already have, just that one-time.

For new deployments, we should only call this method if the checklistID is missing, or the coordinates have changed. We’ll also need at some point to go back and do the existing/past deployments. Let’s wait a bit on that though. We’ll probably want to throttle this a bit, or split it into several sessions.  Maybe this is also something we can do through the procs queue.

**Comment by StuMackenzie** [comment]
How specific will this be, or can we throttle it sensitivity wise? I didn’t ask this on the call- should have.

Flag if not on the checklist at all, or a threshold, eg ‘rare’?

For the most part I think the eBird checklists will probably represent 95% or more of the scenarios, but vagrant studies in particular will be an issue. We should be able to turn it off somehow for some projects - not sure if that should be a user feature?

Another test, or example, some of the late night hawks detected here would show up as Rare after Oct 1.

https://motus.org/data/receiverDeploymentDetections?id=6011

____________________

**Comment by denislepage** [comment]
Good point. Filters are often made to catch slightly unusual records. There are several possible levels to derive:


1.       A species is not at all on the filter. We’d need to potentially consider how to deal with subspecies, which may often be missing on filters.

2.       A species is marked as rare year-round (limit = 0 from Jan 1 to Dec 31).

3.       A species is marked as rare part of the year, and we stick to these dates.

4.       We could potentially add or subtract a buffer to reduce flagging of the early/late migrants (e.g. 1 month)

I’m not sure where the threshold for display should be. Likely hiding at least #1. #2 would be a bummer if you are tracking say Loggerhead Shrikes.

A yellow warbler in Ontario in January is highly suspect (or dead). One in early April is possible and potentially very interesting to show. Using a buffer is probably useful in a case like this.

We can certainly add this information to the filter and let users decide how they want to make use of it. The value stored could be the eBird filter limit, including a distinction between NULL and 0’s. That said, the limit would not integrate the notion of buffer.

I’m less clear how we use it ourselves beyond #1, without letting users modulating the threshold for each tagged bird, or toggle the eBird filtering on the public map (yes/no or a choice among the ones above).

I’m a tad worried about the overhead that resolving the correct filter period for each run would represent. Some runs also last extended periods, and deciding if you use the start or end point is context dependent.

I knew I jinxed it.

**Comment by cjardine-bsc** [comment]
Moving some email discussion to this git. 

Elizabeth:

You may already know about this, but you can get shape files for all bird species through BirdLife: https://www.iucnredlist.org/resources/spatial-data-download
and there is a new package in R called CoordinateCleaner that links to these maps and flags coordinates outside of a bird’s range. I think this will be helpful with filtering motus data. I’ve put in a data request for range maps, it may take a few weeks. So we will see how well it works. In the mean time there are some other filters in the package I’m going to play around with (namely flagging coordinates over water). 

Thought I would pass this resource on in case it will be useful to others. 

Denis: 

Thanks. I didn’t know about the R package, but we do have a slightly older version of the layers in our database.

Range maps can be helpful, but they probably have more issues than it’s worth investing too much time into. We now have in our database a process to pull the eBird filters for each receiver location, and those are probably more reliable (they also include a seasonal component). Avibase lists are available at a relatively fine scale as well (usually counties in Canada and US, state/province further south in the Americas with a few exceptions where counties are also used), and they already incorporate birdlife range map information.

The other issue you’ll run into is that Birdlife taxonomy differ from ours, which follows Clements/eBird, in many respects. This will probably have a limited impact in term of species concepts, but the names won’t always match well. I have the mapping between the 2 in Avibase, but the concepts are not aligned, so that would be a bit more work. A benefit of using eBird or Avibase is that we can also keep up more easily with future taxonomic changes.

We chatted about this a couple weeks ago on of call. Can’t remember if you were on the call. eBird filters aren’t perfect either. Someone studying Eastern Loggerhead Shrike in Canada would see all of their sightings flagged as rare, for instance, whereas range maps would probably be more useful for that species. Range maps would not do well to flag a Yellow Warbler in January in Ontario (though they do separate ranges by breeding cycle), but eBird filters would also needlessly flag species that are expected but rare (a migrant that arrives a week early).

Another option we have is to use eBird seasonal bar charts, which is essentially a % of complete checklists reporting a species in a given week, again at the county (US/CA) or province scale. This works very well in areas with lots of data coverage, but would require combining data temporally in certain areas, or relying on other sources. The thresholds will also be very species specific. Yellow and Yellow-rumped Warblers in Ontario in January are both rare, but one is expected and the other pretty much a sure error, something that seasonal bar chart data would tell you to some degree.

Then, of course, these cover only birds.

Anyway. All of these are complementary sources that can help. I am just not sure which one(s) makes the most sense for us to invest into. 

I don’t see a reason why you shouldn’t explore range maps, especially if there’s already a tool that can help you, but so so you are aware of the other options.

What I think we will have in the database in the end is a list of species expected at each receiver, ideally with a seasonal component. We already have a process in place to populate this data for birds using eBird filters, so we’re not too far off that goal, though some questions remain about how we’d use the data.

**Comment by StuMackenzie** [comment]
Closed in deference to #853
