### ISSUE TITLE
Documentation of Documentation

### ISSUE THREAD

**Issue by jsayers-bsc** [MotusDev/Motus-TO-DO#865]
Thought it might be nice to have some of the most helpful documentation posts in one place for reference. Some of this stuff is also in the R book, and elsewhere. But it's often hard to find when needed, and maybe this will help gather some of the important pieces into an easier-to-find location. Below are a handful that spring to mind.

- [Description of the formats and contents of the files recorded by the various receiver types ](https://github.com/MotusWTS/motusServer/blob/master/inst/doc/motus_data_formats.md)

- [What is Aliasing and how best to deal with it](https://github.com/MotusDev/Motus-TO-DO/issues/779)

- [Parameters for Find Tags](https://github.com/MotusDev/Motus-TO-DO/issues/465)

- [Overview of the nuts and bolts of how Motus (and tagfinder) work](https://github.com/MotusWTS/motusServer/blob/master/inst/doc/motus_data_overview.md)

**Comment by leberrigan** [comment]
## Motus Guides
Here we outline how various instructions are organised into Motus Guides. It may eventually make sense to combine multiple guides together into a single comprehensive Motus Book.

### Motus R Book
•	This is strictly an R guide.
•	Contains all information regarding Motus Data downloads and processing through the Motus R package.
•	Edited thru GitHub: https://github.com/MotusWTS/MotusRBook/
•	Public interface: https://motus.org/MotusRBook/
•	Mostly managed by Steffi and Denis.
### Sensorgnome Guide
•	This is strictly a Motus SensorGnome guide.
•	A new repository for sensorgnome.org documentation and will include much of the same information, albeit reorganised and formatted.
•	Developers will be instructed to visit the GitHub Wiki which will be managed by Dale.
•	Edited thru GitHub: https://github.com/sensorgnome-org/sensorgnome-docs
•	Public interface: https://sensorgnome.readthedocs.io/en/latest/ 
•	How to build a Sensorgnome
•	Sensorgnome configuration
•	Sensorgnome troubleshooting
### Motus Equipment Guide
•	Includes ‘selection guide’ that already exists.
•	Contains information on the different equipment used in the Motus network.
•	Edited thru Wordpress.
•	Public interface: https://motus.org/selection-guide/
### Motus Station Installation Guide
•	Covers information on how to install a station in different settings.
•	In development. You can find the latest draft here: https://docs.google.com/document/d/1xntozG3LuynD2dCGXUtYDZjf7W-O-F-FsVSaszZJ_6I/edit?usp=sharing
•	Currently contains a lot of information about equipment, but is intended to specifically talk about how to install Motus equipment.
•	I’m thinking we should make one comprehensive guide that covers both equipment selection and installation since they have so much overlap.
### Motus Tagging Guide
•	How to tag animals.
•	Current version: https://motus.org/data/download/tag_deployment_methods.pdf
## Other Potential Guides
### Motus Study Design
•	Relevant considering the amount of inquiries we get about this. 
•	Could cover details such as: 
•	Tags/receivers to use
•	Selecting a species to study
•	Station placement
•	Type of data that can be collected and how it can be analyzed (examples).
•	We should keep this separate from the R book since nobody will be reading that yet when at the study design stage.
### Motus for Dummies
•	Related to the work Liza was doing, this would be an easy-to-grasp information booklet on wildlife tracking and Motus.
•	Maybe we shouldn’t call it that.
### Manual Tracking
•	We get enough questions about this that I think some kind of methodology would be useful to have.
•	Working draft can be found here: https://docs.google.com/document/d/1cdPzXC-riOqBngdtF73H-llB7RudMB0zgAeG0MyoVEY/edit#

**Comment by StuMackenzie** [comment]
I wonder if this should ultimately just take the form of a 'GUIDES' Page that points users in the direction of all the various guides?
