### ISSUE TITLE
Not all receivers showning up in project Motus file

### ISSUE THREAD

**Issue by j-sayers** [MotusDev/Motus-TO-DO#867]
I'm trying to get the list of project receivers for 210 from the Project-201.motus file. They have a [number of receivers](https://motus.org/data/project/recvs?projectID=210), but only 3 show up in the R data. 
```

m <- tagme(210, update = T, new = F, dir = 'D:/MotusData')
Checking for new data in project 210
activity:     0 new batch records to check
nodeData:     0 new batch records to check
r <- tbl(sql, 'recvDeps') %>% collect() %>% as.data.frame()
distinct(r, serno)
            serno
1 SG-1614BBBK1620
2 SG-E522RPI3C0D7
3 SG-3420RPI3496B
```

It's the same in recvs table. The first two receivers aren't even part of Project 210 at all

**Comment by adamdsmith** [comment]
Possibly related to #838?

**Comment by StuMackenzie** [comment]
resolved @jsayers-bsc

**Comment by jsayers-bsc** [comment]
It is not. Just tried again with a fresh download. Only 3 receivers present in recvDeps. 5 different projects represented in the 3 receivers (2 of which have never been associated with Project 210)

> m <- tagme(210, update = T, new = T, dir = 'D:/MotusData')
Warning in tagme(210, update = T, new = T, dir = "D:/MotusData") :
  Database D:/MotusData/project-210.motus already exists, so I'm ignoring the 'new=TRUE' option
Checking for new data in project 210
activity:     0 new batch records to check
nodeData:     0 new batch records to check
> r <- tbl(m, 'recvDeps') %>% collect() %>% as.data.frame()
> distinct(r, projectID)
  projectID
1        26
2        10
3         2
4         1
5       210

The `recvDeps` table of a Project .motus file should contain **all** a project's receivers, and **only** that project's receivers, correct?

**Comment by denislepage** [comment]
I’m not quite sure I am following.

The theory: receiver metadata when calling tagme on a project # is that you get all detections associated with that “tag” project #, but on any “receiver” project.

E.g. if your tags are in project 1, but your bird was detected on various receivers, you *should* see multiple receiver projects in your data and receiver metadata.

Also in theory: your metadata for receivers should match the same list (including third-party projects).

Finally, the tag metadata should only be for tags in your project. I’m not sure if this is based on the detections or all deployed tags (most will have at least a hit anyway).

If you have tag detections for receivers that are not in your recvDepl table, that’s an issue, but I can’t tell if this is what you are saying below.

Are you missing detections? Tag deployment records? Receiver deployment records? Or are you saying that you are seeing data or metadata that you shouldn’t?

**Comment by cjardine-bsc** [comment]
Heya, 

This is the second time this has shown up as an issue when its a "feature". Maybe we need to be clearer about this in the R book. It seems to confuse people. 

Tagme(project) only give receiver deployments where the project's tags were detected. NOT receivers registered to the project (use tagme(receiver) for that. 

So to answer your question: The recvDeps table of a Project .motus file should contain all a project's receivers, and only that project's receivers, correct?

Answer: Nope. It contains recvDep records of all receivers where the tag from that project was detected.

**Comment by StuMackenzie** [comment]
@jsayers-bsc please examine whether any text/documentation in the R book needs to revised.

**Comment by jsayers-bsc** [comment]
> Heya,
> 
> This is the second time this has shown up as an issue when its a "feature". Maybe we need to be clearer about this in the R book. It seems to confuse people.
> 
> Tagme(project) only give receiver deployments where the project's tags were detected. NOT receivers registered to the project (use tagme(receiver) for that.
> 
> So to answer your question: The recvDeps table of a Project .motus file should contain all a project's receivers, and only that project's receivers, correct?
> 
> Answer: Nope. It contains recvDep records of all receivers where the tag from that project was detected.

Ok so tagme(project) > recvDeps will only contain receivers that detected that project's tags...?

I can see why that would be the case -- so you have a list of only those receivers that have detected your tags -- but yes it's confusing since the expectation may be that tagme(project) would contain all project receivers. 

However, tagme(receiver) > recvDeps also does not contain all project receivers either, but rather just the 1 receiver being queried. Below are two of Project 210 receivers:

```
mr1 <- tagme('SG-3420RPI3496B', update = T, new = T, forceMeta = T, dir = dd)
r1 <- tbl(mr1, 'recvDeps') %>% collect() %>% as.data.frame()
mr2 <- tagme('SG-2C20RPI3AE28', update = T, new = T, forceMeta = T, dir = dd)
r2 <- tbl(mr2, 'recvDeps') %>% collect() %>% as.data.frame()

unique(r1$serno)
[1] "SG-3420RPI3496B"
unique(r2$serno)
[1] "SG-2C20RPI3AE28"
```

I'm  not sure how often anyone tries to use these tables to run through a list of receivers. I hadn't previously myself, but the R Book does suggest using recvDeps for this purpose.

e.g. Section 3.5.4

```
3.5.4 Downloading multiple receivers at the same time
If you have a large number of receivers in your project, and wish to get receiver specific data for each one, rather than downloading them one by one as above, we can download them with a simple loop. Note that since the sample project doesn’t have any receivers associated with it, this script will not result in a download but you can try it with your own project if you have receivers.

# specify the project whose receivers you wish to download:
proj.num <- 176

# get a copy of the metadata only
sql.motus <- tagme(proj.num, new = TRUE, update = FALSE, dir = "./data/")
metadata(sql.motus, proj.num)
tbl.recvDeps <- tbl(sql.motus, "recvDeps")

df.serno <- tbl.recvDeps %>% 
  filter(projectID == proj.num) %>% 
  select(serno) %>% 
  distinct() %>% 
  collect() %>% as.data.frame()

# loop through each receiver (may take a while!)
for (row in 1:nrow(df.serno)) {
  tagme(df.serno[row, "serno"], dir = "./data/", new = TRUE, update = TRUE)
}

# Note you can remove the dir argument if you want to save it to your working
# directory, just make sure that you use the same directory in both calls

```

**SO**. I just ran the bit above from the Motus book, substituting Project 210.  And lo, all 16 receivers registered to Project 210 appear in the result (along with the 2 other receivers outside project 210: SG-1614BBBK1620 SG-E522RPI3C0D7). 

As for my original code, which resulted in only 3 receivers, those are in fact the only 3 receivers that Project 210's single tag has been detected on. So basically as @cjardine-bsc described. 

The main difference is explicitly calling `metadata()` in the second code block. Though `forceMeta = T` was included in my previous code, that didn't seem to result in the addition of the other project receivers. 

The two non-Project 210 receivers that showed up had detections with runLen < 3, so false positives. However, multiple records of one of the receivers are present. Looks like the receivers are being summarized based on DeviceID, rather than SensorID. This doesn't seem desirable since only one of these is actually relevant. 

![image](https://user-images.githubusercontent.com/55001144/104343681-3b4d9800-54ca-11eb-8f49-39a84b4e41a9.png)

Well, I'm no less confused than at the outset. Here are a couple lingering questions, as well as one suggestion:

- Should `tagme(project)` in fact include all project receivers as suggested by the R Book (and as seems to be the case with Project 210 after calling `metadata()`? 
- Is `forceMeta = T` doing what it's supposed to be doing? Should it not force a metadata update in the same way that `metadata()` does?
- The list of receivers in `recvDeps` should be summarized by SensorID rather than DeviceID

**Comment by steffilazerte** [comment]
@jsayers-bsc, is there perhaps a bit of confusion between the use of `tagme(..., forceMeta = TRUE)` and `metadata()`? From the package docs, `metadata()` *is* different:

> update entire metadata for receivers and tags from Motus server. Contrary to tagme, 
> this function retrieves the entire set of metadata for tags and receivers, and not only those 
> pertinent to the detections of your local file.

Again perhaps confusion to be better explained in the Motus R book?

**Comment by jsayers-bsc** [comment]
Yes I'm a little uncertain about the differences between the various incarnations of `forceMeta = T` and `metadata()` whether they are called on a tag project, a receiver project, or system wide. There are a handful of different combinations and they have different results. 

Part of this could be resolved by better clarification in the R book about the various differences between the options. But as I write that, I'm wondering whether we should be dealing with metadata differently in these cases in the first place. Metadata tables are comparatively tiny; what's the advantage to providing partial metadata in any case?

**Should we even be providing selective (aka incomplete) metadata when we could just provide/update _all_ metadata every time?**

That aside, there still does seem to be an issue with updating metadata using `forceMeta = T`. My experience has been that `tagme(..., forceMeta = T)` is unreliable whereas `metadata()` actually does update metadata, provided there is no error as in #929. 

And yes, it would be great if the R book and package help both reflected the same up-to-date documentation. In this case, the R Book offered little explanation on the differences between the different ways of updating metadata whereas the package help did (and apparently I was looking in the wrong place!). Hopefully moving this documentation to the pkgdown format will keep the docs more in sync.

**Comment by steffilazerte** [comment]
Possibly (probably) related to #955, we should check again after that's been tested

**Comment by leberrigan** [comment]
Reopen if it's not resolved
