### ISSUE TITLE
Add Species name to deployment plot

### ISSUE THREAD

**Issue by j-sayers** [MotusDev/Motus-TO-DO#870]
@Hussell Can you add the species names to [these plots ](https://motus.org/data/receiver/deployment/plot/SG-E522RPI3C0D7-2018%20MotusON%2C%20High%20Park.png?id=4945&n=100&firstTag=0)in addition to the FullID?

**Comment by leberrigan** [comment]
It's by design that it shows `fullID` and not `species` since species are associated with deployments and `fullID` is associated with the tag itself. When looking at a deployment plot, you're looking at data that has come directly out of TagFinder, before it has been associated with deployments and filtered for public output. For this reason, it doesn't really make sense to apply species to this plot.

The idea is to provide a more useful plot on the explore dashboard that would provide species and that this plot would only ever be used as a last resort for diagnostics.
