### ISSUE TITLE
Motus.org painfully slow

### ISSUE THREAD

**Issue by StuMackenzie** [MotusDev/Motus-TO-DO#874]
Just me, or are others having issues?

Beta seems more responsive.

Maybe its just my internet.

**Comment by jsayers-bsc** [comment]
Slow for me as well. Though nothing is timing out, just taking a while to load.

**Comment by leberrigan** [comment]
It's been like this since Tuesday. I have been getting frequent 'server not responding' errors and can't download data. We have received 4 emails in 3 days from people who can't access the server.

Sometimes it works really fast, then the 30 minutes later it's painfully slow again. Seems like something is clogging up our server.
