### ISSUE TITLE
Ability to scroll through species list

### ISSUE THREAD

**Issue by zcrysler** [MotusDev/Motus-TO-DO#88]
When you start typing a species name in the species list for a tag deployment, can we make it so you can scroll through the list that pops up?  Currently when you want to enter a deployment for a monarch butterfly, typing "Monarch" results in a species list that is too long to show the butterfly option, the user thought it was not an accepted species since she couldn't select from the list.

**Comment by denislepage** [comment]
A quick work-around for her would be to enter the scientific name, which you may have already told her.

The issue here could be resolved a few ways:


1)      restrict the list of species. It’s not likely, but not impossible, that people tag Monarch birds in the near future. I view this as less than ideal long term though. It’ll be hard to predict now where Motus will expand and we’d have to adjust later.


2)      make a longer list available for scrolling, but there are 53 birds with the name monarch globally, so the list would have to be at least that long. It could not return the entire list of matches though unless we only searched hen the string contained enough characters (e.g. 3 or 4), but some combinations may well produce hundreds of matches.



3)      An alternative is to be a bit wiser about the order in which we return names. If names that start with the search string were always put at the top, that would address the issue in this case. Another similar approach to consider is to sort names based on the number of characters. That way, entering the complete name would always bring it to the top, even if it is partially contained in other names. A downside would the that if people enter “warbler”, then the ordering will make no sense for them.



Something like this would ensure that the single-word species monarch would be at the top, and this is what I think we should go for. I am not sure if we’d still need to increase slightly the number of hits, and/or make the list scrollable, but maybe not.

select * from lk_species where name like ‘%monarch%’ order by CASE WHEN name like ‘monarch%’ then 0 else 1 end, name

**Comment by pmorrill** [comment]
Has anyone experimented with this yet?  Denis' 3rd suggestions should help with no impact on the J code. 

The proc in question is prSearchSpecies. (it's a little more complicated than the sample sql Denis gives above!)

**Comment by cjardine-bsc** [comment]
I've made a change to the proc. 

ALTER PROC [dbo].[prSearchSpecies]
    @qstr varchar(50),
    @n int = 5,
    @group varchar(16) = NULL,
    @lang char(2) = NULL
AS
select top (@n) species_id, english_name, scientific_name, french_name, taxon_group, species_code,
(select sort_order from [dbo].[lk_species_sort_order] b where a.species_id = b.species_id and sort_id = 1) as sort_order
 from dbo.lk_species a
where 
(
(ISNULL(@lang,'EN') = 'EN' and (english_name like '%' + @qstr + '%' COLLATE latin1_general_ci_ai))
or (scientific_name like '%' + @qstr + '%' COLLATE latin1_general_ci_ai))
or (ISNULL(@lang,'FR') = 'FR' and (french_name like '%' + @qstr + '%' COLLATE latin1_general_ci_ai))
or (ISNULL(@lang,'CD') = 'CD' and len(@qstr) in (4,6) 
and exists (select species_code from dbo.lk_species_codes b where a.species_id = b.species_id and b.species_code = @qstr))
-- and exists (select species_id from dendroica.dbo.checklists_species c where a.species_id = c.species_id)
and exists (select sort_order from [dbo].[lk_species_sort_order] b where a.species_id = b.species_id and sort_id = 1) 
and ((@group IS NULL and (taxon_group = null or taxon_group <> 'PLANTS')) OR taxon_group = @group)
and a.species_status = 1
ORDER BY CASE WHEN (CASE WHEN ISNULL(@lang,'EN') = 'EN' THEN english_name else french_name end) like '' + @qstr + '%' then 0 else 
(select sort_order from [dbo].[lk_species_sort_order] b where a.species_id = b.species_id and sort_id = 1) end 

seems to be working well.
