### ISSUE TITLE
Options for data access records/notifications

### ISSUE THREAD

**Issue by ajmacdonald3** [MotusDev/Motus-TO-DO#887]
Currently every time data get accessed through a tagme() call, it gets recorded, whether the user is registered to the project or not and whether it's a new download or an update. Some PIs may not want a record/notification every time data are downloaded, for example if they have several techs or students working on projects and updating data regularly. Collaborative projects combining data from several projects might also lead to lots of records. Some options:

1. PIs can check a box not to record data access for users registered to their project and only record data access for users not registered to their project (public downloads)
2. PIs can check a box not to record data access for updates, only new downloads of the project's data

If we ever do email notifications, it's probably likely PIs wouldn't want to receive emails for downloads by users registered to their project or updates to data the user has already downloaded. Reducing clutter! 

We don't want an option to turn off data access records entirely, as we do want to have this information.

**Comment by cjardine-bsc** [comment]
Small clarification. We will continue to record everything in the database, but what we display to the user in their log can be customized.

**Comment by denislepage** [comment]
As Catherine says. We'll record every log, but we'll build options on the view page to hide project users, and perhaps the default initial view should be to summarize the data by user  (with a number of calls and a range of dates). I guess one thing this won't show is whether people actually downloaded the whole data, or simply called the wrong project and stopped the download immediately, Probably not worth worrying about tracking this more closely.

It'd be really nice to be able to assign DOI's. I think we'd have to go through an established DOI provider. We were a DataCite participant until a couple years ago, but they've changed their rules, so that door is closed.

**Comment by leberrigan** [comment]
Closing the issue for now since it's a feature request. It's link to the feature request project.
