### ISSUE TITLE
Connected receiver repeatedly uploading the same data

### ISSUE THREAD

**Issue by Hussell** [MotusDev/Motus-TO-DO#888]
There's some weird behaviour from SG-F28CRPI33503 on sgdata, where it's been re-uploading the same data from 2017 over and over again. https://sgdata.motus.org/status?logMatch=F28CRPI33503

Perhaps even more concerning is the way the number of hits is decreasing from time to time, even though every batch has the same start and end date. Though that might be a clue to why the same files are being repeatedly uploaded, if they're getting shortened by a small amount, over and over.

**Comment by Hussell** [comment]
I'm getting empty pages for individual receivers at sensorgnome.org, e.g. https://sg-f28crpi33503.sensorgnome.org/ or https://sg-e55brpi3d04c.sensorgnome.org/

**Comment by jsayers-bsc** [comment]
> There's some weird behaviour from SG-F28CRPI33503 on sgdata, where it's been re-uploading the same data from 2017 over and over again. https://sgdata.motus.org/status?logMatch=F28CRPI33503
> 
> Perhaps even more concerning is the way the number of hits is decreasing from time to time, even though every batch has the same start and end date. Though that might be a clue to why the same files are being repeatedly uploaded, if they're getting shortened by a small amount, over and over.

FYI This SG is at @dfloer's for testing. Perhaps that's relevant?

**Comment by dfloer** [comment]
I shouldn't have done anything to that SG that'd cause that, but on the other hand, I have done a few things on it for testing.

I do have a radio and a tag (though the battery may be dead) connected to it, so it should at least be detecting tags.

I'm not sure why it wouldn't be accessible through the web, but the `E55` SG definitely shouldn't because SG.org does not think it exists.
