### ISSUE TITLE
Encoding of characters in error popups

### ISSUE THREAD

**Issue by cjardine-bsc** [MotusDev/Motus-TO-DO#908]
French text 

![image](https://user-images.githubusercontent.com/22172758/106824918-b6711c80-6638-11eb-8417-89a3bc4da884.png)

**Comment by denislepage** [comment]
This is typically the result of pasting text from Word, which converts all apostrophes to curly ones.

A bulk fix would be to update the database directly.

update table set text = replace(text, '&#39;', '''') where text like '%&#39;%'

**Comment by pmorrill** [comment]
Yes - the translations must have been copied in from Word. The curly's work if you deliver your pages as charset=windows-1252; but utf-8 not so well.

**Comment by cjardine-bsc** [comment]
Sorry I should have been more clear. I know I can update characters like this in the database, but I'm not sure that text is IN the database. It isn't in adm_text_descr or adm_error_code. Where are we storing that text?

**Comment by pmorrill** [comment]
Actually, when I re-inspect this, the problem is not really the curly quotes. The issue is probably that someone has put html entities into the text, and our delivery mechanics are then html-entity-encoding that text. This takes something legitimate like this:

&#39;

and turns it into this:

&amp;#39;

The latter does not render as a character anymore.

I will track down the entry to confirm.

**Comment by pmorrill** [comment]
aha. The issue here is one I can fix. The language resolve function is incorrect for use in a jscript alert message box. I will update master and beta9 later today, and search for other uses of this.

**Comment by pmorrill** [comment]
Retest after next beta build..... :)
