### ISSUE TITLE
Home for API docs

### ISSUE THREAD

**Issue by steffilazerte** [MotusDev/Motus-TO-DO#911]
As it came up in #905, we probably need to have a good home for API documentation so that I don't bug people all the time when I'm trying to figure things out. 

Right now I'm trying to document R code design in [CODE_DESIGN.md](https://github.com/MotusWTS/motus/blob/master/CODE_DESIGN.md) in the R package repository.

The old API docs are in the R package repository under [inst/api_docs](https://github.com/MotusWTS/motus/tree/master/inst/api_docs), but perhaps we want a different place for these (I'm not sure it makes sense to update the R package if the API docs change, but don't require a corresponding change in the R package. 

There are some docs in the repository [MotusDev/MotusAPI](https://github.com/MotusDev/MotusAPI) that would make a good place to start documenting things...?

Ping @pmorrill @denislepage

**Comment by pmorrill** [comment]
I'm pretty confused as to where everything is now too. My vote is that we put api documentation under the MotusDev site, since it is really for internal use. The so-called 'upstream_api' term is confusing to me and stems from John's original build of these specs. The documentation is almost certainly not up to date, but maybe we should move it over to the MotusDev/MotusAPI site, and rename it to 'Motus R-client API' or some such.....? IE, this content:

https://github.com/MotusWTS/motusClient/blob/master/inst/doc/upstream_api.md

Note that the 'Motus_API_v2' that is already under MotusDev/MotusAPI is only used internally by the SGServer to talk to Motus. Again, maybe a name change would make this more clear? ie, this one:

https://github.com/MotusDev/MotusAPI/blob/master/Motus_API_2.0.md

**Comment by steffilazerte** [comment]
Ah, I see, that makes sense. Good idea to put docs under MotusDev, I think it makes sense to keep all API docs together. 

I agree that some updated names might be helpful since it seems like there are so many different APIs!
