### ISSUE TITLE
Difficult tag registration - unable to estimate burst interval

### ISSUE THREAD

**Issue by adamdsmith** [MotusDev/Motus-TO-DO#915]
I've tried multiple recordings of increasing length. The tag registration for the attached .wav file keeps failing. This is to be registered with Project 140. The remaining 25 tags registered fine.

[REKN_2021_retry2.zip](https://github.com/MotusDev/Motus-TO-DO/files/6038567/REKN_2021_retry2.zip)

**Comment by denislepage** [comment]
One issue we have seen with failing registration was due to the USB connection with the desktop (some of the recording was being cutoff, creating the impression of different burst intervals, or corrupting the bursts). Trying on a different desktop often seemed to produce different results.

Given that all other tags have registered, this may be different. I examined the pulses, and I am not seeing anything obvious.

The pulse intervals seem to match the manufacturer’s values (I haven’t checked if they are within the allowed slop, but they appear to match within 1 ms at least), and the burst intervals seem consistent.

Thus, so far, I have nothing useful to offer.

**Comment by leberrigan** [comment]
As Denis mentioned, we think this related to the USB implementation of the computer that the FUNcube is plugged in to during registration. It is believed that some data packets sent by the FUNcube to the computer are being dropped, likely because of the way the specific model of computer is implementing USB. Many ports will share the same hardware and the computer cannot read from the simultaneously. If multiple ports are being used, it must quickly switch between devices to transcieve data from each one.
For this reason, we suggest you try to keep other USB ports free if possible, and don't use an external port splitter. A desktop is likely better than a laptop.

**Comment by adamdsmith** [comment]
Right-o. I'll give it a try on another computer with no other significant USB devices and report back. Thanks

**Comment by adamdsmith** [comment]
I think it's the tag. See the attached longer recording from a different computer. That burst interval is not nearly consistent enough....

[tag014_extended.zip](https://github.com/MotusDev/Motus-TO-DO/files/6045194/tag014_extended.zip)

**Comment by denislepage** [comment]
Do you have a way to run the VAMP plugin as a stand-alone to convert the wav file into pulses? There is a call to vamp from motusServer/R/wavFindTags.R, but I haven't tried to do this as a stand-alone.

If you had that file, you can potentially run the pulse file through Unifile.exe and see if you are getting individual hits at least, and whether the burst intervals fall outside the burst slop.

That might at least tell you whether the bursts are being picked up, and give you the precise measures of the intervals. 

Defective tags happen, I assume, but should be rare. Since you only have 1 here, that probably advocate for a tag issue rather than a registration issue.

**Comment by joeybernard** [comment]
This is part of setting up a test framework that I was going to look at. If you don't already have a standalone way to process WAV files, I'll look into it.

**Comment by adamdsmith** [comment]
I’ve not had a chance to explore the VAMP option. I could, but it’s a low priority. So I’d rather defer to @joeybernard finding an alternative if it’s a worthwhile tool to have available.

**Comment by denislepage** [comment]
Given that we are working on having Lotek register tags for user, this is possibly moot at this point
