### ISSUE TITLE
Track search is only returning 68 BANS when there should be 321?

### ISSUE THREAD

**Issue by StuMackenzie** [MotusDev/Motus-TO-DO#924]
https://motus.org/data/tracksSelect?e=2013-01-01&l=2021-12-31&s=35407

logged in or not logged in.

There should be 321. What am I doing wrong?

**Comment by StuMackenzie** [comment]
Also only about 25 projects are being shown in that drop down

**Comment by leberrigan** [comment]
I noticed not all projects are showing up any more. I don't think it will display birds that have no tracks after filtering.

**Comment by denislepage** [comment]
I know Jeremy was working on the track script, and ran into an error, so that might explain it, but maybe this was only on sandbox.

**Comment by StuMackenzie** [comment]
Collaborators are onto us - Received our first inquiry about the track tool.

**Comment by StuMackenzie** [comment]
@another collaborator inquiry about the track tool

**Comment by jsayers-bsc** [comment]
Noticed this too.

**Comment by Hussell** [comment]
321 tag deployments on Bank swallows. Tag deployments with no valid tracks don't show up on this page. 252 when filters are off, 68 when filters are on.

**Comment by Hussell** [comment]
Alright, some examples of tracks that are present when filters are off, absent when filters are on, but look to me like they're valid and shouldn't have been filtered out:
https://motus.org/data/tracksMap?t=1954
https://motus.org/data/tracksMap?t=2002
https://motus.org/data/tracksMap?t=17452
https://motus.org/data/tracksMap?t=18481
https://motus.org/data/tracksMap?t=23439

The numbers are tag deployment IDs.

**Comment by cjardine-bsc** [comment]
Okay so none of those tag_deploy_ids are part of the det_runs_filters_manual table. So that eliminates that as a possible source of error.  *phew*

I decided to trace the first tag back.  It has 6798 runs where the motus filter is NULL (good run). If I look at that based on sensor_deployments it looks like their are plenty of valid runs on 12 different sensors which should make a valid unfiltered track. So it doesn't look like the problem is in the run filters table. 

SELECT c.sensor_deploy_id, count(*) as numRuns, lat, long
  FROM [det_runs] a 
  left  join det_runs_filters b on a.runID =b.runID 
  left join [det_taghits_runs]  c on a.runID =c.run_id 
  where motusTagID = 15195
  and b.probability is null 
  and c.tag_deploy_id = 1954
  group by c.sensor_deploy_id, lat, long


sensor_deploy_id | numRuns | lat | long
-- | -- | -- | --
753 | 17 | 42.6898 | -80.3495
1124 | 141 | 42.5835 | -80.3966
2114 | 6551 | 42.6227 | -80.7218
2137 | 5 | 42.75463 | -80.2708
2140 | 5 | 42.0427 | -82.5144
2145 | 2 | 42.6731 | -81.3254
2146 | 22 | 42.6154 | -80.4582
2147 | 6 | 42.2136 | -82.1727
2153 | 7 | 42.5611 | -80.2844
2293 | 18 | 42.6618 | -80.9044
2368 | 22 | 42.1167 | -83.1891
2429 | 2 | 42.6354 | -80.5577

Here's a thought. You're looking at the "motusFilter" column right? Not the "probmiss" column? The probMiss is a completely different thing (probability of missing a hit within the run) and shouldn't be used for filtering. 

The motusFilter is available in det_runs_filters and det_taghits_runs. A zero value denotes a run that should not be displayed. A NULL value is used for runs that should be displayed. (That's slightly counter intuitive, we had originally set this field up as a probability field, so a probability of 0 means the run is bogus).

Anyway, from what I can see the filters look correct in the DB. Back over to you @Hussell, let me know if you'd like me to trace anything else back.

**Comment by Hussell** [comment]
Looks like it was due to using the wrong securable in one spot. Now we're showing 250 tags having tracks while the filters are on.

**Comment by StuMackenzie** [comment]
@jsayers-bsc  can you test?
