### ISSUE TITLE
Erroneous data issues

### ISSUE THREAD

**Issue by j-sayers** [MotusDev/Motus-TO-DO#930]
Project 129 has a number of ["detections outside of deployment" errors](https://motus.org/data/issues?id=129#) showing up for tags and receivers during periods when deployments were active.

Receivers:

![image](https://user-images.githubusercontent.com/55001144/111661201-32888380-87e5-11eb-852f-f13c1687f100.png)

And yet these 3 receivers each have uninterrupted deployments during this period. One example below:

![image](https://user-images.githubusercontent.com/55001144/111661350-56e46000-87e5-11eb-8f9f-a6da2450b3c9.png)

Same thing with tags

![image](https://user-images.githubusercontent.com/55001144/111668091-c3faf400-87eb-11eb-91af-59f4eabc379e.png)

Again, these tags have active deployments throughout the period (first one as an example)

![image](https://user-images.githubusercontent.com/55001144/111668148-d6752d80-87eb-11eb-8347-71ec1968b4aa.png)

**Comment by cjardine-bsc** [comment]
Huh. 

Sensors:

These rely on the det_taghits_daily table. That table should be re-generated whenever a deployment is updated with a new start or end date via a trigger (tr_sensor_deployments_update). 

But that trigger is running prTaghitsSummariesSensorDeployID which doesn't remove the records from det_taghits_daily where deploy_id = 0. Which it needs to. 

So I think need to change tr_sensor_deployments_update to run prTaghitsSummariesSensorID instead of prTaghitsSummariesSensorDeployID (via the procs queue). @denislepage any objections or red flags?

In the meantime I re-ran the following 4 sensors.

4207
4210
4227
4237

Tags:  Same problem but with tr_tags_deployments_update 

In the meantime I re-ran the following tags. 
44625
44636
44637
44639
44642
44643
44647
48956
50859

@jsayers-bsc  FYI that test deployment for 44625 is probably problematic. I'm suspicious that the tag wasn't on for that whole period. So that's going to cause issues with it's lifespan. 

https://www.youtube.com/watch?v=vmJcHaPlROY (I feel like the Motus team playing a few rounds of Among Us would be an excellent team building exercise ;-)

**Comment by eageldart** [comment]
The Receiver error: No Recent Detection Data (e.g., https://motus.org/data/issues?id=2#v_sensor_no_recent_data180) seems to be based on the data from the most recent receiver, not the station. So if we switch the receiver at a station after having uploaded new detection data from the previous receiver, we get this error that we have not uploaded new detection data. @leberrigan and I think it may now make more sense to base this issue on the station rather than the receiver. Does this make sense?

**Comment by cjardine-bsc** [comment]
hmmmm That error should only come in for active deployments. So if you've swapped the receiver, the old deployment should be set to terminated and shouldn't trigger an error. 

I looked at the proc and the logic seems right. But I might be missing something. Can you tell me one of these deployments that does have recent data but is flagging incorrectly? I can maybe work from there backwards to see if there is an issue.

**Comment by cjardine-bsc** [comment]
I've implemented this in the two triggers tr_sensor_deployments_update and tr_tags_deployments_update
