### ISSUE TITLE
What to do with "groups" 

### ISSUE THREAD

**Issue by leberrigan** [MotusDev/Motus-TO-DO#937]
We have discussed putting the 'group' definition at the receiver or tag level such that a single project can be part of multiple groups. At least, that's how it would be defined in the database. 

However, as a user it would be tedious and confusing to set groups by individual deployment. I think we should start with the option to set a group for an entire project at once and then think about adding settings for individual stations/animals in the future. 

In addition, if we're adding a new definition we should probably make sure we're picking the right term. In English, "group" is often interchangeable with "organisation" which could be confusing in this context. Perhaps we could use the words "category" or "class" instead? Or maybe that only adds to the confusion.

**Comment by StuMackenzie** [comment]
This requires discussion again. There are other considerations, or reasons why we may want to 'Group' projects. Take collaborative works for instance. A researcher wants to collect data from 15 different projects tagging shorebirds. PI's can 'label' their project as 'Shorebird Collective' and then have access to all project data through summary tools, and/or the ability to download all data from these projects with one call rather than 15.

In the case of the offshore wind project we just need a 'group' where all these projects data can be grouped and summarized. 

The issue of whether a station or tag is included in these groups is a separate issue that can be defined using regional or polygon-related summaries. 

So, I think they need to be handled separately. Garbled for now...

**Comment by cjardine-bsc** [comment]
I think Lucas has got it right when he says "that's how its defined in the database". 

We can set up the backend to be managed by a list of stations or tag_deployments, but how the user populates that list from the web end is flexible. It can be as simple as them picking a project and having it's list of tags added to that "group". 

***slowly backs away from naming debate***

**Comment by StuMackenzie** [comment]
That's fine - I'd like to talk about how the front end will be organized - at the moment the best 'group' we have is the admin label., so we need something else.
