### ISSUE TITLE
No data from SensorStations since 2021-03-26 4:00 UTC

### ISSUE THREAD

**Issue by jsayers-bsc** [MotusDev/Motus-TO-DO#938]
Just heard from Project 129 by way of CTT that they have no data from their SensorStations since 2021-03-26 4:00 UTC. But they appear to be sending data to CTT regularly. I checked with the 10 or so in Ontario and then system wide and there doesn't appear to be any batches from SensorStations at all since that date (again, ours are syncing fine to CTT).

Has anything changed on our end around that time that would affect data import?

**Comment by Hussell** [comment]
In the job logs I'm seeing AmazonS3Exception "AccessDenied" on sandbox from the ReadCTTFiles process since the 26th.

**Comment by denislepage** [comment]
The timing seemed a bit suspicious, since we just launched the new portion for dual mode data, but I think it was done before the 26th.

In any case, the AWS browser is giving us the same error on both sandbox and live, so this is almost certainly a token permission issue on AWS’s end. I wonder if those have expiry dates.

I’ll poke CTT.

**Comment by Hussell** [comment]
They're back. Took most of a day to process the backlog.
