### ISSUE TITLE
Web glitches

### ISSUE THREAD

**Issue by StuMackenzie** [MotusDev/Motus-TO-DO#945]
- headers and drop down menu's don't always match options on the landing page
- guides dropdown link returns a 404 error

- Track Search - when on mobile putting one letter in the search box automatically triggers a search

**Comment by denislepage** [comment]
Menu in jsp folders need to be refreshed after changes in wordpress. I think we have a tool in the admin pages.

**Comment by Hussell** [comment]
Headers and menus seem to match between WordPress and Tomcat (/data) for me. On the other hand, the French and English menus don't match. It looks as though English links have been added, moved to different menus, and changed, without making the corresponding changes to the French menus. General policy when there's no French translation of a linked page has been to link to the English page instead rather than omit the link, so the menus should have the same items in the same order.

The guides link works for me on both WordPress and Tomcat, whether or not I'm logged in. Missing from the French menus.

The track search thing is a whole different issue. Those aren't search boxes, they're multi-select menus. They were created with mouse interaction in mind. I may have to redo them while keeping keyboard interaction in mind as well.

**Comment by Hussell** [comment]
@StuMackenzie, test putting one letter in the search box on mobile here: https://beta.motus.org/data/tracksSearch

**Comment by StuMackenzie** [comment]
Thanks - that one seems ok. The other problem was the search box in explore projects. i suspect it may be the same wherever we have a search box?

**Comment by leberrigan** [comment]
Are you still getting the 404 error when navigating to guide thru dropdown menu?

Search boxes on Explore Projects and Explore Species Tagged pages still triggers the form to submit on 'input' event (Line 40 in motusTable.js).
