### ISSUE TITLE
Switch to using Station Name on the tracks maps

### ISSUE THREAD

**Issue by j-sayers** [MotusDev/Motus-TO-DO#948]
For [this tag](https://motus.org/data/tagDeployment?id=28612), there are detections at one of the more problematic stations -- Tadoussac. But when clicking on the tracks map, the popup shows "Grève de Tadoussac", whereas in the name "Tadoussac - André" is displayed. Thing is, there doesn't even seem to be a "Grève de Tadoussac" in the db at all! Where is that name coming from?!

![image](https://user-images.githubusercontent.com/55001144/114708918-f9670480-9cf9-11eb-94e7-d600fdd6715c.png)

**Comment by jsayers-bsc** [comment]
Also, while _a_ Tadoussac shows up in the detections [Table ](https://motus.org/data/tagDeploymentDetections?id=28615)(the correct name?) and one with a different name is in the [Map](https://motus.org/data/track?tagDeploymentId=28615), Tadoussac is absent entirely from the [timeline](https://motus.org/data/tag/deployment/detections/timeline?year=2021&id=28615). I thought maybe this was because it was flagged as problematic and just didn't show show up here (as in #919) but this tagDeployID is not present in runs_filters_manual.

**Comment by cjardine-bsc** [comment]
It's the site name, instead of the deployment name: 

SELECT * 
  FROM [motus].[dbo].[sensor_sites]
  where name like '%Tadoussac%'

I'll leave it with @Hussell to figure out why the deployment isn't on the timeline.

**Comment by leberrigan** [comment]
This is because there is a difference between the `sitename` and `recvDeployName`. I believe Jeremy is using `recvDeployName` in these maps, whereas usually it's `sitename` that's used in the tables.

**Comment by leberrigan** [comment]
I think we can close this in favor of the new explore dashboard
