### ISSUE TITLE
Maintain access to Manage Receivers in beta 

### ISSUE THREAD

**Issue by jsayers-bsc** [MotusDev/Motus-TO-DO#960]
I've been trying to use Beta for daily tasks to test as I work and notice that Manage Receivers isn't accessible. This is obviously because we're moving to Manage Stations, but the Stations side of things isn't completely implemented so there isn't much there. Manage Receivers is still in the Manage Data dropdown, but it doesn't lead anywhere.

Can we keep both Manage Receivers and Manage Stations while we test the new features? Aside from not having to jump back and forth as much between Beta and Live, it will probably also help with testing the Stations function as we get closer to rolling that out.

Not sure if this is @Hussell or @pmorrill or both...

**Comment by pmorrill** [comment]
It's to late for that. Manage Recv's is gone from the branch.

The manage stations tools will let you do everything that you did with receivers, but not until @cjardine-bsc  finishes running scripts to link the receivers to the stations.

**Comment by cjardine-bsc** [comment]
Agreed. And I wouldn't want you making changes to the Stations in Beta anyway because I'll be wiping them and replacing them when we push to live. 

Basically I suggest you use live to manage receiver deployments and sites at this point. 

But yeah, I can run my script so you can test the stations stuff, but I wouldn't want you to make any real changes there until things have gone to live.

**Comment by jsayers-bsc** [comment]
Well then. I'll just close this for now then :)
