### ISSUE TITLE
Make website warnings modals or popups to preserve user data entry

### ISSUE THREAD

**Issue by j-sayers** [MotusDev/Motus-TO-DO#966]
I was just entering deployment details for a repaired station. After I entered everything and saved I got an error that there was an existing deployment for this receiver, but the error was presented on page reload and I lost everything I had just copied over from the previous deployment. Having to manually copy all details whenever a receiver is swapped will be a thing of the past once management by station is in place. But having form entry lost on page reload is an irritation anywhere, not just the Motus site.

Is it possible to present such warnings as modals or similar so that user entry is preserved?

![image](https://user-images.githubusercontent.com/55001144/118359991-b9db4480-b553-11eb-9ed1-171fa534c73d.png)

**Comment by pmorrill** [comment]
It's not so simple (what is). Data validation has to occur in order to detect the error, and data validation happens server side, for the most part. So form submission is required, preventing a simple modal error box.

But - in most cases we try to 'recycle' the data that was submitted, and then present it again to the user (even though it was not saved in the database due to an error somewhere). But clearly that is not happening here. The short answer is: the error msg (modal vs non-modal) is not the issue. The issue is that the unsaved data is not getting re-displayed when the page is presented back to the user. I will try to look at why that is not happening.

**Comment by jsayers-bsc** [comment]
Right, good to know.
