### ISSUE TITLE
Batch in the Future (and some questions)

### ISSUE THREAD

**Issue by j-sayers** [MotusDev/Motus-TO-DO#969]
Project 213 recently inquired about why one of their receivers has a "Last Data Date" in the future. This has been addressed before (#362 and #574), but I'm not sure if it's been completely resolved. This one looked a bit different, and brings up several general questions I have.

The source of the wonky date appears to be a single run of length 1 (runID 170764059). As it's clearly a faulty date it seems the best option here is simply to **delete that run?** Or is there a better method? The hit itself may well be legitimate as the tag is deployed and active around this receiver.

Do we have any better sense for how this is happening? The time stamps in the gps table all appear to be fine. And though it was just a single run, it's a little worrying that incorrect dates can occur in devices with real-time clocks and battery backup as well. We notice it when it's conspicuously in the future, but if the incorrect date was only off by days or weeks it might not get noticed. Maybe the run length is always short so it would tend to filtered out anyway, but who knows...

As I was trying to find where the date was coming from I also had some general questions about the batches table.

select top 100
batchID,
projectID,
motusDeviceID, 
monoBN,
dbo.ts2datetime(tsBegin) tsBegin,
dbo.ts2datetime(tsEnd) tsEnd,
dbo.ts2datetime(ts) ts,
dbo.ts2datetime(tsMotus) tsMotus,
numHits,
is_new
from det_batches
where motusDeviceID = 1825 
order by tsEnd desc;

- Why is projectID 0? This receiver is registered to Project 113
- tsBegin and tsEnd are presumably the start and end of the batch as recorded by the receiver, but what is ts? Sometimes ts is earlier than tsBegin; sometimes it's later. Likewise ts and tsEnd. 
- tsMotus is the time it was processed? 
- What does the isNew field represent? A reprocessed batch?
- Thanks!

**Comment by cjardine-bsc** [comment]
RE:  As it's clearly a faulty date it seems the best option here is simply to delete that run? Or is there a better method? The hit itself may well be legitimate as the tag is deployed and active around this receiver.

Its from a bad GPS timestamp. When this happens we update the end date of the batch. @Hussell did you want to look at this one? 

This is not fully resolved in an elegant way. It's something we could look at, but lower priority. 


Why is projectID 0? This receiver is registered to Project 113

The projectID is the project that uploaded the data. If it's a linked receiver it's 0. But this field isn't used for anything other than seeing who uploaded the data for trouble shooting purposes. So don't worry too much about it. 

tsBegin and tsEnd are presumably the start and end of the batch as recorded by the receiver, but what is ts? Sometimes ts is earlier than tsBegin; sometimes it's later. Likewise ts and tsEnd.

The time the batch was processed by tagfinder. It shouldn't be earlier that tsBegin. That indicates a bad timestamp. 

tsMotus is the time it was processed?

Imported into our DB. 

What does the isNew field represent? A reprocessed batch?

No. This is a field used when importing, it is set to true when the batch is written and false once all the summaries on the batch have finished running. Not something you should need to worry about.

**Comment by Hussell** [comment]
This is interesting because the source of the run and batch is CTT, not our tag finder. I'm not sure whether I should add a filter to the "Last data received" query to only look at batches from our tag finder, or if we need to figure out how to deal with bad timestamps from CTT as well.

**Comment by jsayers-bsc** [comment]
> > tsBegin and tsEnd are presumably the start and end of the batch as recorded by the receiver, but what is ts? Sometimes ts is earlier than tsBegin; sometimes it's later. Likewise ts and tsEnd.
> 
> The time the batch was processed by tagfinder. It shouldn't be earlier that tsBegin. That indicates a bad timestamp.
> 

For this particular receiver anyway, there are actually more than _twice_ as many batches where ts < tsBegin than the other way around. Even more so where ts < tsEnd (~4600 vs ~650 where ts > tsEnd).

**Comment by jsayers-bsc** [comment]
Another case of an individual hit causing the last data date to be in the future. This is runID 203625841, and it stems from a node connected to a SensorStation. https://motus.org/data/receiverDeployment?id=7573

Related to one of my previous questions, looks like there are lots of batches in the database where `ts` precedes `tsBegin` (~750,0000) and where `tsMotus` precedes `tsBegin` (32,000). And some where `tsEnd` precedes `tsBegin' (1,300). In theory this should always be tsBegin < tsEnd < ts < tsMotus right?

**Comment by Hussell** [comment]
Yes, in theory tsBegin <= tsEnd <= ts <= tsMotus.

tsBegin > tsEnd: 1,227 from CTT, 2 from our tag finder. Both of the ones from us involve invalid timestamps, where tsEnd is near 0. A few of the ones from CTT are similar, but the bulk all have an identical tsEnd of 2016-12-28 12:03:51. All of the latter were generated between 2020-08-10 and 2020-08-13, and we haven't had any new ones from CTT since 2020-08-18. Probably a solved issue.

tsEnd > ts: 799,971 from CTT, 704 from our tag finder. The ones from us all involve small time differences, less than two minutes, which might be accounted for by differences between the clock on the receiver and the clock on the server. The CTT ones involve a wide range of differences, up to the maximum possible, more than 85 years. They seem to be produced regularly, from 2019-10-17 up to the present day. Perhaps six or seven thousand involve impossibly large values of tsEnd, up near the maximum size of a 32 bit integer. The remainder (99.2%) involve differences of less than 24 hours, but only 293 (far less than 1%) are differences of less than two minutes. There's nothing we can do about this other than point it out to CTT.

ts > tsMotus: 0 from CTT, 83 from our tag finder. The maximum difference here is a bit less than 4 hours. All of these were generated between 2019-07-20 and 2019-07-24. Might have been that one time one of the server clocks suddenly started drifting off so far that authentication tokens started to instantly expire. Fixed now, obviously.
