### ISSUE TITLE
Manual uploads of CTT detection data from SensorStations

### ISSUE THREAD

**Issue by jsayers-bsc** [MotusDev/Motus-TO-DO#974]
I just did a manual upload from a SS and none of the CTT detections are present after processing. Makes me wonder if the file is perhaps not being parsed properly?

When data files are manually downloaded from SensorStations, two zip files are acquired: one contains the SG data and can be uploaded as is; the other contains the CTT data. 

Based on the job log it looks like we don't recognize the CTT data file format when coming from a SS.

![image](https://user-images.githubusercontent.com/55001144/119038242-e098e100-b980-11eb-8102-871fdff6374c.png)

**Comment by StuMackenzie** [comment]
elevating this warning from @jsayers-bsc . You'll see why ;)

**Comment by dfloer** [comment]
Presume this is the same issue as the email from Denis?

**Comment by denislepage** [comment]
I don't think this is an issue for @dfloer.

CTT log files are a new type that sgdata didn't know how to handle. @Hussell will need to deploy a change to motusServer to also recognize these files, so they are pushed to /sgm/ctt_outgoing, like we do for gps, data and node files.

BTW, this is the same folder that is getting stuck, but I managed to push everything pending to AWS over the weekend. Don't yet have the process fully automated.

**Comment by Hussell** [comment]
<a href='https://sgdata.motus.org/status?jobID=6855406'>Job #6855406</a> was due to an upload on May 20th. I reran it on Nov. 19th as <a href='https://sgdata.motus.org/status?jobID=10600405'>job #10600405</a>, after fixing the thing with the log files, so unless there's new information somewhere, this issue can be closed.

**Comment by StuMackenzie** [comment]
Sorry - just searching for related issues haphazardly.

**Comment by denislepage** [comment]
I think that makes sense, as CTT files are parsed out to the outgoing folder only during the initial processing, but I suspect those log files were pushed to the file_repo folder since motusServer didn't know how to handle them at that stage. It'd be challenging to hunt them all them, but we can manually inspect this one and try to manually move them to ctt_outgoing.
