### ISSUE TITLE
New SensorStations allow 434 dongles on all USB ports 

### ISSUE THREAD

**Issue by j-sayers** [MotusDev/Motus-TO-DO#977]
Recent SensorStation software allows users to add more than 5 434 MHz radios by using a CTT dongle in the USB ports. There are a few outstanding questions related to this, but it looks like it may require some changes on our end to accommodate.

At the moment the SS records 434 and 166 MHz data in different files, and the ports are just recorded as numbers 1 through 5 for CTT and 1 through 7 for Lotek data; the "L" prefix is added to the CTT detections to differentiate the ports. With the new changes the USB ports will be labelled 6 through 12. Unfortunately this only applies to internal numbering; the ports will still be labelled USB1-USB7 on the board, which will definitely cause some confusion.

One question is whether the new ports would have the "L" prefix for 434 detections. There wouldn't seem to be any need for that since there would be no ambiguity between detections of either tag type. Then these could be entered in the same way as a 166 antenna, just that a different dongle type would be selected.

**Comment by jsayers-bsc** [comment]
I got some more information from CTT about this. Port numbering for Nanotag antennas will is unchanged (1 through 7).

However if a 434 antenna is attached to any of these ports, the port will instead be registered as 6-12. This will be a bit confusing for users entering deployment records, but it does keep things a bit simpler. 

- Any time we receive CTT detection data from SensorStations on ports > 5 those would require the "L" prefix.
- We need to provide options for ports L6 through L12 in the antenna dropdown -- if there's even room to do that since that would make a long dropdown! Either way we need some way for user to indicate this in their deployment records.

This is likely to be an uncommon practice in general. However there is at least one project already doing this.

**Comment by denislepage** [comment]
Following up from our chat yesterday. Here's what I am proposing we do. Choices available on the antenna table will vary based on 1) the receiver type and 2) the dongle associated with the port. The only downside as I mentioned yesterday is that the port number makes more logical sense to be the first column for users, but in practical term, this new approach means that the port number will depend on the dongle used. Once the data is entered, we could potentially reorder the columns, though that also might be unintuitive.

### CTT SensorStations

**No Dongle (CTT station):**
L1
L2
L3
L4
L5

Freq: 434

**CTT dongle:**

L6 (USB 1)
L7 (USB 2)
L8 (USB 3)
L9 (USB 4)
L10 (USB 5)
L11 (USB 6)
L12 (USB 7)

Freq: 434

**Funcube Pro (or any other Dongle for Lotek tags)**

1 (USB 1)
2 (USB 2)
3 (USB 3)
4 (USB 4)
5 (USB 5)
6 (USB 6)
7 (USB 7)

Freq: 150.10, 151.50, 166.38

###SensorGnome

**Funcube Pro (or any other Dongle for Lotek tags)**

1 (USB 1)
2 (USB 2)
3 (USB 3)
4 (USB 4)
5 (USB 5)
6 (USB 6)
7 (USB 7)

Freq: 150.10, 151.50, 166.38

**CTT dongle:**

1 (USB 1)
2 (USB 2)
3 (USB 3)
4 (USB 4)
5 (USB 5)
6 (USB 6)
7 (USB 7)

Freq: 434

I think this approach will address the possible confusions arising from having the data coming from different port numbers depending on the type of dongle used, and should cover the various choices available.

@pmorrill I have also started to look at table changes to give you 1) a list of possible dongles based on the receiver type (actually, the device type, which is a new concept we didn't have) and 2) a list of possible frequencies and port numbers based on the device type and dongle type.  Turned out to be slightly more complicated than I wanted (of course), but I'd rather have this logic build into the database, which makes it easier to change later.

I'll report back on that.

**Comment by denislepage** [comment]
Here are the queries needed. 

**1. List of dongles by receiver type:**

First a list of dongle_type values supported by each receiver (each receiver is actually attached to a device type, and we have a list of dongles for each of the following device types: ctt, sg, sei, lotek and unknown).

```
select dongle_type from lk_receiver_type a inner join lk_device_dongles c 
  on a.device_type = c.device_type where a.receiver_type = ?
```

Two examples:

```
select dongle_type from lk_receiver_type a inner join lk_device_dongles c 
on a.device_type = c.device_type where a.receiver_type = 'SENSORGNOME'

select dongle_type from lk_receiver_type a inner join lk_device_dongles c 
on a.device_type = c.device_type where a.receiver_type = 'LOTEKSRX800.

```
I also realized that the structure we are proposing (pick a dongle first) means that the dongle type will now be a required field. This has at least 2 consequences:

- I had to include a new dongle type for Lotek Integrated, which we also need to enforce for all antennae on Lotek SRX. That will be the only option available for Lotek. I haven't added those to the sensor_antenna table.

- We may also need a generic Unknown dongle type?

**2. List of frequencies for a given dongle type**

```
select frequency from lk_dongle_frequencies where dongle_type = 'Funcube pro'
```

Example: 
```
select frequency from lk_dongle_frequencies where dongle_type = ?
```

Actually, the full list of possible frequencies for all available dongles should probably be loaded with the page for a given receiver type, so this can be managed on the client side:

```
select c.dongle_type, c.frequency from lk_receiver_type a inner join lk_device_dongles b on a.device_type = b.device_type
inner join lk_dongle_frequencies c on b.dongle_type = c.dongle_type
where a.receiver_type = 'SENSORGNOME'
```

**3. List of available port numbers based on the receiver and dongle types.**

Again, probably best to load the full list of available ports per receiver type. There are some examples currently where the port number exceeds the values I have put in the lk_port_numbers table, so we'll need to make sure we have all basis covered. This query could potentially be used in place of the first one since it also returns the list of dongles per receiver type

``` 
select b.dongle_type, c.port, c.port_descr, c.sort from lk_receiver_type a inner join lk_device_dongles b 
on a.device_type = b.device_type
inner join lk_port_numbers c on b.port_config = c.port_config
where a.receiver_type = 'SENSORSTATION'
order by b.dongle_type, c.sort
``` 

My suggestion would be to build a JSON object that we can place in a separate servlet that contains all the necessary info for a given receiver type. The benefit of a JSON servlet is that the browser will be able to cache it for later use. For example:

/receiverDongles?receiverType=SENSORSTATION

```
[{
		"dongleType": "CTT Integrated",
		"frequencies": [434.00],
		"ports": ["L1", "L2", "L3", "L4", "L5"],
		"portsDescr": ["L1", "L2", "L3", "L4", "L5"]
	},
	{
		"dongleType": "CTT LifeTag (TM)",
		"frequencies": [434.00],
		"ports": ["L6", "L7", "L8", "L9", "L10", "L11", "L12"],
		"portsDescr": ["L6 (USB 1)", "L7 (USB 2)", "L8 (USB 3)", "L9 (USB 4)", "L10 (USB 5)", "L11 (USB 6)", "L12 (USB 7)"]
	},
	{
		"dongleType": "FunCube Pro Plus",
		"frequencies": [150.10, 151.50, 166.38],
		"ports": ["1", "2", "3", "4", "5", "6", "7"],
		"portsDescr": ["1 (USB 1)", "2 (USB 2)", "3 (USB 3)", "4 (USB 4)", "5 (USB 5)", "6 (USB 6)", "7 (USB 7)"]
	},
	{
		"dongleType": "RTL-SDR",
		"frequencies": [150.10, 151.50, 166.38],
		"ports": ["1", "2", "3", "4", "5", "6", "7"],
		"portsDescr": ["1 (USB 1)", "2 (USB 2)", "3 (USB 3)", "4 (USB 4)", "5 (USB 5)", "6 (USB 6)", "7 (USB 7)"]
	}
]
```

**Comment by denislepage** [comment]
For @cjardine-bsc : the list of new tables or changes I made to support this. Both database should be relatively in sync for these changes, but we should double-check.

- lk_port_config: new table (list of possible port configurations)
- lk_port_numbers: new table (list of ports available per configuration)
- lk_device_type: new values added (table existed, but wasn't used)
- lk_device_dongles: new table (list of dongles supported by device type)
- lk_dongle_type (1 value added: "Lotek Integrated", may need 1 for "Unknown" also)
- lk_receiver_type (1 required column added: device_type, which ties each receiver type to a device type)
- lk_dongle_frequencies: new table (XCVR may need to also support 150-166 range).

- sensor_antenna will probably need to have missing dongle_type populated.

See if you want to go away again... ;-)

**Comment by pmorrill** [comment]
I have posted a new Antenna mgmt interface into master branch (only). Using the tables listed above, client side code drives the population of the port and frequency selection boxes based on dongle type selection.

Someone with good knowledge of the hardware needs to experiment and make sure the options are set correctly.

**Comment by leberrigan** [comment]
Has been tested and deployed
