### ISSUE TITLE
No tags visible in Manage Tags (beta)

### ISSUE THREAD

**Issue by jsayers-bsc** [MotusDev/Motus-TO-DO#980]
Nothing in the table visible in the Manage Tags section https://beta.motus.org/data/project/tags?projectID=115. Clicking on a line bring up a developer error page.

**Comment by pmorrill** [comment]
It looks like beta server is currently hosting beta9 (judging by the options on the project landing page). But the error trace you are seeing includes reference to a jsp that does not exist in beta9. (It is part of beta10).

I have checked the git repo to ensure that the ManageTagServlet code is consistent with what we want for beta9, and it appears to be (last change was in Apr 2020).

@Hussell could this be a case of needing a complete clean and rebuild of beta9? I can't see any issues with this servlet on the live server, which is more or less running beta9 as well.

**Comment by Hussell** [comment]
Arg, yes, needed to restart the Tomcat context.

**Comment by Hussell** [comment]
Following up, after the embedded page started loading correctly, I noticed an issue with text fragments there. I think @leberrigan or @jsayers-bsc might have brought this up during a recent call, but I didn't quite understand what was being discussed.

The issue was with the button meant to show "Download all tags", "Download undeployed tags", or other variations based on the deployment status. In the code, this was broken up into three text fragments, one for "Download", one for "tags", and a different one for each deployment status.

In short, this doesn't work. Different languages use different word orders, show agreement between different words, and just generally make it impossible to translate a single word without affecting the rest of a sentence. For example, in French most adjectives follow their noun, rather than preceding it as in English, so "Download active tags" translates as "Télécharger les émetteurs actifs", literally "Load the transmitters active". So, hard-coding the order of the words in the source-code makes it impossible to translate the sentence correctly. A template might have been better, e.g. "Download %s tags" translated as "Télécharger les émetteurs %s", except there are some adjectives in French which go before the noun, including "tous" ("all")!

Note also that the words "les émetteurs actifs" all agree with each-other in number and grammatical gender, e.g. it would be "actives" if "émetteurs" were replaced by a feminine noun instead of a masculine noun. A lot of languages also have the verb agree in number, person, and gender with it's subject, so inserting different nouns into a template will, in some languages, force verbs as well as adjectives to change to agree with the noun.

So: make your text fragments as large as possible. Whole sentences and paragraphs are best. Include all adjacent punctuation. E.g. "Deployments:" is better than "Deployments" with a hard-coded colon, because various languages use different punctuation marks for labelling things.

I've fixed this example by making separate text fragments for "Download all tags", "Download active tags", etc., but in future I'd like everyone to try to remember the rule of thumb above. The apparent duplication of content goes against deeply ingrained programmer instincts, but in text fragments it's better to duplicate some text because it makes correct translation possible.
