### ISSUE TITLE
Test Stations

### ISSUE THREAD

**Issue by leberrigan** [MotusDev/Motus-TO-DO#999]
As discussed on today's call:
- We need a method for registering and managing multiple concurrent test deployments
- The best solution may be to create a **test station** for each project, one which has no lat/lon and allows for multiple concurrent deployments.
- The purpose is to flag deployments that we don't want to have displayed on the public interface, but also to avoid forcing users to create a different station for each test (as is the case with the current behaviour).
   - I.e., make the interface more intuitive and less cluttered
- The management interface can be adapted so that test deployments are managed separately.
  - For instance, the option to 'manage test deployments' (or something along those lines) could sit next to 'add a station,' or something like that.
  - The actual page to edit an individual deployment would essentially be the same.

**Comment by denislepage** [comment]
One additional note: the interface should make it clear to users what the purpose/value of a test station is.  Basically, they are just a way to confirm that their equipment is working, and they mainly intended to temporary.

Test stations:

- removes data from the public outputs on the web site

- continues to allow downloading of data on a receiver basis, or potentially on a station ID basis (a feature we may want to add)

- are we going to exclude detections those receivers from the tag projects downloads?? I can see some merit in this.  

- as you say above, test stations are not assigned to a site or landowners, and there is no enforcement of the rule to have a single concurrent deployment per station.

- the requirement to only allow a single concurrent deployment per receiver number remains in place (always, including for test deployments). This is presumably also being checked across projects.

- only 1 test station would be permitted by project. Not sure whether this needs to be enforced at the database level, but if it is not, the Java code may need to assume that data integrity may be broken (e.g. what happens if a project has 2 stations marked as test: presumably only ever pick the first of the 2).

- deployments can be deleted from test stations. We should ensure that the correct processes are in place, but we shouldn't be able to delete a record until the deployID's are removed from the det_taghits_deploy_id table (pretty sure that's already handle directly in Java or SQL by a single update statement prior to deleting).

- There should be a visible difference in the interface that makes it clear that you are managing a test station or a deployment on a test station.

**Comment by denislepage** [comment]
We haven't discussed this recently, but it strikes me that mobile deployments have many of the same requirements and properties as above, but with some exceptions.  We should be careful not to conflate the 2 things.

- Data would **not** be removed from public outputs, or anywhere else.

- How is a station defined in a mobile context? If we ask for a starting point or a general location, are we mostly expecting a general location around which people are using the receiver.

- It seems to me that mobile deployments should be allowed to be concurrent within the same station (if they use a distinct receiver number). E.g. two field staff each roaming around the same area with their own receiver. But maybe that is not something common enough to warrant a special treatment.

- The concept of "mobile" should probably also apply **only** at the station level. IE, users couldn't have a mix of mobile and fixed deployments at the same station. Right?

Perhaps the way to handle this is to have the option when creating a station to say whether it is a fixed location, a site for mobile deployments, or a station for test deployments, which would then control the behavior of the station page. I think Paul was wanting to create a separate page for test deployments, which I still support. I'm not sure where mobile deployments fall in this, however.

How were we planning to incorporate mobile deployments into stations so far? Can we have a working solution that doesn't prevent us from releasing beta10?

**Comment by pmorrill** [comment]
I have added a checkbox to station properties tool, to mark a station as 'test'. With a couple of minor adjustments in the receiver deployment logic, it **seems** to allow you to add multiple concurrent active deployments to that station. But it will require testing to understand the impact, and whether there are restrictions.

Also: do we now remove the 'test' checkbox from the recv deployment edit page. eg:

https://sandbox.motus.org/data/station/deployment/edit?projectID=1&id=3560

Is this field completely deprecated on sensors_deployments records?
